### ISSUE TITLE
New user or editing existing user doesn't work

### ISSUE THREAD

**Issue by dundunn** [shopware/shopware#100]
I can't add a new user nor can I edit an existing one. Everything else seems to work fine. 
The loading circle just spins indefinitely. Sorry for the vague description I can't find any logs. 
![Add user](https://i.imgur.com/bpkyErw.png)

**Comment by mitelg** [comment]
hey @dundunn 
could you have a look in the dev console tool of your browser? Inspecting the requests should give you more information about what's wrong

**Comment by dundunn** [comment]
Awww damn I should have tested another browser profile or at least empty the cache. The problem is solved thanks :)
