### ISSUE TITLE
[6.2.0] Unable to change shipping address during checkout

### ISSUE THREAD

**Issue by patpilus** [shopware/shopware#1009]
**Description**  
After update to Shopware 6.2.0 it's impossible to change shipping address on `checkout/confirm` page. Clicking `Change shipping address` button shows billing address change modal instead of shipping one. 

Also confirmed that on 6.2 DemoStore (without any modifications):
![image](https://user-images.githubusercontent.com/13252273/84136212-45e31300-aa4b-11ea-980f-208c135c1f55.png)

**Comment by mitelg** [comment]
hey @patpilus 
seems to be that problem https://github.com/shopware/platform/pull/973
will be fixed with 6.2.1
