### ISSUE TITLE
Plugin - Theme

### ISSUE THREAD

**Issue by dahormez** [shopware/shopware#101]
Hello,

- Plugin Theme uninstall does not remove the theme from storefront and admin view. (would be great for completly re-apply theme config or something)

- Theme configuration custom logos in dist folder can only installed once:
Message: A file with the name "logo.x" already exists.
On a new install, you cant apply the theme.json again - force command?!

- the documentation say, place theme.json under resources, but it should be placed under src

Cheers :-)!

**Comment by jenskueper** [comment]
Hello!

These are all three valid issues! We are currently working on a theme system update and these issues will be addressed.

Best regards,
Jens

**Comment by jenskueper** [comment]
Hey dahormez,

with the EA1.1 release we have fixed these and a couple of other issues.
