### ISSUE TITLE
Account order edit enables to pay for a order multiple times

### ISSUE THREAD

**Issue by jochenmanz** [shopware/shopware#1010]
**Description**  

If a PaymentProcessException is thrown, the corresponding edit order page does not check if the order is actually paid. As the edit page can be accessed multiple times, i could pay for the order also multiple times.

**Possible Solution**  

Check if the sum of all transactions (filtered by state is not equals to cancelled) equals the order amount.

**Additional context**

**Comment by mitelg** [comment]
thanks for the report @jochenmanz :+1: 
we will take your ticket https://issues.shopware.com/issues/NEXT-9735 to take care of the problem
