### ISSUE TITLE
Custom domain local

### ISSUE THREAD

**Issue by MajorKuprich** [shopware/shopware#1016]
**Description**  
Custom domain in local environment not working with shopware.
1) I want to assign shopware.test to 127.0.0.1 in /etc/hosts but it's not working.
2) I can change only ports for docker services (docker-compose.ovveride.yml), but where I can change default ip address?

**Possible Solution**  
What should I do to change default local shopware ip address?
Is there any description for this?

**Comment by shyim** [comment]
Just add to the port the ip address like
```
- ''MYIP:8000:8000"
```
