### ISSUE TITLE
Own theme, JS files and CSS files from plugins are no longer included

### ISSUE THREAD

**Issue by nergerf** [shopware/shopware#1018]
**Description**  

Use the developer version from Git as of June 11th, 2020.
I created a theme plugin via the console and assigned it to the storefront. Now the JS files and the SCSS files are no longer included. Emptying the cache doesn't help. Even if I ran storefront: build from the console, it doesn't work. Errors are not output.
It works with the productive shop.

**Comment by almare** [comment]
I have the same problem. All of my plugins are broken with current dev.

**Comment by nicoanders** [comment]
[cc0c2fc](https://github.com/shopware/platform/commit/cc0c2fcac3a187e4a559de4fe5dac0965018b2b5#diff-fd22aad7c042a776062404ee088a631cR108) in #486 is the source of the problem. The condition for the recursion level breaks the functionality.

**Comment by nergerf** [comment]
@nicoanders Danke für die Hilfe

**Comment by mitelg** [comment]
there is a PR with a ticket, which fixes the problem: https://github.com/shopware/platform/pull/1031

**Comment by mitelg** [comment]
should be fixed now in 6.2.2

**Comment by nergerf** [comment]
Danke Michael
