### ISSUE TITLE
Main-Navigation recursion

### ISSUE THREAD

**Issue by dahormez** [shopware/shopware#102]
Hello Guys,

The Main-Navigation recursion not working properly, frontend should be fine, but the CategoryLoader not. It wont load the children of children (mobile works..).

Maybe also cool if {% set navigationMaxDepth = 3 %} in layout/navigation/categories.html.twig will be added in own block for override purposes.

King regards,
Daniel

**Comment by Phil23** [comment]
Hey @dahormez,

thank you for reporting an issue. I created an official ticket in our issue tracker for this. 

You can follow the issue here: https://issues.shopware.com/issues/NEXT-4311

Greetings,
Phil
