### ISSUE TITLE
Product stock inheritance issue

### ISSUE THREAD

**Issue by sawden** [shopware/shopware#1021]
**Description**  
Cant save product variation if you restore inheritance on the stock field.

1. Create a Product variation
2. Click on "Edit"
3. Scroll to "Deliverability" and click on the inheritance icon
4. Click on "Save"

![produkt_lagerbestand](https://user-images.githubusercontent.com/36924392/84598617-63114a80-ae6c-11ea-8327-ce947913855c.png)

**Comment by shyim** [comment]
Duplicates #537
