### ISSUE TITLE
Variant Prices in listing are displayed wrong

### ISSUE THREAD

**Issue by PhenomEY** [shopware/shopware#1035]
If you have a article with variants which have different prices, the lowest price does not get displayed in the product listing.

example a T-Shirt: M costs 10$  L costs 15$ and XXL costs 20$
If you chose L as default the price in the listing will be **15$**

It should be **starting at 10$**

**Comment by moorl** [comment]
Additional the list prices are not displayed in the storefront (dev v6.2.2)

**Comment by OliverSkroblin** [comment]
Hi @PhenomEY,

thanks for the hint, we fixed this bug with the following commit: https://github.com/shopware/platform/commit/298a9a02b4f4af670c0db504bfe48ceb436728b0
