### ISSUE TITLE
Missing thumbnails

### ISSUE THREAD

**Issue by jacekwilczynski** [shopware/shopware#1062]
**Description**  
Sometimes the thumbnail generation seems not to work, resulting in 404 errors when an <img> tag points to non-existing files. The error is hard to replicate now because if I upload a new image, it's ok, so I'm attaching a video of what things look like with an existing image.

It seems related to https://issues.shopware.com/issues/NEXT-7754 but that issue does not mention the problem of memory consumption, which might be the source of the failures.

**Possible Solution**  
Perhaps it's a memory overconsumption issue: the thumbnail generation service tried to allocate 30 GB of working memory. This happened when I ran `bin/console media:generate-thumbnails`:
```
"exception": {
      "code": 0,
      "file": "/app/vendor/shopware/core/Content/Media/Thumbnail/ThumbnailService.php:237",
      "message": "Error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 300000000 bytes)",
      "class": "Symfony\\Component\\ErrorHandler\\Error\\OutOfMemoryError"
    }
```

I would also check what happens when the processing of an image fails - it should be retried on the next call, not skipped.

**Additional context**  
https://youtu.be/CM6_-1LTx7g

At the beginning of the video, I show that when the full-size image has been loaded, the banner is visible.

Later I shrink the browser and refresh so you see the banner has failed to load. Then I show that the URLs referred to in `srcset` point to non-existing files, leading to 404 errors.

In the final part of the video I show that using another image works fine, however after going back to the original image, the problem still exists.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
