### ISSUE TITLE
[Message Queue] Unable to route message to single transport (always fallbacks to default)

### ISSUE THREAD

**Issue by patpilus** [shopware/shopware#1066]
**Description**

I want to configure my custom message to single Symfony Messenger's transport (other than `default`), eg.:
```
'MyApp\Message\SmsNotification': another_transport
``` 

In [Message Queue documentation](https://docs.shopware.com/en/shopware-platform-dev-en/references-internals/core/module/queue#routing) there's such statement:
> You can route messages by their classname and use the asterisk as a fallback for all other messages.

Unfortunately it doesn't work this way. Wildcard `'*'` set in Shopware config causes each message to be send via `default` transport regardless of the routing set for this particular message: https://github.com/shopware/core/blob/master/Framework/Resources/config/packages/framework.yaml#L37

As a result, message is sent via both transports: `default` and `another_transport`.

From what I see it's impossible to route message to single transport. Please advise how to deal with it. Thanks.

**Shopware version:** 6.1.6

**Comment by pajonas** [comment]
hey @patpilus,

did you find any solution or workaround for this?

**Comment by patpilus** [comment]
@PascalJonassonDV, there's a tricky workaround proposed by Shopware support...:

>  Hi, to get around your problems with the current default routing I recommend you
> 
> Add a marker interface without any methods "CustomMessage" for example or "AsyncMessage"
> Then you can route all messages implementing this interface to your own Bus
> To stop your custom messages from being send twice, you can add a custom middleware to the "messenger.bus.shopware". This middleware then filters out any message implementing the "CustomMessage" interface.
> Example handle method for the middleware:
> 
> ```php
> public function handle(Envelope $envelope, StackInterface $stack): Envelope
> {
>     if ($envelope->getMessage() instanceof CustomMessage && count($envelope->all(ReceivedStamp::class)) === 0) {
>       return Envelope;
>     }
>     return $stack->next()->handle($envelope, $stack);
> }
> ```
> That way you can decouple your changes from any Shopware core routing.

**Comment by pajonas** [comment]
@patpilus, Thank you very much for sharing this!

**Comment by pajonas** [comment]
> @PascalJonassonDV, there's a tricky workaround proposed by Shopware support...:
> 
> > Hi, to get around your problems with the current default routing I recommend you
> > Add a marker interface without any methods "CustomMessage" for example or "AsyncMessage"
> > Then you can route all messages implementing this interface to your own Bus
> > To stop your custom messages from being send twice, you can add a custom middleware to the "messenger.bus.shopware". This middleware then filters out any message implementing the "CustomMessage" interface.
> > Example handle method for the middleware:
> > ```
> > public function handle(Envelope $envelope, StackInterface $stack): Envelope
> > {
> >     if ($envelope->getMessage() instanceof CustomMessage && count($envelope->all(ReceivedStamp::class)) === 0) {
> >       return Envelope;
> >     }
> >     return $stack->next()->handle($envelope, $stack);
> > }
> > ```
> > 
> > 
> > That way you can decouple your changes from any Shopware core routing.

Hey there. 

Did you get this working? I tried as suggested, but my own bus sends the message into both transports because the global messenger routing is set to my_queue and *. Is there anyway to configure the routing for a specific bus?

```
messenger:
        transports:
            default:
                dsn: "enqueue://default"
                options:
                    receiveTimeout: 1000
            my_queue:
                dsn: "enqueue://default"
                options:
                    queue:
                        name: "my_queue"
                    topic:
                        name: "my_queue"
                    receiveTimeout: 1000
        routing:
            'App\Message\AsyncMessage': my_queue
            '*': default
        default_bus: messenger.bus.shopware
        buses:
            messenger.bus.shopware:
                middleware:
                    - App\Message\IgnoreMyQueueRetryMiddleware
            messenger.bus.my_bus:
                middleware:
                    - Shopware\Core\Framework\MessageQueue\Middleware\RetryMiddleware

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
