### ISSUE TITLE
Product export does not honour 'include variants' config setting

### ISSUE THREAD

**Issue by bug-or-feature** [shopware/shopware#1074]
## Description
Product export from Admin screens does not include variants, even when "Export product variants" is toggled on

### Setup
- Delete all products
- Create one new product
- Add a few simple variants to the product

### Test 1
- Export the Products to CSV. Admin Dashboard > Settings > Import/Export > Export > Choose 'Default product' profile > Leave 'Export product variants' off > Start Export button
- View resulting file
- There is one row or product data - works as expected

### Test 2
- Export the Products to CSV. Admin Dashboard > Settings > Import/Export > Export > Choose 'Default product' profile > Set  'Export product variants' on > Start Export button
- View resulting file
- There is one row of data, there should be a row for each variant

**Comment by keulinho** [comment]
Seems to be fixed already [here](https://issues.shopware.com/issues/NEXT-8722).

Please reopen if it is still an issue.
