### ISSUE TITLE
Installation Database: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes"

### ISSUE THREAD

**Issue by selfphp** [shopware/shopware#108]
During installation (Shopware 6 Early Access), some tables are not created in InnoDB, but in MyISAM. As a result, the following error may occur (if no default storage engine has been set):

Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes "

One can eliminate the error by entering the following value in the * .ini:

default-storage-engine = InnoDB

However, it would be nice if the installation of the tables is implemented properly.

**Comment by pweyck** [comment]
Thank you for reporting this. This issue will be fixed with the next release, see: 
https://github.com/shopware/platform/blob/3c186a179ecfaed80ed16cf0c9c0f5a2dcd3277b/src/Core/Framework/Migration/MigrationRuntime.php#L93-L96
