### ISSUE TITLE
Inherited / getParent() bug within the DAL

### ISSUE THREAD

**Issue by ChristopherDosin** [shopware/shopware#1082]
If you try to get the **parent** product it's currently not possible due to a bug in DAL which causes an SQL error.

`getParent()` is giving `null` even though `getParentId()` is within the product.

I also tried to add the  `$criteria->addAssociation('parent');`  which results then in an SQL error
```
The given alias '`product.parent.translation`' is not unique in FROM and JOIN clause table. The currently registered aliases are: `product`, `product.parent`, `product.translation`, `product.tax`, `product.foo`, `product.bar`, `product.parent.translation`, `product.parent.parent`.
```
`product.bar` & `product.foo` are two entity extensions.

As @shyim mentioned within [this slack thread](https://shopwarecommunity.slack.com/archives/C011VFQT7GB/p1593184879017500?thread_ts=1593184879.017500&cid=C011VFQT7GB), it seems to be a bug within the DAL.

![image](https://user-images.githubusercontent.com/8193345/85977335-16d61680-b9e5-11ea-94c9-7d5ee66d5492.png)

**Comment by zaifastafa** [comment]
I think there should be a section in docs which gives a list of all associations for each individual entities.

**Comment by rvzug** [comment]
Facing the same problem. Is there a internal ticket we can follow on this issue?

**Comment by shyim** [comment]
Imported as Issue in Jira: https://issues.shopware.com/issues/NEXT-10437

**Comment by rvzug** [comment]
Is this also related? #1091

**Comment by shyim** [comment]
Its not related

**Comment by shyim** [comment]
Its not possible anymore to load the parent. This is not possible due limitations in the Translation Handling of the DAL
