### ISSUE TITLE
theme:compile failed for Google Storage adapter

### ISSUE THREAD

**Issue by cuonghuynh** [shopware/shopware#1097]
**Description**  
I changed public filesystem to Google Cloud Storage adapter, then theme:compile command failed with error:
> php bin/console theme:compile
```
Start theme compilation

In Filesystem.php line 111:

  [InvalidArgumentException]
  League\Flysystem\Filesystem::putStream expects argument #2 to be a valid resource.

```

**Possible Solution**  
For Google Cloud Storage filesystem closes the stream after upload finished so we have to check resource is valid before putting the stream.
The function `handle` in src/Core/Framework/Adapter/Filesystem/Plugin/CopyBatch.php should be:
```
...
foreach ($batchInput->getTargetFiles() as $targetFile) {
    if (is_resource($handle)) {
        $this->filesystem->putStream($targetFile, $handle);
    }
}

if (is_resource($handle)) {
    fclose($handle);
}
...
```

**Comment by shyim** [comment]
Is fixed with https://github.com/shopware/platform/commit/5e5ead7e84be7857a0f22a6d534eff696fe603c2
