### ISSUE TITLE
Persisting data in context

### ISSUE THREAD

**Issue by MajorKuprich** [shopware/shopware#1108]
**Description**  
How can we share additional data on checkout pages.
I want to save data in context on _/checkout/cart_ page and display it on _/checkout/confirm_ page.
I've tried with custom collector class which implements **CartProcessorInterface** and override **process** method.
I've tried save data (into Cart or SalesChannelContext), but it doesn't work.

**Possible Solution**  
Creating something like in Magento - checkoutsession and quoteData, in which we can save and share data in the checkout logic :)

**Additional context**  
Is there any doc examples related with this issue?

**Comment by shyim** [comment]
The normal context is not intended for that. You could use the ContextPersister to write additional payload into the SalesChannelContext
