### ISSUE TITLE
Admin request check?domain is not called in plugins list for pages 2 and above

### ISSUE THREAD

**Issue by MDSLKTR** [shopware/shopware#1109]
**Description**  
`https://[server]/api/v1/_action/system-config/check?domain=[plugin].config` is not called for plugins on page 2 or higher with in Plugins list. This results in the plugin config not being accessible.

See this video for details.

https://[server]/admin#/sw/plugin/index/list?
[Bildschirmvideo aufnehmen 2020-07-07 um 18.02.24.zip](https://github.com/shopware/platform/files/4885897/Bildschirmvideo.aufnehmen.2020-07-07.um.18.02.24.zip)

limit=25&page=1&sortBy=upgradedAt&sortDirection=desc&naturalSorting=false

This can be fixed by loading the page with a higher limit at the moment.

**Comment by MDSLKTR** [comment]
If it helps: `plugins` is a computed property which doesn't update when the pagination fetches a new result with the search criteria settings. The Store is completely disconnected here so only the first load will properly trigger a all functionality.

**Comment by shyim** [comment]
Is fixed already
