### ISSUE TITLE
Scheduled Tasks behave unexpectedly

### ISSUE THREAD

**Issue by Watschman** [shopware/shopware#111]
Used Version: User v6.0.0-Early Access 1
Installation: Manual Installation on a local system
System: Linux CentOS 7
PHP-Version: PHP 7.2.14RC1
Web-Server:  Apache 2.4.37, PHP-FPM
Database: MariaDB-10.2.21

I've been trying to set up scheduled Tasks in a Plugin. I've followed the steps at: https://docs.shopware.com/en/shopware-platform-dev-en/how-to/scheduled-tasks?category=shopware-platform-dev-en/how-to but could not seem to make it work. Upon further investigation in the database, I discovered some strange behaviour while monitoring the scheduled_task table. 
When using the Administration backend under Plugins, then ACTIVATING the Plugin with a scheduled task, the database table does not update. BUT when DEACTIVATING the Plugin with a scheduled task, the database table does an update and includes the scheduled task of the plugin and runs it once.
Since I wasn't sure whether or not I made an error in my plugin structure, I decided to test the same procedure with your provided Example Plugin at https://github.com/shopware/swag-docs-scheduled-task-plugin .
To make it easier to track I only altered the MyTaskHandler.php::run function and added a simple `error_log("Hello World");` instruction to it. - The same phenomenon happened.
Steps I have done to make this issue occur:

1. Install and Configure a Shopware 6 installation
2. Fetch Plugin from https://github.com/shopware/swag-docs-scheduled-task-plugin
3. Place Plugin to /custom/plugins
4. Initiate Command /bin/console plugin:refresh
5. Install Plugin in Admin Backend
6. Activate Plugin in Admin Backend (No Scheduled Task in Database)
7. Deactivate Plugin in Admin Backend (Scheduled Task in Database, but only 1 execution)
8. Activate Plugin in Admin Backend (Scheduled Task disappears from Database)
.....

I didn't have time to test it on a separate server installation yet.

Maybe I did a crucial mistake in the order of execution here, or I found a bug in how scheduled tasks are handled. Either way I would be delighted to hear back from you.

**Comment by Christian-Rades** [comment]
Thank you for your detailed report.
I've looked into the issue and you've found a bug indeed. I have created a Ticket for it. You can follow it through our issue tracker: 
https://issues.shopware.com/issues/NEXT-4343
