### ISSUE TITLE
Empty request in custom store-api route

### ISSUE THREAD

**Issue by pallemach2** [shopware/shopware#1110]
**Description**  
I registered a custom route for the store-api (like mentioned here in the documentation: https://docs.shopware.com/en/shopware-platform-dev-en/developer-guide/controller), but sadly the request object keeps empty.

![image](https://user-images.githubusercontent.com/56473073/86855928-a05ba780-c0bb-11ea-9ad8-8ade6e4413d3.png)

Thats the generated request-object, even if i set a json body or append query params.
![image](https://user-images.githubusercontent.com/56473073/86856167-0ea06a00-c0bc-11ea-9202-9518f78c0cf7.png)

**Comment by MajorKuprich** [comment]
Did You used JSON.parse on response object?

**Comment by pallemach2** [comment]
why json.parse? The snippets above are written in PHP. And the request-object is generated by shopware, so i think i dont need to parse anythink, or do i?

**Comment by shyim** [comment]
You need to pass as header Content-Type application/json otherwise shopware does not parse it
