### ISSUE TITLE
Installation without mod_rewrite

### ISSUE THREAD

**Issue by selfphp** [shopware/shopware#112]
Currently it is possible to install the shop without mod_rewrite - the installation routine runs through clean but the shop shows serious errors. Maybe you should check the value in the installation routine?!? The error message after installation is:

Slim Application Error

The application could not run because of the following error:
details
Type: Shopware \ Recovery \ Common \ HttpClient \ ClientException
Code: 6
Message: Could not resolve host: shopware6.ubuntuserver
File: /var/www/html/shopware6/public/recovery/common/src/HttpClient/CurlClient.php
Line: 96
trace

**Comment by shyim** [comment]
The issue that you describe and the exception does not match. The application server can't resolve own domain. Maybe missing hosts entry?

**Comment by selfphp** [comment]
We installed it on a fresh Ubuntu system and forgot to enable mod_rewrite. This error was displayed and the frontend was also faulty. After activating mod_rewrite everything was ok

**Comment by selfphp** [comment]
You were right, there was still a host entry missing and now the installation is running through clean! However, as already described, the routine does not complain if mod_rewrite is disabled
