### ISSUE TITLE
Search on Manufacturer name not working

### ISSUE THREAD

**Issue by runelaenen** [shopware/shopware#1120]
**Description**  
The fields manufacturer name is never indexed by the ProductSearchKeywordAnalyzer because the association is not loaded.

**Possible Solution**  
Add the required associations to the search criteria in \Shopware\Core\Content\Product\DataAbstractionLayer\SearchKeywordUpdater::updateLanguage

**Additional context**

**Comment by shyim** [comment]
The search has been reworked meanwhile
