### ISSUE TITLE
Swagger shows incorrect request body

### ISSUE THREAD

**Issue by zavodyanka** [shopware/shopware#1156]
**Description**  
Swagger shows incorrect request body

**Additional context**  
![postman](https://user-images.githubusercontent.com/8125287/87676504-fba32f00-c778-11ea-92b1-cd28eee875fd.png)
![swagger](https://user-images.githubusercontent.com/8125287/87676516-ff36b600-c778-11ea-9075-8451aad666f3.png)

**Comment by shyim** [comment]
It is not wrong. Change the Request body to `application/json` at the select on right side
