### ISSUE TITLE
Add to Shopping Cart Button in Listing doesn't work with Minimum Order Quantity

### ISSUE THREAD

**Issue by Watschman** [shopware/shopware#117]
Used Version: User v6.0.0-Early Access 1
Installation: Manual Installation on a local system
System: Linux CentOS 7
PHP-Version: PHP 7.2.14RC1
Web-Server: Apache 2.4.37, PHP-FPM
Database: MariaDB-10.2.21

Hello, 
today I've discovered while trying out various functions of the shop, that the "Add to Shopping Cart" button, which is displayed in the storefront listing, doesn't work when you specify a Minimum Order Quantity for the product. 
When you click on the Button an error occurs "The product <product_name> is not available anymore.", this is obviously wrong since it just simply fails because you have to buy more than 1 item.

Steps to reproduce:
1. Install Shopware
2. Create new Product
3. Specify Minimum Order Quantity greater than 1
4. Save Product
5. Look at Storefront and see "Add to Shopping Cart" Button in Product Listing
6. Click on Button and receive Error.

My suggestion would be to simply remove the Button from the Product Listing view, similar to Products with Properties/Variants, when Minimum Order Quantity is greater than 1.

**Comment by Phil23** [comment]
Hey @Watschman,

thank you for reporting an issue. I created a ticket in our official ticket system. You can follow the status here: https://issues.shopware.com/issues/NEXT-4410

Greetings
