### ISSUE TITLE
Refresh index fails with a high number of variants and properties with Elasticsearch enabled

### ISSUE THREAD

**Issue by henrikvolmer** [shopware/shopware#1174]
**Description**  
If a high number of variants per master product (<600), together with a high number of property options (~400) are exported to Elasticsearch, `dal:refresh:index` will fail.

The following error message appears:

`ERROR     [app] The number of nested documents has exceeded the allowed limit of [10000]. This limit can be set by changing the [index.mapping.nested_objects.limit] index level setting.\n23:23:50 ERROR     [console] Error thrown while running command \"dal:refresh:index\". Message: \"Following errors occurred while indexing: \\n\" [\"exception\" => Shopware\\Elasticsearch\\Exception\\ElasticsearchIndexingException { …},\"command\" => \"dal:refresh:index\",\"message\" => \"Following errors occurred while indexing: \\n\"]\n\nIn ElasticsearchIndexer.php line 286:`

**Possible Solution**  
The increase of the `index.mapping.nested_objects.limit` parameter

**Additional context**

**Comment by shyim** [comment]
Is fixed with the new elasticsearch indexing
