### ISSUE TITLE
Search for property group only searches for option values

### ISSUE THREAD

**Issue by runelaenen** [shopware/shopware#1176]
**Description**  
It is not possible to search for property names themselves, only for their options.

For example:
![Screenshot 2020-07-22 at 10 28 07](https://user-images.githubusercontent.com/3930922/88153711-0ee54d00-cc06-11ea-8b7c-54aee15ea9fd.png)

searching "afwerking" would not give any results, but searching for "gegoten" will return this line.

The same faulty search is active on searching in the administration listing (using the search on the top), as when searching in a entity multi select.

**Comment by keulinho** [comment]
Should have been fixed here: https://github.com/shopware/platform/pull/1463
