### ISSUE TITLE
TypeError: Cannot read property 'removable' of undefined

### ISSUE THREAD

**Issue by granitibrahimi** [shopware/shopware#1178]
**Description**  

An issue with VueJS for a component.

`TypeError: Cannot read property 'removable' of undefined at s.blockIsRemovable`

**Possible Solution**  

What I did to make it work is I searched for that function blockIsRemovable and I found it on `sw-cms-sidebar.html.twig`
under `shopware/administration/Resources/app/administration/src/module/sw-cms/component/sw-cms-sidebar` and removed :removable="blockIsRemovable(block)" property on rows 275 & 307 and now works ok (since we are not using this component).

**Additional context** 

Screenshot:
![image](https://user-images.githubusercontent.com/16402164/88169689-a786c780-cc1c-11ea-8955-449af264ff6b.png)

**Comment by dominikkremer** [comment]
Hi @granitibrahimi 👋 

I would like to look into this issue.
Could you provide some details on how to reproduce the error?

**Comment by Dary08** [comment]
I've temporarily changed the `blockIsremovable` function in `vendor/shopware/administration/Resources/app/administration/src/module/sw-cms/component/sw-cms-sidebar/index.js` to:

```
        blockIsRemovable(block) {
            if (typeof this.cmsBlocks[block.type] === "undefined") {
                return false;
            }
            if (!this.cmsBlocks[block.type].hasOwnProperty('removable')) {
                return false;
            }
            return (this.cmsBlocks[block.type].removable !== false) && this.isSystemDefaultLanguage;
        },
```

Then re-compile the administration theme. This makes the error go away, but doesn't solve the underlying problem.

**Comment by granitibrahimi** [comment]
@Dary08 @dominikkremer 

With a re-compile of the administration theme after we adjusted some extended components the issue is not appearing amonyre.

@Dary08 I would close it, but if you have the same issue would be good to provide more information so we can check on it.

Thanks

**Comment by Dary08** [comment]
Here's a [vaimo/composer-patches](https://github.com/vaimo/composer-patches) patch we made to fix this;

```
Fixes an error in the administration where we cant delete or add a block becuase of an error with removable or something

@package shopware/administration
@level 1
@link https://github.com/shopware/platform/issues/1178
@version >=6.3.1.0

diff --git a/Resources/app/administration/src/module/sw-cms/component/sw-cms-sidebar/index.js b/Resources/app/administration/src/module/sw-cms/component/sw-cms-sidebar/index.js
index 36bcdc3..f440c5f 100644
--- a/Resources/app/administration/src/module/sw-cms/component/sw-cms-sidebar/index.js
+++ b/Resources/app/administration/src/module/sw-cms/component/sw-cms-sidebar/index.js
@@ -106,6 +106,12 @@ Component.register('sw-cms-sidebar', {
         },

         blockIsRemovable(block) {
+            if (typeof this.cmsBlocks[block.type] === "undefined") {
+                return false;
+            }
+            if (!this.cmsBlocks[block.type].hasOwnProperty('removable')) {
+                return false;
+            }
             return (this.cmsBlocks[block.type].removable !== false) && this.isSystemDefaultLanguage;
         },
```

**Comment by peterjaap** [comment]
Some additional info for @dominikkremer, we ran into this issue with Shopping Experience Layouts that were created by [the theme we use](https://store.shopware.com/en/tcinn42873094627/themeware-bio-sales-increasing-and-customizable.html?c=4), specifically with the Homepage layout.

I'm guessing that these are instantiated at some point and the `removable` property was missing when it was instantiated. The administration then assumes it exists and errors out when it can't find it.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
