### ISSUE TITLE
PHP API Documentation

### ISSUE THREAD

**Issue by flashback2k14** [shopware/shopware#118]
Hey,

could somebody tell me where I can find the API documention for the php classes for shopware 6? Or how I could build this.

Thanks

**Comment by Staff-d** [comment]
Hey @flashback2k14 !

Thank you for your interest in Shopware 6! I am afraid that, at least at the moment, a documentation on class level does not exist. 

As an alternative entry point into getting to know how the php classes work together you could take a look at the entity relationship diagrams we have for most of our core modules (https://docs.shopware.com/en/shopware-platform-dev-en/internals/core/modules). Each of the entities listed there is represented in the PHP code via [entityName]Entity and [entityName]Definition, where [entityName] refers to the name of the entity in the erd in camelCase (see https://docs.shopware.com/en/shopware-platform-dev-en/internals/core/data-abstraction-layer#creating-your-own-entities). If you search for usages of the entity classes you are interested in you should get a rough idea of how they work together pretty fast ;) 

Best regards,
Sebastian
