### ISSUE TITLE
Update from admin panel from 6.2.0 to 6.2.3. not working

### ISSUE THREAD

**Issue by joanna-gil** [shopware/shopware#1181]
**Description**  
When I try to update Shopware 6 with 6.2.0 stable version to 6.2.3 from the admin panel I get an error (screen). 
Running the composer install command doesn't help
![Screenshot from 2020-07-24 11-16-32](https://user-images.githubusercontent.com/57439261/88377361-52bf8a00-cd9f-11ea-89be-6597c207d5fb.png).

**Comment by shyim** [comment]
Hey,

that is known. The  Auto Updater had an issue which is fixed since 6.2.1. For the updates before, it can happen that not all files are unpacked.

Use an update zip when its failed. See update notification here: https://www.shopware.com/en/changelog/#6-2-0
