### ISSUE TITLE
Symfony still at 4.4.4? 4.4.8 had a minor security fix.

### ISSUE THREAD

**Issue by AndreasA** [shopware/shopware#1185]
Symfony 4.4.11 of the LTS is now available and 4.4.8 had a minor security fix, so the dependencies should be updated accordingly

**Comment by patpilus** [comment]
To even tell more, I don't get why Symfony packages versions in composer are locked at patch one. Symfony follows semver, so there can't be breaking changes...

**Comment by shyim** [comment]
The current version is not vulnerable check your composer.lock using https://security.symfony.com/

**Comment by AndreasA** [comment]
@shyim It isn't a huge vulnerability but according to https://symfony.com/blog/symfony-4-4-7-released

However, there is a minor vulnerability. And even if not, 4.4.4 is quite old now. It would be nice to get the latest bugfixes etc. in.

**Comment by shyim** [comment]
We have created an internal Issue :)

**Comment by NeoBlack** [comment]
Another reason to re-open and fix: https://github.com/shopware/platform/issues/86 ...

**Comment by shyim** [comment]
We don't really work with Github Issues https://issues.shopware.com/issues/NEXT-9961

**Comment by AndreasA** [comment]
@shyim If you don't work with github issues wouldn't it make more sense to disable github issues and at a link to the README to the correct issue tracker instead?

**Comment by shyim** [comment]
Symfony has been updated. https://github.com/shopware/platform/commit/d05da6f6559fdae7b1a43ad1202b2bca5ccb7d3d
We set this time **only a min version**. So you will get Symfony updates without a new Shopware version :) 

@AndreasA We will disable the Github Issue Tracker in future. Currently there are some discussions
