### ISSUE TITLE
PluginManager.override does not work when overriding multiple times

### ISSUE THREAD

**Issue by AlexBa** [shopware/shopware#1194]
Hey,
it seems like the PluginManager.override does not work for storefront JS plugins when overriding multiple times.  

### Current situation
I'm developing a Shopware community plugin called "Pixel Your Shop" (https://store.shopware.com/en/shops88897352858/pixel-your-shop.html), where I want to add Facebook "add-to-cart" events for the off canvas checkout. Thus, I just want to override the "OffCanvasCart" plugin. Rather easy and it's working correctly just like the docs are describing it (https://docs.shopware.com/en/shopware-platform-dev-en/how-to/extend-core-js-storefront-plugin).

However, my customers are reporting that this feature does not work anymore. If I look at the environment of the customer, multiple plugins are overriding the "OffCanvasCart" plugin. But only one plugin is able to execute the code. If I temporarily disable all overrides except the one of my plugin, everything is working correctly again. 

### Environment
The environment is Shopware 6.2.2

### Code
Here is the relevant code of my plugin. The other plugins are correct too - as far as I see it. They use methods like "super.init()" and override the plugin via "PluginManager.override"  the right way too.

main.js
```
import OffCanvasCartPlugin from './plugin/offcanvas-cart/offcanvas-cart.plugin';

const { PluginManager } = window;
PluginManager.override('OffCanvasCart', OffCanvasCartPlugin, '[data-offcanvas-cart]');
```

plugin/offcanvas-cart/offcanvas-cart.plugin.js
```
import BaseOffCanvasCartPlugin from 'src/plugin/offcanvas-cart/offcanvas-cart.plugin';

/**
 * @since 1.0.0
 */
export default class OffCanvasCartPlugin extends BaseOffCanvasCartPlugin {
    /**
     * @since 1.0.0
     *
     * @inheritDoc
     */
    init() {
        super.init();

        // Does not trigger...
        alert("Working");
    }
}
```

### Question

Do any of you have the same problem?

**Comment by AlexBa** [comment]
This problem is now marked as "Scheduled patch": https://issues.shopware.com/issues/NEXT-10099

**Comment by hakimdjabri** [comment]
I have the same problem !! 6.3.3.1

**Comment by hakimdjabri** [comment]
> This problem is now marked as "Scheduled patch": https://issues.shopware.com/issues/NEXT-10099

I have used the global plugin manager to override my js plugin, could you try this in your main.js : 

`window.PluginManager.override('OffCanvasCart', OffCanvasCartPlugin, '[data-offcanvas-cart]');`

**Comment by keulinho** [comment]
Please follow the status on the official issue: https://issues.shopware.com/issues/NEXT-10099

I'm closing this as a duplicate for now.
