### ISSUE TITLE
ERROR: Can't run export when profile is created by Not-Default-Language | Profile->Label will be null

### ISSUE THREAD

**Issue by LinoJo** [shopware/shopware#1195]
**Description**
You create a store with an default language (e.g. English).
After that you go to Settings->Import/Export and create a custom profile with a new Label everythings works fine, **WHEN you not change the language!** Otherwise, If you choose another language (e.g. German) before saving your custom profile the name/lable will be NULL in the default language. And than you can't create a export, because:

_URL: http://localhost:8000/admin#/sw/import-export/index/export_
0: Argument 1 passed to Shopware\Core\Content\ImportExport\Aggregate\ImportExportLog\ImportExportLogEntity::setProfileName() must be of the type string, null given, called in /app/vendor/shopware/platform/src/Core/Content/ImportExport/Service/ImportExportService.php on line 245
Line 245 in ImportExportService.php is:
$logEntity->setProfileName($profile->getTranslation('label'));

See the images below!!

**Possible Solution**
Solution 1: Save the Label in default-Language too or ask for that.
Solution 2: Check variable before asking for that ;-). Like: 
`if(empty($profile->getTranslation('label')))`
**Soulution 3: DO BOTH PLS! :+1:**

**Additional context**  
![image](https://user-images.githubusercontent.com/27199272/88659945-288b0680-d0d6-11ea-9bf6-1b93f4cc981d.png)
![image](https://user-images.githubusercontent.com/27199272/88660002-3fc9f400-d0d6-11ea-9d42-cce6ea4070b4.png)

**Comment by shyim** [comment]
Is fixed in trunk
