### ISSUE TITLE
Allow media import from localhost or file URL

### ISSUE THREAD

**Issue by macster84** [shopware/shopware#1207]
**Description**  
Using a media URL that points to localhost (or any private IP) is forbidden during import:entity command. That hardens setup for local test environments that do not have a public IP.
The only workaround I found was to override the FileUrlValidator and commenting out the _filter_var_ part that was using _FILTER_VALIDATE_IP_ with _FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE_ flags.

E.g. I'd like to import from media URLs like this:

`http://localhost/temp_media/Kraeuterstempel.jpg`

**Possible Solution**  
I do not see a reason why imports from localhost should be forbidden at all. Please remove that restriction.

**Comment by shyim** [comment]
Hey,

You can disable it in the shopware.yaml https://github.com/shopware/platform/blob/master/src/Core/Framework/Resources/config/packages/shopware.yaml#L53.

We won't disable it by default. For more information why please read: https://owasp.org/www-community/attacks/Server_Side_Request_Forgery
