### ISSUE TITLE
Contact form template missing and silently ignored

### ISSUE THREAD

**Issue by roben** [shopware/shopware#121]
We noticed that the contact form does not sent any mails, even though a green success messages is shown to the user after submitting. After digging around in the code, we discovered two issues in the `sendMail` method `MailSendSubscriber.php`:
- `$mailTemplate` is null
- the method then silently exits without throwing any error

Although we never touched these settings, we in fact do not have any contact form template listed. Maybe some migrations did not complete during installation?
![image](https://user-images.githubusercontent.com/812205/62788600-8d191400-bac7-11e9-8ee2-d3293c009b33.png)

We have two independent shopware 6 installations freshly installed with the EA1 installer. The template is missing in both.

**Comment by ssltg** [comment]
Hi,

thank you for reporting this issue. I created an official ticket in our issue tracker. You can follow the issue here: https://issues.shopware.com/issues/NEXT-4519

Greetings,
Stefan
