### ISSUE TITLE
Use npm_modules for storefront Plugins: Compiled JS Plugin with node_modules intefering with shopware storefront JS

### ISSUE THREAD

**Issue by creifferscheid** [shopware/shopware#1212]
**Description**  
We developed a frontend configurator using Vue and Vuex in our plugin. In development everything works fine.
When we build our JS for production, webpack bundles everything correctly in one js file.
If we want to install it on a fresh new shopware in production, our JS get's concatetenated correctly to the all.js, but the referencing variables overlap so that we get the following error:

**"Uncaught TypeError: Cannot read property 'call' of undefined" in all. js on line... "**

**How can we correctly implement plugins using npm modules in a plugin, so that the JS variables don't overlap?**

**Additional context**  
Our App.js

`import Vue from '../../node_modules/vue/dist/vue.js';
import Vuex from '../../node_modules/vuex/dist/vuex';
import Main from '../components/Main.vue.js';
import store from './store/store';
import {toLocale} from '../utils/utils';

const app = () => {

    Vue.filter('toLocale', toLocale);
    Vue.use(Vuex);
    Vue.component('Main', Main);
    new Vue({
        el: '#vue-product',
        template: '<Main/>',
        store: new Vuex.Store(store),
    })
};
`

**Comment by tyurderi** [comment]
@creifferscheid I had this issue too in one of our plugins. I have solved this problem by bundling the dist files ourselves using `webpack`.

 Hopefully Shopware will find a fix for this soon.

**Comment by jeanfortheweb** [comment]
Same for us, not working in production. Has eaten 24 hours so far still no fix found. We're using jsx for some files. If injecting a custom ts-loader rule for tsx files, it's working for development, but not on production.

**Comment by klarstil** [comment]
@creifferscheid I was checking out the issue you're describing here and I can't see any problems.

So what I did is the following:

1. Created a custom webpack config which extends the core config, so I can create aliases for Vue and Vuex
2. Imported both libraries in my `main.js` file using the previously defined aliases.
3. Created a template override to hook my Vue.js application into the storefront using a simple div element.
4. Used `./psh.phar storefront:build` & `./psh.phar storefront:hot-proxy` to verify that everything is working. I'm using the development template here.

I created a test plugin which you can check out: https://github.com/klarstil/npm-storefront-test Please lemme know if this solves your issue.

Best regards
