### ISSUE TITLE
inactive products should be displayed

### ISSUE THREAD

**Issue by tinect** [shopware/shopware#1219]
**Description**  
There is a filter onto `product.active = true` in https://github.com/shopware/platform/blob/master/src/Core/Content/Product/SalesChannel/ProductAvailableFilter.php#L19
This results in 404 error-Page visiting known product.

But some things are handled in storefront which doesn't have any effect at the moment:
1. https://github.com/shopware/platform/blob/master/src/Storefront/Resources/views/storefront/component/delivery-information.html.twig#L15
2. https://github.com/shopware/platform/blob/master/src/Storefront/Resources/views/storefront/page/product-detail/buy-widget.html.twig#L166

**Possible Solution**  
Remove filter for `product.active` from ProductAvailableFilter + Set availability in delivery-information to SoldOut.
Generally, there should be an info of SoldOut product instead of 404-Error page
Add option `Hide inactive products in Storefront` to keep current behaviour.

Hiding products should just be managed with Visibility-Settings.

**Additional context**

**Comment by moorl** [comment]
Same problem here, I need to replace the ProductAvailableFilter with own conditions, but there is no CriteriaEvent, no decorator or anything else I can Use.

I have tried something like this in several criteria events:
```php
    private function replaceProductAvailableFilter(Criteria $origin, string $salesChannelId): void
    {
        $criteria = clone $origin;
        $origin->resetFilters();

        foreach ($criteria->getFilters() as $filter) {
            if ($filter instanceof ProductAvailableFilter) {
                foreach ($filter->getQueries() as $query) {
                    if (in_array('product.visibilities.visibility', $query->getFields())) {
                        $visibility = $query->getVars()[0];
                        $origin->addFilter(new MultiStockProductAvailableFilter($salesChannelId, $visibility));
                    }
                }
            } else {
                $origin->addFilter($filter);
            }
        }
    }
```

```php
class MultiStockProductAvailableFilter extends ProductAvailableFilter
{
    public function __construct(string $salesChannelId, int $visibility = ProductVisibilityDefinition::VISIBILITY_ALL)
    {
        MultiFilter::__construct(
            self::CONNECTION_AND,
            [
                new RangeFilter('product.msStocks.visibility', [RangeFilter::GTE => $visibility]),
                new EqualsFilter('product.msStocks.msWarehouse.salesChannels.id', $salesChannelId),
                new EqualsFilter('product.active', true),
            ]
        );
    }
}
```

It is actually impossible to do anything :(

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
