### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by DanielRuf** [shopware/shopware#122]
It seems there is currently no CI here which runs for all PRs, only a CI config for GitLab.

https://github.com/shopware/platform/blob/master/.gitlab-ci.yml

So is this project hosted on GitLab and where can we find it there and is this here just a mirror?

How should we know if something breaks tests or the current CI status?

https://www.shopware.com/de/community/entwickler/ still links to GitHub

**Comment by janbuecker** [comment]
We use GitLab internally and it's not open to the public. Yes, we mirror our repository to GitHub. We have plans for adding travis again like with the shopware/shopware repository.

I hope I was able to help you out!

**Comment by DanielRuf** [comment]
Unfortunately I see no mention of "tests" in the readme and there is no CONTRIBUTING.md.

And no mention how we can run tests at https://github.com/shopware/platform/blob/master/.github/PULL_REQUEST_TEMPLATE.md

As a contributor I want to find this info in the repo so I can test my changes.

**Comment by mitelg** [comment]
Thanks for the hints @DanielRuf :+1: 
I created a PR internally to add a CONTRIBUTING.md and a short howto in the docs. Also adjusted the readme.
Please check again later, if there are still information missing
