### ISSUE TITLE
Child theme doesn't inherit parent's theme database config

### ISSUE THREAD

**Issue by peterjaap** [shopware/shopware#1227]
We created our own theme based on a 3rd party theme, like so;

```
{
    "name": "OurTheme",
    "views": [
        "@Storefront",
        "@3rdPartyTheme",
        "@OurTheme"
    ],
    "style": [
        "@Storefront",
        "app/storefront/src/scss/overrides.scss",
        "@3rdPartyTheme",
        "app/storefront/src/scss/base.scss"
    ],
        "@Storefront",
    "script": [
        "@3rdPartyTheme",
        "app/storefront/dist/storefront/js/our-theme.js"
    ],
    "asset": [
        "@Storefront",
        "@3rdPartyTheme",
        "app/storefront/src/assets"
    ]
}
```

This seems to work just fine after doing these steps;
- `bin/console theme:create OurTheme`
- update `theme.json` to match above
- `bin/console plugin:install OurTheme --refresh --activate`
- `./psh.phar storefront:build`
- `./psh.phar cache`

However, we noticed the theme settings we did in `3rdPartyTheme` settings in the admin weren't honored (such as color hex values etcetera).

When looking in the `theme` table in the database, I noticed the `base_config` and `config_values` fields of `OurTheme` were empty. Those for `3rdPartyTheme` were populated however, which the settings we had changed.

I then copied over these settings from `3rdPartyTheme` to `OurTheme`;

```
UPDATE theme SET base_config = (SELECT base_config FROM (SELECT * FROM theme) as t WHERE technical_name = '3rdPartyTheme') WHERE technical_name = 'OurTheme';
UPDATE theme SET config_values = (SELECT config_values FROM (SELECT * FROM theme) as t WHERE technical_name = '3rdPartyTheme') WHERE technical_name = 'OurTheme';
```

Then I ran `./psh.phar storefront:build &&./psh.phar cache` and the updated values were shown on the frontend.

So it seems the parent theme config settings in the database aren't merged into the child theme. This corresponds with [this code](https://github.com/shopware/platform/blob/v6.3.0.1/src/Storefront/Theme/ThemeService.php#L150-L173).

You see there that on line 173 the configurations are merged. However, the `$configuredTheme` (which in our case is `OurTheme`) is merged with the `$baseTheme`, which is *always* `Storefront` (see [line 153](https://github.com/shopware/platform/blob/v6.3.0.1/src/Storefront/Theme/ThemeService.php#L153) and [StorefrontPluginRegistry's line 16](https://github.com/shopware/platform/blob/v6.3.0.1/src/Storefront/Theme/StorefrontPluginRegistry.php#L16)) and *not* `3rdPartyTheme`, as I would've expected (which in turn would've been merged with `Storefront`).

I would expect that the merging of these config values would be infinite, based on the inheritance defined in `theme.json`.

Not sure whether this is a bug or a feature request, but judging from the code I'd say it's an oversight (or a deliberate choice) so a feature request would be most fitting.

**Comment by AlexBa** [comment]
Yes, this is a known issue. Other developers including me are already struggeling with this issue. I think, you have to copy the whole config from the parent's theme.json file.

**Comment by peterjaap** [comment]
@AlexBa I'm talking about the config settings in the database, not in the `theme.json` file.

**Comment by peterjaap** [comment]
On second look, it does look like the fallback for the config settings in `theme.json` doesn't work either.

**Comment by BrocksiNet** [comment]
Is this still an issue? 

Because I see a `"parentThemeId": "df9761ce76b047cebabc625d5dc9a2e2",` Option 
for theme.json in new Shopware 6.4.1.2 Version.

Also this code has also changed: [ThemeService.php](https://github.com/shopware/platform/blob/6.4.2.0/src/Storefront/Theme/ThemeService.php#L148)

**Comment by BrocksiNet** [comment]
Updated `parentThemeId` via API and still the config get's not merged. Sadly.

**Comment by BrocksiNet** [comment]
I solved this problem with a decorator. 
Should I somehow provide a PullRequest @AlexBa

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
