### ISSUE TITLE
API search-endpoint for `currency` is not able to filter for `iso_code`

### ISSUE THREAD

**Issue by UlrichThomasGabor** [shopware/shopware#1228]
Using the search endpoint of the API for the `currency` entity (`/api/v2/search/currency`) and filtering for `iso_code` returns the error `FRAMEWORK__UNMAPPED_FIELD`, although this is only a `char` type in the database.

**Comment by shyim** [comment]
The field is isoCode

**Comment by UlrichThomasGabor** [comment]
Thanks, working.

Maybe document somewhere more clearly that identifiers are expected in camelCase?

**Comment by shyim** [comment]
Just look into swagger documentation how the fields are named
https://api-doc.friendsofshopware.com/?urls.primaryName=Management%20API%20(6.2.0)#/Currency/getCurrencyList

**Comment by UlrichThomasGabor** [comment]
I do not think this is a replacement for proper official documentation.
