### ISSUE TITLE
Product Detailpage - Gallery shows the same picture

### ISSUE THREAD

**Issue by lorenzpfei** [shopware/shopware#123]
https://demo.shopwaredemo.de/detail/65666d2629744f65b981cc6263d3ef0a if you click on one of the preview pictures you will see the picture in fullscreen. If you click on the switching button to the right or left picture the same picture is shown.

**Comment by Phil23** [comment]
Hey @ElDiabolus,

thank you for reporting an issue. There is already a ticket which describes this issue in our official issue tracker. You can follow the status here: https://issues.shopware.com/issues/NEXT-4389

Thank you for your support
