### ISSUE TITLE
Vagrant administration:watch

### ISSUE THREAD

**Issue by juanitolaguna** [shopware/shopware#1235]
**Description**  
In the vagrant workflow the /admin login does not work for administration:watch

**Possible Solution**  
Change the cookieStorageFactory method as described here: https://forum.shopware.com/discussion/68312/admin-watch-login-geht-nicht-unter-version-6-2-0-rc1.

Albeit it screws up the administration:build, so when developing you have to switch between the old method implementation and the other as described in the forum.

**Comment by shyim** [comment]
The hostname issue in administration:watch has been fixed
