### ISSUE TITLE
Paypal doesn't work

### ISSUE THREAD

**Issue by lorenzpfei** [shopware/shopware#124]
If you want to pay with paypal (sandbox mode - not tested realmode), you'll receive a 500 error and the paypal popup is closing.
https://i.imgur.com/YUbztOL.png
https://i.imgur.com/LvmJeFx.png

> GET https://www.domain.com/sales-channel-api/v1/_action/paypal/spb/create-payment 500

> Uncaught Error: Expected an order id to be passed

**Comment by mitelg** [comment]
hey @ElDiabolus 
which version of the plugin and Shopware do you use?

**Comment by lorenzpfei** [comment]
Paypal: 0.10.1
Shopware: 6.0.0-ea1

Can I update my shopware manually using the fixed github files?

**Comment by mitelg** [comment]
we already fixed this error. Updates for the plugin and Shopware are planned for this week. 
here is the fix for PayPal https://github.com/shopwareLabs/SwagPayPal/commit/59571c664ed906b2912d0d6704752780c7b6cca4

**Comment by lorenzpfei** [comment]
So this week I can get the shopware updates via the administration ui?

**Comment by mitelg** [comment]
yes :+1:
