### ISSUE TITLE
ThemeCompiler should use webpack if callable

### ISSUE THREAD

**Issue by htuscher** [shopware/shopware#1246]
**Description**  
Compiling the scss via PHP and autoprefixing it consumes a serious amount of computational power.

The ThemeCompiler could test if NodeJS is installed and callable and use webpack instead of php scss if possible to speed up the theme compilation. This is done by every bigger Symfony project like e.g. Akeneo. Most of them even require NodeJS for compiling the assets. But it's perfectly possible with a fallback.

**Comment by ssltg** [comment]
Hi @hhoechtl 
thank you for your contribution and ideas. 👍 
By the process of finding a good match between your suggestions and our plans, we implemented our approach for a more flexible way of compiling the themes with this commit: https://github.com/shopware/platform/commit/00f11cbbb68422568e7cfc4d4993fa3b68c4bb6b
With this you should be able to write a ScssCompiler which uses webpack.
If our approach does not fit your usecases, feel free to open another issue.

regards
