### ISSUE TITLE
ProductNotFoundException in Storefront - Products only visible in Administration and DB [SW 6.2.3]

### ISSUE THREAD

**Issue by dreadog** [shopware/shopware#1250]
I'm currently running SW 6.2.3 on docker setup with install via:

```
./psh.phar init
./psh.phar administration:init
./psh.phar storefront:init
bin/console assets:install
bin/console theme:compile
```

to avoid the irremovable demo-products.

**I am able to create products in the backend and use them in Shopping Experiences or associate them with a category.**

Opening the Storefront representation of the category (listing page) returns a 'No products found.' info.

Using products in Commerce-Blocks, results in the id being entered into the sliderConfig, yet not into element.data.products.elements. Therefore it returns blank cards, slides or listings.

Opening the default product URL in the browser (http://sw-domain.com/productname/productnumber) returns a **ProductNotFoundException with the info 'Product for id 959f2f4034544fe3873d02113da46654 not found.'**.

Here is the Stack Trace:

Shopware\Core\Content\Product\Exception\ProductNotFoundException:
Product for id 959f2f4034544fe3873d02113da46654 not found.

```
  at vendor/shopware/platform/src/Storefront/Page/Product/ProductLoader.php:90
  at Shopware\Storefront\Page\Product\ProductLoader->load('959f2f4034544fe3873d02113da46654', object(SalesChannelContext))
     (vendor/shopware/platform/src/Storefront/Page/Product/ProductPageLoader.php:122)
  at Shopware\Storefront\Page\Product\ProductPageLoader->load(object(Request), object(SalesChannelContext))
     (vendor/shopware/platform/src/Storefront/Controller/ProductController.php:88)
  at Shopware\Storefront\Controller\ProductController->index(object(SalesChannelContext), object(Request))
     (vendor/symfony/http-kernel/HttpKernel.php:146)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request), 1, true)
     (vendor/shopware/platform/src/Core/HttpKernel.php:148)
  at Shopware\Core\HttpKernel->doHandle(object(Request), 1, true)
     (vendor/shopware/platform/src/Core/HttpKernel.php:77)
  at Shopware\Core\HttpKernel->handle(object(Request))
     (public/index.php:55)    

```
Clearly shopware is able to resolve a name or number to an id. Yet it is not able to find the product with that id.

The database seems to be fine as well:

```
mysql> select id from product;
+------------------------------------+
| id                                 |
+------------------------------------+
| 0x959F2F4034544FE3873D02113DA46654 |
| 0xE81C7602AE1A45F8AC4D0667592F474B |
| 0x6C84592A617D4F27A54AB1509697EF69 |
+------------------------------------+

```

**How can that be fixed? 
Is there additional information I may supply?
How would one generally debug such an exception?**

**Comment by MelvinAchterhuis** [comment]
@dreadog How did you resolve this issue?

**Comment by dreadog** [comment]
In this specific case the issue was not a bug but a misconfiguration in the backend. 

As products are created the default for assignment to sales channels is empty. Therefore one has to specify a sales channel for every product.

**Assigning a sales channel to the product resolved this issue.**
