### ISSUE TITLE
Wrong ChangeSet Data when updating multiple entities

### ISSUE THREAD

**Issue by s-diez** [shopware/shopware#1258]
**Description**  

The wrong change set data is assigned to a command, when the entity primary key consists of a version_id and id and multiple entities with the same version_id are updated at the same time.
In the following lines it is only checked if any part of the primary key matches not all of it. 
 https://github.com/shopware/platform/blob/97d3677d214ab9fd3a8d0b1f93f57a55e5fd3a31/src/Core/Framework/DataAbstractionLayer/Dbal/EntityWriteGateway.php#L524-L538

When updating multiple entities this will lead to changesets with the wrong payloads for some of them.
I created a little plugin to reproduce the problem. https://github.com/s-diez/shopware-changesetbug
The output of this is:

```
entity primary key: 00cd4e8dc52e41a6a511c4a306ff15f7
changeset primary key: 0086915735ea4bc6a225cad06d6fb9ae


entity primary key: 00bec8faf4c949b79aa853155ae15680
changeset primary key: 0086915735ea4bc6a225cad06d6fb9ae


entity primary key: 00aa1b08a24c4c2181f215769d70b969
changeset primary key: 0086915735ea4bc6a225cad06d6fb9ae


entity primary key: 0086915735ea4bc6a225cad06d6fb9ae
changeset primary key: 0086915735ea4bc6a225cad06d6fb9ae

```

**Possible Solution**  

Check for the size of the intersect like:

```php
if (!$primaryKey || count($primaryKey) !== count($command->getPrimaryKey())) {
```
But I do not know if in some cases the version_id is allowed to be different or a partial match is actually the desired behaviour.

**Comment by ireznik** [comment]
@s-diez possibly related Issue https://issues.shopware.com/issues/NEXT-10379 ?

**Comment by s-diez** [comment]
Could be, could be something totally different. I did not use or look at the admin at all.

**Comment by s-diez** [comment]
Solved through https://github.com/shopware/platform/commit/189f7882a729384d3b0028f70aa4ebf38d44aa44
