### ISSUE TITLE
Sort manufacturers

### ISSUE THREAD

**Issue by tinect** [shopware/shopware#1265]
**Description**  
Manufacturers in filter are sorted as they become used in listing by products. But they should be sorted alphanumeric.
Doing this in template feels dirty.

Position in template:
https://github.com/shopware/platform/blob/c5b78af033b1438e497e28ec7b10ab25cedb8a0d/src/Storefront/Resources/views/storefront/component/listing/filter-panel.html.twig#L23

Can we add here some sorting? Is it the correct point? :-)
https://github.com/shopware/platform/blob/7704106f4627996de0689b4ea91db58b1687f9ff/src/Core/Content/Product/SalesChannel/Listing/ProductListingFeaturesSubscriber.php#L199-L201

**Example**  
![image](https://user-images.githubusercontent.com/135993/90989548-d507bd80-e59a-11ea-9a82-ac89d937697d.png)

**Comment by keulinho** [comment]
Should have been fixed with this [ticket](https://issues.shopware.com/issues/NEXT-10671).

Please reopen if the issue still exists.
