### ISSUE TITLE
Save and Generate Codes for Promo does not have an effect (when promo not saved?)

### ISSUE THREAD

**Issue by amenk** [shopware/shopware#1268]
**Description**  

Steps to reproduce:

1. Add new promo on  /admin#/sw/promotion/create/base
2. Write name: test
3. Sales channel: Store front
4. Promotion code required: tick
5. Use individual promotion codes: tick
6. Manage individual codes
7. In the popup:
8. Pattern: `%s`
9. Click "save and generate" -> nothing happens
10. Expected: It generates the codes

![image](https://user-images.githubusercontent.com/1087128/91044449-96fbaf80-e615-11ea-822a-9115da1c408b.png)

**Possible Solution**  

If it is technically problematic to generate codes before the entity is saved, we should show a message, that it needs to be saved first.

***Workaround***
It seems to work if you save the promo first and then start generating the codes.

**Additional context**  

* shopware/administration 6.3.0.2

**Comment by keulinho** [comment]
Should have been fixed with this [ticket](https://issues.shopware.com/issues/NEXT-12139).
