### ISSUE TITLE
Variants are shown as empty lines in rule builder

### ISSUE THREAD

**Issue by amenk** [shopware/shopware#1269]
**Description**  

On a fresh installation with demo data I noticed empty lines in the rule builder.

![image](https://user-images.githubusercontent.com/1087128/91046281-6c5f2600-e618-11ea-9166-6415edd8f0a6.png)

Having a look at the network tab /products API request I found, that those products seem to be variants, for example 
SKU SWDEMO10007.4

**Possible Solution** 

Show the SKU in addition to the name in the dropdown, which should never be empty

**Additional context**  

* shopware/administration 6.3.0.2 
* URL: /admin#/sw/settings/rule/detail/....

**Comment by keulinho** [comment]
Should have been fixed with this [ticket](https://issues.shopware.com/issues/NEXT-10369).
