### ISSUE TITLE
Theme Inheritance 

### ISSUE THREAD

**Issue by ghost** [shopware/shopware#127]
Hi!

I have a shop with a different Sales Channel (Storefronts) and different themes for the different Storefronts.

When customizing a specific twig template in the different themes, only the changes in the last activated theme are shown and it is shown in all the different Storefronts, even though, the said theme has not been chosen for the shopfront.

Kind Regards!

**Comment by jenskueper** [comment]
Hello!

Thank you for opening this issue. This is currently a bug which we have already fixed internally but it hasn't been merged into the master yet. I can't give you an exact date when it will be merged into the master but if I have to guess I would say next week.

Best regards!
