### ISSUE TITLE
PHP Autoprefixer generates unwanted styles

### ISSUE THREAD

**Issue by htuscher** [shopware/shopware#1271]
**Description**  
We just discovered, that the PHP autoprefixer that is used by the ThemeCompiler generates unwanted styles like e.g. `.table th { background-color: #fff !important`. 
This style was not present after being compiled by the `scssCompiler`.

**Possible Solution**  
As stated in https://github.com/shopware/platform/issues/1246 switch to webpack if possible to avoid such pitfalls.

**Comment by shyim** [comment]
Please create an Issue in the Package itself. https://github.com/padaliyajay/php-autoprefixer
