### ISSUE TITLE
Multiple spaces in header triggers error

### ISSUE THREAD

**Issue by runelaenen** [shopware/shopware#1272]
**Description**  
When typing multiple spaces the ajax search gives errors because PHP does a trim on the input.

**Possible Solution**  
Trim in javascript before calculating search length.

**Additional context**  
![Screenshot 2020-08-25 at 15 16 14](https://user-images.githubusercontent.com/3930922/91178787-f3c69b00-e6e5-11ea-8e2f-ccf0a912b2d4.png)

[Screen Recording 2020-08-25 at 15.09.53.mov.zip](https://github.com/shopware/platform/files/5123895/Screen.Recording.2020-08-25.at.15.09.53.mov.zip)

![Screen Recording 2020-08-25 at 15 09 53](https://user-images.githubusercontent.com/3930922/91182806-f081de00-e6ea-11ea-8b2c-0d2d68539892.gif)

**Comment by JoshuaBehrens** [comment]
You can convert screen recordings into gif for easier viewing experience :) watch-out 10mb limit

**Comment by runelaenen** [comment]
> You can convert screen recordings into gif for easier viewing experience :) watch-out 10mb limit

I've added it, but the quality loss is extreme 😅

**Comment by JoshuaBehrens** [comment]
Enough to get a gist of the actions happening. But I get you. It is not always very pleasant but I had good experiences in the past

**Comment by runelaenen** [comment]
Fixed in https://github.com/shopware/platform/pull/1226
