### ISSUE TITLE
any one guide what the right event for checkout page... in shopware 6 Shopware\Core\Checkout\Cart\Event\CheckoutOrderPlacedEvent; CheckoutOrderPlacedEvent::class=>'onCheckoutOrderPlacedEvent', this event is not working on checkout page ..

### ISSUE THREAD

**Issue by TanveerBalti123** [shopware/shopware#1274]
**Description**  

**Example**

**Comment by mitelg** [comment]
Please use our Slack Channel, if you are looking for support :blush:  https://slack.shopware.com/

You could create an issue, if you have found an error on Shopware, or for suggesting new features
