### ISSUE TITLE
can't get it to work

### ISSUE THREAD

**Issue by deansoffer** [shopware/shopware#128]
i followed the instructions in the installation page.
after filling phar install quuestions i get this error:
`Using .psh.yaml.dist extended by .psh.yaml.override

" in "C:\xampp\htdocs\shopware\development/dev-ops/common/actions/install.sh" in phar://C:/xampp/htdocs/shopware/development/psh.phar/src/ScriptRuntime/ScriptLoader.php:142
Stack trace:
#0 phar://C:/xampp/htdocs/shopware/development/psh.phar/src/ScriptRuntime/ScriptLoader.php(70): Shopware\Psh\ScriptRuntime\ScriptLoader->findInclude(Object(Shopware\Psh\Listing\Script), './init-composer...')
#1 phar://C:/xampp/htdocs/shopware/development/psh.phar/src/ScriptRuntime/ScriptLoader.php(54): Shopware\Psh\ScriptRuntime\ScriptLoader->Shopware\Psh\ScriptRuntime\{closure}('INCLUDE: ./init...', 6, Object(Shopware\Psh\Li
sting\Script))
#2 phar://C:/xampp/htdocs/shopware/development/psh.phar/src/Application/ApplicationFactory.php(96): Shopware\Psh\ScriptRuntime\ScriptLoader->loadScript(Object(Shopware\Psh\Listing\Script))
#3 phar://C:/xampp/htdocs/shopware/development/psh.phar/src/Application/Application.php(163): Shopware\Psh\Application\Appli in phar://C:/xampp/htdocs/shopware/development/psh.phar/src/ScriptRuntime/ScriptLoader.php on li
ne 142

" in "C:\xampp\htdocs\shopware\development/dev-ops/common/actions/install.sh" in phar://C:/xampp/htdocs/shopware/development/psh.phar/src/ScriptRuntime/ScriptLoader.php:142
Stack trace:
#0 phar://C:/xampp/htdocs/shopware/development/psh.phar/src/ScriptRuntime/ScriptLoader.php(70): Shopware\Psh\ScriptRuntime\ScriptLoader->findInclude(Object(Shopware\Psh\Listing\Script), './init-composer...')
#1 phar://C:/xampp/htdocs/shopware/development/psh.phar/src/ScriptRuntime/ScriptLoader.php(54): Shopware\Psh\ScriptRuntime\ScriptLoader->Shopware\Psh\ScriptRuntime\{closure}('INCLUDE: ./init...', 6, Object(Shopware\Psh\Li
sting\Script))
#2 phar://C:/xampp/htdocs/shopware/development/psh.phar/src/Application/ApplicationFactory.php(96): Shopware\Psh\ScriptRuntime\ScriptLoader->loadScript(Object(Shopware\Psh\Listing\Script))
#3 phar://C:/xampp/htdocs/shopware/development/psh.phar/src/Application/Application.php(163): Shopware\Psh\Application\Appli in phar://C:/xampp/htdocs/shopware/development/psh.phar/src/ScriptRuntime/ScriptLoader.php on li
ne 142
`

any ideas?

Thanks!

**Comment by S-M-O** [comment]
Hello,

Are you trying to install the developer version as described [here](https://docs.shopware.com/en/shopware-platform-dev-en/getting-started/installation-guide)?
The problem is that windows does not have a good working linux shell and as shopware 6 is developed under linux you won't be able to get it working so easily in a windows environment. You can try it with gitbash or windows subsystem for linux (wsl).

If you only need a "normal" installation in docker you can find a working setup here
https://github.com/shopware/platform/issues/126

Best regards,
Stefan

**Comment by tobiasberge** [comment]
Hi deansoffer,

unfortunately those `.sh` scripts do not run properly on Windows - like S-M-O already mentioned. I agree that WSL (https://docs.microsoft.com/windows/wsl/install-win10) is a good alternative. It gives you a pretty native experience. But this only works when you have Windows 10.

If you want to have less setup effort you could also try a Vagrant Box:

Vagrant Box: https://github.com/shopwareLabs/shopware-platform-vagrant
Documentation: https://docs.shopware.com/en/shopware-platform-dev-en/getting-started/system-installation-guides/vagrant

Best regards
Tobias

**Comment by deansoffer** [comment]
tobiasberge, S-M-O  thanks guys,
windows truely made the problem.
manged to get it work with WSL.
:)
