### ISSUE TITLE
Product import: Native vs. API

### ISSUE THREAD

**Issue by qx54** [shopware/shopware#129]
Hi,

I can't find any public information regarding the planned product import/export feature.

Will the import feature allow XML files and include field mapping?
Also will it support cron and command line execution?

What will be the advantages of the native product import feature over a custom implementation via API? Speed? Or just ease of use?

Thanks

**Comment by janbuecker** [comment]
Thank you @qx54, I'll answer your questions below:

1. Will the import feature allow XML files and include field mapping?
    *Yes, it will be possible to use XML and map the fields.*

2. Also will it support cron and command line execution?
    *Yes, would make much sense.* :)

3. What will be the advantages of the native product import feature over a custom implementation via API?
    *Currently, the Sync API has about the same performance as the admin API, because we haven't done any optimizations yet. Right now, the only benefit is less HTTP overhead because you can write multiple entities at once, instead of sending n requests. The performance will increase in the future!*
