### ISSUE TITLE
Allow open basedir restrictions in installers op cache check

### ISSUE THREAD

**Issue by amenk** [shopware/shopware#1291]
https://github.com/shopware/platform/blob/a7f1cbb7a46fde993e97bfcd5c5a4cb19e29e026/src/Recovery/Install/src/Requirements.php#L244

We should catch an exception and still add the check

See

https://github.com/shopware/shopware/pull/2052#issuecomment-501271424

In contrast to Shopware 5, Shopware 6 installation crashes here.

As reported here https://issues.shopware.com/issues/NEXT-10564

**Comment by amenk** [comment]
There was a fix added in shopware 5 which tries to catche an exception if open_basedir is set.
I believe catching the ErrorException does not really work - it would still throw a warning.


	$ php7.4 -dopen_basedir=/home/ -a
	Interactive mode enabled

	php > try { echo fileinode('/'); } catch ( \ErrorException $e ) { echo 'does not work'; }
	PHP Warning:  fileinode(): open_basedir restriction in effect. File(/) is not within the allowed path(s): (/home/) in php shell code on line 1
	PHP Stack trace:
	PHP   1. {main}() php shell code:0
	PHP   2. fileinode() php shell code:1

**Comment by FrSelo** [comment]
is there any workaround to install Shopware6 now?

i get the following error
PHP Warning:  openssl_pkey_export_to_file(): cannot get key from parameter 1 in /var/customers/webs/customor/vendor/shopware/recovery/Common/src/Service/JwtCertificateService.php

**Comment by amenk** [comment]
@FrSelo  Why do you think this is related to this issue? You might want to create a new one or better ask in the support forum. It might be a OpenSSL configuration problem on your site. Good luck :)

**Comment by shyim** [comment]
Add a try catch around

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
