### ISSUE TITLE
German "valide"

### ISSUE THREAD

**Issue by tinect** [shopware/shopware#1294]
**Description**  
The german "Valide" is educational language.
We should move to "gültig".

Additionally, these two variants are mixed in use.

**Possible Solution**  
Adjust them all to one variant. Give me a info how you would like to have it, so I can create a PR.

**Additional context**

**Comment by GitEvil** [comment]
"Gültig" sounds like the correct term. Go for it! :)

**Comment by tinect** [comment]
done
