### ISSUE TITLE
Account Registration: Alternative shipping address allways shows "company, department and VAT ID" Fields

### ISSUE THREAD

**Issue by seriewe** [shopware/shopware#1299]
**Description**  

Alternative shipping address Form always shows company, department and VAT fields even if it is a private customer

**Possible Solution**  

platform\src\Storefront\Resources\views\storefront\component\address\address-form.html.twig

Check `prefix == "shippingAddress"` should be changed to `prefix == "billingAddress"` so the fields are just shown for the billing address or an additional check for selected accountTypeSelection if this fields are requiered for both.

```
 {% if shopware.config.core.loginRegistration.showAccountTypeSelection or prefix == "address" or prefix == "shippingAddress" %}
            <div class="{% if prefix == "shippingAddress" %}address-contact-type-company{% elseif prefix == "address" %}js-field-toggle-contact-type-company d-block{% else %}js-field-toggle-contact-type-company d-none{% endif %}">

```

**Additional context**  

![image](https://user-images.githubusercontent.com/10572013/91895254-36b0e180-ec97-11ea-8c36-e69fc005774c.png)

**Comment by keulinho** [comment]
This should already be fixed according this [ticket](https://issues.shopware.com/issues/NEXT-11760).
