### ISSUE TITLE
API search endpoint

### ISSUE THREAD

**Issue by S-M-O** [shopware/shopware#130]
Hello all,

Is there more information than [this](https://docs.shopware.com/en/shopware-platform-dev-en/api/filter-search-limit?category=shopware-platform-dev-en/api) about the search endpoint available?

E.g. is it possible to search for ranges or dates older/newer than etc.?

Thank you and best regards,
Stefan

**Comment by jenskueper** [comment]
Hello,

the API documentation is not complete yet. I have created a new ticket in our issue tracker https://issues.shopware.com/issues/NEXT-4643

You can do the following to filter dates:

POST http://shopware.next/api/v1/search/product

```
{
	"filter": [
		{
			"type": "range",
			"field": "createdAt",
			"parameters": {
				"gt": "2018-10-05 0:0:0"
			}
		},
		{
			"type": "range",
			"field": "createdAt",
			"parameters": {
				"lt": "2020-10-05 0:0:0"
			}
		}
	]
}
```

**Comment by S-M-O** [comment]
Hey,

Awesome! Thank you very much. I'll give it a try.

Best regards,
Stefan

--------
Edit:
Works like a charm!
