### ISSUE TITLE
[Bug][6.3.0.2] Vagrant and BundleExample plugin

### ISSUE THREAD

**Issue by dxdo** [shopware/shopware#1303]
How to reproduce:

1. Install Vagrant box with SW 6.3.0.2
2. Follow tutorial [here](https://docs.shopware.com/en/shopware-platform-dev-en/how-to/indepth-guide-bundle/introduction) or download that plugin [here](https://docs.shopware.com/en/shopware-platform-dev-en/how-to/indepth-guide-bundle/introduction)
3. Install and try to activate the plugin

Activation will fail with an error message:

> Plugin could not be activated due to error message "The "Shopware\Core\Framework\DataAbstractionLayer\Indexing\EntityIndexerRegistry" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead."

According to **data-abstraction-layer.xml** located in platform/src/Core/Framework/DependencyInjection `"Shopware\Core\Framework\DataAbstractionLayer\Indexing\EntityIndexerRegistry"` is a valid and public service.

Attempt to debug that service  with 
```
./bin/console debug:container "Shopware\Core\Framework\DataAbstractionLayer\Indexing\EntityIndexerRegistry"`
```
Gives
>Information for Service "Shopware\Core\Framework\DataAbstractionLayer\Indexing\EntityIndexerRegistry"
>
> =========================================================================================
> 
>  ---------------- -----------------------------------------------------------------------------
>   Option           Value
>  ---------------- -----------------------------------------------------------------------------
>   Service ID       Shopware\Core\Framework\DataAbstractionLayer\Indexing\EntityIndexerRegistry
>   Class            Shopware\Core\Framework\DataAbstractionLayer\Indexing\EntityIndexerRegistry
>   Tags             messenger.message_handler
>                    kernel.event_subscriber
>   **Public           no**
>   Synthetic        no
>   Lazy             no
>   Shared           yes
>   Abstract         no
>   Autowired        no
>   Autoconfigured   no
>  ---------------- -----------------------------------------------------------------------------
> 
> 
>  **! [NOTE] The "Shopware\Core\Framework\DataAbstractionLayer\Indexing\EntityIndexerRegistry" service or alias has been
>  !        removed or inlined when the container was compiled.**
> 

The service is inaccessible via Container->get();

Possible problem in another **data-abstraction-layer.xml** which is located in  /**vendor**/shopware/platform/src/Core/Framework/DependencyInjection

```
 <service id="Shopware\Core\Framework\DataAbstractionLayer\Indexing\EntityIndexerRegistry">
           <argument type="tagged" tag="shopware.entity_indexer"/>
           <argument type="service" id="messenger.bus.shopware"/>
           <tag name="messenger.message_handler" />
           <tag name="kernel.event_subscriber" />
 </service>
```

**Comment by mitelg** [comment]
hey @dxdo 

as you can see here https://github.com/shopware/platform/blob/6.3.1.0/src/Core/Framework/DependencyInjection/data-abstraction-layer.xml#L556 this is already fixed in the upcoming version 6.3.1.0 

it will probably released within the next week
