### ISSUE TITLE
Webpack SCSS compiling differs from `theme:compile`

### ISSUE THREAD

**Issue by htuscher** [shopware/shopware#1321]
![image](https://user-images.githubusercontent.com/5076356/70640985-38380680-1c3d-11ea-91a5-0bb69d43cbfd.png)

Same SCSS, left side is hot-reloading, right side is `theme:compile`.

I suspect that webpack has inheritance issues with Bootstrap variables. In this particular case:

`Resources/app/storefront/src/scss/skin/shopware/abstract/variables/_bootstrap.scss`

```
$component-active-bg: $sw-color-brand-secondary;
```

It seems that webpack can't deal with transitive variables when compiling scss compared to `theme:compile` but that's just a guess.

**Comment by shyim** [comment]
This can be never fixed as they are different implemented compilers.

**Comment by JoshuaBehrens** [comment]
@shyim run one compiler in the others language? e.g. php-v8?

**Comment by shyim** [comment]
We need to be able to run on any PHP only based setup.

I would rather push the days https://github.com/shopware/platform/pull/1466 so it's possible to easy exchange it :)

**Comment by htuscher** [comment]
Yes, that's what #1466 is for. We can write a detector and see if nodejs is available and then use webpack instead of php-scss.

That would be awesome if @shyim could push that forward.
