### ISSUE TITLE
SW6 Hello world: Not replacing twig templates from custom/plugins

### ISSUE THREAD

**Issue by jlgonzalezdev** [shopware/shopware#1322]
Using MacOs catalina with docker or vagrant.

SW version -> 6.3

I have not been able to make SW to replace twig templates.  I'm trying to complete a basic example with a new theme.

this is my folder structure:

![image](https://user-images.githubusercontent.com/41166517/92638216-9282f800-f29f-11ea-9f6e-9411bad9a5ba.png)

I have installed, activated and applied the new theme "MarketV2" to storefront sale channel, only css is applied.

in that this example neither footer.html.twig nor logo.html.twig are replaced. but if I change some css class in bases.scss it is applied. 

I cleared cache,  recompile the theme with "psh.phar storefront:dev"  and "bin/console theme:compile" and nothing change. it doesn't matter if the twig templates in my theme are just empty files or something else, they never replace the original template file from platform. 

Any help with this?? What I'm missing here?

**Comment by jlgonzalezdev** [comment]
@shyim  sure, this is just a basic theme created with bin/console theme:create. not much code, just a couple  of empty twig files trying to replace some basic templates from the default behavior in SPW.

[Marketv2.zip](https://github.com/shopware/platform/files/5210390/Marketv2.zip)

**Comment by jlgonzalezdev** [comment]
@shyim , any Idea why this is happening? to verify this wasn't an issue related with my local environment I have tried this plugin also in a docker from https://github.com/shyim/shopwarev deployed in Aws ec2, same result, twig files are never replaced with the twig templates from my theme. only css is applied

**Comment by shyim** [comment]
This issue seems very old. Can you try it on the newest version again?
