### ISSUE TITLE
SSL/TLS mariadb

### ISSUE THREAD

**Issue by ognjen-it** [shopware/shopware#1323]
Hello everyone,

Does shopware can work with a database which enforces **SSL connections**?
For example, if we have shopware on Amazon cloud and MariaDB on Google Cloud, important is to use an SSL connection.

**Comment by shyim** [comment]
When you need a Workaround apply this patch and fill the variables https://github.com/shyim/shopware/blob/master/patches/mysql_ssl_connection_vars.patch
