### ISSUE TITLE
Category Cache Warmup

### ISSUE THREAD

**Issue by ghost** [shopware/shopware#133]
I see there is been a feature/bug missing from since Shopware 5
Is that cache warmup does not warmup the category page until is visited, then next visit to that category section it is already warmed
This is very important on big catalogues (we running 10K categories)

I there any plan for this?

**Comment by Phil23** [comment]
Hey @Yafar-ISI,

thank you for your request. We are aware of this and have it on our roadmap. There will be different caching solutions implemented in the shopware 6 final release.

Greetings,
Phil
