### ISSUE TITLE
Mail timezone not right

### ISSUE THREAD

**Issue by htuscher** [shopware/shopware#1333]
**Description**  
If you're working with timezone `Europe/Berlin`, the `DateTime` stored in the DB is `UTC` which is correct.
It get's loaded with the correct timezone, but in the order confirmation mail e.g. it gets always formatted in `UTC`.

The Shopware Kernel has `date_default_timezone_set('UTC');` in its constructor and for frontend requests there's a workaround to set the timezone for Twig in `TwigDateRequestListener`.

But that doesn't work for mail templates. 

**Possible Solution**  

**Additional context**

**Comment by htuscher** [comment]
Workaround:

```php
class MailTimezoneSubscriber implements EventSubscriberInterface
{
    /** @var string */
    private $originalTimezone;
    private $requestStack;

    public function __construct(RequestStack $requestStack)
    {
        $this->requestStack = $requestStack;
    }

    public static function getSubscribedEvents(): array
    {
        return [
            MailBeforeValidateEvent::EVENT_NAME => 'beforeSendMail',
            MailBeforeValidateEvent::class      => 'beforeSendMail',
            MailSentEvent::EVENT_NAME           => 'afterSendMail',
            MailSentEvent::class                => 'afterSendMail',
        ];
    }

    public function beforeSendMail(): void
    {
        $this->originalTimezone = date_default_timezone_get();
        $timezone = $requestStack->getMasterRequest()->cookies->get(TwigDateRequestListener::TIMEZONE_COOKIE) ?? getenv('TZ') ?? 'UTC';
        date_default_timezone_set($timezone);
    }

    public function afterSendMail(): void
    {
        date_default_timezone_set($this->originalTimezone);
    }
}

```

**Comment by htuscher** [comment]
Finding:  The `MailService` uses a `StringTemplateRenderer` which has a private instance of Twig. You can't fix the timezone there. Usually the `TwigDateRequestListener` would do that.

**Comment by shyim** [comment]
This is currently in code-review and will be merged soon https://issues.shopware.com/issues/NEXT-10126
