### ISSUE TITLE
Feature request: Flag customers when they subscribe to newsletter

### ISSUE THREAD

**Issue by dannyqwertz** [shopware/shopware#1337]
**Description**
We are trying to implement a discount code for new subscribers to our newsletter and want to make sure the account is really subscribed before the discount code applies.

This would be possible within the Rule Builder and the discount-conditions (via customer flag or group)

There is currently no automatic assignment, though.

**Example**  
Customer subscribes to the newsletter, account gets automatically tagged 'newsletter-receiver' or joins group 'newsletter'

**Comment by keulinho** [comment]
Is already fixed by this [ticket](https://issues.shopware.com/issues/NEXT-13720).
