### ISSUE TITLE
Shipping country in the cart page is not sorted alphabetically 

### ISSUE THREAD

**Issue by zaifastafa** [shopware/shopware#1341]
**Description**  
The title says it all. 

**Possible Solution**  
A simple sortBy and sortDirection maybe?

**Comment by mitelg** [comment]
countries have a position. 
https://github.com/shopware/platform/blob/master/src/Core/System/Country/CountryDefinition.php#L56

I think, they should be sorted by this

**Comment by zaifastafa** [comment]
But it's not user friendly. Someone would have 2, maybe 5 or even 10 countries they need at certain positions. But the ones which do not have any position I think those remaining ones should be sorted alphabetically.

**Comment by mitelg** [comment]
yes that's true. first sort by position and then alphabetically. 
should be done here, I think https://github.com/shopware/platform/blob/master/src/Storefront/Page/Checkout/Cart/CheckoutCartPageLoader.php#L116

**Comment by J-Rahe** [comment]
The Issue has just been resolved by @zaifastafa 's commit.
