### ISSUE TITLE
storefront:build - node_modules migration

### ISSUE THREAD

**Issue by moorl** [shopware/shopware#136]
administration:build works well, my node_modules directory is located at MyModule/src/Resources/node_modules and i can easy use them in my administration script like:

`import {fromLonLat, toLonLat} from 'ol/proj.js';
import {Map, Overlay, View, Feature} from 'ol';
import {Tile, Vector} from 'ol/layer';
import {Vector as VectorSource} from 'ol/source';
import {Style, Icon} from 'ol/style';
import {Point} from 'ol/geom';
import {defaults as defaultInteractions, Pointer as PointerInteraction} from 'ol/interaction';
import OSM from 'ol/source/OSM';`

but storefront:build can*t resolve my requested scripts. In this case i need to install my modules in the Storefront root directory

**Comment by klarstil** [comment]
Hey @wa-pgeorg, what's your issue here? Can you explain what you have tried, what you're expected and what is the current behavior.

**Comment by moorl** [comment]
Hello @klarstil. I want to use custom scripts via npm. I use the npm installer within my module's Resource directory. After that i get a package-lock.json and a node_modules directory containing all my scripts and theirs's dependencies.

I can now import those scripts using their namespaces:
`import {Map, Overlay, View, Feature} from 'ol';`
This works well for administration:build - no need to add any npm package here:
platform/src/Administration/Resources

For storefront:build it does not work, here i have to use "npm install ol" in the core directory of the storefront:
platform/src/Storefront/Resources

My conclusion is, that the administration builder is migrating my external node.js modules and storefront builder not.

**Comment by moorl** [comment]
Any updates here?

**Comment by pantrtxp** [comment]
HI @wa-pgeorg, 

I'm sorry it took so long. Is this issue still existent?
Since you referenced another closed issue I cant tell

**Comment by moorl** [comment]
Hi @pantrtxp 
Currently not for me, because i use relative paths now. But would be nice if this is possible in the future.

**Comment by pantrtxp** [comment]
Okay, we'll keep track of this but I'll close this issue and create an Ticket for us. Our Member @klarstil is currently out of office fore some time. Maybe he'll get back to you about this issue.

Thanks for informing us.
