### ISSUE TITLE
Master broken: can't open backend

### ISSUE THREAD

**Issue by moorl** [shopware/shopware#137]
Notice: Undefined index: class
Shopware\\Core\\Profiling\\Doctrine\\{closure}
Shopware\\Core\\Profiling\\Doctrine\\DebugStack

https://github.com/shopware/platform/commit/d0c6c7c87e93ea78e1220a669bba5c667e16038b#diff-7c1257b179104a6d17e242dfbe97f399

**Comment by klarstil** [comment]
Hey @wa-pgeorg your issue is related to this issue: https://github.com/shopware/development/issues/50

I'll close yours as duplicate.
