### ISSUE TITLE
TypeScript-Support in SW6-Administration

### ISSUE THREAD

**Issue by spieles21** [shopware/shopware#1377]
Dear Shopware team,

i'm currently in the process of writing a new plugin for SW6. Here the question arose,
whether it is possible to use TypeScript natively in the administration. (compiling to JS takes over the build process e.g.)

Are there currently plans to use TypeScript in the SW6 administration?

Thank you in advance.

**Comment by mitelg** [comment]
it is already possible to use typescript :wink: we had the same chat today in our [community slack](https://shopwarecommunity.slack.com/archives/C011VFQT7GB/p1601310851402000)
to cite my colleague @jleifeld :
> You could use Typescript if you want. But I don´t know if its extremely useful because our Admin API has no type definitions and therefore you need to write your own definition file.
