### ISSUE TITLE
Developer friendly plugin policy

### ISSUE THREAD

**Issue by bergstar** [shopware/shopware#138]
Please consider this workflow, and see maybe you can change it. Simple developer use case might be something like: 
"Oh I want to contribute with a plugin or translation."

Step 1. Setup local dev enviroment
Step 2. Register an account at https://account.shopware.com
Step 3. Buy a domain and verify it at https://account.shopware.com/shops/shops
Step 4. "Buy" a free open source plugin at the https://store.shopware.com
Step 5. Try to locate source code locally and make sense what has been installed. 
Step 6. Make local adjustments and contribution as intended.
Step 7. What to do now - can I even publish it on github?

It is all great that you sponsor VueJS and try to be developer friendly. But at the current state it is not possible to use or develop this project as open source. And I understand it is exactly how Magento 2 and PrestaShop operates. But that is also the very reason they are not exactly popular among the developers.

**Comment by Phil23** [comment]
Hey @bergstar,

thank you for your feedback. With shopware 6 we are working on becoming more and more open source. As you already know the code of the shopware 6 platform is already available on GitHub and you can start to contribute to the shopware core right away. Also plugins which are developed by us inhouse for the shopware 6 platform will be available on GitHub. For example you can find our PayPal integration and the data migration tool already here:

https://github.com/shopwareLabs/SwagPayPal
https://github.com/shopwareLabs/SwagMigration

More plugins will follow. In case of other community or third-party plugins we do not have the responsibility to publish them. It depends on the creator of the plugin if he wants to publish it or not. Of course we try to encourage our partners to do so.

If you want to contribute to the translations of shopware you can find all languages on crowdin:

https://crowdin.com/project/shopware6

If you want to learn more about the possibilities as a developer of the shopware community you can find more information here:

https://www.shopware.com/en/community/developers/


I hope this information helps you to understand our open source strategy. We appreciate every contribution or community project regarding shopware.

Greetings,
Phil
