### ISSUE TITLE
Encoding != Verschlüsselung

### ISSUE THREAD

**Issue by bh** [shopware/shopware#1380]
https://github.com/shopware/platform/blob/870f58f4f036dc063b5ca233a3ac1ba5fc4d7d18/src/Administration/Resources/app/administration/src/module/sw-sales-channel/snippet/de-DE.json#L123-L124

Also "Encoding" mit "Verschlüsselung" zu übersetzen ist hier absolut falsch. Im Kontext von UTF-8 etc. ist das eine "Zeichenkodierung". Im Deutschen kann man das ruhig auch "Encoding" nennen. Bitte richtig übersetzen.

Danke! 👍

**Comment by JoshuaBehrens** [comment]
I added a pull request for it
