### ISSUE TITLE
Database Dump creation and import via bin/console

### ISSUE THREAD

**Issue by ts-mothership** [shopware/shopware#1385]
**Description**  
As a shop maintainer I have to create database dumps on a regular basis. Although there are possibilities with mysqldump, we would like a shortcut command that automatically loads the Shopware Configuration containing database credentials and uses mysqldump to create a dump file.
Conversely, there should also be a database:import command that takes the dump file and imports it into the MySQL server (e.g. a Dev-System).

Benefits:
- There is a common way to dump the database
- Future enhancements like DB anonymization could be added
- Smaller risk of exposing database password when using mysqldump in terminal

**Example**  
Magento's magerun command https://n98-magerun.readthedocs.io/en/latest/commands/db.html#db-dump adapted to bin/console:
```bin/console database:dump [-t|--add-time[=...]] [-c|--compression=...] [--only-command] [--print-only-filename] [--no-single-transaction] [--human-readable] [--stdout] [-s|--strip[=...]] [-f|--force] [filename]```

**Comment by shyim** [comment]
Why? There are many other tools which fits much better than doing implementing an own thing here. I don't see it in Core. Maybe an extension

**Comment by ts-mothership** [comment]
Hi @shyim , at the moment we're doing a weekly dump and we're planning to increase the frequency as well as doing a dump each time we deploy your code. I'm sure we're not the only one doing dumps on a regular bases.

The main reason why I believe a command makes sense is that not everyone wants to create a shell script for dumping, because either you have to provide the database credentials directly in the shell script (or parameter) or need to read the .env. To properly read a dotenv file in shell external modules are recommended (bashup/dotenv).

Since Shopware already has the database connection, it could proxy to mysqldump. Also there are already database commands available in bin/console.

**Comment by JoshuaBehrens** [comment]
Yes, shopware has the connection. The hosting environment can change and the command would probably still work. I have scenarios where I could not make use of this command as my connection is bound to a user that is not able to do everything on the database. How should this command know what to export? Every table in the database? What about views (shopware is not using views and therefore would not care for them)? Every table that has an entity definition (RIP cart)? Who is importing that file? How will the database be resetted on an import? Where to export? That is also a question up for the hosting.

Database anonymization is already a feature of other dumping tools. In the past I made good experiences with mysqldump, mysqlpump, pynonymizer, anonymize-mysqldump and mysqldump-php. These tools also work when shopware isn't. Changing/reading the content of the database in a non-business-workflow-related manner should be a task for some sort of admin user. As you are not switching hosting environments too often you can specialize it for your hosting and your workflows. Those workflow intergrations most often work for other projects that are not shopware (yes, these exist 😅) so you do not have to add this kind of command in every project.

**Comment by ts-mothership** [comment]
@JoshuaBehrens I agree to your points. :smile:

In our case a proxy to mysqldump + gzip would be enough, which the equivalent Magento command supported (` cd /project/ && magerun db:dump --compression="gzip" <file>`). When I get time, I'm trying to contribute as well. Eventually it's up to Shopware to decide if they want to implement such a command and what should be part of the command. I'm just saying that a helper command would be probably appreciated in the community. :wink:

**Comment by ts-mothership** [comment]
Solved internally by ourselves. We added new bash scripts in bin directory. A few things can be optimized but this is the general idea:

bin/database-dump.sh
```
#!/usr/bin/env bash
FILE="${1}"
BIN_DIR="$(cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
PROJECT_ROOT="${PROJECT_ROOT:-"$(dirname "$BIN_DIR")"}"
set -o allexport; source "${PROJECT_ROOT}/.env"; set +o allexport

DB_HOST=$(php -r "echo parse_url('${DATABASE_URL}', PHP_URL_HOST);")
DB_PORT=$(php -r "echo parse_url('${DATABASE_URL}', PHP_URL_PORT);")
DB_USER=$(php -r "echo parse_url('${DATABASE_URL}', PHP_URL_USER);")
DB_PASS=$(php -r "echo parse_url('${DATABASE_URL}', PHP_URL_PASS);")
DB_NAME=$(php -r "echo trim(parse_url('${DATABASE_URL}', PHP_URL_PATH), '/');")

mysqldump --lock-tables=false --no-tablespaces --routines -h ${DB_HOST} -P ${DB_PORT} -u ${DB_USER} -p${DB_PASS} ${DB_NAME} |gzip > "${FILE}"
```

bin/database-import.sh:
```
#!/usr/bin/env bash
FILE="${1}"
BIN_DIR="$(cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
PROJECT_ROOT="${PROJECT_ROOT:-"$(dirname "$BIN_DIR")"}"
set -o allexport; source "${PROJECT_ROOT}/.env"; set +o allexport

DB_HOST=$(php -r "echo parse_url('${DATABASE_URL}', PHP_URL_HOST);")
DB_PORT=$(php -r "echo parse_url('${DATABASE_URL}', PHP_URL_PORT);")
DB_USER=$(php -r "echo parse_url('${DATABASE_URL}', PHP_URL_USER);")
DB_PASS=$(php -r "echo parse_url('${DATABASE_URL}', PHP_URL_PASS);")
DB_NAME=$(php -r "echo trim(parse_url('${DATABASE_URL}', PHP_URL_PATH), '/');")

ARGUMENTS=$(cat <<-END
    --default-character-set=utf8
    -P ${DB_PORT}
    -h ${DB_HOST}
    -u ${DB_USER}
    -p${DB_PASS}
END
)

echo "DROP DATABASE IF EXISTS ${DB_NAME};" | mysql ${ARGUMENTS}

echo "CREATE DATABASE ${DB_NAME};" | mysql ${ARGUMENTS}

gunzip -k -c ${FILE} | sed 's/DEFINER=`.*`@`%`/DEFINER=`'${DB_USER}'`@`localhost`/g' | mysql ${ARGUMENTS} ${DB_NAME}
```

**Comment by JoshuaBehrens** [comment]
@ts-mothership thanks for sharing your code :) When we dump dbs we have --hex-blob in mysqldump. Maybe this is beneficial for you
