### ISSUE TITLE
Wrong node version requirement?

### ISSUE THREAD

**Issue by didi-at-work** [shopware/shopware#14]
https://github.com/shopware/platform/blob/80a5bf385d312946361ea607b04bc1d700c9b48f/src/Administration/Resources/administration/package.json#L130

Trying to build with node 8.14.0 this exits out with an error. Shouldn't the line read
`    "node": ">=6.14.0 || >=8.10.0 || >=9.10.0",`
?

**Comment by klarstil** [comment]
Hey @didi-at-work,
you're right, the version isn't matching correctly. Thanks for pointing it out 👍 I'll create a PR in a few and will fix it.
Best regards
