### ISSUE TITLE
Rule Builder only works on first position of the product

### ISSUE THREAD

**Issue by skyracer2012** [shopware/shopware#1404]
**Description**  
Lets say you have a rule which is supposed to remove a shipping method if any item in your cart has the category "restricted goods".

If I now create a rule which does exactly that (first attached image) and have a product in category "restricted goods" as the first product entry in your basket, it will restrict your shipping method because it is not mathing the rule (second attachment).

If you now have a product in the first item slot (index 0) which is matching that rule and another product being in the "restricted goods" category in any other index (here index 1) it doesnt check all positions for the matching rule.

In other words rules do not check if every product in your basket is matching it but will enable the shipping method if any product matches it even if there is one product not matching it.

**Possible Solution**  
My suggestion is to make it configurable if the rule should apply on every product or just one product in the basket.
**Additional context**  
![image](https://user-images.githubusercontent.com/31547155/95491402-d69a1300-0999-11eb-88c7-f4672ff93261.png)
![image](https://user-images.githubusercontent.com/31547155/95491888-8e2f2500-099a-11eb-9bda-2901e5e1579b.png)
![image](https://user-images.githubusercontent.com/31547155/95492029-c59dd180-099a-11eb-9027-e5092a45d3c3.png)
![image](https://user-images.githubusercontent.com/31547155/95493157-5fb24980-099c-11eb-8d6b-fffbc00b683b.png)
![image](https://user-images.githubusercontent.com/31547155/95493201-722c8300-099c-11eb-8434-24c30de96283.png)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
