### ISSUE TITLE
Storefront PDP only shows single property option

### ISSUE THREAD

**Issue by runelaenen** [shopware/shopware#1412]
**Description**  
The product page only shows 1 option value per property group, also when multiple are selected.
This used to be working correctly in earlier shopware versions.

**Possible Solution**  

**Additional context**  
![Screenshot 2020-10-13 at 11 23 08](https://user-images.githubusercontent.com/3930922/95842328-b4601680-0d46-11eb-8bff-66298221f270.png)
![Screenshot 2020-10-13 at 11 23 13](https://user-images.githubusercontent.com/3930922/95842331-b5914380-0d46-11eb-82f4-63f304fee0a5.png)

**Comment by axzx** [comment]
I have encountered it too and am looking for why it is happening.
Interestingly, sometimes there are many options and I don't know what the relationship is.
It would be good to fix this error :)

**Comment by runelaenen** [comment]
> I have encountered it too and am looking for why it is happening.
> Interestingly, sometimes there are many options and I don't know what the relationship is.
> It would be good to fix this error :)

It has already been fixed, it just also has to still get merged 👍  https://github.com/shopware/platform/pull/1413

**Comment by axzx** [comment]
> It has already been fixed, it just also has to still get merged +1 #1413

Yes, I have seen this PR but I wonder why it takes so long.
The lack of all product properties appears to be a serious error.

**Comment by runelaenen** [comment]
> > It has already been fixed, it just also has to still get merged +1 #1413
> 
> Yes, I have seen this PR but I wonder why it takes so long.
> The lack of all product properties appears to be a serious error.

Yes, I think so too...

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
