### ISSUE TITLE
Bug: message:consume consumes 90% CPU with 10k MySQL queries per minute

### ISSUE THREAD

**Issue by ts-mothership** [shopware/shopware#1415]
## Description

The message queue consume command executes ~10k queries/minute and causes high load. Per default It was running as AJAX request in Shopware Admin Interface. After we noticed those AJAX requests taking 30 seconds and causing load on the system, and based on https://docs.shopware.com/en/shopware-platform-dev-en/references-internals/core/module/queue#the-admin-worker we switched to the cli worker (running via supervisor):
`bin/console messenger:consume --limit 50`

Still the message consume command causing a lot of load on the system. Why is that? This command should sleep if there is nothing to do, except when it receives a message.

## Additional context
We’re currently using a basic SW6 Setup on one server with 1 CPU and 2 GB memory. No special configuration except config/packages/shopware.yml:
```
shopware:
  admin_worker:
    enable_admin_worker: false
```

If we disable the message queue, there is no load.

Here’s a picture what happens on MySQL side if the command is running:
<img width="737" alt="screenshot" src="https://user-images.githubusercontent.com/60600855/95878260-4ed74e80-0d75-11eb-88d9-450e08da0c17.png">

Side note:
The command "messenger:stop-workers" does nothing with standard configuration, because app cache is set to 'cache.adapter.array'. Only by overwriting cache.yaml and setting 'cache.adapter.filesystem' those commands can communicate.

**Comment by ts-mothership** [comment]
**Update:** Running `bin/console messenger:consume -vv` manually seems to hint to Sitemap generation (endlessly spamming)

```
09:40:02 INFO      [messenger] Shopware\Core\Content\Sitemap\ScheduledTask\SitemapMessage was handled successfully (acknowledging to transport). ["message" => Shopware\Core\Content\Sitemap\ScheduledTask\SitemapMessage^ { …},"class" => "Shopware\Core\Content\Sitemap\ScheduledTask\SitemapMessage"]
09:40:02 INFO      [messenger] Received message Shopware\Core\Content\Sitemap\ScheduledTask\SitemapMessage ["message" => Shopware\Core\Content\Sitemap\ScheduledTask\SitemapMessage^ { …},"class" => "Shopware\Core\Content\Sitemap\ScheduledTask\SitemapMessage"]
09:40:02 INFO      [messenger] Sending message Shopware\Core\Content\Sitemap\ScheduledTask\SitemapMessage with Enqueue\MessengerAdapter\QueueInteropTransport ["message" => Shopware\Core\Content\Sitemap\ScheduledTask\SitemapMessage^ { …},"class" => "Shopware\Core\Content\Sitemap\ScheduledTask\SitemapMessage","sender" => "Enqueue\MessengerAdapter\QueueInteropTransport"]
09:40:02 INFO      [messenger] Message Shopware\Core\Content\Sitemap\ScheduledTask\SitemapMessage handled by Shopware\Core\Content\Sitemap\ScheduledTask\SitemapGenerateTaskHandler::__invoke ["message" => Shopware\Core\Content\Sitemap\ScheduledTask\SitemapMessage^ { …},"class" => "Shopware\Core\Content\Sitemap\ScheduledTask\SitemapMessage","handler" => "Shopware\Core\Content\Sitemap\ScheduledTask\SitemapGenerateTaskHandler::__invoke"]
```

**Comment by dominikmank** [comment]
> **Update:** Running `bin/console messenger:consume -vv` manually seems to hint to Sitemap generation (endlessly spamming)
> 
> ```
> 09:40:02 INFO      [messenger] Shopware\Core\Content\Sitemap\ScheduledTask\SitemapMessage was handled successfully (acknowledging to transport). ["message" => Shopware\Core\Content\Sitemap\ScheduledTask\SitemapMessage^ { …},"class" => "Shopware\Core\Content\Sitemap\ScheduledTask\SitemapMessage"]
> 09:40:02 INFO      [messenger] Received message Shopware\Core\Content\Sitemap\ScheduledTask\SitemapMessage ["message" => Shopware\Core\Content\Sitemap\ScheduledTask\SitemapMessage^ { …},"class" => "Shopware\Core\Content\Sitemap\ScheduledTask\SitemapMessage"]
> 09:40:02 INFO      [messenger] Sending message Shopware\Core\Content\Sitemap\ScheduledTask\SitemapMessage with Enqueue\MessengerAdapter\QueueInteropTransport ["message" => Shopware\Core\Content\Sitemap\ScheduledTask\SitemapMessage^ { …},"class" => "Shopware\Core\Content\Sitemap\ScheduledTask\SitemapMessage","sender" => "Enqueue\MessengerAdapter\QueueInteropTransport"]
> 09:40:02 INFO      [messenger] Message Shopware\Core\Content\Sitemap\ScheduledTask\SitemapMessage handled by Shopware\Core\Content\Sitemap\ScheduledTask\SitemapGenerateTaskHandler::__invoke ["message" => Shopware\Core\Content\Sitemap\ScheduledTask\SitemapMessage^ { …},"class" => "Shopware\Core\Content\Sitemap\ScheduledTask\SitemapMessage","handler" => "Shopware\Core\Content\Sitemap\ScheduledTask\SitemapGenerateTaskHandler::__invoke"]
> ```

same issue here...setting sitemap generation to "manual" solves the issue (for now), but it's not the fix :D

**Comment by patpilus** [comment]
If you analyse the code responsible for Sitemap generation, you can find that it can easily go into infinite loop of messages being produced and handled...

**Comment by StevendeVries** [comment]
I'm guessing you are referring to the `SitemapExporter`? The `$needRun` might be a culprit there since it's based on `$result` which is freshly created within the loop. (just looking at the code)

**Comment by pkramme** [comment]
We are seeing this too across our infrastructure, individual shops regardless of actual use now saturate multiple CPU cores. We were able to fix  this manualy by disabling the task altogether:
```
update system_config set configuration_value = "{\"_value\": \"3\"}" where configuration_key = "core.sitemap.sitemapRefreshStrategy";
```
It is highly critical that a fix is deployed as soon as possible, this is creating major headaches for hosting infrastructure.

**Comment by lroehrs** [comment]
With the configuration from @pkramme we reduce our CPU usage on Shared-Hosting systems from 70-80% to ~20%.
Only a few customers on these systems used Shopware 6.

I write since a few months with shopware about Shopware 6 CPU problems, but the issuese wouldn't recognized.

**Comment by pkramme** [comment]
I am neither a shopware expert nor know a lot of PHP, but if I read this correctly, there is a "is this completed" check missing in [in line 95 of the Scheduled Task](https://github.com/shopware/platform/blob/master/src/Core/Content/Sitemap/ScheduledTask/SitemapGenerateTaskHandler.php#L95), right @patpilus ?

@Shyim Can you help here?

**Comment by ireznik** [comment]
> With the configuration from @pkramme we reduce our CPU usage on Shared-Hosting systems from 70-80% to ~20%.
> Only a few customers on these systems used Shopware 6.
> 
> I write since a few months with shopware about Shopware 6 CPU problems, but the issuese wouldn't recognized.

I contacted the support and asked the same - the answer was simple: no there are no known cpu performance issues

**Comment by shyim** [comment]
The only known problem so far is the Sitemap generation (Configure it manually and run the command). Which is on the roadmap.

The feedback here does not help. Setup a APM (like Blackfire, Tideways) and share with us the logs

**Comment by lroehrs** [comment]
Hi @shyim, 
sry for the late reply.
Here is a 15s trace: 

https://blackfire.io/profiles/c65b2235-6924-4082-97b3-56d8d26b2fda/graph

```
/usr/local/php7.3/bin/php /home/bomermdb/www.bombasei-test.de/bin/console  messenger:consume --time-limit=15
```

And a 30s verbose trace:

https://blackfire.io/profiles/3ce54262-e1f0-491d-b089-40c59191d02c/graph


CMD:
```
/usr/local/php7.3/bin/php /home/bomermdb/www.bombasei-test.de/bin/console  messenger:consume --time-limit=30 -vvv
```

[messenger_consume.log](https://github.com/shopware/platform/files/5567463/messenger_consume.log)
Do you need something else?

**Comment by lroehrs** [comment]
Hi @shyim, 
sry for the late reply.
Here is a 15s trace: 

https://blackfire.io/profiles/c65b2235-6924-4082-97b3-56d8d26b2fda/graph

```
/usr/local/php7.3/bin/php /home/bomermdb/www.bombasei-test.de/bin/console  messenger:consume --time-limit=15
```

And a 30s verbose trace:

https://blackfire.io/profiles/3ce54262-e1f0-491d-b089-40c59191d02c/graph


CMD:
```
/usr/local/php7.3/bin/php /home/bomermdb/www.bombasei-test.de/bin/console  messenger:consume --time-limit=30 -vvv
```

[messenger_consume.log](https://github.com/shopware/platform/files/5567463/messenger_consume.log)
Do you need something else?

**Comment by patpilus** [comment]
> I am neither a shopware expert nor know a lot of PHP, but if I read this correctly, there is a "is this completed" check missing in [in line 95 of the Scheduled Task](https://github.com/shopware/platform/blob/master/src/Core/Content/Sitemap/ScheduledTask/SitemapGenerateTaskHandler.php#L95), right @patpilus ?

@pkramme apologise for the delayed response, but I didn't receive notification. 

Yeah, the problem from my perspective lies in the line you mentioned. Each time when `SitemapGenerateTaskHandler` `handle` function is called it generates new `SitemapMessage` which is handled by the same handler. It generates new message and so on...

Maybe someone from Shopware will correct me, but it looks like an infinite loop - we had exactly the same behaviour like described in the topic and must set sitemap generation strategy to manual.

If you want to have this functionality you can probably use `sitemap:generate` console command as a cronjob.

**Comment by lutek** [comment]
I have the same problem, clean installation of shopware.
After switching to the sitemap manual. I still have at `bin/console messenger:consume -vv` database strange load.

<img width="888" alt="image" src="https://user-images.githubusercontent.com/846598/105735565-221a0200-5f34-11eb-8d75-001efad884a7.png">

**Comment by shyim** [comment]
We have changed in 6.4 how the message queue works. It will quit directly when nothing is to do. This should reduce the load
