### ISSUE TITLE
Can't pull master branch using Git for Windows

### ISSUE THREAD

**Issue by GhoulofGSG9** [shopware/shopware#1427]
**Description**
Git for windows relies on the Win32 subsystem APIs. Thus it doesn't support any file name with a reserved character like '<'. So  currently any attempt to pull the master branch of this repository fails with the following error:
```
error: invalid path 'changelog/_unreleased/2020-10-06-fix-systemconfigservice-on-mariabdb-<10.3.22.md
```

For more details please have a look at https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file

**Possible Solution**  
Rename the given file and avoid using potential reserved characters when naming files in the future.

**Additional context**  
It's possible to work around this issue locally but I would prefer not having to do so. Thanks.

**Comment by mitelg** [comment]
there is already a PR fixing this https://github.com/shopware/platform/pull/1426

**Comment by GhoulofGSG9** [comment]
> there is already a PR fixing this #1426

Oh somehow the PR didn't show up in my search before opening this issue. Feel free to close this issue.
