### ISSUE TITLE
problem with composer version

### ISSUE THREAD

**Issue by DevertNet** [shopware/shopware#145]
Hello,

i want to update my test Installation to 6.0.0+ea1.1.
So i changed the shopware/development composer.json to:
`"shopware/platform": "6.0.0+ea1.1"`

But everytime composer want wo "update" to the latest commit...
I tested many more version strings, but no one has worked.

As workaround i am using now the commit hash:
`"shopware/platform": "dev-master#f93d9135e427f55f122b60a186b675d4956288bb"`

But the backend shows the wrong version "v9999999 Developer Version"...

What is the correct version for the composer.json? :)

Best regards,
Leon

**Comment by pweyck** [comment]
Hello DevertNet,

we've pushed a new development release a few minutes ago. You can now checkout development with tag `v6.0.0+ea1.1` and will automatically pull the pinned platform release `v6.0.0+ea1.1`.

Best regards,
Patrick

**Comment by DevertNet** [comment]
Hey Patrick,

i did make a mistake :D
The "problem" was that composer always want to update to 6.0.0.0:
`Installing shopware/platform (6.0.0.0): Symlinking from platform`

But this is correct, because the vendor/shopware/platform folder is symlinked to the the regular platform folder...

So composer says "6.0.0.0", but means "v6.0.0+ea1.1"...

Best regards,
Leon
