### ISSUE TITLE
Update without reseting the database

### ISSUE THREAD

**Issue by DevertNet** [shopware/shopware#146]
Hello,

it would be great if you can make a small how to, to update without reseting the database:
https://docs.shopware.com/en/shopware-platform-dev-en/getting-started/installation-guide#updating-the-repositories

After some research my current update proccess is:

> 1. Change composer.json (of shopware/development):
> e.g. "shopware/platform": "6.0.0+ea1"
> 2. Checkout the correct tag/branch in the platform folder
> 3. run these commands...
> composer update
> ./psh.phar cache
> rm -rf var/cache
> ./bin/console database:migrate --all
> ./bin/console database:migrate --all Shopware
> ./bin/console database:migrate-destructive --all Shopware
> ./psh.phar storefront:install-dependencies
> ./psh.phar administration:build
> ./psh.phar storefront:build
> ./psh.phar cache
> rm -rf var/cache

**Comment by Phil23** [comment]
@DevertNet,

this is not the recommended way to do this, but we are planning to provide a workflow to manage and update shopware installations via Git and Composer. We will update the documentation when we have more information about this option.

Thank you for your feedback!

Greetings,
Phil

**Comment by TormentedSoul666** [comment]
Any news on this? I'm developing a theme, while other people are filling the shop with content.
I need the dev tools in the dev template and can therefore not change to the production template.

**Comment by keulinho** [comment]
Hey @TormentedSoul666,

`./psh.phar update` should help you there, so the workflow would be:

1. check out new version of shopware
1. `composer update`
1. `./psh.phar update`

Kind regards
Jonas

**Comment by TormentedSoul666** [comment]
Thank you @keulinho, shouldn't this be added to doc?
