### ISSUE TITLE
Entity definitions containing the word "Test" incorrectly excluded from validation

### ISSUE THREAD

**Issue by lars-feyerabend** [shopware/shopware#1464]
**Description**  
I was wondering why `bin/console dal:validate` would complain about a missing OneToMany relationship on one of my entities, and not on another, where I used the exact same construct. Turns out, validation of my other entity was completely skipped, because it contains the word "Test" in its name.

**Possible Solution**  
Here's the offending lines in [DefinitionValidator](https://github.com/shopware/platform/blob/master/src/Core/Framework/DataAbstractionLayer/DefinitionValidator.php#L123-L126):

```php
// ignore definitions from a test namespace
if (preg_match('/.*\\Test\\.*/', $definition->getClass())) {
    continue;
}
```

From the code comment I assume that the correct regex that should have been used here is `'/.*\\\\Test\\\\.*/'`, with correctly double-escaped backslashes to match only classes that have a namespace segment of "Test" in them.

**Additional context**  
See the note on [this page](https://www.php.net/manual/de/regexp.reference.escape.php) in the PHP docs.

**Comment by mitelg** [comment]
but it seems to work? https://regex101.com/r/BpoCaK/1 or did I missed a point?

**Comment by lars-feyerabend** [comment]
Yes, you missed the point that to define the perfectly good regex that you used in that online tool in a PHP string, the backslash has to be escaped (because it's an escape character in PHP strings as well).

Quote from doc page above:
> Single and double quoted PHP strings have special meaning of backslash. Thus if \ has to be matched with a regular expression \\, then "\\\\" or '\\\\' must be used in PHP code.

See this: https://3v4l.org/M1pOP (of note: PHP 8 will detect the mistake and throw an error (because `\T` is not a valid regex escape sequence)

**Comment by lars-feyerabend** [comment]
Added in Shopware issue tracker: https://issues.shopware.com/issues/NEXT-11788

**Comment by keulinho** [comment]
I will close this issue here, as there was already a issue tracker ticket for it.
