### ISSUE TITLE
Selected default payment method is not showing at the complete order page.

### ISSUE THREAD

**Issue by chakradharkr** [shopware/shopware#1465]
**Description**  
In the sales channel selected default payment method is "invoice" but at the complete order page "Direct Debit" payment method is showing as a default payment method

**Possible Solution**  
Selected default payment method should be shown at complete order page as a default payment.

![defaultpayment](https://user-images.githubusercontent.com/50448681/97423240-eff90400-1934-11eb-95d7-c37487ed3204.png)

![Screenshot (12)](https://user-images.githubusercontent.com/50448681/97423257-f8513f00-1934-11eb-9ed7-0aa6b4fffe92.png)

**Comment by mitelg** [comment]
what has the customer set as default payment?

**Comment by chakradharkr** [comment]
ok @mitelg sir, Actually customer has selected Direct debit.So it is depend on customer selection.
