### ISSUE TITLE
Using extensions in vue/vuex?

### ISSUE THREAD

**Issue by observant2** [shopware/shopware#150]
I extended the "product" table in my plugin similar to how it is extended in the in-depth-guide. So I have product, a mapping table and a table "country". Now I want to add countries to products in the administration. So I override sw-product-basic-form and write

```javascript
this.product.extensions.countries = countries;
```
Where `product` comes from the product repository and `countries` represents some country entities (with id, name...). When I save the product in the administration, the changes on the edited product that are found by `src/core/data-new/Repository.sendChanges()` are simply the ids like this:

```javascript
{countries: [
    {id: "..."},
    {id: "..."}
]}
```
And the PATCH API call to `/api/v1/product/<productid>` returns the error
```javascript
{"errors":
    [{"code":"FRAMEWORK__WRITE_MALFORMED_INPUT",
       "status":"400",
       "detail":"Expected data to be array.",
       "source":{"pointer":"\/0\/countries\/0"},...
```

Any idea what I'm doing wrong?

**Comment by observant2** [comment]
Wow. Spent two days on this.

It turns out that the ORM fails, when the reference column has the same name as the referenced table. In the bundle example: When you use `bundle` instead of `bundle_id` in the `swag_bundle_product` table and name the references in the OneToMany/ManyToMany functions accordingly, things don't work anymore. 

In my example I just renamed `country` to `country_id` in my mapping table and now stuff works. It had nothing to do with the API call. I guess something weird goes on in doctrine. :thinking:

**Comment by janbuecker** [comment]
I'm glad your problem has been solved. :) Just for clarification: we don't use Doctrine ORM, just Doctrine DBAL, which is a database abstraction layer. :wink:
