### ISSUE TITLE
Image sorting in Gallery CMS element

### ISSUE THREAD

**Issue by runelaenen** [shopware/shopware#1501]
**Description**  
It is not possible to sort images correctly in the CMS element. They are now sorted by ID (I think?) while this should be draggable to have the right customizable order.

**Comment by keulinho** [comment]
Theres already a [issue tracker ticket](https://issues.shopware.com/issues/NEXT-10244) for it. That's currently in progress, so please check for updates there, i'm closing this now as duplicate.
