### ISSUE TITLE
Wrong file path in controller documentation?

### ISSUE THREAD

**Issue by alexschwarz89** [shopware/shopware#1506]
**Description**  
In this documentation
https://github.com/shopware/platform/blob/master/src/Docs/Resources/current/20-developer-guide/20-controller.md on line 53 is stated to write

`<import resource="../../src/Controller" type="annotation" />` inside routes.xml,

but routes.xml is inside the src folder so it would resolve to "Resources/src" which is wrong.

**Possible Solution**  
Change line 53 in docs to
`<import resource="../../Controller" type="annotation" />`

**Additional context**  

Wasn't sure if it's a typo/bug or just dependent of my setup so i didn't create a PR directly.

**Comment by mitelg** [comment]
hey @alexschwarz89 
you are right, this is the wrong path for this example :+1: 

would be nice, if you could create a PR to fix that :blue_heart:

**Comment by alexschwarz89** [comment]
@mitelg PR created ;-)
