### ISSUE TITLE
Cart LineItemCollection cant hold multiple non-stackable products

### ISSUE THREAD

**Issue by JoshuaBehrens** [shopware/shopware#151]
I stumbled upon the parameters in the twig block `page_product_detail_buy_product_buy_info`. Any client can change the `stackable` input to 0. That is a nice feature I want to use. When I add a product with `stackable` set to 0/false my cart crashes and this is not fixable in an easy way without some discussion so I start one :wink: 

Facts:
* You can't change the quantity of a `LineItem` if it is non-stackable. throw Exception
* A `LineItemCollection` groups `LineItem`s by their id and expects multiple `LineItem`s to have same type if they share the id :+1: 
* The `LineItemCollection` sums just quantities (no children :warning:) if one add an a `LineItem` with an id already in the collection
* A product `LineItem` has the product id as `LineItem.id` :thinking: 
* The `CartService` has no interface
* The `CartService` dispatches an event on adding an item after the collection was changed

Problem occurs when you add a non-stackable product `LineItem` twice. This ends up in the `LineItemCollection` seeing the same `LineItem` and it is up to merge the quantities. This will fail as the `LineItem`s are not stackable. Easy. Just use different ids. But then the product `LineItem`s need to have someone to merge them as their ids now differ although they link to the same product.
What really grind my gears: Why are the product `LineItem`s keyed with the product id when the product id is in the `referencedId` field? This means that two products in a cart are not allowed to be different. Shouldn't a `LineItem` have a unique id everytime you add it to a collection? Why should one add a `LineItem` to the cart and already know the primary key for it?
It is ok for me if you have to add it with a generated UUID because I still don't know it in before hand.

**Comment by OliverSkroblin** [comment]
* A product LineItem has the product id as LineItem.id
	* The core uses the product id as line item identifier, because all products which are added by the core can be stacked.

* The CartService has no interface
	* It is not intended to decorate or replace this service 

* Problem occurs when you add a non-stackable product LineItem twice. 	
	* This runs in an exception because the line item is non-stackable ;)

* Why are the product LineItems keyed with the product id when the product id is in the referencedId field? 
	* The product processor uses the referenceId to update the product data (price, name, description, etc.).
	* The core uses the product id as line item identifier to display only one position for a product.

* This means that two products in a cart are not allowed to be different
	* Thats right. The core adds a product as type:product and line-item.id=productId. This is important to validate which price is the current quantity price.
	* If you want to add a product as a single row, simply add generate a unqiue key and provide it as line item key.


The following example shows how to add the same product twice but as single row in the cart:

```
/** @var EntityRepositoryInterface $repo */
$repo = $this->get('product.repository');

$product = $repo->search((new Criteria())->setLimit(1), $context->getContext())->first();

$service = $this->get(CartService::class);
$cart = $service->getCart(Uuid::randomHex(), $context);

/** @var ProductEntity $product */
$lineItem = (new LineItem('test-1', LineItem::PRODUCT_LINE_ITEM_TYPE, $product->getId(), 1))
    ->setRemovable(false)
    ->setStackable(false);

$cart = $service->add($cart, $lineItem, $context);

/** @var ProductEntity $product */
$lineItem = (new LineItem('test-2', LineItem::PRODUCT_LINE_ITEM_TYPE, $product->getId(), 1))
    ->setRemovable(false)
    ->setStackable(false);

$cart = $service->add($cart, $lineItem, $context);
```	

Can you provide an use case which is not possible with the current cart implementation?

**Comment by JoshuaBehrens** [comment]
> The core uses the product id as line item identifier, because all products which are added by the core can be stacked.

So a product `LineItem` is doomed to be stackable by type? Is there a need to pass both information? Feels like any `LineItem` is doomed to be stackable. The stackable information isn't used elsewhere but the quantity change.
My current understanding: If I want to stack, I use the same id. That's it.

Can I generate a UUID in the twig template without being cached? I think I have to make an own storefront controller for that.

> It is not intended to decorate or replace this service

Meeh, but ok so far (although I stated differently on the q/a to the presentations this year :stuck_out_tongue:). Just wanted to point out that there is no real way to intercept the process before the collection manipulation happens.

In my case I want to customize a product with an uploaded file. So I store the uploaded file, track it in a table and want to connect that one to a line item id. I can't order two different configured products in the same cart as their quantities gets merged and my second file is sort of lost.

In my current attempt I am up to create children for this product so the products gets merged correctly (after I merged the children in as well) but still have multiple configurations on them. Is that a way to go? More properties of the product like price and delivery depends on that configuration as well.

**Comment by OliverSkroblin** [comment]
Hey,

A product doesn't have to be stackable in the cart, as you can see in the above example source code.
For your special use case, I would simply generate a random uuid every time you add a product with an uploaded image to your cart and use it as line item id. 

Unfortunately I can't tell you how to generate a uuid in twig that is not cached. I would rather write my own controller to put the product with the picture into the cart.

**Comment by JoshuaBehrens** [comment]
For now I've added an own controller. That really worked out quite well. I just had to do a lot of changes everywhere the line item had to behave different as well. But that is part of adding a new line item type. I also found an issue about the fact `LineItem.id = LineItem.referencedId = product.id` and fixed it: https://github.com/shopware/platform/pull/174

For now as I got a better understanding of the cart this issue can be closed but I still think that the stacking functionality in the `LineItemCollection` where the quantities are summed up is still weird as lots of other information can get lost if one is not aware of the update/patch routines. This merging should rather throw a `KeyAlreadyInCollectionException` which makes everyone merge items for themselves as everyone got in ones mind *I rather find an existing item and update it*.

**Comment by OliverSkroblin** [comment]
Hi @JoshuaBehrens,

thanks for the #174 😄 . 
If you have any further questions about the cart, please do not hesitate to contact me. We can also simply make a phone call, then I could also include the open questions in a FAQ.

**Comment by JoshuaBehrens** [comment]
:call_me_hand: ? That is new to me. Maybe I come back to it later. Thanks so far

**Comment by almare** [comment]
I think I have to reopen this issue. I ran into a similar problem described by Joshua. 
What happens if I would like to extend Joshuas Product with an gift package extension. I extend the product form with an selection of giftpackages. Do I also have to overwrite the product with an custom uuid like Joshua did, because I don't know if the product uses his plugin extension or not. If yes, does his extension still work, or must I look for his plugin and how he did change the uuid?

Another more real life example: The gift package extension has 3 options (No gift package, Flowers, Planes).
Every product should be stackable on his own. Because I would like to buy the product once with no gift package, one with plane packaging and one with flower packaging. 

Then I found out uiii I forgot one birthday child and would like to add the same product once more with plane packaging. For now I have 3 times the same product inside the cart, with different gift packages. By the way the gift packages are childs of the line item!

I think this behavior is not uncommon.

**Comment by JoshuaBehrens** [comment]
I expect that our plugins would not be compatible at first.

You have to reverse the tree. You add gift packages and their children are the gifted/wrapped products.

**Comment by almare** [comment]
> I expect that our plugins would not be compatible at first.

This already a problem now for me. I have 2 plugins which could add childs to the same product on different combinations. The current situation make it impossible to add different combinations and additionally it's incompatible to other developer extensions. The example of the gift package is just a simplification, so what should i do in the case described above with 2 plugins. Correct  me if I am  wrong. As far I understand you right I have to inverse the tree, but to which line item?

**Comment by almare** [comment]
@OliverSkroblin any suggestions how to handle this behaviour. Specially if I as a developer don't want to break cart extensions from other developers?
