### ISSUE TITLE
Cannot remove value of date type custom field

### ISSUE THREAD

**Issue by zaifastafa** [shopware/shopware#1510]
**Description**  
Setting a blank value to a `datetime` custom field does not make it blank. For e.g if I have entered a value in a datetime custom field, but later want to delete it, then setting it to an empty value does not overwrite it. Instead the previous value is still there. 

**Possible Solution**  
Allow empty values in datetime.

**Additional context**  
![image](https://user-images.githubusercontent.com/24492269/99253891-533ecd80-2833-11eb-8808-3530bee1ddeb.png)

**Comment by keulinho** [comment]
There was already a [issue tracker ticket](https://issues.shopware.com/issues/NEXT-12220) for this, so i'll close this as duplicate.
