### ISSUE TITLE
DAL documentation needs to be completed

### ISSUE THREAD

**Issue by alexschwarz89** [shopware/shopware#1516]
**Description**  
The DAL documentation is incomplete. A typically needed function like insertOrUpdate exists (upsert), but it's missing completely in DAL documentation as well as Database access section. 

https://docs.shopware.com/en/shopware-platform-dev-en/developer-guide/database?category=shopware-platform-dev-en/developer-guide
https://docs.shopware.com/en/shopware-platform-dev-en/references-internals/core/dal

**Comment by shyim** [comment]
We have new docs which are more complete then the old ones now: https://developer.shopware.com
