### ISSUE TITLE
Error when indexing products with extended prices into Elasticsearch

### ISSUE THREAD

**Issue by henrikvolmer** [shopware/shopware#1527]
**Description**  
Error when indexing products with extended prices into Elasticsearch.

The following error occurs:

`app.ERROR: mapper [listingPrices.from.listPrice.gross] cannot be changed from type [float] to [long]`

**Possible Solution**  
#1526 

**Additional context**

**Comment by shyim** [comment]
We have refactored entirely Elasticsearch in 6.4. Can you check there too?
