### ISSUE TITLE
Can't assign landingpages (Shopping Experiences)

### ISSUE THREAD

**Issue by d42me** [shopware/shopware#153]
In the current version it's impossible to assign a landingpage or to set the url for it.

**Comment by pantrtxp** [comment]
Could you please specify more details for your problem? I just tested the assignment in 6.0.0+ea1.1 and on the master branch. All works fine for me. Did you assign your landingpage to a category?

**Comment by d42me** [comment]
Yeah that is working. But can you assign it also for the homepage?

**Comment by pantrtxp** [comment]
What exactly does "homepage" mean?
If you mean your start page of the storefront simply assign the layout to the first level of your categories

**Comment by d42me** [comment]
@pantrtxp Thanks solved my issue! Maybe add this to the documentation.
