### ISSUE TITLE
API register call should respond with a context token for guest users

### ISSUE THREAD

**Issue by Der-Alex** [shopware/shopware#1531]
**Description**  
The shopware api documentation (https://docs.shopware.com/en/shopware-platform-dev-en/store-api-guide/account?category=shopware-platform-dev-en/store-api-guide#register) says, that either `/store-api/v3/account/register` or `/store-api/v3/account/register-confirm` **gives a logged in context-token**. Unfortunately this token doesn't exist as a part of the  response data for registrations as a **guest**. The new token only exists in the response header. This new token can only be accessed when the webserver is properly configured with `Access-Control-Expose-Headers sw-context-token`. Otherwise, clients like e.g. axios won't expose this custom header. 

The solution to this should be, that the `sw-context-token` is part of the response data, just as it is in other api calls (e.g. login).

**Comment by dm-heinze** [comment]
This issue makes a checkout process as a guest impossible via store-api endpoints. Until fixed, we have to use the sales-channel api for guest checkout.

**Comment by shyim** [comment]
The api returns it in the response header

**Comment by Der-Alex** [comment]
Hi @shyim. This is a very frustrating solution to just close the ticket with the response, that the api returns the token in the header, what i already said in my issue. Nearly every api call in shopware 6 returns the context token as part of the response body, so this api call should behave the same. 
Please reopen this one becaue I think many developers would benefit from this tiny fix.
thanks

**Comment by shyim** [comment]
The context token should be not in the response, as there are normally entities encoded. I have created an issue in the tracker to unify it to the response header on all api calls and remove that body in future version https://issues.shopware.com/issues/NEXT-17944?
