### ISSUE TITLE
6.3.4.0 - @Storefront/storefront/layout/meta.html.twig wird mehrfach eingebunden

### ISSUE THREAD

**Issue by marvinschroeder** [shopware/shopware#1539]
Die @Storefront/storefront/layout/meta.html.twig wird mehrfach in die Seite eingebunden.

Meta-Tags bzw. das View @Storefront/storefront/layout/meta.html.twig werden anscheinend immer dort eingebunden, wo es in irgendeiner Weise verwendet wird. Vor allem an Stellen, an denen von anderen Views Dinge in der meta.html.twig Datei "überschreiben" wollen.

Siehe Screens:

Es gibt 5 x die Stylesheet Datei:
https://www.dropbox.com/s/63h6ijdcjdqxzex/meta-tag-code.png?dl=0

Es wird an mehreren Stellen die Datei - anscheinend vollständig - inkludiert:
https://www.dropbox.com/s/sx8kvobycldd7wb/meta-tag-profiler.png?dl=0

**Comment by Phil23** [comment]
Hey @marvinschroeder,

thank you for reporting this. I have imported this to our internal issue tracker.

https://issues.shopware.com/issues/NEXT-12451

Thank you!
