### ISSUE TITLE
Media urls

### ISSUE THREAD

**Issue by ghost** [shopware/shopware#154]
Not sure if this is an issue but here it goes:

If you set up multiple domains on a storefront
The media url is generated from the domain you made it from

Replicate issue:

1. Make two domains for a Storefront
2. From domain A go to the theme, set a logo (save...)
3. From domain B go to the frontend, inspect the media url of the logo
    It will be http://domainA/media...
    instead of 
    http://domainB/media...

I think the media prefix should be dynamic based on the domain you are on
Not on the domain source....

**Comment by janbuecker** [comment]
The sales channels don't have any configuration for a CDN *yet*. You can only configure a CDN for the whole system. So in your scenario, every media file would be served from the globally configured url.

The use a global CDN url, update your project config yaml file:

```yaml
shopware:
    cdn:
        url: https://cdn.domain.com
```

I've created a ticket for the feature request. You can track the status here: https://issues.shopware.com/issues/NEXT-4754
