### ISSUE TITLE
JS-Utils ==> Plugins?

### ISSUE THREAD

**Issue by tinect** [shopware/shopware#1540]
**Description**  
https://issues.shopware.com/issues/NEXT-7553
The Problem is the AjaxModalExtensionUtil which is no plugin.

**Possible Solution**  
Make plugins from Utils and mark Utils deprecated.
I'd create a PR for it if it's a way to go.

**Additional context**

**Comment by mitelg** [comment]
@tinect there was someone faster :wink: https://github.com/shopware/platform/pull/1214

you may want to add your 2 cents to this PR :blush:

**Comment by tinect** [comment]
@mitelg Ahhhh, thank you for keeping an eye on everything and helping blind people!

**Comment by JoshuaBehrens** [comment]
Got you covered @tinect ;)
