### ISSUE TITLE
Import of products with variations bug

### ISSUE THREAD

**Issue by ZigaVukcevicDev** [shopware/shopware#1545]
**Description**  
Import of product with variations not working.
v6.3.3.1 Stable Version

**Additional context**  
I am trying to import product with 2 variations. My properties are already set up by CMS admin. I am enclosing CSV files:
- product import and
- product variations import.

[import-files.zip](https://github.com/shopware/platform/files/5616255/import-files.zip)

Here is the flow.

1. Importing products (works ok)

![Screenshot 2020-11-30 at 14 42 06](https://user-images.githubusercontent.com/10107183/100617050-3d90d400-331a-11eb-998a-7f608356cf05.png)

2. I am getting product id from URL and set it in CVS file, then importing variations (works ok)

![Screenshot 2020-11-30 at 14 44 00](https://user-images.githubusercontent.com/10107183/100617243-8779ba00-331a-11eb-93a2-91a6e73e012b.png)

3. Going to product and try to generate variations hangs

As you can see, my properties are already selected as expected.

![Screenshot 2020-11-30 at 14 45 17](https://user-images.githubusercontent.com/10107183/100617369-b6902b80-331a-11eb-8efb-d68330d64103.png)

But when trying to generate them, app hangs like this.

![Screenshot 2020-11-30 at 14 46 08](https://user-images.githubusercontent.com/10107183/100617442-ce67af80-331a-11eb-9bea-417103a667cd.png)

Is there any other/prefered way of importing product with variations?

**Comment by keulinho** [comment]
This should have been fixed in this [ticket](https://issues.shopware.com/issues/NEXT-16935).
