### ISSUE TITLE
Apps: Twig set function doesn't work

### ISSUE THREAD

**Issue by ROBJkE** [shopware/shopware#1550]
**Description**  
if i try to `{% set someVar = 'string' %}` in a Twig Template for my App that doesn't work.  
It doesn't even recognize `someVar` if I `dump()`.  

I think it's really nessecary to provide this function in Apps.  

I use SW 6.3.2.0 with the SaaS Plugin

**Comment by shyim** [comment]
This has nothing to do with the Apps. That's how Twig works:  https://twigfiddle.com/8oz2tv they are scoped to the block

**Comment by ROBJkE** [comment]
thats right. i missed that point. no bug at all. closed
