### ISSUE TITLE
Docs: Registering new block for CMS

### ISSUE THREAD

**Issue by ZigaVukcevicDev** [shopware/shopware#1552]
When registering [new custom block](https://docs.shopware.com/en/shopware-platform-dev-en/developer-guide/cms?category=shopware-platform-dev-en/developer-guide), I think the code should be:

```
import { Component } from 'src/core/shopware';
...

Component.register('sw-cms-block-...', {
  template
});
```

instead of

```
import template from './sw-cms-block-image-text-reversed.html.twig';
import './sw-cms-block-image-text-reversed.scss';

Shopware.Component.register('sw-cms-block-image-text-reversed', {
    template
});
```

Please check all other occurrences.

**Comment by shyim** [comment]
We have updated the docs: https://developer.shopware.com/docs/guides/plugins/plugins/content/cms/add-cms-element
