### ISSUE TITLE
Unable to push orders via admin/sync api.

### ISSUE THREAD

**Issue by radixs** [shopware/shopware#1555]
**Description**  
Hello everyone,
First off - I am not certain if what I will be describing is actually a bug or if I am doing something wrong, but i have followed an example given to me by shopware support and no budge.

I am in a process of migrating a shop based on Magento 1.8 to Shopware 6. The chosen way to do that by my team (the migration plugin works with >=1.9 unfortunately) is to write a script that reads data from magento db directly, does all necessary conversions and then pushes it into Shopware 6 via admin/sync API entity endpoints. We have managed to move everything (customers, categories, products, images, reviews, addresses etc.) except for the orders. The main issue being the fact that orders have states and by default the API token does not seem to have permissions to do operations on these fields (only core can).

Here is what I went through already:
Initially I tried pushing the order by pushing entities separately - first the `order` entity itself (with `price` body, `shippingCosts` body, `lineItems` and `orderCustome`r) - but pushing just that would have the orders list in admin panel hang (see attachment). Then I added `order_address` and `order_delivery`... and here I ran into a wall where it would not let me set the `stateId` because the API token does not have permissions to write to that field.
At that point I have written to shopware support and asked for help. They have returned to me with an advice to use sync api instead and provided me with an example of a request. Here it is:

```
{
    "write-my-new-order": {
        "entity": "order",
        "action": "upsert",
        "payload": [
            {
                "id": "f3240c6dc8db4de2bca5388252894666",
                "billingAddress": {
                    "id": "f3240c6dc8db4de2bca5388252894111",
                    "firstName": "John",
                    "lastName": "Doe",
                    "street": "John-Doe Street 13",
                    "zipcode": "11111",
                    "city": "Schöppingen",
                    "countryId": "3dadd0e8681e418a9e77505d01babe60",
                    "salutationId": "e2ca107f30784b6aba64f64a614b7b8f"
                },
                "billingAddressId": "f3240c6dc8db4de2bca5388252894111",
                "orderCustomer": {
                    "groupId": "cfbd5018d38d41d8adca10d94fc8bdd6",
                    "defaultPaymentMethodId": "0c10a352281942b8b45aa73d9c6f1ac8",
                    "firstName": "John",
                    "lastName": "Doe",
                    "email": "john@doe.com",
                    "salutationId": "e2ca107f30784b6aba64f64a614b7b8f",
                    "addresses": [
                        {
                            "id": "f3240c6dc8db4de2bca5388252894113",
                            "firstName": "John",
                            "lastName": "Doe",
                            "street": "John-Doe Street 13",
                            "zipcode": "11111",
                            "city": "Schöppingen",
                            "countryId": "3dadd0e8681e418a9e77505d01babe60",
                            "salutationId": "e2ca107f30784b6aba64f64a614b7b8f"
                        }
                    ],
                    "salesChannelId": "98432def39fc4624b33213a56b8c944d",
                    "defaultBillingAddressId": "f3240c6dc8db4de2bca5388252894113",
                    "defaultShippingAddressId": "f3240c6dc8db4de2bca5388252894113",
                    "customerNumber": "10000"
                },
                "customerId": "f3240c6dc8db4de2bca5388252894111",
                "salesChannelId": "98432def39fc4624b33213a56b8c944d",
                "stateId": "00c0d8f50624490993d8dafb9d27ece4",
                "currencyId": "b7d2554b0ce847cd82f3ac9bd1c0dfca",
                "orderDateTime": "2020-10-21T14:00:00Z",
                "price": {
                    "netPrice": 15514.19,
                    "taxRules": [
                        {
                            "taxRate": 0.0,
                            "extensions": [],
                            "percentage": 100.0
                        },
                        {
                            "taxRate": 7.0,
                            "extensions": [],
                            "percentage": 100.0
                        }
                    ],
                    "taxStatus": "gross",
                    "totalPrice": 16174.02,
                    "positionPrice": 16174.02,
                    "calculatedTaxes": [
                        {
                            "tax": 0.0,
                            "price": 6088.04,
                            "taxRate": 0.0,
                            "extensions": []
                        },
                        {
                            "tax": 659.8299999999999,
                            "price": 10085.981308411214,
                            "taxRate": 7.0,
                            "extensions": []
                        }
                    ]
                },
                "shippingCosts": {
                    "quantity": 1,
                    "taxRules": [
                        {
                            "taxRate": 0.0,
                            "extensions": [],
                            "percentage": 37.64085861152638
                        },
                        {
                            "taxRate": 7.0,
                            "extensions": [],
                            "percentage": 62.35914947805934
                        }
                    ],
                    "listPrice": null,
                    "unitPrice": 0.0,
                    "totalPrice": 0.0,
                    "referencePrice": null,
                    "calculatedTaxes": [
                        {
                            "tax": 0.0,
                            "price": 0.0,
                            "taxRate": 0.0,
                            "extensions": []
                        },
                        {
                            "tax": 0.0,
                            "price": 0.0,
                            "taxRate": 7.0,
                            "extensions": []
                        }
                    ]
                },
                "currencyFactor": 1
            }
        ]
    }
}
```
I have adapted my script to use that (also tried without `orderCustomer` and `billingAddress`) and this got me to the same place I initially ran into using the admin api - I get `"success":true` response but it breaks the admin panel order list. 

I have spent many days trying different entity combinations, different orders of making requests etc and nothing is working. So I have started wondering that perhaps there is some kind of a bug on the storefront that makes it unable to load orders pushed using the admin/sync api? I suspect it is because those orders do not have shipment and payment states set (because they are read only for the api) but I might be wrong. Please help!

**Possible Solution**  
A minimal example of how the body of the POST request to the sync api should look like would work. Or if that is not the problem then give the specific API token the right/scope to write to protected fields (or make it configurable).

The solution should enable upsertion of orders via the api and ensure it is structurally okay (states and required actions/transitions got executed without requiring the products to be available).

**Additional context**  
Orders list in administration after the order gets sent in via admin/sync api:
![sync_api_bug](https://user-images.githubusercontent.com/8850714/101507222-a0b3e380-3976-11eb-8192-ec7c84db0b73.jpg)

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
