### ISSUE TITLE
Admin plugin manager UI issues

### ISSUE THREAD

**Issue by aayaresko** [shopware/shopware#1556]
On the plugin manager page in the admin panel.
If we try to sort, go to 'next' page or change the number of items per page, and then click on '...' symbol next to a plugin, we will see that there will be only one option for it - 'uninstall' regardless of whether the plugin has config or not.
None the less, when plugin manager page get's reloaded - when we press '...', we will see that all options are available for the plugin. 

It looks like something wrong with the state management system of the vuejs app

**Comment by runelaenen** [comment]
I've fixed this issue back in july, and it has only gotten the 'scheduled' label a few days ago. Long story short, Shopware should manage it's PRs better, but the problem should be fixed in one of the next releases...

https://github.com/shopware/platform/pull/1163

**Comment by shyim** [comment]
We rewriting the entire plugin manager currently. This should be fixed then.
