### ISSUE TITLE
Plugin Updates not working

### ISSUE THREAD

**Issue by reutli** [shopware/shopware#1559]
Tried to install PlugIn updates.
Clicking on "Aktualisieren" nothing appears and PlugIn is not being updated.

**Comment by maxzirps** [comment]
Try to update it via the terminal and see if there is an error logged

**Comment by reutli** [comment]
nice try but how without ssh on the provider-side?

**Comment by maxzirps** [comment]
Does the console/network tab in your browser output anything?

**Comment by reutli** [comment]
I deleted the PlugIn and reinstalled it with the new version. This was my way. Therefore I'm not able to reconstruct the error.
But it was the second time with a other plugin the error occurred.

**Comment by shyim** [comment]
With the information in this issue we can't do anything. Please create a new Issue with more informations
