### ISSUE TITLE
Cannot delete a NumberRangeType: can not detect foreign key for parent definition

### ISSUE THREAD

**Issue by floriandammeyer** [shopware/shopware#1573]
### Description

We created a plugin that creates a custom `document_type` with its according `number_range` and `number_range_type`. The uninstall action of our plugin should obviously remove all created entries, but when we want to delete the `number_range_type` we get the error 

```
 In VersionManager.php line 794:
                                                                                                            
   [RuntimeException]                                                                                       
   Can not detect foreign key for parent definition Shopware\Core\System\NumberRange\NumberRangeDefinition  
```

### Possible Solution

?

### Additional context

`shopware/platform` version is 6.3.4.1

Our uninstall code is the following. We tried if there is a cascade delete for the `number_range`s, but in the class `NumberRangeTypeDefintion` we saw that the relation is actually set to restrict delete, so we delete the `number_range`s before we delete the `number_range_type`. We tried it without deleting the `number_range`s explicitly, but that resulted in the same error. So the problem must be somewhere in deleting the `number_range_type`.

```
/** @var EntityRepositoryInterface $documentTypeRepository */
$documentTypeRepository = $this->container->get('document_type.repository');
/** @var EntityRepositoryInterface $numberRangeRepository */
$numberRangeRepository = $this->container->get('number_range.repository');
/** @var EntityRepositoryInterface $numberRangeTypeRepository */
$numberRangeTypeRepository = $this->container->get('number_range_type.repository');

/** @var DocumentTypeEntity $documentType */
$documentType = $documentTypeRepository
    ->search(
        (new Criteria())
            ->addFilter(new EqualsFilter('technicalName', AddressLabelGenerator::ADDRESS_LABEL)), 
            $uninstallContext->getContext()
    )
    ->first();

$numberRangeType = $numberRangeTypeRepository
    ->search(
        (new Criteria())
            ->addFilter(new EqualsFilter('technicalName', $this->getNumberRangeTypeTechnicalName())),
        $uninstallContext->getContext()
     )
     ->first();


$numberRanges = $numberRangeRepository
    ->search(
        (new Criteria())
            ->addFilter(new EqualsFilter('typeId', $numberRangeType->getId())),
        $uninstallContext->getContext()
    )
    ->getEntities();

foreach ($numberRanges as $numberRange) {
    $numberRangeRepository->delete(
        [['id' => $numberRange->getId()]],
        $uninstallContext->getContext()
    );
}

$numberRangeTypeRepository->delete(
    [['id' => $numberRangeType->getId()]],
    $uninstallContext->getContext()
);

$documentTypeRepository->delete(
    [['id' => $documentType->getId()]],
    $uninstallContext->getContext()
);
```

I noticed that there is no actual foreign key set up in our database. May that be the problem?

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
