### ISSUE TITLE
Documentation for Entity Types partially outdated

### ISSUE THREAD

**Issue by SironheartAcc** [shopware/shopware#158]
The documentation concerning AssociationFields is outdated.

For example:
[Here](https://docs.shopware.com/en/shopware-platform-dev-en/internals/core/data-abstraction-layer/types?category=shopware-platform-dev-en/internals/core/data-abstraction-layer#onetomanyassociationfield) point 4 is documented to be a `bool $loadinBasic`, which isn't captured in the example on top. 

Also the `bool $loadInBasic` is always written down as 4th argument, which seems to be wrong when looking at the [ManyToOneAssociationField](https://docs.shopware.com/en/shopware-platform-dev-en/internals/core/data-abstraction-layer/types?category=shopware-platform-dev-en/internals/core/data-abstraction-layer#manytooneassociationfield).

I believe this should be fixed to prevent confusion for new developers.

**Comment by OliverSkroblin** [comment]
Hi @Sironheart,

Thank you for pointing that out. I have updated the documentation. The new version will be available in a few minutes.
