### ISSUE TITLE
Google Analytics - Tracking orders several times because of wrong transactionID

### ISSUE THREAD

**Issue by marcmanusch** [shopware/shopware#1586]
**Description**  
https://github.com/shopware/platform/commit/c2dbfb120e21308b9aea245ffb783a48d43db420
By using: 'transaction_id': this.generateUuid() the ID of an oder is random and will be pushed several times, if the customer reloads the page, so the conversions will be counted wrong.

**Possible Solution**  
The transaction_id need to be the orderId of the order, like in Shopware 5.

Google:
https://support.google.com/google-ads/answer/6386790?hl=de

**Additional context**  
![i4HDfW7](https://user-images.githubusercontent.com/31078285/103909393-ebef1c80-5103-11eb-93eb-d2725ec3bedf.png)

**Comment by mitelg** [comment]
hey @marcmanusch 

thanks for your issue. as there is already a ticket for that (https://issues.shopware.com/issues/NEXT-12660) I will close this issue here.

Best regards from Schöppingen
Michael Telgmann
