### ISSUE TITLE
Plugin configuration default values config.xml 

### ISSUE THREAD

**Issue by 0f8** [shopware/shopware#159]
Hi,

is it possible to set a default value in the config.xml of a Plugin? 
https://docs.shopware.com/en/shopware-platform-dev-en/internals/plugins/plugin-config

Thanks

**Comment by mitelg** [comment]
hey @0f8 
this is currently not possible. but there is already a ticket for that. please follow the state here: https://issues.shopware.com/issues/NEXT-3647
