### ISSUE TITLE
storefront:watch broken since June

### ISSUE THREAD

**Issue by audaki** [shopware/shopware#1613]
**Description**  
Since June ./psh.phar storefront:watch is broken due to this commit:

https://github.com/shopware/storefront/commit/0bf72847bba83968ce6f83e11cae00f0fdbc5dc6#diff-7fca9b4ec42e199993d4074fef47a6643235268c9e4464ddbf01fdbec6a6db3d

**Possible Solution**  
Revert the deleted line

**Comment by mitelg** [comment]
you can use `storefront:hot-proxy` instead

**Comment by audaki** [comment]
> you can use `storefront:hot-proxy` instead

Your answer is a workaround (and a different functionality) which does not fix the reported issue. And this is a bug report and not a shopware forum topic asking for help.

Unless you as an official Shopware employee want to say that the storefront:watch functionality is no longer supposed to work? In that case you should remove storefront:watch from the psh.phar file. And in all other cases just readd the line and storefront:watch works again.

**Comment by audaki** [comment]
I've created a pull request for it: https://github.com/shopware/platform/pull/1614

**Comment by mitelg** [comment]
hey @audaki 

sorry that I tried to help you here, so you might could go on with your work :slightly_smiling_face: 

I'm not sure about the intention of the removal. we will clarify that in your PR. thanks for this one, btw :+1:

**Comment by mitelg** [comment]
hey @audaki 

I spoke to my colleague and indeed the command was removed intentionally. We will remove the regarding PSH command. You can find some more information here: https://issues.shopware.com/issues/NEXT-13399
