### ISSUE TITLE
data-toggle plug-ins will not re-initialized after content-replacement by a widget

### ISSUE THREAD

**Issue by Gainto** [shopware/shopware#1618]
Let's take the product listing as an example.
When using the filter, the "/widgets/cms/navigation/" will be called.
This widget loads the filtered products and replaces the content in the listing.
If this content do have a data-toggle attribute, it will stop working.
Apparently the data-toggle plugins will not re-inizialize after the content has been changed.

I think that every Shopware Core JS Plug-In should be re-inizialized (if available) after a widget causes the content to change dynamically.

For testing purposes you could use this Plug-In:
https://store.shopware.com/coe8689552580742/merkzettel/wunschlisten-fuer-shopware6.html

This Plug-In adds an add-to-favorite button to the listing which opens a modal with data-toggle.
Once you set a filter and the content has been changed, the data-toggle will stop working.

**Comment by Gainto** [comment]
Gibt es hier schon Neuigkeiten?

**Comment by Gainto** [comment]
??

**Comment by Gainto** [comment]
Any News? @mitelg ?

**Comment by mitelg** [comment]
Hey @Gainto,

as you may have noticed, we are currently only doing a very rough screening of the GitHub issues. We are mainly using our own issue tracker https://issues.shopware.com/
We are planning to merge the GitHub issues with our issue tracker, but this is an ongoing process and will still take some time.

The fastest way to get a fix into Shopware would be creating a pull request. :wink: Find more about that [here](https://developer.shopware.com/docs/resources/guidelines/code/contribution).
Additionally, if this is really important for you, I would recommend to [create a ticket on our issue tracker](https://issues.shopware.com/) and link to this issue in the text.

Sorry for the inconvenience, but unfortunately this is the current status, we also have to deal with. :frowning_face: I assure you, that we are also not happy with it.

I know this actually does not really help, but this is our current situation :slightly_smiling_face:  

Best regards from Schöppingen
Michael Telgmann

**Comment by Gainto** [comment]
https://issues.shopware.com/issues/NEXT-15619

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
