### ISSUE TITLE
[BUG/QUESTION] Plugin uninstallation/installation - access custom services to e.g. clean plugin data?

### ISSUE THREAD

**Issue by AndreasA** [shopware/shopware#1619]
**Description**  
Hi,

if I understand the plugin lifecycle correctly according to: https://github.com/shopware/platform/blob/master/src/Core/Framework/Plugin/PluginLifecycleService.php

I only have access to the container which includes my custom plugin services, during activate and deactivate and, if the plugin was already active during update. However, maybe I would like to add custom data already during an installation which would not work, if I intend to use a custom repository.

However, if I want to remove data using a custom services, this would not work as deactivate is executed before the uninstall, which makes sense as the plugin could already be deactivated manually.

Of course, I in most cases using Shopware services for uninstallation should be enough as it will mostly contain drop table and entity cleanup of existing Shopware data but e.g. if I have a helper service that uses DAL to find things which I wanted to use this will not be possible.

It would be nice if it was possible to access custom services during all plugin life cycles.

Furthermore, I think it would be better to use the Symfony events for plugin lifecycles instead of the methods which is will not work, if the services are not available at all times. This will be better as we do not need to access public services but can use dependency injection for constructor etc.

**Possible Solution**  
Maybe always ensure the plugin services are available during all methods, as that should work, as long as the src folder exists?

But maybe that has some issues I forgot to take into consideration.

But I really think that e.g. the  post-install, pre-uninstall events should always contain the container with the plugin services and update pre and post.

**Comment by shyim** [comment]
It is not possible as we can't know where what is needed by extensions. When an extension hangs in kernel.request and does something on their own table which is not existing, the entire shop will crash
