### ISSUE TITLE
Deleting previously used shipping methods can disrupt customer accounts due to lack of fallback

### ISSUE THREAD

**Issue by Josniii** [shopware/shopware#1624]
**Description**  
It seems there's a bug in the code that sets the active shipping method for customers. If a customer has previously selected a shipping method in checkout which then gets deleted from the administration, this customer's sessions will crash.

To reproduce:

1. Create a shipping method in the administration and hook it up to a sales channel
2. Login with a customer on the sales channel and head to checkout.
3. Select the new shipping method on the cart (optionally, place the order as the shipping method will be stored for future orders as well)
4. Delete this shipping method completely in the administration.

The customer is now locked out of the system by page crashes due to `\Shopware\Core\System\SalesChannel\Context\SalesChannelContextFactory::getShippingMethod` having to return a ShippingMethodEntity, but actually returning null due to the Shipping Method selected by the customer no longer existing.

I believe the samme issue probably exists with payment methods, from what I can discern on `\Shopware\Core\System\SalesChannel\Context\SalesChannelContextFactory::getPaymentMethod` - this also tries to use customer specific IDs for payment methods and probably could also fail in the same manner. I haven't actually tried it out though.

**Possible Solution**  
The issue could be fixed by fallback logic in the above mentioned function. Something like this:

```
private function getShippingMethod(array $options, Context $context, SalesChannelEntity $salesChannel): ShippingMethodEntity
{
    if (array_key_exists(SalesChannelContextService::SHIPPING_METHOD_ID, $options)) {
        $id = $options[SalesChannelContextService::SHIPPING_METHOD_ID];

        $criteria = (new Criteria([$id]))->addAssociation('media');
        $criteria->setTitle('context-factory::shipping-method');

        $shippingMethod = $this->shippingMethodRepository->search($criteria, $context)->get($id);
        if ($shippingMethod) {
            return $shippingMethod;
        }
    }

    $id = $salesChannel->getShippingMethodId();

    $criteria = (new Criteria([$id]))->addAssociation('media');
    $criteria->setTitle('context-factory::shipping-method');

    return $this->shippingMethodRepository->search($criteria, $context)->get($id);
}
```

Obviously this is just copy-pasting and moving some logic around, but the idea should work. If the `$options` contain a shipping method ID, make sure that it actually gets an entity. Otherwise, retry with the default ID for the Sales Channel. If you want, I can make a PR with something like this.

**Comment by mitelg** [comment]
hey @Josniii 

could you reproduce this on the current master or on the upcoming 6.3.5.0 ? We fixed some things regarding deleting of relationships. So for example, if a rule is still in use on a payment method, the rule could not be deleted. maybe this mechanic also fixes your use case?

**Comment by Josniii** [comment]
Hey @mitelg 
Sorry for the delay, I just tried replicating on v6.3.5.1 and the issue still exists. The issue is that the shipping method ID is still stored inside the sales channel context of the customer inside a JSON blob with no relation to the shipping method table. The system will always use the customer's preferred shipping method if one is set, regardless of whether it exists or not.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
