### ISSUE TITLE
Entity customer is missing discardChanges method

### ISSUE THREAD

**Issue by observant2** [shopware/shopware#166]
When editing a customer in the shopware administration panel and clicking on `Cancel`, the console prints:
```
[Discard-detail-page-changes Mixin] Could not discard changes for entity with name "customer".
```
and of course the changes that I made to the customer are permanent.

**Comment by taltholtmann** [comment]
Hello @itmuckel and thank you for reporting the bug.

I created an issue ticket for this. Here you can see the actual status: [NEXT-4842](https://issues.shopware.com/issues/NEXT-4842)
