### ISSUE TITLE
[Feature Request] Plugin/ThemeInterface method on assignment to sales channel

### ISSUE THREAD

**Issue by moorl** [shopware/shopware#172]
Hey guys,

I would like to have a method like this, including the sales channel context.

reason: on theme assignment I like to write a sales channel specific config. I built a wingman-plugin for basic theme functionalities like google fonts and animations. I would like to use this wingman-plugin for all my themes and the themes of other publishers, so its easier to keep them up to date ;)

Actually i am using the activate() method, but its setting up my config globally - not sales channel specific:

```
public function activate(ActivateContext $activateContext): void
    {
        parent::activate($activateContext);
        $animateConfig = json_encode([
            '.cms-element-image, .footer-logos' => [
                'in' => 'flipInX',
                'out' => 'flipOutX',
                'mouseOver' => null,
            ],
            '.card-col:first-child > .cms-element-product-box' => [
                'in' => 'fadeInLeft',
                'out' => 'flipOutX',
                'mouseOver' => null,
            ],
            '.card-col:last-child > .cms-element-product-box' => [
                'in' => 'fadeInRight',
                'out' => 'flipOutX',
                'mouseOver' => null,
            ],
            '.footer-column-headline' => [
                'in' => 'lightSpeedIn',
                'out' => 'flipOutX',
                'mouseOver' => null,
            ],
        ]);
        $connection = $this->container->get(Connection::class);
        $configRepository = $this->container->get('system_config.repository');
        $systemConfigService = new SystemConfigService($connection, $configRepository);
        $systemConfigService->set('WingMan.config.animateConfig', $animateConfig);
        $systemConfigService->set('WingMan.config.googlefonts', true);
        $systemConfigService->set('WingMan.config.googlefontsQuery', 'family=Kalam&display=swap');
}
```

**Comment by jenskueper** [comment]
Hey there,

thank you for the suggestion! I understand that there is a need to react to theme assignments. I see it a bit problematic to add this to the plugin bootstrap file since the methods (install, postInstall, update, postUpdate, **activate**, deactivate and uninstall already exists and refer to the plugin lifecycle.

But we could introduce events for theme assignment/compilation etc. where you could handle the config. Would you be okay with this solution?

Do you always create the same default config for a theme assignment? As far as I know, its possible to create a system config and the user can set different configuration for each sales channel.

Best regards
Jens

**Comment by moorl** [comment]
Hey Jens,

at the moments it isn't so important, it's just a suggestion. Since the theme bootstrap file is implementing the ThemeInterface we could be able to inherit some extra methods for the theme assignment and as you said: the compilation.

I just think it could be problematic when a customer uses two different sales channel and themes. Suddenly if he has installed the wingman-plugin he could get unwished animations and effects on his other theme.

Ofcourse its possible to adjust the config on himself, but there he need some experiences to JSON.

The event-solution sounds good for me!

Best Regards
Philipp
