### ISSUE TITLE
No editor to manage delivery times in administration

### ISSUE THREAD

**Issue by JoshuaBehrens** [shopware/shopware#176]
Currently I can only select delivery times for shipping methods but I can't manage(CRUD) delivery times in the administration.

**Comment by pantrtxp** [comment]
Hi @JoshuaBehrens 

unfortunately this feature will be developed at a later date.
sorry for any inconvenience.

**Comment by JoshuaBehrens** [comment]
I guessed so but why is this issue closed? It remains unavailable and you will provide a solution at a later date. I don't think issues work this way

**Comment by mitelg** [comment]
@pantrtxp maybe you could provide a ticket link, so one could follow that one instead of this github issue

**Comment by pantrtxp** [comment]
@JoshuaBehrens sorry, I will get back to you next week and try to provide more information.
At the current time this is all I can provide.
