### ISSUE TITLE
Flatpickr has a bug in time-only mode

### ISSUE THREAD

**Issue by JoshuaBehrens** [shopware/shopware#178]
I fixed a bug in https://github.com/flatpickr/flatpickr/pull/1938 so if this is merged you should update the flatpickr dependency immediately.

When you use the `sw-datepicker` like this:
```
<sw-datepicker dateType="time"
               v-bind:label="$t('my-date')"
               v-bind:config="{dateFormat: 'H:i:S'}"
               v-bind:required="true"
               v-model="entity.timeString">
</sw-datepicker>
```
it throws the following exceptions:
```
vue.esm.js?a026:1897 TypeError: Cannot read property 'children' of undefined
    at updateWeekdays (flatpickr.js?cf06:1345)
    at eval (flatpickr.js?cf06:2157)
    at Array.forEach (<anonymous>)
    at Object.set (flatpickr.js?cf06:2157)
    at VueComponent.updateFlatpickrInstance (index.js?a739:1)
    at VueComponent.handler (index.js?a739:1)
    at Watcher.run (vue.esm.js?a026:4571)
    at flushSchedulerQueue (vue.esm.js?a026:4313)
    at Array.eval (vue.esm.js?a026:1989)
    at flushCallbacks (vue.esm.js?a026:1915)
```

**Comment by pantrtxp** [comment]
Hi @JoshuaBehrens 

I've created a ticket for this: https://issues.shopware.com/issues/NEXT-4882 
and subscribed to your flatpickr PR to get notified as soon as it is merged.

If we don't get back to you please remind us in this thread as soon as your PR is merged

**Comment by JoshuaBehrens** [comment]
Merged it is. No release yet

**Comment by JoshuaBehrens** [comment]
Release with my fix is public https://github.com/flatpickr/flatpickr/releases/tag/v4.6.3

**Comment by pantrtxp** [comment]
Sorry it took so long, but I'm on it. Will probably be merged today

**Comment by JoshuaBehrens** [comment]
Nice. Thanks :blue_heart:
