### ISSUE TITLE
Install Extention DemoData

### ISSUE THREAD

**Issue by kveldscholten** [shopware/shopware#179]
We have installed the Shopware 6 v6.0.0 Early Access 1.1 on our Nginx with PHP 7.2 (chroot)
But after installing the Shopware DemoData Plugin we always get the error by the install context:
```{"errors":[{"code":"0","status":"500","title":"Internal Server Error","detail":"Cannot obtain the lock for destination messages"}]}```

We locate the error is fired in the File:`Shopware\Core\Content\Media\File\FileSaver::persistFileToMedia`
When it hand over the Thumbnail generation in Line:142 `$this->messageBus->dispatch($message);`

**Comment by pweyck** [comment]
We use the fs transport for the message bus by default. It uses flock to synchronize the workers. On some setups this may not work as expected. (For example NFS). We have an open Issues with a workaround in german. (I can translate it if required).

See: https://issues.shopware.com/issues/NEXT-4662

We consider making enqueue/dbal the default.

**Comment by pweyck** [comment]
We've changed the default transport from `enqueue/fs` to `enqueue/dbal` on master. That should fix your problem. The next release 6.0.0 EA2 will contain those changes. 

Feel free to reopen the issue, if it still doesn't work.
