### ISSUE TITLE
PHP Fatal error - Attempted to call function "next741" from namespace "Flag"

### ISSUE THREAD

**Issue by a-buzdugan** [shopware/shopware#185]
Hello,

For my local SW6 under vagrant setup up-to-date (HEAD) dev and platform: git pull origin master 

when I am trying to install shopware with:

vagrant@shopware:~/shopware-dev$ ./psh.phar install

I get:

(8/38) Starting
> bin/console database:migrate --all Shopware\\
        PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\UndefinedFunctionException: Attempted to call function "next741" from namespace "Flag". in /home/vagrant/shopware-dev/platform/src/Storefront/Framework/Seo/Subscriber/SeoUrlLoaderSubscriber.php:52
        Stack trace:
        #0 /home/vagrant/shopware-dev/vendor/symfony/event-dispatcher/DependencyInjection/RegisterListenersPass.php(146): Shopware\Storefront\Framework\Seo\Subscriber\SeoUrlLoaderSubscriber::getSubscribedEvents()
        #1 /home/vagrant/shopware-dev/vendor/symfony/event-dispatcher/EventDispatcher.php(191): Symfony\Component\EventDispatcher\DependencyInjection\ExtractingEventDispatcher::getSubscribedEvents()
        #2 /home/vagrant/shopware-dev/vendor/symfony/event-dispatcher/DependencyInjection/RegisterListenersPass.php(112): Symfony\Component\EventDispatcher\EventDispatcher->addSubscriber(Object(Symfony\Component\EventDispatcher\DependencyInjection\ExtractingEventDispatcher))
        #3 /home/vagrant/shopware-dev/vendor/symfony/dependency-injection/Compiler/Compiler.php(95): Symfony\Compon in /home/vagrant/shopware-dev/platform/src/Storefront/Framework/Seo/Subscriber/SeoUrlLoaderSubscriber.php on line 52

Execution aborted, a subcommand failed!

Please assist.

Thank you,
Andrei B.

**Comment by keulinho** [comment]
Do a `composer update` in the development folder this should fix your problem.

**Comment by a-buzdugan** [comment]
Composer update fixed my install issue.
Thank you for the quick response!
