### ISSUE TITLE
[Minor issue] Administration backend sw-alert html escape

### ISSUE THREAD

**Issue by a-buzdugan** [shopware/shopware#186]
Hello,

[Minor issue]

User Story: Administrators can submit html tags for entity fields

Steps:
1. Login in administration backend 
2. Go on a listings (eg. Customers: /admin#/sw/customer/index?limit=25&page=1&sortBy=customerNumber&sortDirection=DESC&naturalSorting=true )
3. On entity fast edit field (double click on a row field)
4. Submit data containing html tags (eg. \<b> \<i>)

Expected result: Field value is sanitized, saved accordingly and output value escaped
Actual result: Field value is sanitized, saved accordingly and output displayed back in alerts is html interpreted
Hint: sw-alert.

Please let me know if this is an issue.

Thank you,
Andrei B.

![sw-alert](https://user-images.githubusercontent.com/54103115/64766700-1e5c2a00-d54f-11e9-87d0-df9b80679612.png)

**Comment by pantrtxp** [comment]
Hi @a-buzdugan 
We'll close this issue right away. 
I've already submitted a PR with a Fix for this.

Thank your for informing us.

**Comment by pantrtxp** [comment]
https://github.com/shopware/platform/commit/9691ffee321b0b0371f02df65deedc1e355c54a6 

sw-notification messages are now 100% html free :wink: 

Thank you @a-buzdugan for notifying us.
