### ISSUE TITLE
The custom CMS block is not displayed

### ISSUE THREAD

**Issue by Patrokl42** [shopware/shopware#190]
Hello.
I created a plugin and custom cms block like here
https://github.com/shopware/swag-docs-custom-cms-block
But for some reason it does not appear in the page edit.

**Comment by pantrtxp** [comment]
Hi @Patrokl42, 

there are currently some issues with plugins in the administration:watch mode. I guess that you are looking into this one.
Please look up if the block will be shown in your builded state of the administration.

If you should need more help feel free to ask :)

**Comment by Patrokl42** [comment]
@pantrtxp thanks for the answer.
But I already used the command administration:build.

**Comment by pantrtxp** [comment]
Hi @Patrokl42 

sorry but my information was deprecated anyway, that's why i deleted this comment.

please check if your plugin is installed and activated (`bin/console plugin:refresh`). If it's not please run `bin/console plugin:install --activate CustomCmsBlock` and `./psh-phar cache`

**Comment by Patrokl42** [comment]
@pantrtxp I followed all of these steps as indicated in your documentation.
https://docs.shopware.com/en/shopware-platform-dev-en/how-to/custom-cms-block?category=shopware-platform-dev-en/how-to
Everything worked, but for some reason there is no block in admin.

**Comment by pantrtxp** [comment]
But in this How-To there is not specified how to install a Plugin so please follow the steps above.

What you've done so far is create a custom plugin but you have not installed it, thus making it unavailable in your System (assuming that you did not do the steps i wrote above)

**Comment by Patrokl42** [comment]
@pantrtxp I did all these activities.
My plugin overwrites some templates.
It is activated and everything works.
But not with custom blocks.

**Comment by pantrtxp** [comment]
Since I don't know your Setup, have you tried re-installing the Plugin if you made changes? 
And do you have just one plugin or multiple? 

as a last resort, you can try cloning https://github.com/shopware/swag-docs-custom-cms-block into `custom/plugin` and installing this one? (I just did this and everything works fine :thinking: )

**Comment by Patrokl42** [comment]
@pantrtxp I cloned this plugin and it worked.
Thank you for help.

**Comment by Stephen-2Hats** [comment]
@pantrtxp I cloned the same and tried my own plugin both do not work for me. After activating the cloned plugin the admin dashboard is not loading.
