### ISSUE TITLE
Installer Error "Critical environment variable 'DATABASE_URL' missing!\n"

### ISSUE THREAD

**Issue by miracleman** [shopware/shopware#191]
I try to install shopware 6 and I get
"Critical environment variable 'DATABASE_URL' missing!\n"

url
/recovery/install/database-import/

**Comment by pweyck** [comment]
Im closing this in favor of https://github.com/shopware/platform/issues/192 and https://issues.shopware.com/issues/NEXT-4939.

**Comment by hucario** [comment]
so.. are there any fixes / workarounds for this that I can use to install Shopware?
