### ISSUE TITLE
installer Error Identifier DB not initialized yet

### ISSUE THREAD

**Issue by miracleman** [shopware/shopware#192]
I tried to install shopware 6 an I get the following error

Type: RuntimeException
Message: Identifier DB not initialized yet
File: /.../recovery/install/src/ContainerProvider.php
Line: 162

I was able to fix it with this information at
https://stackoverflow.com/questions/45637033/shopware-installation-error-identifier-db-not-initialized-yet

Info This error is also in installer of 5.6 (will file an issue there too)

**Comment by pweyck** [comment]
Hello miracleman,

thank you for reporting this issue. My first guess is that the connection information is not validated correctly or the session is expired. 

Strictly speaking, the installer is not part of the platform, so this issue does not belong here. I've create an issue in our issue tracker:

https://issues.shopware.com/issues/NEXT-4939

Kind regards
