### ISSUE TITLE
Return value of Shopware\Storefront\Page\Product\ProductPage::getCmsPage() must be an instance of Shopware\Core\Content\Cms\CmsPageEntity, null returned

### ISSUE THREAD

**Issue by moorl** [shopware/shopware#193]
Just forgot the questionmark?

https://github.com/shopware/platform/blob/dc4d16ecfc8ebf7015abeb942b8cddf908ecadab/src/Storefront/Page/Product/ProductPage.php#L56

**Comment by mitelg** [comment]
hey @wa-pgeorg 
do you have an example, when this failure occurs?

**Comment by rhwebdesign** [comment]
@mitelg 

Hey!

In my custom twig function:
```
public function CurrentPicSrc($page): array
{
if (method_exists($page, 'getCmsPage') && $page->getCmsPage()) {
    /* Do something */
}
}
```

In the ProductPage Controller has the value cmsPage defined as null. My Plugin checks the current Page and if it has the method getCmsPage it is calling it. Just putted a questionmark there:
`public function getCmsPage(): ?CmsPageEntity `
and it works fine then.

There is a plan to put CMS content on product details?

**Comment by pantrtxp** [comment]
Hi @wa-pgeorg
I've just fixed this issue and it will be deployed in the morning. 

@rhwebdesign
Yes, it is planned to be able to create product detail pages with the CMS as well.
