### ISSUE TITLE
Customer Entity is null in Documents

### ISSUE THREAD

**Issue by Gainto** [shopware/shopware#197]
When you create an document (e.g. invoice) and dump out the "customer" variable in the base.html.twig file you'll get the following output:

 #email: "test@test.de
" #orderId: "df29d6ba13d04fcfb4acaf9045c493a9
" #salutationId: "f2855d8bb01b4ae090495050b96ac9e7
" #firstName: "test
" #lastName: "test
" #title: "test
" #company: null
 #customerNumber: "10087
" #customerId: "b772fcc315b54017accc4378036b1001
" **#customer: null**
 #salutation: null
 #order: null
 #customFields: null
 #_uniqueIdentifier: "4b8fa00e0f224b31b5e147988182d1aa
" #versionId: "0fa91ce3e96a4bc2be4bd9ce752c3425
" #translated
: [] #createdAt: DateTimeImmutable @1568746529 {#1644
date: 2019-09-17 18:55:29.752 UTC (+00:00)
} #updatedAt: null
 #extensions: array:1 [
 "internal_mapping_storage" => ArrayEntity^ {#1621
 #data
: [] #_uniqueIdentifier: null
 #versionId: null
 #translated
: [] #createdAt: null
 #updatedAt: null
 #extensions
: []
}
] #id: "4b8fa00e0f224b31b5e147988182d1aa
" +"orderVersionId": "0fa91ce3e96a4bc2be4bd9ce752c3425
"
}

I expect the "customer" field to automatically beeing mapped to the customer. seems like there was no association set, when the entity has been created. I don't see any point in creating the association manually, this should be done by the core.

**Comment by ssltg** [comment]
the "customer" variable in the documents is the order.orderCustomer and the customerEntity is not mapped for this call. If you need additional Information from the customerEntity you need to subscribe to the Event "order.search.result.loaded" but you can't rely on the fact that an orderCustomer has a customerEntity associated. This field can be null under some circumstances.

But I see the requirement to have an event when the order for documents is called and will discuss if we will implement it.

To get a better overview, can you tell me which values from the customer you need, which are not already present in the orderCustomer?

**Comment by Gainto** [comment]
> To get a better overview, can you tell me which values from the customer you need, which are not already present in the orderCustomer?

the custom_field entry :)

**Comment by mitelg** [comment]
@ssltg maybe customFields need to be synced to the orderCustomers while creating them

**Comment by Gainto** [comment]
yes. Same for the orderAddress.

**Comment by Gainto** [comment]
Is this planned for the next release?
Currently i'm listening to the CartConvertedEvent and add the missing data by myself.

But in general, the AddressTransformer.php and the CustomerTransformer.php only need a new entry, or ?
            'customFields' => $address -> getCustomFields(),

**Comment by ssltg** [comment]
Sorry for the late answer.
The Event on the documentGeneration will come in the next Release. But we are still unsure what solution we will take for customFields for the orders. We don't want to duplicate every customField "just in Case". So currently you need to hook into the CartConvertedEvent and enrich the data there.

**Comment by Gainto** [comment]
Hi @ssltg,

well, using the CartConverted Event won't work in every scenario.
The custom_fields field isn't just empty for the customer entity, it's also empty for the billingAddress and shippingAddress (for example).

I can understand the choice, why you don't want to copy every customField just in case.
Maybe the right approach would be to implement an event which fires after an entity has been transformed?

Like for these files:
Core/Checkout/Cart/Order/Transformer/AddressTransformer.php
..../CartTransformer
..../CustomerTransformer
..../DeliveryTransformer
..../LineItemTransformer
..../TransactionTransformer

after a transformation has been done, a developer should be able to add additional data to the transformed array by listening to an event. 
Whats your opinion?

**Comment by a-buzdugan** [comment]
Thank you for pointing the Transformer event.

What we did on EA6.0 was to:
1. create a LineItemCustom that extends LineItem
2. LineItemCustom supports extra fields in customFields (with getters and setters for every key in customFields)
3. We add into cart the LineItemCustom and cart contains this entity with extra fields (make sure it is a persistent change)
4. After the order we have the extra fields in OrderLineItem with customFields // but we need to review the logic as it was not final

We will focus on events.

**Comment by Gainto** [comment]
well, which solution has been implemented in the 6.1 to populate the custom-fields to the associated transformed items (customer, address, etc.) ?
