### ISSUE TITLE
Watcher is not reflecting changes

### ISSUE THREAD

**Issue by pimjansen** [shopware/shopware#198]
Im running Shopware 6 in docker. However when i run the watcher in my pod using:
`application@ba3e3eeff9da:/app$ ./psh.phar administration:watch`

Then the changes are not reflecting when i open the webpage via my host system at http://localhost:8000/admin

**Comment by pimjansen** [comment]
Found the solution also that the watcher is running a new service update at 8080 instead of 8000.
Maybe we should add it more clear in the docs?

**Comment by pantrtxp** [comment]
Hi @pimjansen, we'll consider if this has to be more documented.
but in the console after `./psh.phar administration:watch` the output as well tells you where to finde it and provides a link

Since you resolved your issue i'll close this ticket then :)
