### ISSUE TITLE
Register Controller as Plugin

### ISSUE THREAD

**Issue by EtienneBruines** [shopware/shopware#2]
# The Problem
In order for plugins to create custom controllers, it needs to be possible to register custom routes. 

(And one needs to be able to create custom controllers, if only to extend the administration/backend.)

# Where do we need changes?
Within the `Core/Kernel.php`, there's a `configureRoutes` method which already loads the basic routes as provided by `config/routes***`. It would only make sense that within this method, there will also be some code that loads the plugin-specific routes.

The `ObjectRouteLoader` dynamically calls this `loadRoutes` method in the Kernel (as part of the `MicroKernelTrait`). 

# The Solutions
Two possible solutions, of which I dislike the first. The second one feels more `Bundle`-like, e.g. where you don't have to rely on magic filenames / directories that get loaded. Alternatively, it allows for dynamically loading routes (PHP), instead of having to hardcode them into the yaml/xml files. I've added a third point because it feels related. 

1. Dynamically load all route files/directories defined in the plugin, much like the kernel does, but then without `Resources`:
```php
$routes->import($confDir . '/{routes}/*' . self::CONFIG_EXTS, '/', 'glob');
$routes->import($confDir . '/{routes}/' . $this->environment . '/**/*' . self::CONFIG_EXTS, '/', 'glob');
$routes->import($confDir . '/{routes}' . self::CONFIG_EXTS, '/', 'glob');
```

2. One could extend the `Plugin` class definition to include a `protected function configureRoutes(RouteCollectionBuilder $routes)` which can be overwritten by the `Plugin` itself (as an alternative to the `build` method). Then one could specifically import the files needed, or add them dynamically as needed. 

3. A new service which contains the logic described. On top of either of the above solutions, one could extend this service to do crazy stuff itself, like completely replacing routes. 

I'm not sure what the recommended approach is to overriding / decorating such controller-services. This should be taken into account when testing the above.

**Comment by janbuecker** [comment]
Thank you @EtienneBruines. We don't have a production-ready solution yet so your ideas are welcome. 

We'll consider your solutions and I think I like solution 2 the most. But maybe for convenience, the `configureRoutes` in a plugin should automatically register all controllers within a given default path.
