### ISSUE TITLE
`npm clean-install` requires npm >= v6.5.0

### ISSUE THREAD

**Issue by LiaraAlis** [shopware/shopware#20]
With commit 7add82d348bfa957a52672e26b3aa972e27d792a `npm clean-install` is used. This command is not available before npm version `6.5.0`: https://github.com/npm/cli/releases/tag/v6.5.0
But currently required is npm `>= 3.5.2`.

**Comment by mitelg** [comment]
fixed with https://github.com/shopware/platform/commit/e43a4d4be5e00a979e444cd16d3026a2f5c0d791

**Comment by LiaraAlis** [comment]
@mitelg 
Thanks for the fix.
But the documentation on docs.shopware.com does not seem to be up to date: https://docs.shopware.com/en/shopware-platform-en/getting-started/dev-setup?category=shopware-platform-en/getting-started#hard-requirements

**Comment by mitelg** [comment]
@LiaraAlis thanks for the hint. Unfortunately the sync is a bit out of date. As you can see in the [docs repo](https://github.com/shopware/platform/blob/master/src/Docs/1-getting-started/10-dev-setup.md), this is already fixed, but not yet deployed. but we are working on that with high prio :+1: 
Nevertheless I fixed the npm version manually for the time being :wink:
