### ISSUE TITLE
[Minor Doc Issue] DAL Aggregations

### ISSUE THREAD

**Issue by a-buzdugan** [shopware/shopware#204]
Hello,

I think there is a mistake here:

https://docs.shopware.com/en/shopware-platform-dev-en/internals/core/data-abstraction-layer/search#countaggregation

and on all documented aggregators.

The order of parameters should be switched, for eg:

new CountAggregation('count-manufacturer', 'product.manufacturerId')

should be

new CountAggregation('product.manufacturerId', 'count-manufacturer')

I think.

Please check.

Thank you,
Andrei B.

**Comment by OliverSkroblin** [comment]
Hi
we have adapted the aggregations of the data abstraction layer. The name is now the first parameter because some aggregations have no field. 
You can find the corresponding change here: https://github.com/shopware/platform/commit/f6679aab2a2bf6d9130aef5653c689a047dbd5b8
