### ISSUE TITLE
Argument 3 passed to PasswordField::__construct() must be of the type integer, string given

### ISSUE THREAD

**Issue by kkrieger85** [shopware/shopware#21]
While generating demodata with `APP_ENV=prod bin/console framework:demodata` I got following error:

```
Argument 3 passed to Shopware\Core\Framework\DataAbstractionLayer\Field\PasswordField::__construct()
  must be of the type integer, string given, called in /var/www/vhosts/MYPROJECT/vendor/shopware/platform/src/Core/Checkout/Customer/CustomerDefinition.php on line 78
```

This leads to: 

https://github.com/shopware/platform/blob/e36a665bc580a675d27b2942a998bd82ad47e659/src/Core/Framework/DataAbstractionLayer/Field/PasswordField.php#L24

where constant `PASSWORD_ARGON2I` is used to define hash algorithm. 

On my used environment, php7.2.x was not compiled with argon2 support as [needed]( http://php.net/manual/de/function.password-hash.php )

**Workaround:**
Replace with `PASSWORD_DEFAULT`

I **do not recommend this workaround for production environment!**

**Comment by kkrieger85** [comment]
This Issue may be closed. I just want to document this "issue".

**Comment by ChristopherDosin** [comment]
I had the same issue - Thanks for the workaround!
But with PHP 7.2 Argon should be installed and it should work. 7.2 is shipped with Argon by default, at least in my case with Homebrew.

In my case i had to stop another PHP 7.1 version which was running, so Shopware was running on PHP 7.1 without Argon. Shopware 6 requires 7.2

My console said i am running 7.2, but `phpinfo()` said that Shopware is running on 7.1
Maybe you should check your php version @kkrieger85

**Comment by mitelg** [comment]
Hey @kkrieger85 
thanks for your report. We changed the encryption back to bycript. see here: 406f90140049faf57c4ea1dd394c6f575b63b580
