### ISSUE TITLE
Language switch in editing component via sw-language-info automatically discards data

### ISSUE THREAD

**Issue by JoshuaBehrens** [shopware/shopware#213]
When you have a `sw-language-switch` component you need to confirm the language switch as the currently editing entity will be reloaded. When you click on the language in the `sw-language-info` the entity is automatically reloaded in the newly selected language. In that case there is no language change confirmation and all data is lost.

Either interrupting language change has to be managed more globally (difficult) or the `sw-language-info` has to be aware of an editing mode like the `sw-language-switch` (easier). What do you think about it?

**Comment by pantrtxp** [comment]
Hi @JoshuaBehrens, sorry for the late reply, 
I've created a Ticket for this Issue which you can track here https://issues.shopware.com/issues/NEXT-5186

**Comment by JoshuaBehrens** [comment]
Note: The ticket title is "Language switch verwirft Daten" but it should be "Switch durch language info verwirft Daten". The sw-language-switch works fine :)

**Comment by pantrtxp** [comment]
done :heavy_check_mark:

**Comment by JoshuaBehrens** [comment]
I am waiting for the commits to see your implementation and really interested in your code. Thanks for solving it :blue_heart:

**Comment by pantrtxp** [comment]
hold up :sweat_smile: I've just updated the title to your suggestions. I have not solved this issue. Sadly I can't even tell you when exactly this will be fixed.

**Comment by JoshuaBehrens** [comment]
:o: :nose: 
Got that now. I think I just have to wait a little longer then :man_shrugging:

**Comment by pantrtxp** [comment]
Sorry to put you through this rollercoaster of emotions. :confused: :smile:

**Comment by pantrtxp** [comment]
Hi @JoshuaBehrens I'd like to close this issue as well, if this is okay for you. You can keep Track of this issue here https://issues.shopware.com/issues/NEXT-5186

**Comment by JoshuaBehrens** [comment]
Is there a way to follow tickets on issues.shopware.com? It gets annoying to have all issues as new tab in my browser :D I have a dedicated window full of issues there.

**Comment by mitelg** [comment]
@JoshuaBehrens I think you can upvote a ticket, and then you should get notifications. (no guarantee though :smile: )

**Comment by pantrtxp** [comment]
I'll find out @JoshuaBehrens

**Comment by pantrtxp** [comment]
Sadly you won't get any notifications, this was deactivated a while ago.
I guess we'd better leave the tickets open at github then.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
