### ISSUE TITLE
Error on running bin/setup

### ISSUE THREAD

**Issue by BogdanChayka** [shopware/shopware#217]
I'm using the debian subsystem and went through all requirements of the setup, since docker is not working on a Linux Subsystem either.

`  12:12:39 ERROR     [console] Error thrown while running command "dal:refresh:index". Message: "UUID has a invalid length. 16 bytes expected, 32 given. Hexadecimal reprensentation: 3061363530646464373062663433643661333330633261393930396639663061" ["exception" => Shopware\Core\Framework\Uuid\Exception\InvalidUuidLengthException { …},"command" => "dal:refresh:index","message" => "UUID has a invalid length. 16 bytes expected, 32 given. Hexadecimal reprensentation: 3061363530646464373062663433643661333330633261393930396639663061"]

        In Uuid.php line 49:

          UUID has a invalid length. 16 bytes expected, 32 given. Hexadecimal reprens
          entation: 3061363530646464373062663433643661333330633261393930396639663061`

**Comment by OliverSkroblin** [comment]
Hi @BogdanChayka,

thanks for the report. We found the bug and fixed it, if you update your environment the bug should not occur anymore.
