### ISSUE TITLE
Environment files for configuration in production

### ISSUE THREAD

**Issue by observant2** [shopware/shopware#223]
Hey guys!
We need an easily deployable production configuration. Therefore we need to pass information like the database connection string, shop name etc. via environment variables to the installer, so a manual install process isn't necessary.

I skimmed through the code and found that `shopware/core/Kernel.php` does read the environment variable `DATABASE_URL`, but setting it through an `.env` file won't change anything in the installer.

Is an automatic installation through env files in production planned or even already possible?

**Comment by pweyck** [comment]
Hey itmuckel,

the installer generates a new `.env` file during the installation. You could try the cli version of the installer.

For example:
```bash
cd $SHOPWARE_DIR
php public/recovery/install/index.php \
        --no-interaction \
	--db-user=root \
	--db-password=root \
	--db-name="shopware" \
	--shop-locale=de-DE \
	--shop-host=shopware.test \
	--shop-path="" \
	--shop-name='CLI Installer test' \
	--shop-currency=EUR \
	--admin-username=demo \
	--admin-password=demo \
	--admin-email=demo@example.com \
	--admin-locale=de-DE \
	--admin-firstname=Max \
	--admin-lastname=Mustermann
```
Additionally, you are free to modify the `.env` file after the installation.

If the cli installer is not enough, I can say that we've planed a production template (similar to development template) to make custom deployments easier. It should be ready for the 6.1 release.

Kind regards

**Comment by observant2** [comment]
Thank you! I'll try that.
