### ISSUE TITLE
Auto Generate API Client possible?

### ISSUE THREAD

**Issue by S-M-O** [shopware/shopware#227]
Hello all,

I asked myself if it is possible to not just do a
```bash
framework:schema
```
but to auto generate a whole client from the schema json or directly from the shopware project since the open api standard supports this. I know some routes are generated automatically so I assume it is not possible to include all routes in an api client automatically.

Does someone has an idea or probably already did it?

Thank you very much and best regards,
Stefan

**Comment by keulinho** [comment]
Hello Stefan,

our open api schema currently doesn't cover all possibilities provided by the API, the action routes are missing right now.
Basically the open api schema currently just covers the CRUD operation for all entities in the system and these are the routes that are automatically generated.

But for the CRUD operation you should be able to generate an api client by one of these tools out there.

I personally don't have any experience  on how good and usable these auto generated clients are.
But my personal opinion is to not use auto-generated clients, as you depend on your once generated clients and it can get really complicated if the API evolves and changes.

Kind regards
Jonas

**Comment by S-M-O** [comment]
What a pitty.

Thank you very much,
Stefan
