### ISSUE TITLE
Wrong format in RESTAPI

### ISSUE THREAD

**Issue by mschradi** [shopware/shopware#228]
Hello everybody,

I've autogenerated the API Classes with OpenApi for C#.

The serialization of the json have some problems, for example in the "/product" (getProductList) response json.
The Swagger Scheme tells that the "included" part of the json will look like this (/api/v1/_info/swagger.html#/Product/getProductList):
```
"included": [
    {
      "type": "string",
      "id": "string",
      "attributes": {
        "additionalProp1": {}
      },
      "relationships": {},
      "links": {},
      "meta": {
        "additionalProp1": {}
      }
    }
  ]
```
but my response from the api looks like this:
```
"included": [
        {
            "id": "5dedcc1252d94b1f8f3135949334798a",
            "type": "extension",
            "attributes": { "canonicalUrl": null },
            "links": [],
            "relationships": {
                "seoUrls": {
                    "data": [],
                    "links": { "related": "http:\/\/testshop\/api\/v1\/product\/(someguid)\/extensions\/seoUrls" }
                }
            },
            "meta": null
        }
]
```
The problem is the "links" attribute of the included. my program expects an dictionary ({}), but i get a list ([]). To make it even worse, if there is a link inside, it is a dictionary:
```
"included": [
        {
            "id": "dd52ad97a3db430481267cfabbc4c993",
            "type": "tax",
            "attributes": {
                "taxRate": 19.0,
                "name": "19%",
                "customFields": null,
                "createdAt": "2019-10-01T06:15:46+00:00",
                "updatedAt": null
            },
            "links": { "self": "http:\/\/testshop\/api\/v1\/tax\/(someguid)" },
            "relationships": {
                "products": {
                    "data": [],
                    "links": { "related": "http:\/\/testshop\/api\/v1\/tax\/(someguid)\/products" }
                }
            },
            "meta": null
        }
]
```

**Comment by keulinho** [comment]
Hello Max,

you are right about this issue, the `links` attribute has to be an object (empty or dict), not just according to our open api schema but also according to the JsonApi Spec: https://jsonapi.org/format/#document-links.

We are working on a fix for this.

**Comment by keulinho** [comment]
Thanks @mschradi for raising this issue, it should be fixed now.
