### ISSUE TITLE
[Docs] Cart 'Get deliveries' example missing

### ISSUE THREAD

**Issue by a-buzdugan** [shopware/shopware#229]
Hello,

https://docs.shopware.com/en/shopware-platform-dev-en/internals/core/checkout-process/cart?category=shopware-platform-dev-en/internals/core/checkout-process

"Get deliveries" section:

proper example is missing and it represents at the moment a copy of "Remove line item" excerpt.

Please check.

Thank you,
Andrei B.

**Comment by keulinho** [comment]
Hello @a-buzdugan,

thanks for raising this issue, we will fix the `getDelivieries()` example.

Kind regards
Jonas
