### ISSUE TITLE
[Request] Before Events

### ISSUE THREAD

**Issue by a-buzdugan** [shopware/shopware#230]
Hello,

Is it possible to have events before operations?

Examples:
before page load (so we can force a redirect)
before adding line item to cart (so we can restrict adding to cart with custom validations)

In general, based on your experience with the platform, where it makes sense to have before events I think it would help.

Thank you,
Andrei B.

**Comment by OliverSkroblin** [comment]
Hi @a-buzdugan,

we do not plan to install "before events" to prevent certain actions in the system. You can better listen to the "after events" to revise certain actions afterwards.
For example to redirect a page load to another route there are several possibilities:
* Rewrite the route in the template
* Register to the Kernel::Request event and set a redirect to your controller action
* ...

To avoid certain line items in the cart you should rather work with the processor pattern of the cart and simply implement a processor there which removes the line item.

I hope this helps you.
Greetings Oliver
