### ISSUE TITLE
Different Tax Rate for billing country

### ISSUE THREAD

**Issue by 0f8** [shopware/shopware#236]
Hi,

is it possible to set different tax rates for a product,  depending on the customer address?

With the rulebuilder i am able to configure the product that per country it has a specific price.
The problem is that in the basket the calculation for the tax is always in base of the the base configuration.

example:

| Customer Country | Tax % | Price Gross | Price Net |  Tax € |
| ------ | ------ | -------- | ----------- | ------- |
| DE | 19% | 119€ | 100€ | 19€ |
| IT | 22% | 119€ | 97,55€ | 21,45€ |

actual state:
![basket](https://user-images.githubusercontent.com/54704329/66208568-a26c8200-e6b5-11e9-8153-7a44ca4b18ed.JPG)

![rules](https://user-images.githubusercontent.com/54704329/66208661-eeb7c200-e6b5-11e9-96ec-2c72463365cf.JPG)

Please could you tell us if the this feature is not implemented jet or or is there an other way to configure it?

Thanks

**Comment by OliverSkroblin** [comment]
Hi @0f8 ,

this feauture has not yet been implemented, but is already on our roadmap.

**Comment by zperee** [comment]
Is this feature implemented now? I have a problem regarding Net and Gross prices. Gross prices are only shown in Germany when the country is changed e.g to Switzerland I get the Net price.

**Comment by keulinho** [comment]
Hey @zperee,

what you experience is that you can define countries that are "tax free", this means just the net prices get displayed. In the default setup this is just the case for Switzerland.

You can activate or deactivate the "tax free" setting for each country under "Settings->Countries".

Kind regards
Jonas

**Comment by sebschaefer** [comment]
any updates on this ?
