### ISSUE TITLE
Bug in static code analysis / Community Store

### ISSUE THREAD

**Issue by Gainto** [shopware/shopware#244]
I don't know whether i'm doing something wrong or this is a bug actually.

Given the scenario:
File: custom/plugins/<myplugin>/src/Resources/administration/src/<somefolder>/index.js

The file has the following content:
`const { Component } = Shopware;
Component.override('somecomponent', {
...
});`

When trying to upload the Plug-In to the community store, I get the following error message regarding this file:
**"Shopware" does not exist. Change its name or declare it so that its usage doesn't result in a "ReferenceError".** 

Well, according to the documentation:
_"...The admin core framework of shopware from src/core/ should always be accessed via the global available Shopware object and not via static imports. ..."_

For me that means, that the code is correct.
When I change:
`const { Component } = Shopware;`
to
`"import { Component } from 'src/core/shopware';"`
the code analysis after uploading the Plug-In works just fine.

But as the documentation stated, import the Compontent from src/core/shopware is not the way to go.

Looks like the static code analysis tool is not able to handle global objects? there is no way for me to publish the plugin other than using a "wrong method" (import from src/core/shopware).

I hope this is understandable, if not, feel free to reply and ask questions.

**Comment by shyim** [comment]
Hey,
I have disabled the rule. Should be away with a new scan. Next time please write an email to plugin-manufacturer@shopware.com cause it not related to the product :blush: 

and the code review is failed cause your bootstrap class name is wrong
