### ISSUE TITLE
[Feature Request] Wishlist functionality

### ISSUE THREAD

**Issue by BogdanChayka** [shopware/shopware#253]
Hey, when is the wishlist functionality coming? It's a core feature in my opinion

**Comment by pantrtxp** [comment]
Hi @BogdanChayka, this feature is definitely on our to-do list. Sadly I can't just yet tell you when this will be implemented.

**Comment by BogdanChayka** [comment]
@pantrtxp alright, will it be at least in 6.1 ? because my customer expects it in his relaunch

**Comment by pantrtxp** [comment]
Sorry to tell you but it is not planned yet. Maybe there will be a plugin from the community for it.
The SW6 wish list will presumably be slightly different as well. More like a persistent shopping cart AFAIK, so maybe a plugin would fit your needs better.

**Comment by BogdanChayka** [comment]
@pantrtxp I would do a plugin, but so far only extending frontend works, I can't override Storefront PHP Classes in plugin for some reason and there is no real documentation on that, for example I would like to override the ProductLoader, instead I have to work with the API

**Comment by keulinho** [comment]
@BogdanChayka what are you trying to achieve?
We throw events for most use cases in the Storefront part, so there shouldn't be a need for overriding.
Did you check the `ProductLoaderCriteriaEvent`? What are you missing there?

**Comment by pantrtxp** [comment]
@BogdanChayka 
Can I close this or do you still ne our support?

**Comment by pantrtxp** [comment]
Closed due to inactivity.

**Comment by mihaifaget** [comment]
Why the documentation shows you how to use the wishlist, when the settings don't exist ?
