### ISSUE TITLE
Warning: Duplicate HttpCacheWarmUpCommand

### ISSUE THREAD

**Issue by tanmarpaul** [shopware/shopware#254]
Not that big of an issue in _src/Storefront/Framework/Command/_

`Warning: Ambiguous class resolution, "Shopware\Storefront\Framework\Command\HttpCacheWarmUpCommand" was found in both "/home/vagrant/shopware-dev/vendor/shopware/platform/src/Storefront/Framework/Command/HttpCacheWarmupCommand.php" and "/home/vagrant/shopware-dev/vendor/shopware/platform/src/Storefront/Framework/Command/HttpCacheWarmUpCommand.php", the first will be used.`

**Comment by keulinho** [comment]
Hey @tanmarpaul,

thanks for raising this issue, we've found the underlying problem and will fix it.

Kind regards
Jonas Elfering
