### ISSUE TITLE
Registration: Phone number validation

### ISSUE THREAD

**Issue by Gainto** [shopware/shopware#257]
If you go to "Settings -> Login / Registration" and activate the field "Phone number field required",
the frontend-validation of the phone number works just fine during the registration process.

There seems to be no backend validation though.
When I remove the "required" flag out of the DOM manually, there seems to be no backend validation and the registration process is successful.

Tested in EA2 and current master

**Comment by keulinho** [comment]
Hey @Gainto,

thanks for raising this issue, a fix is underway.
