### ISSUE TITLE
[Feature Request] Duplicate Product

### ISSUE THREAD

**Issue by BogdanChayka** [shopware/shopware#258]
It's not possible yet to duplicate the product in the admin. For some reason in the database as well, is it encrypted?

**Comment by pantrtxp** [comment]
Could you please tell us what you are trying to achieve? You can not just duplicate products in the database due to primary keys and/or unique fields

**Comment by BogdanChayka** [comment]
![duplicate](https://user-images.githubusercontent.com/3680195/67209106-082b6e80-f417-11e9-873a-d0e052ae39bf.PNG)
In products I'd expect the function "Duplicate" besides edit and delete, just like in WordPress.

**Comment by pantrtxp** [comment]
If you like, you could create an internal ticket for this issue [here](issues.shopware.com). I can not say when or even if this will be implemented though.
It would need to be discussed internally in the first place.

If you need this asap you could only extend the current code via plugin.

Sunny regards 
Thorben Pantring
