### ISSUE TITLE
./bin/console usage flow

### ISSUE THREAD

**Issue by bystro** [shopware/shopware#261]
It is imposible to use ./bin/console before `migration` table is created.
https://github.com/shopware/platform/blob/master/src/Core/Kernel.php#L274

In some deployment flows it is impossible to run scripts or use container entrypoint and the only one way is to write and use console command.

**Comment by pweyck** [comment]
Hello @bystro,

thank you for reporting this. A simple kernel boot should be possible without a database connection. I've create an issue in our issue tracker:

https://issues.shopware.com/issues/NEXT-5307

We're still collecting feedback for a production template. This is one of the issues we want to fix. If there are other issues that would make deployment easier, please report them :) 

Best regards

**Comment by pweyck** [comment]
We've published the production template a few days ago, that fixes this problem.

https://github.com/shopware/production/
