### ISSUE TITLE
Invoice Document: Logo and Country is Null

### ISSUE THREAD

**Issue by Gainto** [shopware/shopware#264]
Logo: Even though I added a logo in the document configuration, config.logo remains null, no matter what I do. I would expect the logo to be set when it has been set in the config. In the document_base_config table the corresponding logo_id field is set properly.

country: In the "document_recipient" Block a variable "billingAddress.country.name" is beeing accessed. billingAddress.country seems is null, even though a country for the billingAddress has been set.

Just create an invoice wihthin the admin for an order to reproduce the issue

EA2 and current Master

**Comment by ssltg** [comment]
We found the problem with the Logo and fixed it.
The billingAddress can be found in order.addresses: this is an array of addresses and you have to match the id against the billingAddressId. Also we fixed a case, that the country was not fully loaded.

**Comment by Gainto** [comment]
Hey @ssltg 
Thanks for the reply.

> The billingAddress can be found in order.addresses:

Well, the "document_recipient" Block uses the "billingAddress.country.name"-variable.
This is the default-block provided by shopware.
When the billingAddress can be found in order.addresses, as you mentioned, then this seems to be a bug. Because  "billingAddress.country.name" is always empty

**Comment by ssltg** [comment]
Hi  @Gainto 

you are right, the local variable in the template is called _billingAddress_, didn't saw that. 
This local variable is set on the top of the Template from 
_{% set billingAddress = order.addresses.get(order.billingAddressId) %}_ 
so the fix above should fix this issue too (added **addresses.country** to the associations )
