### ISSUE TITLE
Issue in sidebar filter if no manufacturer specified in any product in this view

### ISSUE THREAD

**Issue by daMupfel** [shopware/shopware#268]
If i open the shop on a page that only shows products without a manufacturer defined i get a javascript error and i can't use filters or the pagination.

JavaScript error:
```
all.js:78 Uncaught Error: At least one item of ".filter-multi-select-checkbox" must exist in parent node!
    at Function.value (all.js:78)
    at e.value (all.js:80)
    at e.value (all.js:80)
    at e.value (all.js:78)
    at e.value (all.js:80)
    at e (all.js:78)
    at e (all.js:80)
    at new e (all.js:80)
    at Function.value (all.js:78)
    at all.js:78
```

Issue solves itself as soon as i add a manufacturer to a product.

**Comment by almare** [comment]
I can confirm this behavior. I had imported a set of demo products without a manufacturer. I ran into the same problem.

**Comment by pantrtxp** [comment]
Hi @daMupfel and @almare. 
This is a known issue, since the manufacturer is no longer required.
We already have a Ticket for this behavior but cant find it at this moment

Sunny regards
Thorben Pantring

**Comment by pantrtxp** [comment]
Cloud not find the existing one so I created a new one, just to be sure

You can keep Track of this issue [here](https://issues.shopware.com/issues/NEXT-5360)
