### ISSUE TITLE
Adding the same promotion to the cart fails without a clear reason for the end-user

### ISSUE THREAD

**Issue by JoshuaBehrens** [shopware/shopware#275]
**Description**  
Adding the same promotion code (or an other code of the same promotion) results in showing the generic error message.

**Possible Solution**  
Display the message that the code is already used (maybe even in your own cart).

**Additional context**  
A promotion with individual codes fails just with the generic error message. The source of failure when adding the same code or a code of the same promotion is the error that the promotion line item is not stackable. There is already a check for trying to add the same code but that check in `Shopware\Storefront\Controller\CartLineItemController::addPromotion`/`checkout.promotionAlreadyExistsInfo` is not reached as building the new cart is some steps before the duplication check.

**Comment by keulinho** [comment]
Hello,

thank you for creating this issue.
I have opened a ticket on our Issue Tracker for you. See the ticket link: https://issues.shopware.com/issues/NEXT-5434

Please use this ticket to track the state of your issue.
