### ISSUE TITLE
failOnError = false not working in Sync Service

### ISSUE THREAD

**Issue by MrMDeluxe** [shopware/shopware#277]
Due to nested transactions, the Sync Service with failOnError = false is not working.
After the first Doctrine Exception, the next Transaction is always marked for rollback only.
So a commit for the next successful payload causes this Exception:
"Transaction commit failed because the transaction has been marked for rollback only."

When i **remove the calls to beginTransaction(), rollBack() and  commit() from the sync function of the sync service** 
everything works fine.

The EntityWriteGateway calls the transactional function, where the closure is already executed in a transaction. 
So no need for nested ones here...

**Comment by ssltg** [comment]
Hi MrMDeluxe,

thank you for bring this up. This Issue is known and a fix is on its way.

**Comment by MrMDeluxe** [comment]
That sounds good! Thanks.
