### ISSUE TITLE
Custom fields in category entity 

### ISSUE THREAD

**Issue by PheysX** [shopware/shopware#278]
**Description**  
At the moment, its not possible to create custom fields for the category entity.

We need this custom fields for an internally project, is a solution in progress?

**Comment by pantrtxp** [comment]
Hi @PheysX, 

This is currently not possible. But I've created an internal Ticket for this issue since this has to be fixed 
You can keep track of this issue [here](https://issues.shopware.com/issues/NEXT-5448)

Sunny reagrds
Pantrtxp

**Comment by PheysX** [comment]
Hi @pantrtxp 

Can u explain me the problem, maybe we can create a pull request for this issue.

**Comment by keulinho** [comment]
Hey @PheysX 
The backend side should already be done, just the admin component is missing.

Basically you have to add the custom Field card to the `sw-category-detail-base` component. An example of such an card can be found in the `sw-product-detail-base` component.

PRs are always welcomed!
