### ISSUE TITLE
Use ISO codes / enums instead of UUIDs in REST API

### ISSUE THREAD

**Issue by patpilus** [shopware/shopware#279]
**Description**  
Shopware REST API (eg. SalesChannel API - https://docs.shopware.com/en/shopware-platform-dev-en/api/sales-channel-customer-api?category=shopware-platform-dev-en/api) forces to use UUIDs for 'dictionary' terms like countries of the world, salutations etc. 
What is more, these UUIDs are randomly generated during database initialisation. As a result it's impossible to test endpoints on CI, where the database is initialised from the scratch on each run.

Why frontend client must be forced to know these random identifiers? Isn't better to use widely known ISO-3166 standard for countries? Similarly eg. `salutationId` can be replaced with API documented enums etc.

**Possible resolution**
Replace UUID requirement with ISO codes where it is possible or enums otherwise. 
If that requires huge refactor, please adjust migrations to use 'constant' UUIDs for these terms instead of generating random ones each time the database migrations are executed.

**Comment by pweyck** [comment]
Hello @patpilus,

thank you for your feedback. I agree with you that looking up UUIDs for entities with natural primary key is tedious. I've created an issue in our issue tracker:

https://issues.shopware.com/issues/NEXT-5497

Regarding the other solution: I personally dislike magic identifiers. We've removed a lot of them recently and want to remove more. We don't want third-parties to depend on these.

Kind regards
Patrick
