### ISSUE TITLE
Show exception details in frontend

### ISSUE THREAD

**Issue by tyurderi** [shopware/shopware#282]
**Description**
If you are developing a new plugin and something you are doing is wrong which then throws an exception yet the only output in the frontend I'll get is a message like `Unfortunately, something went wrong.`

At this point I would except the normal behaviour of the Symfony ErrorHandler. My current workaround is the following in `src/Storefront/Framework/Routing/StorefrontSubscriber.php`.

```
127      public function showHtmlExceptionResponse(ExceptionEvent $event): void
128      {
    +        return;
129          if ($event->getRequest()->attributes->has(PlatformRequest::ATTRIBUTE_SALES_CHANNEL_CONTEXT_OBJECT)) {
```

**Example**  

While `APP_ENV=dev` the Symfony ErrorHandler should be used instead of the customization from Shopware.

**Comment by mitelg** [comment]
thanks for your contribution @tyurderi :+1: :tada: :blue_heart:
