### ISSUE TITLE
Cannot extend Storefront js Plugin with PluginManager

### ISSUE THREAD

**Issue by binaermanufaktur** [shopware/shopware#289]
Trying to override an existing Storefront Plugin (OffCanvasCart) as in [here](https://docs.shopware.com/en/shopware-platform-dev-en/how-to/extend-core-js-storefront-plugin?category=shopware-platform-dev-en/how-to).
With `./psh:phar storefront:build` from within the container the webpack process compiles js files without error.
Within my storefront/main.js calling the the PluginManager works:
`console.log(PluginManager.getPlugin('OffCanvasCart'));`
outputs an Object
`Map(4) {"class" => ƒ, "name" => "OffCanvasCart", "registrations" => Map(1), "instances" => Array(0)}`
, but 
`PluginManager.override('OffCanvasCart',MyOffCanvas);`
outputs
`Uncaught Error: The plugin "OffCanvasCart" is not registered.`
This happens with every Plugin (not only OffCanvasCart) from 
`PluginManager.getPluginList()`

**Comment by klarstil** [comment]
Hey @binaermanufaktur,

thanks for creating this issue and excuse the delay please. I tried out your provided use case and it works like a charm. Here's the code I used to reproduce the issue:

```js
// 1. Import the plugin you want to override
import OffcanvasCartPlugin from 'src/plugin/offcanvas-cart/offcanvas-cart.plugin';

// 2. Create a new plugin which extends the original plugin
class MyOffCanvasCart extends OffcanvasCartPlugin {
    init() {
        super.init();
        console.log('my offcanvas cart override');
    }

    newFooMethod() {
        console.log('foo');
    }
}

// 3. Use the global plugin manager to override the plugin
window.PluginManager.override('OffCanvasCart', MyOffCanvasCart, '[data-offcanvas-cart]');

// 4. Get the plugin
console.log(window.PluginManager.getPlugin('OffCanvasCart'));
```

After running the command `./psh.phar storefront:build` I get the following console output in the storefront:

![Screenshot 2019-11-19 at 14 08 31](https://user-images.githubusercontent.com/170133/69149448-c73a7e80-0ad6-11ea-8e00-09c7e7d9cc4f.png)

Could you please provide a detailed workflow how to reproduce the issue?

Best regards

**Comment by binaermanufaktur** [comment]
@klarstil 
Sorry for the delay on getting back on this.
It works with your input...
It was calling the PluginManager in a global scope...
Thanks!

**Comment by keulinho** [comment]
Glad that you figured it out ;)

**Comment by saeid-elio** [comment]
> [@klarstil](https://github.com/klarstil) Sorry for the delay on getting back on this. It works with your input... It was calling the PluginManager in a global scope... Thanks!

I don't understand your comment. You mean the problem was that you were calling PluginManager without prefixing it with "window"? That should make no difference since window is the global environment in a browser.
