### ISSUE TITLE
Elasticsearch ElasticsearchProductDefinition functions not called

### ISSUE THREAD

**Issue by almare** [shopware/shopware#291]
**Description**  
If I try to extend the elasticsearch with an ElasticsearchProductDefinition class. I would expect that the functions 
```
    public function extendCriteria(Criteria $criteria): void
    public function buildFullText(Entity $entity): FullText
```
would be called. This is currently not the case. This makes it impossible to extend the search with custom fields.
 
**Possible Solution**  
It should work like described in the docs.

**Comment by OliverSkroblin** [comment]
Hi @almare,

It would be good if you could give some more information about your example implementation:

- Did you decorate the existing ElasticsearchProductDefinition?
- How is your definition registered in the DI container?
- What exactly do you expect from the functions? They are called when the data is indexed.

**Comment by almare** [comment]
Hi @OliverSkroblin ,
thank you for your response. I followed the guide from here [docu](https://docs.shopware.com/en/shopware-platform-dev-en/how-to/index-entity-to-elasticsearch?category=shopware-platform-dev-en/how-to) 

I guess the the registration of my DI container works so far, because I can see the entities inside the elasticsearch index and also the xdebugger stops inside my getMapping function if I set a breakpoint. 
So the basic indexing is working. My problem is now, I am not able to use the provided functions, because they are not called.

The buildFullText function in my ElasticsearchProductDefinition for example. I would like to add additional data / informations into the full text search field. Due to the reason that this function is not called I am not able to extend this field and test the behaviour of the search. I started debugging the index process, and it looks for me that this function is is not called in context of the provided definition classes. Currently it looks that only the original shopware function buildFullText is called in this case. Shouldn't there be a piece of code which iterates over the provided class functions?

Honestly the extendCriteria I didn't check it depth. Here I am saying it "looks" like it is also not called.
I just tried to add my custom enitites to  the critiria object, to see how is it working and how I could manipulate the search process.
 
I expect, when the buildFullText function is called, that I am able to enrich the indexed data with my provided plugin informations. So customers should be able to find a product which contains parts of my plugin informations which enrich the product.

Hopefully this helps to find the problem if there is one.

**Comment by OliverSkroblin** [comment]
Hi @almare,

the `extendCriteria` function is called here: https://github.com/shopware/platform/blob/master/src/Elasticsearch/Framework/Indexing/IndexingMessageHandler.php#L112

and the `buildFullText` is called here: 
https://github.com/shopware/platform/blob/master/src/Elasticsearch/Framework/Indexing/IndexingMessageHandler.php#L157

If i add a debug state in the original `ElasticSearchProductDefinition` the output will be printed.

**Comment by almare** [comment]
Regarding the `buildFullText`
Right this is the place where the original shopware ElasticSearchProductDefinition is called. I completely agree. I also see the shopware output, but I also would like to add my data :-)
 
At this point I thought my custom `buildFullText` function from my custom ElasticSearchProductDefinition class would be executed, but this doesn't happen. This is exactly my problem.

**Comment by OliverSkroblin** [comment]
Hi @almare,
sorry for the late response. I created a test plugin which decorates the original product definition of the elasticsearch.

https://github.com/OliverSkroblin/sw6-test-plugin

The `buildFullText` will be called from the `php bin/console messenger:consume` command

**Comment by almare** [comment]
Now I understand my mistake. I completely misunderstand the demo code. Thank your very much for clarifying how it works.

**Comment by OliverSkroblin** [comment]
You're welcome ;)
