### ISSUE TITLE
Can't save HTML in Snippets

### ISSUE THREAD

**Issue by BogdanChayka** [shopware/shopware#293]
**Description**  
At the moment when I try to save "supportInfo" the string gets escaped and no HTML is being saved.

**Possible Solution**  
Allow saving HTML to Snippets.

**Comment by ssltg** [comment]
Thank you for bringing this up.
The Problem with the "supportInfo" snippet is, that we don't allow the <small>-Tag currently. If you delete it, the snippet will be saveable. We will figure out wether we allow this tag or change the snippet to a set of allowed tags.

**Comment by ssltg** [comment]
Hi @BogdanChayka ,

are you on an EA Version or on the current master? With the master it should work now.

**Comment by ssltg** [comment]
Closed due to inactivity
