### ISSUE TITLE
Filter orders based on status

### ISSUE THREAD

**Issue by tekbird** [shopware/shopware#294]
I want to filter orders based on their status (open, in_progress, ...)

However, the admin API does not seem to do this correctly. In fact, the admin API does not do any filtering at all.

I access the following API:
http://xxxxxxxxxxxxxxx/api/v1/order?filter[0][field]=orderDateTime&filter[0][value]=2019-11-15T14:28:15+00:00&filter[0][expression]=>=&filter[0][type]=multi

The response still contains all orders, not just the ones whose orderDateTime are greater than or equal to the given value.

Although the above url tries to filter based on orderDateTime, I wanted to filter based on status and have no idea or documentation on how to do it. So I was trying to see if filtering works at all.

**Comment by OliverSkroblin** [comment]
Hi @tekbird,

to filter via API I would recommend the `POST /api/v1/search/..` endpoint. Here you can send the filters via JSON:

`api/v1/search/order`
```
{
   "filter": [
      { 
         "type": "range", 
         "field": "orderDateTime", 
         "parameters": {
            "gte": "2019-11-21"   
         }
      }   
   ]
}
```

To filter for the different order states you can use this query:
```
{
   "filter": [
      { 
         "type": "equalsAny", 
         "field": "stateMachineState.technicalName", 
         "value": ["open", "in_progress"]
      }   
   ]
}

```

**Comment by tekbird** [comment]
@OliverSkroblin , hello, thanks for the support. it is indeed the right way.
