### ISSUE TITLE
Use Composer for Plugins

### ISSUE THREAD

**Issue by htuscher** [shopware/shopware#300]
**Description**  

It would be great if there would be a composer repository to require shopware plugins which also respects all other dependencies from that plugins composer.json.

A possible solution would be to modify the composer installer for the `shopware-plugin` type to remove vendor directories if the plugin is included via composer. Therefore there would be a common standard for shipping dependencies either as standalone plugins (classical way with vendor dir) or via a composer repository.

You could even go full composer when using the approach from Contao:
https://medium.com/@yanick.witschi/composer-cloud-resolver-e64254f5728e

It's always a problem if you need to ship a plugin with an external library that has e.g. a dependency to Monolog or Guzzle or something widely used.

**Comment by pantrtxp** [comment]
Hi @hhoechtl,

sorry for the late reply.

Currently this is not planned. We'll think about realising this when we upgrade composer to Version 2 or above.

Sunny regards
Pantrtxp
