### ISSUE TITLE
Internally seo generated links in sw-text-editor

### ISSUE THREAD

**Issue by PheysX** [shopware/shopware#304]
**Description**  
Choose between internally and externally links in the sw-text-editor component in administration to link products and categories with seourls.

Is Shopware open for that? We will do it for our company anyways, so we can pull it to platform.

**Comment by mnaczenski** [comment]
It should be already possible to link a seo url with a specific combination of uuid and placeholder.

https://github.com/shopware/platform/blob/e20ad19c2de3c3ccc355a0fd4dfafcb5def0bbe9/src/Core/Framework/Seo/SeoUrlPlaceholderHandler.php#L52

`<a  href="124c71d524604ccbad6042edce3ac799/detail/uuid#">
   Link Title
</a>`

So it should be possible to Link products, categories and so on with their technical url and the magic placeholder "124c71d524604ccbad6042edce3ac799".


![Bildschirmfoto 2019-11-22 um 14 03 39](https://user-images.githubusercontent.com/10058559/69428218-f9471d00-0d30-11ea-8f56-eec519b6de33.png)

![Bildschirmfoto 2019-11-22 um 14 04 01](https://user-images.githubusercontent.com/10058559/69428235-ff3cfe00-0d30-11ea-97a3-5167c6e7befc.png)

It will be converted to the SEO Url in the frontend.

**Comment by PheysX** [comment]
Good to know but it should be possible to select them as editor in the gui with the sw-entity-single-select component. 

I would add this element to the sw-text-editor-toolbar-button component.

**Comment by mnaczenski** [comment]
Sure, an UI-component for selecting entities (categories, products) would be nice. Feel free to make an PR :)

Please keep in mind, that urls might change and the solution above should be "bullet proof", so linking directly with the SEO Url won't be a good solution.

**Comment by PheysX** [comment]
Hey Moritz,

i would create a tabs component (internal, external) and add a select to the internal tab to choose the entity who display an entity input. Also i would  add a title input. Something like this:

![Unbenannt](https://user-images.githubusercontent.com/28557712/69995301-1d380900-1550-11ea-89ff-45c6279bb410.png)

What do you think about my graphic masterpiece? :)

**Comment by mnaczenski** [comment]
Looks good!
I think this would be a huge improvement for shopware.

**Comment by hlohaus** [comment]
Additionally a media selection would be nice. :D
Like i did it in
https://github.com/hlohaus/SheTinyMce

**Comment by PheysX** [comment]
@hlohaus This feature is in another castle :D

**Comment by mnaczenski** [comment]
@PheysX 
Can we close this issue for now or do you need some additional information?

**Comment by PheysX** [comment]
Yeah, u can close this issue, sry for my late response.  @mnaczenski

**Comment by AndreasA** [comment]
@mnaczenski I know this issue is older, I would just like to know if I am correct and it is necessary to place `#` at the end of the URL
 for the replacing to work as expected and, of course, to start it with `124c71d524604ccbad6042edce3ac799/`?
