### ISSUE TITLE
The color and font settings do not appear in the admin panel

### ISSUE THREAD

**Issue by joanna-gil** [shopware/shopware#309]
**Description**
After installing "pure" shopware6, there is no way to change colors and fonts in the admin panel, also for the default theme. No error appears in the console either

![Screenshot from 2019-11-26 09-53-30](https://user-images.githubusercontent.com/57439261/69614075-d79cad00-1032-11ea-9430-6ee1a4d64302.png)

**Comment by keulinho** [comment]
Hey @joanna-gil,

thanks for raising this issue. 

First of all i've transfered this issue to `shopware/platform`, as this is the repo where we handle the Shopware 6 Admin, Core and Storefront.

Can you try to run the `./psh.phar administration:build` command in your project root directory, that should already fix your issue.

Kind regards
Jonas

**Comment by joanna-gil** [comment]
Hi @keulinho! Thank you for such a quick response.

Unfortunately, the execution of this command did not add the ability to change colors and fonts, there is still no panel part. The `./psh.phar administration: build` command was issued without any error. I'm working on Linux with a Shopware docker container

**Comment by pantrtxp** [comment]
Hi @joanna-gil 

This behavior was fixed in [this](https://github.com/shopware/platform/commit/78328caedd198fa9876a51cf3db945313656428d) commit today. Please rebase with our master and all should be fine

Sunny Regards
Pantrtxp
