### ISSUE TITLE
api createProduct return code 200

### ISSUE THREAD

**Issue by mschradi** [shopware/shopware#311]
**Description**  
If I try to create a product with the API, I get the return code 200 instead of 201, like the documentation says.

**Possible Solution**  
fix the statuscode if the product is successfully created

**Additional context**

**Comment by mschradi** [comment]
this ist the raw json (application/vnd.api.json)
`{
    "data":{
        "type":"product",
        "id":"",
        "attributes":{
            "active":true,
            "stock":1,
            "taxId":"68d46d674bc0411ebb97d03dad270135",
            "price":[{
                "currencyId":"b7d2554b0ce847cd82f3ac9bd1c0dfca",
                "net":15.0,
                "gross":10.0,
                "linked":true}],
            "productNumber":"TEST001",
            "isCloseout":false,
            "purchaseSteps":0,
            "maxPurchase":0,
            "minPurchase":0,
            "purchaseUnit":0.0,
            "referenceUnit":0.0,
            "shippingFree":false,
            "purchasePrice":0.0,
            "name":"Testproduct No. 1"
        }
    }
}`
![image](https://user-images.githubusercontent.com/7922343/69642621-54934b00-1062-11ea-9ac2-4ef674f0097c.png)

![image](https://user-images.githubusercontent.com/7922343/69642241-c323d900-1061-11ea-8b16-35aecc624557.png)

in this case, I got http statuscode 204. But it still creates my product.

**Comment by pweyck** [comment]
Hello @mschradi,

thanks for reporting it. We already have an issue for that in our issue tracker:

https://issues.shopware.com/issues/NEXT-831

Kind regards
