### ISSUE TITLE
Footer links

### ISSUE THREAD

**Issue by joanna-gil** [shopware/shopware#317]
**Description**  

Footer links do not work. I added a catalog to the footer (admin panel in Storefront> Navigation> Entry point footer navigation), it appears on the page, but if I want to go to the link that has been created (in the admin panel the link is active and has an assign layout) the page takes me to main page. Just now I was pull the latest changes from development and platform repositories

**Comment by taltholtmann** [comment]
Thank you very much @joanna-gil :blue_heart::blue_heart:
We are already informed about the problem, here is a link to the issue page for tracking the status: [NEXT-5322](https://issues.shopware.com/issues/NEXT-5322)

**Comment by colinmurphy** [comment]
For what it is worth you need to have the links under the main root category of the store in order for the links to work. There is a single line of code that checks to see if the footer link is a sub-category of the root category. 

As a workaround, I put the footer links into a sub-category "CMS" under the root category and then I then updated the SEO links to strip out the link "cms/". I hope that helps.
