### ISSUE TITLE
Not able to override templates in storefront/utilities/

### ISSUE THREAD

**Issue by stefanpoensgen** [shopware/shopware#327]
**Description**  
Since https://github.com/shopware/platform/commit/a4ad9346ff6bbc28181be040defa9559c827b6c9 you are not able to override templates from storefront/utilities/ e.g. storefront/utilities/icon.twig.html

There might be something wrong with the bundle sorting in https://github.com/shopware/platform/blob/master/src/Storefront/Theme/Twig/ThemeInheritanceBuilder.php#L32

**Possible Solution**  
`return array_reverse($flat);` will fix it but i'm not sure if this is the right way to fix this

**Comment by labtrix-media** [comment]
The same for /storefront/section/cms...

**Comment by OliverSkroblin** [comment]
Hey @stefanpoensgen,

Thank you for pointing that out. You're right here was still missing an array reverse. I have adapted the whole. Should be sync on Github right away.

**Comment by OliverSkroblin** [comment]
@stefanpoensgen here is the fix: https://github.com/shopware/platform/commit/d4d00ac736043bf30fa25253c9ce2aae2c1a314a
