### ISSUE TITLE
First run wizard domain verification issue

### ISSUE THREAD

**Issue by snax4a** [shopware/shopware#328]
**Description**  
I have installed shopware 6 on OS X with bitnami installer and it looks like there is some issue with domain verification API, I cant finish firtst time run wizard it fails with this error: Internal Server Error
License host verification failed for domain

**Additional context**  
Here is a screenshoot of browser network tab: 
![shopware_issue](https://user-images.githubusercontent.com/20664868/69903525-bb826e00-139a-11ea-9c2c-45960597ebe9.png)

**Comment by snax4a** [comment]
I managed to fix that.
It was because my shopware account had only v.5.6.2 shop created in merchant area
I added another shop with v 6.0.0 ea-2 and it worked.

You should handle this case in the API response

**Comment by pantrtxp** [comment]
Hi @snax4a 

Happy to hear that you could fix this by yourself. We should provide a more verbose error message though. I've created an internal ticket for this behavior.

Thank you for bringing this up. :+1: 

Sunny regards
Pantrtxp
