### ISSUE TITLE
In-depth guide administration module documentation incorrect

### ISSUE THREAD

**Issue by macster84** [shopware/shopware#329]
**Description**  
The in-depth guide documentation contains an error that will ultimately prevent the plugin's administration module being built by webpack.
In file `070-administration.md`, section '_Setting up the the administration_', the `main.js` must be placed in the `Resources/app/administration/src `directory (subdirectory `src` is currently missing). This was forgotten in commit '_NEXT-4148 - Updated missed documentations_'.
It is correct in the [example sources](https://github.com/shopware/swag-docs-bundle-example) though.

**Possible Solution**  
Correct the path for `main.js` to `Resources/app/administration/src`.

**Additional context**  
n/a

**Comment by keulinho** [comment]
Hey @AlPhi247,

thanks for raising this issue we've updated docs and the change should be deployed soonish.

Kind regards
Jonas
