### ISSUE TITLE
Shopware Translator fallback catalogue circular reference when using with Symfony 4.4

### ISSUE THREAD

**Issue by patpilus** [shopware/shopware#330]
**Description**  
After updating to the latest `shopware/core` #369823e master I'm getting exception during execution of components which are utilising `Translator` component (eg. `Validator`):
```
Symfony\Component\Translation\Exception\LogicException {#4058
  #message: "Circular reference detected when adding a fallback catalogue for locale "en-GB"."
```

That's probably due to this change in symfony: https://github.com/symfony/symfony/pull/32106

**Additional context**  
`Symfony\Component\Translation\MessageCatalogue` `getFallbackCatalogue()->getLocale()` returns now `en_GB`. Previously it was just `en`.

Please look also at https://github.com/shopware/core/blob/6fa006dba722cc4b89fc377fdf22556708bab995/Framework/Translation/Translator.php#L101 
On my `shopware/core` instance: `$catalog->getLocale()` returns `en_GB`, but `$fallbackLocale` equals `en-GB`, so it tries to execute `addFallbackCatalogue` when it probably should not.

**Comment by keulinho** [comment]
Thanks for bringing this up @patpilus, but unfortunately i can't reproduce this behaviour.
On my machine `$catalog->getLocale()` returns `en-GB` which works.

I suspect that some configuration in your environment leads to the described bug.

Can you provide more information on how to reproduce this? Ideally you could add a failing test to the `TranslatorTest`, to verify that this issue won't come up again.

**Comment by patpilus** [comment]
@keulinho well, from my side it seems that `default_locale` defined in https://github.com/shopware/core/blob/12f100daba8eede66232eada174a1f4aa831e247/Framework/Resources/config/packages/framework.yaml#L12 is `en_GB`.

Overriding `default_locale` to `en-GB` in `framework.yaml` temporarily solves the circular reference issue, but results in empty `MessageCatalogue`:
```
Symfony\Component\Translation\MessageCatalogue {#3958
  -messages: []
  -metadata: []
  -resources: []
  -locale: "en-GB"
  -fallbackCatalogue: null
  -parent: null
}

```

**Comment by patpilus** [comment]
If you're using Symfony Translator components inside your own Translator, isn't cleaner to use underscores instead of dashes for locales like Symfony does (eg. en_GB, en_US etc.)? 

In my opinion introducing dashes gives no value, but creates only additional mess.

**Comment by keulinho** [comment]
We had for a long time dashes and underscores in locales and converted them in multiple places, because the vue translation component needs dashes

Therefore we refactored everything to just have one way of handling locales and decided to use dashes. We based our decision on this RFC https://tools.ietf.org/html/rfc5646.

**Comment by patpilus** [comment]
I understand this point of view, however if you're utilising Symfony Translator classes you should probably introduce some kind of transformer (in Shopware Translator) between locales with dashes and underscores, to make it work properly.

Could you please verify whether the Symfony `MessageCatalogue` with locale `en-GB` contains any translations or looks rather like empty object below?:
```
Symfony\Component\Translation\MessageCatalogue {#3958
  -messages: []
  -metadata: []
  -resources: []
  -locale: "en-GB"
  -fallbackCatalogue: null
  -parent: null
}
```

**Comment by keulinho** [comment]
I was finally able understand the underlying problem fully and a fix is underway.

If you then request an catalogue with locale `en-GB` the catalogues with locales `en` and `en_GB` would be added as fallback locales, so IMHO it's not necessary to transform the locales in the shopware translator itself.

**Comment by patpilus** [comment]
Thank you @keulinho

**Comment by keulinho** [comment]
Thanks @patpilus for raising this and especially for putting so much effort into reporting so much additional context, e.g. the symfony changes, etc. 
That really helped sorting this out and fixing the underlying problem. :+1: :blue_heart:
