### ISSUE TITLE
PHP 7.4 - unknown password hashing algorithm: DEFAULT, incompatible dependencies

### ISSUE THREAD

**Issue by patpilus** [shopware/shopware#332]
**Description**  
After upgrading to PHP 7.4 I'm getting warning during password hashing:
```
Warning: password_hash(): Unknown password hashing algorithm: DEFAULT in vendor/shopware/core/Framework/DataAbstractionLayer/FieldSerializer/PasswordFieldSerializer.php line 34
```

**Possible Solution**  
Use one of available options returned by `password_algos()`, which currently are: `2y`, `argon2i` or `argond2id`. 

Alternatively use constants like `PASSWORD_DEFAULT`, as stated in: 
https://wiki.php.net/rfc/password_registry#backward_incompatible_changes

**Comment by keulinho** [comment]
Hey @patpilus,

that's weird as it runs on our ci, probably there are differences with different php builds.

However a fix is on the way.

Kind regards
Jonas

**Comment by patpilus** [comment]
@keulinho thanks. I've used `7.4-fpm-alpine-3.10` from docker hub: https://hub.docker.com/layers/php/library/php/7.4-fpm-alpine3.10/images/sha256-74933e05838128c933d7a46dfa718f243a64925afdaa380d133e43df5012f4bf.

I've just noticed another issue regarding php 7.4: shopware/core dev-master requires zircote/swagger-php 3.0.2 (https://github.com/shopware/core/blob/369823e58b01a0ebbdc7efad44d17f154212fa1f/composer.json#L108), which is not fully compatible with 7.4. There's `zircote/swagger-php` 3.0.3 release with php 7.4 support: https://github.com/zircote/swagger-php/releases/tag/3.0.3

**Comment by keulinho** [comment]
Thanks for the information, we'll update the package.

**Comment by keulinho** [comment]
@patpilus we've changed the password hashing handling and it should solve your problem.
We've also updated the zircote/swagger-php package.

Thanks again for raising this issues. Don't hesitate to reopen this or open a new issue if you are still experiencing any problems.
