### ISSUE TITLE
The language switch on the frontend doesn't work

### ISSUE THREAD

**Issue by joanna-gil** [shopware/shopware#335]
**Description**  
When I try to add the ability to change the language to the page, after saving the changes, the following error appears on the store.
![Screenshot from 2019-12-03 10-01-42](https://user-images.githubusercontent.com/57439261/70035980-2b1f7580-15b4-11ea-963f-a03c39071a61.png)

 I change the language in the admin panel using the tutorial available on youtube: https://www.youtube.com/watch?v=PJ1YnNgJeaw

**Comment by keulinho** [comment]
Hey @joanna-gil,

could you try to save the domain for the language with a trailing slash probably `http://localhost:8000/de/`.

Does that solve the problem for you?

However we are looking into this.

**Comment by joanna-gil** [comment]
Sorry for the problem, I found a mistake in my side - I didn't change the security level from https to http, therefore it couldn't find the right location
