### ISSUE TITLE
ProductExportController uses Storefront dependencies

### ISSUE THREAD

**Issue by patpilus** [shopware/shopware#337]
**Description**  
ProductExport controller uses Storefront dependencies, what makes `shopware/core` impossible to use without storefront being installed.

It was introduced here:
https://github.com/shopware/core/commit/db7b70a3579f9b68582a9dd3d4d08fc9199ab17d#diff-db5b2b0ac4427ddbc8eaaa0bf8b88687R21

**Possible Solution**  
Remove Storefront dependencies from `shopware/core`

**Comment by OliverSkroblin** [comment]
Hi @patpilus,

Thank you for pointing that out. I adjusted the things. There was also a dependency in Core\Content\Seo which I fixed. The Administration, Core and Elasticsearch bundles no longer have a dependency on the Storefront Bundle.

**Comment by OliverSkroblin** [comment]
Here is the fix: https://github.com/shopware/platform/commit/5d896acfbf18ab175406283428d3a31dce204dd0
