### ISSUE TITLE
media api getMediaList

### ISSUE THREAD

**Issue by mschradi** [shopware/shopware#338]
**Description**  
same issue like #228 but this time in media api.

attributes and links have to be objects!
https://jsonapi.org/format/#document-links

![image](https://user-images.githubusercontent.com/7922343/70060775-713ffd80-15e3-11ea-847f-b05570770161.png)

**Comment by keulinho** [comment]
Thanks for raising this issue @mschradi, a fix is underway ;)

**Comment by keulinho** [comment]
Hey @mschradi,

we've fixed this issue on the 6.1 branch. Thanks again for raising this issue.

Kind regards
Jonas
