### ISSUE TITLE
Newsletter Controller Overwrites status of existing entitys

### ISSUE THREAD

**Issue by Sheek44** [shopware/shopware#339]
**Description**  
When registering to the newsletter via the sales-channel-api newsletter controller the entered email wont get checked if it already exists in the database.
The old entity just gets overwriten and its status gets set to notSet even if it was optIn before.

**Possible Solution**  
Check if the email is already optIn and return the for that case created constant CUSTOMER_EMAIL_NOT_UNIQUE

**Additional context**

**Comment by ssltg** [comment]
Hi Mortis,

thank you for bringing this up. We have an Issue for this Topic and will fix it.
You can follow the Status here: https://issues.shopware.com/issues/NEXT-3713

Greets,
Stefan
