### ISSUE TITLE
 Removing products from the cart doesn't work.

### ISSUE THREAD

**Issue by joanna-gil** [shopware/shopware#348]
**Description**  
To trigger an error:
- Add product to the basket
- Go to another page that doesn't have products, e.g. Home page then this error appears in the sidebar
![Screenshot from 2019-12-05 13-12-38](https://user-images.githubusercontent.com/57439261/70234519-1af8c900-1761-11ea-91af-c8194a86fee5.png)

- Try to remove the product from the basket using the sidebar
![Screenshot from 2019-12-05 13-13-42](https://user-images.githubusercontent.com/57439261/70234529-1e8c5000-1761-11ea-9fd0-cff4d3869e87.png)

**Comment by keulinho** [comment]
Hey @joanna-gil 
this is a known error and should already be fixed.
The fix was merged yesterday, could you please update to the lastet master it try if the fix solves your bug?

Kind regards 
Jonas

**Comment by joanna-gil** [comment]
Thanks, it actually works. I downloaded Shopware yesterday afternoon and didn't check if something new came out, thank you for fixing the bug!
