### ISSUE TITLE
Can't add new rating

### ISSUE THREAD

**Issue by joanna-gil** [shopware/shopware#350]
**Description**  
When I try to send a rating on the product page, I get such an error in the network
![Screenshot from 2019-12-05 15-20-55](https://user-images.githubusercontent.com/57439261/70243447-dd04a080-1772-11ea-8250-dad9adab4e9f.png)

![Screenshot from 2019-12-05 15-19-35](https://user-images.githubusercontent.com/57439261/70243371-bcd4e180-1772-11ea-8487-579f14998355.png)

**Comment by keulinho** [comment]
Hey @joanna-gil,

thanks for reporting this issue. I can confirm it at will work on a fix.

Kind regards
Jonas Elfering

**Comment by keulinho** [comment]
Hey @joanna-gil,

with commit https://github.com/shopware/platform/commit/ecd8a9735e45318d4c5882f957e484714db2bb20
on the 6.1 branch this issue was fixed.
