### ISSUE TITLE
Shopware 5 Rest API Filter Orders

### ISSUE THREAD

**Issue by tekbird** [shopware/shopware#353]
**Description**  
How to filter orders based on complex conditions

I need to filter orders from Shopware 5 by applying complex conditions. For example: I want to filter orders whose create time is greater than x date and have status either 1 or 250. I tried using the filter based on query params (?filter[0][property]=xx&....) but seems do not work. Is there any way to get this working?

**Comment by OliverSkroblin** [comment]
Hi @tekbird,

this is the shopware 6 repository. You can find the shopware 5 sources here: 
https://github.com/shopware/shopware

**Comment by tekbird** [comment]
HI @OliverSkroblin 
I could not find a place to create issue in Shopware5 repository. Can I do it here: https://github.com/shopware/development/issues ?

**Comment by keulinho** [comment]
development is also for shopware 6. 
Please use the issue tracker for shopware 5 issues: https://issues.shopware.com/
