### ISSUE TITLE
Can't add static assets in custom theme

### ISSUE THREAD

**Issue by joanna-gil** [shopware/shopware#357]
**Description**
When I try to add a static image as an asset I get an error in a network from devtools
![Screenshot from 2019-12-09 10-43-03](https://user-images.githubusercontent.com/57439261/70425043-b72c1400-1a70-11ea-8e71-d318d5ba9023.png)

In the theme.json I add registration for asset as path
''' "assets": [
"app/storefront/src/assets"
],
'''
and trying to get this image from scss file in path 'Resources/app/storefront/src/scss/base.scss' as a '''background: url("../assets/img/Image 17.png");'''
Could you tell how can I get this image or any other icon from custom theme?

**Comment by OliverSkroblin** [comment]
Hi,

Currently we still have a problem with the compatibility between SCSS and templates. In the templates you can use the `asset` function which resolves the corresponding path to an url. In SCSS we have not implemented this yet. Currently you have to specify the path relative to your compiled CSS file:

I have the following folder structure here:
```

MyNewTheme
├── composer.json
└── src
    ├── MyNewTheme.php
    └── Resources
        ├── app
        │       └── src
        │           ├── assets
        │           │   └── test_image.jpg
        │           ├── main.js
        │           └── scss
        │               └── base.scss
        └── theme.json


``` 
In twig:
```
<img src="{{ asset('bundles/mynewtheme/assets/test_image.jpg') }}">
``` 


In SCSS:

```
background: url("../assets/test_image.jpg");
```

**Comment by aloiki** [comment]
Hey, 
the watcher is running and the bundle for 'bundles/mynewtheme/' is not generated. 
How to resolve this problem ? 
And is there a specific place for the CMS blocks to place the images ?
