### ISSUE TITLE
Logged in customer can delete another customer address

### ISSUE THREAD

**Issue by kryst3q** [shopware/shopware#361]
**Description**  
Assume we have two customers registered: A and B. Customer A has address with id 1 and customer B has address with id 2. When I log in as customer A and send request to delete address with id 2 (that belongs to customer B) I succeed.
The problem lies in [validateAddressId method](https://github.com/shopware/core/blob/master/Checkout/Customer/SalesChannel/AddressService.php#L191). Even thought [there](https://github.com/shopware/core/blob/master/Checkout/Customer/SalesChannel/AddressService.php#L191) is `customer_id` filter added in search criteria the address is found. It seems like it is not taken into account or both filters are applied with `OR` connector.

**Additional context**
Shopware/core version: dev-master

**Comment by OliverSkroblin** [comment]
Hi @kryst3q,

thanks for the report. We fixed the issue in the following commit: 
https://github.com/shopware/platform/commit/70a2d24ccf9c0d3e09a757d638bf5a80a25e5535
