### ISSUE TITLE
Custom Plugins do not load anymore

### ISSUE THREAD

**Issue by ic-hv** [shopware/shopware#370]
Starting with commit revision b81d52b8 the plugin directory layout structure was changed heavily. Instead of the previous dynamic resolution mechanism, which utilized `Bundle::getStorefrontStylePath` and `Bundle::getStorefrontScriptPath()` to get the correct paths for js / (s)css files, the mentioned commit introduced a static path setup. 
Because of this all the plugins we have developed for Shopware 6 won't load anymore, though they still are programmed according to the guidelines within the Developer Docs.

Now I am wondering: Do we have to adapt our plugins and use the newly introduced (in my eyes weird) static path setup - or will this issue be fixed? If not - please be so kind and also update the developer docs accordingly. 

Thank you very much, so far!

**Comment by ic-hv** [comment]
Well ok, the following link described what I have to change to make my plugins work again: https://docs.shopware.com/en/shopware-platform-dev-en/getting-started/recent-updates (2019-11-14: Refactored resources directories) ... but unfortunately the link is dead now :( 

Could you please again provide a reference how the plugin directory / path structure should look like ... Thank you!

**Comment by keulinho** [comment]
hey @ic-hv,

you can take a look at the changelog, there are these changes documented.
https://github.com/shopware/platform/blob/master/CHANGELOG-6.0.md#L253

Kind regards
Jonas

**Comment by ic-hv** [comment]
Thanks! So, the plugin directory structure should (now) look like below: 
![grafik](https://user-images.githubusercontent.com/26538616/70886669-4dfe5080-1fdc-11ea-9af9-1b83cfb72a74.png)

**Comment by keulinho** [comment]
exactly :+1:

**Comment by OliverSkroblin** [comment]
Thank you for answering @keulinho . Since here all the questions were answered, i will close the ticket. If something is still open please just open a new ticket ;)
