### ISSUE TITLE
Dublicate mails (404 no route found)

### ISSUE THREAD

**Issue by jd297** [shopware/shopware#371]
**Description**  
Dublicate mails doesn't work because of 404 API route. So the administration loads forever.

**Possible Solution**  
Change API route in the administration.

**Additional context**  
![console](https://user-images.githubusercontent.com/56673596/70791010-76950900-1d96-11ea-91b2-0a172e3fec96.PNG)
![loading](https://user-images.githubusercontent.com/56673596/70791070-9fb59980-1d96-11ea-9dca-aae4a14ae3a4.PNG)

**Comment by keulinho** [comment]
Hey @JD297,

thanks for raising this issue. A fix is underway.

Kind regards
Jonas
