### ISSUE TITLE
Documentation for theme plugins doesn't match code

### ISSUE THREAD

**Issue by pfeiferbit** [shopware/shopware#373]
In the commit for [NEXT-4148](https://github.com/shopware/platform/commit/b81d52b89fb2b83609bf55cbb2e7ee76636a369e) the line [218](https://github.com/shopware/platform/blob/e6ae02b1180afe97160a4893c964e55773cb6a33/src/Storefront/Theme/StorefrontPluginConfiguration/StorefrontPluginConfiguration.php#L218) (before) or [215](https://github.com/shopware/platform/blob/b81d52b89fb2b83609bf55cbb2e7ee76636a369e/src/Storefront/Theme/StorefrontPluginConfiguration/StorefrontPluginConfiguration.php#L215) respectively (after) in StorefrontPluginConfiguration.php changed from:

    $pathname = $bundle->getPath() . DIRECTORY_SEPARATOR . ltrim($bundle->getThemeConfigPath(), DIRECTORY_SEPARATOR);

to:

    $pathname = $bundle->getPath() . DIRECTORY_SEPARATOR . 'Resources/theme.json';

removing the call to `$bundle->getThemeConfigPath()` effectively making it impossible to have the `theme.json` in another location.

If that was intended it would be nice to change the tutorial for how to create theme plugins, i.e. to remove the part that about implementing that method [here](https://docs.shopware.com/en/shopware-platform-dev-en/internals/plugins/plugin-themes?category=shopware-platform-dev-en/internals/plugins#overview):

> If you want to change the location of the `theme.json`, define the method `getThemeConfigPath` in the plugin bootstrap file.

If I try to do that after the commit for NEXT-4148 the console command `bundle:dump` will run into the `InvalidThemeBundleException`.

Greetings.

**Comment by OliverSkroblin** [comment]
Hi @pfeiferbit,

Thanks for the hint. We have updated the documentation accordingly. The current version will be deployed soon.
