### ISSUE TITLE
[Question] How to update an entity (as object) in repository?

### ISSUE THREAD

**Issue by pavog** [shopware/shopware#375]
Hello there,

I just want to know how I can update an entity (which is an object) and save the updated object to a repository? I found [this page](https://docs.shopware.com/en/shopware-platform-dev-en/how-to/updating-entities-dal) in the docs which explains how I can update my entity by using an array with its data, but I have an object (Entity)...

---

My use case is the following:
I work on a plugin which updates products.
I search in the product repository and receive a product entity and edit this.
Now I want to save / update my product entity with its new values.
How can I achieve this without converting / serializing my entity object to an array with its data in a strange way?

---

My code is:
```php
$productCriteria = new Criteria();
$productCriteria->addFilter( new EqualsFilter( 'id', $productId ) );
$productEntityResult = $this->productRepository->search( $productCriteria, $this->context );
$product = $productEntityResult->first();
// Edit $product
// ...
// Save $product to repository
// this: $this->productRepository->upsert( [ (array)$product ], $this->context ); 
// or this: $this->productRepository->update( [ (array)$product ], $this->context ); 
// don't work...
```

Thank you in advance.

**Comment by keulinho** [comment]
Hey @pavog,

it is intended that you can't use the entity object to write back data.
We deliberatly decided to not include a magic change set generation mechanism in our entities. 
Instead please write your changeset directly as an array with the upsert method of the repository.

If you need an updated object representation read the entity again with the repo.

we don't implement a fully fledged ORM and we won't do it, we've built a data abstraction layer specifically tailored for our needs in an e-commerce system. We use the object representation of the entities just in the read-context. For the write side we directly use the chageset as array.

This can be confusing when getting started with shopware 6 and when youre used to working with an fully fledged ORM like Doctrine.

Kind regards
Jonas
