### ISSUE TITLE
Template extension doesn't work as expected

### ISSUE THREAD

**Issue by htuscher** [shopware/shopware#378]
**Description**  
I tried the following:

![image](https://user-images.githubusercontent.com/5076356/70922093-cc331500-2025-11ea-8d49-05d20e7706cb.png)

`FOO` is only displayed if you either:

delete the ` base.html.twig`

OR

add the `base_footer_inner` block to the extended `base.html.twig` that contains the `sw_include`.

**Comment by OliverSkroblin** [comment]
Hi @hhoechtl,

i tested your structure but can not reproduce the wrong behavior. I have the following source structure:

```
my-demo-data
├── composer.json
└── src
    ├── MyDemoData.php
    └── Resources
        └── views
            └── storefront
                ├── base.html.twig
                └── layout
                    └── footer
                        └── footer.html.twig
```


My `base.html.twig` looks as follows:

```
{% sw_extends '@Storefront/storefront/base.html.twig' %}

{% block base_script_hmr_mode %}
    {{ parent() }}
    <script>console.log('test');</script>
{% endblock %}

```

My `footer.html.twig` looks as follows:

```
{% sw_extends '@Storefront/storefront/layout/footer/footer.html.twig' %}

{% block layout_footer_navigation_hotline_content %}
    <h1>Foo</h1>
    {{ parent() }}
{% endblock %}
```

As a result I get in the storefront the `console.log` output and my new headline `Foo`

**Comment by htuscher** [comment]
You accidentally copied the `base.html.twig` twice.

**Comment by OliverSkroblin** [comment]
Sorry, updated ;)

**Comment by htuscher** [comment]
I just tried it again and this time with RC3 it worked after manually clearing the cache (just after creating the template it didn't).

I'm closing this for now and would come back if it occurs again.
