### ISSUE TITLE
Long pathnames prevent windows install

### ISSUE THREAD

**Issue by jurriaanr** [shopware/shopware#379]
**Description**  
While installing on windows, both using the zip file or composer checkout I get errors on too long pathnames. This is because the - presumably - generated file names are long and they are store in very long folder names. 

**Possible Solution**  
Shorter file names :)

**Additional context**  
`error: unable to create file src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-state-change-modal/sw-order-state-change-modal-assign-mail-template/sw-order-state-change-modal-assign-mail-template.html.twig: Filename too long
error: unable to create file src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-state-change-modal/sw-order-state-change-modal-assign-mail-template/sw-order-state-change-modal-assign-mail-template.scss: Filename too long
error: unable to create file src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-state-change-modal/sw-order-state-change-modal-attach-documents/sw-order-state-change-modal-attach-documents.html.twig: Filename too long
error: unable to create file src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-configurator/sw-product-restriction-selection/sw-product-restriction-selection.html.twig: Filename too long
error: unable to create file src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-configurator/sw-product-variants-configurator-prices/sw-product-variants-configurator-prices.html.twig: Filename too long
error: unable to create file src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-configurator/sw-product-variants-configurator-prices/sw-product-variants-configurator-prices.scss: Filename too long
error: unable to create file src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-configurator/sw-product-variants-configurator-restrictions/sw-product-variants-configurator-restrictions.html.twig: Filename too long
error: unable to create file src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-configurator/sw-product-variants-configurator-restrictions/sw-product-variants-configurator-restrictions.scss: Filename too long
error: unable to create file src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-configurator/sw-product-variants-configurator-selection/sw-product-variants-configurator-selection.html.twig: Filename too long
error: unable to create file src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-configurator/sw-product-variants-configurator-selection/sw-product-variants-configurator-selection.scss: Filename too long
error: unable to create file src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-configurator/sw-product-variants-price-field/sw-product-variants-price-field.html.twig: Filename too long
error: unable to create file src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-delivery/sw-product-variants-delivery-media/sw-product-variants-delivery-media.html.twig: Filename too long
error: unable to create file src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-delivery/sw-product-variants-delivery-order/sw-product-variants-delivery-order.html.twig: Filename too long
fatal: Could not reset index file to revision 'a05d93aa4ecfa0880a0ba8fc52c470f2a458f8c6'.`

**Comment by keulinho** [comment]
Hi @jurriaanr,

thanks for reporting this issue. However shopware 6 is not compatible with windows.
As described in the [docs](https://docs.shopware.com/en/shopware-6-en/first-steps/system-requirements) shopware 6 works only on Unix based operating systems.

Kind regards
Jonas
