### ISSUE TITLE
 After clicking "Go to checkout" an error appears

### ISSUE THREAD

**Issue by joanna-gil** [shopware/shopware#381]
**Description**  
When I add some product to cart and want to go to checkout I got error page
![Screenshot from 2019-12-19 15-07-08](https://user-images.githubusercontent.com/57439261/71180000-95513f00-2271-11ea-9985-968f461842cc.png)

**Comment by mitelg** [comment]
hey @joanna-gil 
did you try the current 6.1 branch? this should already be fixed

**Comment by rikterbeek** [comment]
Hi @mitelg,

The 6.1 branch does not work at all see attached screenshot.
![Screen Shot 2019-12-19 at 16 13 40](https://user-images.githubusercontent.com/5948499/71184802-9470db00-227a-11ea-9f0b-d68033bde061.png)


Regards,
Rik

**Comment by mitelg** [comment]
I have no problem on current 6.1 development and current 6.1 platform. Do you use something else?

**Comment by joanna-gil** [comment]
I only work on the master branch, but on 6.1 it looks like it works, thanks :)

**Comment by rikterbeek** [comment]
> I have no problem on current 6.1 development and current 6.1 platform. Do you use something else?

was updating the wrong repo. I updated the development repo to 6.1 instead of the platform repo. Updating platform repo solved the issue.
