### ISSUE TITLE
Sub-categories not working on mobile OffcanvasMenu

### ISSUE THREAD

**Issue by bzannah** [shopware/shopware#387]
**Description**  
I registered for a new shopware 6 demo shop. However, on mobile, if I click on the menu, it shows an empty screen not displaying the sub-categories. Is this the expected behavior?  

**Additional context**  
![alt text](https://i.ibb.co/CBJ4sgX/mobile-menu.jpg "Mobile Menu")

**Comment by OliverSkroblin** [comment]
Hi @bzannah,

this should be fixed by this commit: https://github.com/shopware/platform/commit/1290a76abdc8b748c443d3c982a1fa4f7c0189f7

Could you please verify if you have the latest 6.1 version?

**Comment by bzannah** [comment]
Hi, this is fixed in 6.1. Thanks.
