### ISSUE TITLE
Administration and Storefront build scripts are broken when using node 13

### ISSUE THREAD

**Issue by simkli** [shopware/shopware#393]
Node-sass 4.12 is not compatible with nodejs 13. Inside the storefront's and administration's package.json file, node-sass should be updated to v4.13.0. 

https://github.com/sass/node-sass/releases/tag/v4.13.0

Everything worked for me after changing this.

**Comment by mitelg** [comment]
hey @simkli 
would be nice, if you could create a PR for that :wink:

**Comment by simkli** [comment]
Done https://github.com/shopware/platform/pull/394

**Comment by tobiasberge** [comment]
Hi,

thanks for your PR @simkli. Because it has been merged I will close this issue.
https://github.com/shopware/platform/pull/394

Best regards
Tobias
