### ISSUE TITLE
external file storage

### ISSUE THREAD

**Issue by mibuntu** [shopware/shopware#398]
**Description**  
external file storage for media files

**Example**  
consider https://docs.shopware.com/en/shopware-platform-dev-en/how-to/use-s3-datastorage : 
which setup is needed for remote sftp like it is possible with this: https://github.com/shopwareLabs/SwagMediaSFTP ?

**Comment by pantrtxp** [comment]
Hi @mibuntu, 

please consider our [Forum](forum.shopware.com) for help or, if you have a support subscription, create a support Ticket. 

Sunny regards
Pantrtxp
