### ISSUE TITLE
sw-entity-many-to-many-select removing options duplicate request

### ISSUE THREAD

**Issue by hendrikleyendeckers** [shopware/shopware#402]
**Description**  
If the product module is extended with a new `<sw-entity-many-to-many-select>` field, an error occurs when an option gets removed from the select and the you want to save the product. 

There seems to be an extra delete request, when an option is deselected. If the products gets saved now, an error occurs that the deselcted resource is not found.
```
{
    status: "404"
    code: "FRAMEWORK__RESOURCE_NOT_FOUND"
    title: "Not Found"
    detail: "The example_name resource with the following primary key was not found: productId(0084b26b95854cd7b84432fc682a78a4) exampleId(af9ed0ced8b644068a5c80f1de5708f7) productVersionId(0fa91ce3e96a4bc2be4bd9ce752c3425)"
}
```

The problem also occurs in the example-bundle (https://github.com/shopware/swag-docs-bundle-example) of the documentation.

**Possible Solution**  

**Additional context**  

![grafik](https://user-images.githubusercontent.com/4322098/71960854-54a47000-31f6-11ea-843a-62b47b426519.png)
![grafik](https://user-images.githubusercontent.com/4322098/71960587-af899780-31f5-11ea-8261-ea4641c49b16.png)
![grafik](https://user-images.githubusercontent.com/4322098/71960694-ee1f5200-31f5-11ea-8a20-d2b291e69886.png)
![grafik](https://user-images.githubusercontent.com/4322098/71960712-f4adc980-31f5-11ea-8608-697db4745403.png)

First Request is sent when an option is deselected. The second one is sent, when you save the product and fails with the error above.

**Comment by OliverSkroblin** [comment]
Hi @hendrikleyendeckers,

the `many-to-many-selection` has a property named `localMode`. This property handles the behaviour which depends how the data of the association was loaded.

First possible usage:
The data is loaded within the parent resource (in this case the product). In this case the association is handled by the parent resource and the `localMode` should be set to `true`.

Second possible usage:
The data isn't loaded within the parent resource, which means the `many-to-many-select` handles the crud operations itself. In this case you have to set the `localMode` to `false`.

**Comment by hendrikley** [comment]
Thanks very much for the explanation @OliverSkroblin !
I've had adapted the localMode of the example-bundle (`:localMode="product.isNew()"`), but setting it to true fixes the error. :-)

**Comment by hendrikleyendeckers** [comment]
Thanks very much for the explanation @OliverSkroblin !
I've had adapted the localMode of the example-bundle (:localMode="product.isNew()"), but setting it to true fixes the error. :-)
