### ISSUE TITLE
CORE: Swagger code generation not work

### ISSUE THREAD

**Issue by approached** [shopware/shopware#407]
**Description** 
I'm trying to create a API SDK for shopware 6. With follow command:
```
swagger-codegen generate -i openapi3.json -l php --git-user-id industryarena --git-repo-id shopware6-sdk --invoker-package Shopware6SDK
```

But it creates a unsupported php code with two same methods:
https://github.com/industryarena/shopware6-sdk/blob/master/lib/Api/ProductApi.php#L101
https://github.com/industryarena/shopware6-sdk/blob/master/lib/Api/ProductApi.php#L361

The Docs has also two methods: https://github.com/industryarena/shopware6-sdk/blob/master/docs/Api/ProductApi.md#createproduct

Two same methods in one class are not allowed in PHP!
Has anybody a idea how i can generate a correct SDK?

**Additional context**  
Playground: https://github.com/industryarena/shopware6-sdk

**Comment by pweyck** [comment]
Hello @approached,

thanks for reporting this. We found more issues with our openapi3 schema while trying to reproduce this issue. 

I've created an issue in our issue tracker: 

https://issues.shopware.com/issues/NEXT-6314

**Comment by jalieb** [comment]
Hi @pweyck ,

I still receive an error when validating the schema:

`openapi-generator validate -i openapi3.json`

leads to

`-attribute components.schemas.relationshipLinks.items is missing`

**Comment by marcbln** [comment]
the problem with duplicate generated methods still exists with shopware 6.1.4. and swagger-codegen 3.0.18.  The ticket NEXT-6314 did NOT resolve the issue.

to reproduce:

`./run-in-docker.sh generate -l php -i /gen/openapi3.json -o /gen/sw6api`

creates the classes .. example for duplicate method in class CategoryApi:

```php
    /**
     * Operation createCategory
     *
     * Create a new Category resources
     *
     * @param  \Swagger\Client\Model\Body4 $body body (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\InlineResponse2009
     */
    public function createCategory($body = null, $_response = null)
    {
        list($response) = $this->createCategoryWithHttpInfo($body, $_response);
        return $response;
    }
```

and


```php
    /**
     * Operation createCategory
     *
     * Create a new Category resources
     *
     * @param  \Swagger\Client\Model\CategoryFlat $body body (optional)
     * @param  string $_response Data format for response. Empty if none is provided. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\InlineResponse2009
     */
    public function createCategory($body = null, $_response = null)
    {
        list($response) = $this->createCategoryWithHttpInfo($body, $_response);
        return $response;
    }
```

**Comment by brstgt** [comment]
I dont see why this issue or the shopware issue is closed. It does not seem to be fixed.

**Comment by TaiKamilla** [comment]
> `openapi-generator validate -i openapi3.json`
@jalieb did you find the solution for that?

**Comment by sydetion** [comment]
Please check, seems this issue came back in 6.4.0.0 and leads to https://issues.shopware.com/issues/NEXT-15412
