### ISSUE TITLE
Paypal Checkout - Error payWithDebitOrCreditCard

### ISSUE THREAD

**Issue by cfreak** [shopware/shopware#414]
**Description**  
TypeError: Cannot read property 'payWithDebitOrCreditCard' of undefined

This happens when changing the Payment to Paypal in RC-4 it was working in RC-2

**Additional context**  
<img width="1595" alt="Bildschirmfoto 2020-01-09 um 19 20 16" src="https://user-images.githubusercontent.com/202342/72093692-31bcad80-3315-11ea-8354-24624344ed67.png">
The selected Payment is not showing and there are JS-Errors

**Comment by mitelg** [comment]
hey @cfreak 
could you please create a ticket here? https://issues.shopware.com/?projects=PT&plugin=PayPal 

this is only for the Shopware core 😉
