### ISSUE TITLE
rm -Rf var/cache fails during initial install

### ISSUE THREAD

**Issue by DavidLambauer** [shopware/shopware#42]
Hi,

I followed the instruction within the readme and ended up with the following error on step 21:

``` 
(21/28) Starting
> rm -rf var/cache
	rm: cannot remove 'var/cache/dev_59202da9aa4f43de6b3a45a9585ca53b44378c3f/pools': Directory not empty

Execution aborted, a subcommand failed!
```

any ideas?

**Comment by DavidLambauer** [comment]
seems that there is no var/cache at the time of the command.

**Comment by keulinho** [comment]
Most of the time this issue arises if a different process writes into the cache directory when the psh command tries to delete the directory.
Retrying should help. 
Let us know if you have any further questions!
