### ISSUE TITLE
Different flows for data loading in admin entity listing

### ISSUE THREAD

**Issue by JoshuaBehrens** [shopware/shopware#420]
**Description**  
Any entity listing in the admin like the customer listing or manufacturer listing has different ways to load data. This results in different problems. E.g. you have a customer listing that is empty. Using the demo-data command to fill up demo customers and then click on a column header to trigger a re-sorting. The sorting triggers a search. The search results in an now filled list and an `update-records` event. Without a listener on the `update-records` event to update the total state in the customer-list you get a filled listing but still have the displayed empty state as they depend on the count `<sw-empty-state v-if="!isLoading && !total" :title="$tc('sw-customer.list.messageEmpty')"></sw-empty-state>`
![grafik](https://user-images.githubusercontent.com/1133593/72222064-0928f380-3561-11ea-8479-8f6c1e17c64c.png)
Every entity listing suffers from this as the sorting change triggers the `doSearch` method (as other events do as well). This uses the the assigned repository and the already existing criteria and context on the assigned items. This means the wrapping `sw-customer-list` needs to assign the first resultset to the `sw-entity-listing` and then never has to change anything anymore to work. Instead `sw-customer-list` uses the initialization method `getList`, that one is forced to use by the listing-mixin, multiple times to re-initialize the entity listing. As a third party dev you will look at it and think that `getList` ist the way to assign data. So one is fooled into being able to change the API resultset by adding calculated data to the entities. The *hidden* `doSearch` does not trigger `getList` and therefore the manually added calculated data is missing on e.g. sorting. As well the API search is the only data you can display. There is no simple way to alter the search API resultset.

**Possible Solution**  
My personal conclusion is: there is just a single way to implement `getList`:
```
getList() {
    this.isLoading = true;
    this.repository.search(this.criteria, Shopware.Context.api).then(items => {
        this.total = items.total;
        this.items = items;
        this.isLoading = false;

        return items;
    }).catch(() => {
        this.isLoading = false;
    });
}
```
This means you only have to supply a default critera and a repository. Calculating the changes that are done from the UI should be part of the criteria computation as that one can change. Maybe a change for the listing mixin.

There are multiple ways to change the data from the search call:
1. One can use a service decorator or custom api service implementation for the repository
2. One can add runtime calculated fields to the entity definition
3. One can add columns in the listing and override their display template and use modifiers or custom components that display different values in that column

The `update-records` event is not suitable to change the items as it is triggered on an item change.

**Comment by JoshuaBehrens** [comment]
Which way to go? Adding utility to make it easier to build the methods like `getList` or make `doSearch` less hiddenly used and give control over it in the listing-mixing? I know that this is a result of the mixture of different components in either class-hierarchical, DOM-hierarchical and mixin usage. But this results in a super strange way to handle listings.

**Comment by jleifeld** [comment]
Hey Joshua,

thanks for your great ideas. We also think there is optimization potential in the admin entity listing.

We think it will be a good idea to implement the listing logic more inside the `entity-listing` component so that the initial `getList` call is not needed anymore. You control the listing from the outside with different properties and the listing updates reactively to the changes.

I will create a ticket for this and we will evaluate which solution will be the best.

**Comment by jleifeld** [comment]
https://issues.shopware.com/issues/NEXT-6406

This is the link to our Issuetracker. You can get the latest status about this issue in the link.

Thanks for your contribution! :)

**Comment by JoshuaBehrens** [comment]
Thanks for listening 👍 Still waiting for the notification feature in your issue tracker :(

**Comment by JoshuaBehrens** [comment]
I am experiencing that sub-components which are not pages are working really good with
```javascript
Component.register('component-list', {
    template: `
<sw-entity-listing
    v-if="items"
    :items="items"
    :repository="repository"
    :showSelection="false"
    :showSettings="true"
    :columns="columns"
    :isLoading="!isLoading"
    :showActions="false"
>
    <template #column-createdAt="{ item }">
        {{ item.createdAt | date({ hour: '2-digit', minute: '2-digit' }) }}
    </template>

    <template #pagination>
        <sw-pagination
            :page="page"
            :limit="limit"
            :total="total"
            :total-visible="7"
            @page-change="onPageChange">
        </sw-pagination>
    </template>
</sw-entity-listing>
    `,
    mixins: [
        Mixin.getByName('listing')
    ],

    data() {
        return {
            items: null,
            total: 0,
            isLoading: true,
            disableRouteParams: true
        };
    }
});
```
Are there any flaws in there by chance or can that be part of the docs later? ;)
