### ISSUE TITLE
theme.json inheritance

### ISSUE THREAD

**Issue by htuscher** [shopware/shopware#428]
**Description**  
If you want to modify a field in your `theme.json` which inherits from the `Storefront`, you must specify the entire field. Other properties aren't merged as you would expect.

```json
        "fields": {
            "sw-logo-desktop": {
                "value": "bundles/mytheme/asset/logo/logo.svg"
            }
        }
```

Breaks your theme compilation.

**Possible Solution**  
The `theme.json` should be deeply merged with the base `theme.json` of the storefront.

**Additional context**

**Comment by ssltg** [comment]
Hi @hhoechtl ,

thank you for bringing this up. We found the problem and will fix it soon. This Issue will be closed when the fix is merged.
