### ISSUE TITLE
Optionaly setting to switch from localhost to fqdn

### ISSUE THREAD

**Issue by RogerSik** [shopware/shopware#43]
It is possible to use a fqdn with port 80 instead of localhost:8080?

**Comment by seggewiss** [comment]
I assume we are talking about our docker setup here?

**Comment by RogerSik** [comment]
Yes

**Comment by keulinho** [comment]
It is possible to change the app url in a `psh.yaml.override` file.
But as you speak about port 8080 i guess you want to start the the HotModuleReplacement server, that you start with the `psh administration:watch` command, with a fqdn right?

**Comment by janbuecker** [comment]
The development container is not designed to be used in production. We've provide a production-ready container later this year, which will run on port 80/443. To use port 80 in development, you have to do custom changes in the `Dockerfile` and use it in `docker-compose.yml`.
