### ISSUE TITLE
"document.lineItems.header.productNumber" instead of proper text shown in documents

### ISSUE THREAD

**Issue by schneehaze** [shopware/shopware#431]
**Description**  
The text "document.lineItems.header.productNumber" is shown in invoices and other documents.
This should be a proper Table Header Text.
https://issues.shopware.com/issues/NEXT-6184

`<th>{{ 'document.lineItems.header.productNumber'|trans|sw_sanitize  }}</th>`
in
platform/src/Core/Framework/Resources/views/documents/base.html.twig

**Possible Solution**  
Add german text to the initial installation for document.lineItems.header.productNumber

**Additional context**  
<img width="349" alt="Screenshot 2020-01-13 at 16 52 15" src="https://user-images.githubusercontent.com/25282177/72270211-19a2a200-3625-11ea-8fd5-3c7b119dda8a.png">

**Comment by schneehaze** [comment]
Solution: Add german text to the initial installation for document.lineItems.header.productNumber

<img width="889" alt="Screenshot 2020-01-13 at 17 11 55" src="https://user-images.githubusercontent.com/25282177/72271830-e7467400-3627-11ea-838f-e262a67f4af6.png">

**Comment by pantrtxp** [comment]
HI @schneehaze,

This issue will be fixed with the 6.1.1 patch release in the near future

Sunny regards
Pantrtxp
