### ISSUE TITLE
I am unable to call the API with a language as a parameter

### ISSUE THREAD

**Issue by FlushBG** [shopware/shopware#433]
**Description**  
 I am using a Headless channel with a custom multilingual frontend, written in Nuxt.js. I am not able to find any information on how to call the Shopware Admin API with a language parameter, so I get the content I need in the language that the user picks (products, categories, etc.). 
 I was experimenting with Postman and found that the product has a translations property (an object), which always returned the default english translation, no matter what I tried as params.

**Possible Solution**  
In case this is a feature, please include it in the docs. Otherwise, please advice me how can I get my products, etc. inside the frontend.

**Comment by mitelg** [comment]
hey @FlushBG 
the Admin API is, as the name suggest, for creating, updating, deleting, etc the entities. you should not use it, to get the products for the storefront. 
For this purpose we have the saleschannel API: https://docs.shopware.com/en/shopware-platform-dev-en/api/sales-channel-api?category=shopware-platform-dev-en/api
there are also more articles for further reading, e.g. changing the context, which includes the language

**Comment by FlushBG** [comment]
hi @mitelg, thanks for the response!
The docs describe only GET methods, regarding the context endpoint. Now that you mentioned it, I assume you can somehow set the language with a POST request, but will that affect only the one user that initiates it? Does it work by sending a cookie or? Please add this to the docs.

**Comment by mitelg** [comment]
use this route for an update https://github.com/shopware/platform/blob/6.1/src/Core/System/SalesChannel/SalesChannel/SalesChannelContextController.php#L31
this should be the key for changing the language https://github.com/shopware/platform/blob/6.1/src/Core/System/SalesChannel/Context/SalesChannelContextService.php#L13

**Comment by mitelg** [comment]
I created a ticket for the missing docs https://issues.shopware.com/issues/NEXT-6408

**Comment by FlushBG** [comment]
Thanks for your support! I will close the issue.
