### ISSUE TITLE
If customer try to review on variant product then product name is not visible under the review grid in the admin end.

### ISSUE THREAD

**Issue by deepakk-webkul** [shopware/shopware#436]
Preconditions (*)

Shopware 6.1.0 with demo data installed
PHP 7.2.22
Production Mode

**If customer try to review on variant product then product name is not visible under the review grid in the admin end.**

![Screenshot](https://user-images.githubusercontent.com/50043226/72412017-517b2800-3792-11ea-926f-d8625cf8beb6.png)

![Screenshot (1)](https://user-images.githubusercontent.com/50043226/72412026-55a74580-3792-11ea-87bd-e2a1b342077c.png)

![Screenshot (2)](https://user-images.githubusercontent.com/50043226/72412032-58a23600-3792-11ea-98e7-6f1a7a38079b.png)

**Comment by mitelg** [comment]
hey @deepakk-webkul 

could you check if it works with the https://github.com/shopware/platform/commits/ntr/6.1.1-integration branch?
it seems to be fixed already with this commit: https://github.com/shopware/platform/commit/8544a592533b24b1e2bf146414e4d8a2f403fb0a

**Comment by deepakk-webkul** [comment]
This issue has been fixed in shopware version 6.1.1
