### ISSUE TITLE
extend package.json file

### ISSUE THREAD

**Issue by arkadiuszprzybylski92** [shopware/shopware#438]
Is it possible to add package.json to the custom plugin and install packages in this module using native storefront commands? I know i can extend webpack config, but i need new node packages.

**Comment by klarstil** [comment]
Hey @arkadiuszprzybylski92,

thanks for opening this issue. I'll check if this is possible and give you a information about it. Please give me some time.

Best regards

**Comment by shyim** [comment]
https://www.shopware.com/en/news/installing-your-own-dependencies-via-npm/
