### ISSUE TITLE
demo admin credentials

### ISSUE THREAD

**Issue by NiklasTeich** [shopware/shopware#44]
You should (in a more obvious way) communicate the demo login credentials (User: admin, password: shopware) I only found one place with these informations: [https://docs.shopware.com/en/shopware-platform-dev-en/getting-started/system-installation-guides/mac-os-x](https://docs.shopware.com/en/shopware-platform-dev-en/getting-started/system-installation-guides/mac-os-x)

**Comment by JanPietrzyk** [comment]
They are currently part of the startup guide, but you are right this is not an obvious location.... And the keyword *credentials** is missing.

https://docs.shopware.com/en/shopware-platform-dev-en/getting-started/startup-guide

I would add this information also to this page: https://docs.shopware.com/en/shopware-platform-dev-en/internals/administration

Any suggestions? Where would you have expected it?

**Comment by NiklasTeich** [comment]
Sounds good to me! (adding it on the administration dev. page). And to be really honest: Is there anything against adding the credentials in the "Quickstart / Installation" guide? The Storefront is linked (localhost:8000), the /admin endpoint with the required credentials would also fit, i think :) With that addition, everyone would really have everything needed to start exploring the new system :)

**Comment by JanPietrzyk** [comment]
The *QuickStart* is supposed to be guide that I linked... Yeah, the Storefront needs to be added too - wasn't available when this was written

**Comment by keulinho** [comment]
The credentials are now available in the [Sartup Guide.](https://docs.shopware.com/en/shopware-platform-dev-en/getting-started/startup-guide#default-login-credentials)
