### ISSUE TITLE
JSON file response on IE11 form submit

### ISSUE THREAD

**Issue by jd297** [shopware/shopware#448]
**Description**
If you submit a formular with IE11 you will receive a json file to download instead of the rendered JSON response.

**Additional context**  
![jsonfile](https://user-images.githubusercontent.com/56673596/72717611-a6dd7d80-3b74-11ea-87bb-5f42ef4ed4d0.PNG)

Shopware 6.1 with IE11 on Win10

**Comment by mnaczenski** [comment]
We already have IE 11 compatibility as an epic in our issuetracker: https://issues.shopware.com/issues/NEXT-5992

But honestly it's mostly planned for the next quarter starting april.
