### ISSUE TITLE
npm clean-install: Unable to save binary

### ISSUE THREAD

**Issue by dominikbraun** [shopware/shopware#45]
This issue concerns the installation step 22/28.

When `npm clean-install` is performed, the execution results in an error since the process doesn't have the required permissions for `/app/platform/src/Administration/Resources/administration/node_modules/node-sass/vendor`.

![shopware-installation-npm-error](https://user-images.githubusercontent.com/36575275/58286803-d94d9580-7daf-11e9-9c09-8b59ff2c94d2.png)

I attempted to create the directory manually, but running it again will still result in that error.

Any ideas?

**Comment by keulinho** [comment]
Are you using a local setup or do you use docker?
What permissions are set on the node_modules folder? And are there any other node modules already installed when it crashes? 
You definitley need write permissions to the node_modules folder, do you use a different user for running the install command that doesn't has the write permissions?

**Comment by dominikbraun** [comment]
Some more precise information:

1) I'm running the installation with Docker
2) The `node_modules` directory has the permissions `rwx/r-x/r-x` and is owned by root
3) There are modules in the folder, but I'm not sure if they were created during the install
4) I'm running `./psh.phar install` as root in the container (after accessing it with `./psh.phar docker:ssh`)
5) I started the Docker daemon via `sudo dockerd`

**Comment by pweyck** [comment]
`node_modules` should not be owned by root. Did you run `./psh.phar docker:ssh` as root?

To fix the permissions for your current user, run this with your development directory:
`sudo find $DEVELOPMENT_DIR -not -user "$(id -u)" -and -not -user 999 -exec chown "$(id -u):$(id -g)" {} \;`

This command changes the ownership of all files and directories that are not owned by your current user (`id -u`) or 999 (uid of the mysql user in the container) to your current user.

**Comment by dominikbraun** [comment]
> Did you run ./psh.phar docker:ssh as root?

Yes. The reason is that otherwise (logged in as `application`), I don't have permissions to some composer directories:

```
[ErrorException] copy(./composer/cache/files/composer/xdebug-handler/...): failed to open stream: Permission denied
```

However, it seems that running `./psh.phar docker:ssh` without `sudo` is the way to go...

**Comment by pweyck** [comment]
It seems like your `~/.composer` and maybe your `~/.npm` directory is owned by root. `./psh.phar docker:start` should check that and fail if that's not the case.

**Comment by dominikbraun** [comment]
The error is fixed now.

**Don't run _any_ `./psh.phar` scripts using `sudo`. Otherwise the permissions for `node_modules` are invalid.**

**All scripts _must_ work without sudo. If  `docker:start` does not work without `sudo`, make sure your user is in the system's `docker` group.**
