### ISSUE TITLE
Support all S3Client options

### ISSUE THREAD

**Issue by tiwac100** [shopware/shopware#464]
**Description**  
Currently only the `'credentials', 'version', 'root', 'options'` options are supported when configuring S3 as media filesystem. Please support all available options in `AwsS3v3Factory` because it is currently impossible to use other S3 compatible services like [MinIO](https://github.com/minio/minio).

**Comment by hlohaus** [comment]
try https://github.com/shopware/platform/pull/460

**Comment by OliverSkroblin** [comment]
Hey @timwachsener,

i updated the adapter options in the master branch: https://github.com/shopware/platform/commit/6f10ea0d01650bf36299818d0b61c44cd17c86d8
