### ISSUE TITLE
npm clean-install: Execution aborted, a subcommand failed!

### ISSUE THREAD

**Issue by NiklasTeich** [shopware/shopware#47]
- MAMP PRO 5.3
- OSX 10.11.6
- PHP 7.2.14
- node v10.15.1
- Xcode 8.2.1

I followed these install instructions: [https://docs.shopware.com/en/shopware-platform-dev-en/getting-started/system-installation-guides/mac-os-x](https://docs.shopware.com/en/shopware-platform-dev-en/getting-started/system-installation-guides/mac-os-x). An installation (guided by the quick install guide) worked for me (docker installation)

![terminal](https://i.imgur.com/SVxmG24.png)

**Comment by keulinho** [comment]
The clean-install command is available since NPM v.6.5 as described [here](https://docs.shopware.com/en/shopware-platform-dev-en/getting-started/requirements).
Probably you need to update your npm version.
So what NPM version are you using?

**Comment by dominikbraun** [comment]
I ran into the same error. A quick update of npm to the newest version did the trick for me.

**Comment by keulinho** [comment]
Thanks for verifying, we'll update the installation guide accordingly.

**Comment by NiklasTeich** [comment]
NPM v6.5 fixed this error for me, thank you!

**Comment by klarstil** [comment]
We'll have to bump the required npm version in our `package.json`, thanks for pointing it out
