### ISSUE TITLE
Language integrity

### ISSUE THREAD

**Issue by htuscher** [shopware/shopware#470]
**Description**  

**Case 1**
If you update Shopware and a migration is running, e.g. `Migration1575021466AddCurrencies` it's necessary that you have languages for the locales `de-DE` and `en-GB`. 
Of course that's not necessarily the case, we have neither german nor english in the shop configured.

Not sure what would happen with other migrations if they try to add translations for unused languages, but I assume that would also break.

```
In MigrationCommand.php line 105:

  Migration error: An exception occurred while executing 'INSERT INTO currency_translation (currency_id, language_id, short_name, name, created_at) VALUES (?, ?, ?, ?, ?)' with p
  arams ["\x07\x29\x0a\x6d\xbb\x55\x42\x0a\x87\x33\x30\x54\x6a\xd2\x83\x52", false, "NOK", "Norwegische Kronen", "2020-01-27 09:44:21.000"]:

  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`dev_at`.`currency_translation`, CONSTRAINT `
  fk.currency_translation.language_id` FOREIGN KEY (`language_id`) REFERENCES `language` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
```

This is because this migration selects the `id` for a language for the locale `de-DE` which doesn't exist and is therefore `null`. That fails the foreign key constraint.

**Case 2**

Also when using `theme:refresh` it assumes that the languages for the translations of the themes are present. The `upsert` action on the `theme` entity requires the specified languages to be present.

**Case 3**

Having a system language `fr-FR` causes the `plugin:refresh` command to do this:

```
11:50:06 ERROR     [console] Error thrown while running command "plugin:refresh". Message: "There are 1 error(s) while writing data.\n\n1. [/4/translations/2fbb5fe2e29a4d70aa5854ce7ce3e20b] Translation required for system language 2fbb5fe2e29a4d70aa5854ce7ce3e20b" ["exception" => Shopware\Core\Framework\DataAbstractionLayer\Write\WriteException^ { …},"command" => "plugin:refresh","message" => """  There are 1 error(s) while writing data.\n  \n  1. [/4/translations/2fbb5fe2e29a4d70aa5854ce7ce3e20b] Translation required for system language 2fbb5fe2e29a4d70aa5854ce7ce3e20b  """]
[2020-01-27 11:50:06] console.ERROR: Error thrown while running command "plugin:refresh". Message: "There are 1 error(s) while writing data.  1. [/4/translations/2fbb5fe2e29a4d70aa5854ce7ce3e20b] Translation required for system language 2fbb5fe2e29a4d70aa5854ce7ce3e20b" {"exception":"[object] (Shopware\\Core\\Framework\\DataAbstractionLayer\\Write\\WriteException(code: 0): There are 1 error(s) while writing data.\n\n1. [/4/translations/2fbb5fe2e29a4d70aa5854ce7ce3e20b] Translation required for system language 2fbb5fe2e29a4d70aa5854ce7ce3e20b at /app/vendor/shopware/platform/src/Core/Framework/DataAbstractionLayer/Write/WriteContext.php:41)","command":"plugin:refresh","message":"There are 1 error(s) while writing data.\n\n1. [/4/translations/2fbb5fe2e29a4d70aa5854ce7ce3e20b] Translation required for system language 2fbb5fe2e29a4d70aa5854ce7ce3e20b"} []

In WriteContext.php line 41:

  There are 1 error(s) while writing data.

  1. [/4/translations/2fbb5fe2e29a4d70aa5854ce7ce3e20b] Translation required for system language 2fbb5fe2e29a4d70aa5854ce7ce3e20b
```

The `TranslationsAssociationFieldSerializer` requires the insertion of an entity to contain a translation for the system default language. In this case that would be `fr-FR` but almost no theme or plugin contains translations for `fr-FR`. Therefore you can't use them.

**Case 4**

If a user modified the language `2fbb5fe2e29a4d70aa5854ce7ce3e20b` to another locale (which is possible in the administration). All plugins need to have translations for this new locale. The UUID is hardcoded in the administration `core/shopware.js`.

**Possible Solution**  
Don't assume languages or locales when dealing with translations.

**Additional context**

**Comment by ssltg** [comment]
Thank you for your contribution.
You are right, the Migration shouldn't force to update something with a language that maybe is not available. We will fix this and other Migrations which rely on the german and english locale to exist.

On the other Hand it is possible, but not recommended to delete the german and/or english languages from the System, because all our updates and most Plugins will rely on at least an english locale. It is ok to switch the system language to another Locale, but if you do this, you should readd the english locale to stay update and plugin ready.

Anyway, we will discuss a solution for switched system languages and plugins.

**Comment by ssltg** [comment]
We have created a Ticket for the igration Issue https://issues.shopware.com/issues/NEXT-6509

**Comment by shyim** [comment]
This has been fixed meanwhile
