### ISSUE TITLE
Composer setup

### ISSUE THREAD

**Issue by lyssar** [shopware/shopware#472]
I would like a fully installation via composer, which should be kind of a standard in order to be able to automate rollouts like 90% of other projects.
Is this feature planned and if yes when will it be available?

Actually this is a showstopper for not just me to use Shopware for upcoming projects (to much devops pain)

Kind regards

**Comment by bcremer** [comment]
The default installation method of Shopware 6 is via composer dependency.
There are two template-repositories that contain the glue code to get things started:
https://github.com/shopware/development
https://github.com/shopware/production

For the older Shopware 5 have a look into the following repo: https://github.com/shopware/composer-project

**Comment by lyssar** [comment]
Mhhh FYI the development github just links the official docs. I couldn't find the composer setup over there but the production github actually explains it.
I will try that :)

**Comment by lyssar** [comment]
Oh and thanks for the info ;D

**Comment by pweyck** [comment]
Installing via composer should work. You can reopen this issue, if it didn't work out.
