### ISSUE TITLE
German translation "Durchsuche" or "Suche"

### ISSUE THREAD

**Issue by tinect** [shopware/shopware#478]
**Description**  
"Search [thing]"
Ist mal mit "Suche nach [thing]" übersetzt, mal mit "Durchsuche [thing]".
Vielleicht könnte sich für eins entschieden werden.

**Possible Solution**  

**Additional context**

**Comment by GitEvil** [comment]
Hi, tinect! 
Da bin ich völlig bei dir, Einheitlichkeit sollte ein primäres Ziel sein. Und das ist auch, was ich mir im Arbeitsalltag gerne auf die Fahnen schreibe. Allerdings ist es im iterativen Softwaredevelopment auch ein bisschen ein Kampf gegen Windmühlen, es sind halt viele Köche beteiligt und nicht alle sind so Grammar-Nazis wie ich. xD Deshalb finde ich es super, hier Unterstützung zu bekommen. :) Ich werde mal versuchen im Laufe der Woche zusammenzutragen, welche Konventionen wir eigentlich in Sachen Naming schon so haben und dir das zukommen lassen. Bis dahin, keep up the good work!

**Comment by shyim** [comment]
Pinged it internally again and will close it for now
