### ISSUE TITLE
CustomerMetaFieldSubscriber crashes if the customer of an order does not exist

### ISSUE THREAD

**Issue by windaishi** [shopware/shopware#488]
**Description**  

If an order is created without customer, you will get the error `Error: Call to a member function getCustomerId() on null`.

**Possible Solution**  

Fix this line of code: 
https://github.com/shopware/platform/blob/0394e280b26d9daee52206b8f99f2ba50407fb0b/src/Core/Checkout/Customer/Subscriber/CustomerMetaFieldSubscriber.php#L73-L77
e.g. by replacing it with this:
```php
             $customer = $order->getOrderCustomer(); 
             // happens if the customer was deleted 
             if (!$customer) { 
                 continue; 
             }
             $customerId = $customer->getId();
```

**Comment by ssltg** [comment]
The Order Customer should instead be a required field We pened a Ticket for this Issue.
https://issues.shopware.com/issues/NEXT-7190
