### ISSUE TITLE
Script with name install not found - Following install instructions

### ISSUE THREAD

**Issue by FrazeColder** [shopware/shopware#493]
I want to install the developer version of Shopware 6 on my Mac using MAMP. I do follow the install instructions you can find in the offical Shopware 6 documentation - [here](https://docs.shopware.com/en/shopware-platform-dev-en/getting-started/system-installation-guides/mac-os-x?category=shopware-platform-dev-en/getting-started/system-installation-guides).

However, I get this error on the last step: `Script with name install not found`.

I have already doubled checked every step in the documentation. When I run `bin/setup` I get this error message after entering my MySQL password and pressing enter. I also get this error when running `./psh.phar install`.

I cannot find any people who have the same issue and cannot find any help on Google. Does anyone know how to fix this?

Thanks!

**Comment by shyim** [comment]
Still an issue?
