### ISSUE TITLE
Hello i want to set contact form in detail page and want to send data with email how is it posible....

### ISSUE THREAD

**Issue by thsekeer** [shopware/shopware#496]
**Description**  

**Possible Solution**  

**Additional context**

**Comment by OliverSkroblin** [comment]
Hi @thsekeer,

The github issues in this repository are intended for issues of technical problems within the shopware core. If you need help implementing your plugins or a customer project, please contact our support or write a thread in our forum: 

https://forum.shopware.com/

Greetings Oliver
