### ISSUE TITLE
Invalid json in sw-plugin snippets

### ISSUE THREAD

**Issue by sbossert** [shopware/shopware#497]
**Description**  
In the de-DE.json and en-GB.json in the master branch there is invalid JSON due to superfluous commas at the end of object / list, due to this plugin texts are not set within the administration interface.

```
  "sw-plugin-config": {
    "buttonSave": "Speichern",
    "buttonCancel": "Abbrechen",
    "titleSaveSuccess": "Konfiguration gespeichert",
    "messageSaveSuccess": "Die Konfiguration wurde erfolgreich gespeichert.",
    "titleSaveError": "Fehler beim Speichern der Konfiguration", <---
  },
```
**Possible Solution**  
Remove comma, probably generated somewhere.

**Additional context**  
Issue is only present in master branch.

**Comment by mitelg** [comment]
hey @sbossert 
thanks for bringing up this issue.

As this is already fixed in our current dev branch "6.1" this will be fixed as soon as the 6.1 branch is merged back into the master. which should happen on a regularly base.
