### ISSUE TITLE
sw-context-menu floats out of the window

### ISSUE THREAD

**Issue by Sheek44** [shopware/shopware#503]
When having a large category tree and you want to add a subcategory the sw-context-menu opens directly unter the cursor, even though there isn't enough free space. 

![sw-context-menu-flaot](https://user-images.githubusercontent.com/56643149/73754830-4d28a600-4765-11ea-904d-f4935d1ff7b4.jpg)

**Comment by Haberkamp** [comment]
Hey @MortisReturns,

could you please tell me wich version you're using. Because i cannot reproduce this problem.

Kind regards

Nils

**Comment by Sheek44** [comment]
i'm using v6.1.0 Stable Version right now

**Comment by Haberkamp** [comment]
Sorry, I could not reproduce this problem. And it seems that this is already fixed on the `6.1` branch.

Thank you for creating this issue. If this behaviour is still present in a future version feel free to create another issue.
