### ISSUE TITLE
Problem rendering extended twig template in a controller

### ISSUE THREAD

**Issue by merlin-it** [shopware/shopware#505]
**Description**  

I have a problem extending the cart widget template, but it is very likely the same behaviour for other templates which are loaded the same way:

For customisazion of the cart widget I created the following file:
`/custom/plugins/MyPlugin/src/Resources/views/storefront/layout/header/actions/cart-widget.html.twig`

When the main template is rendered everything is working fine and my customized template gets loaded. This is done using sw_include in 
`/vendor/shopware/platform/src/Storefront/Resources/views/storefront/layout/header/header.html.twig` 

`{% sw_include '@Storefront/storefront/layout/header/actions/cart-widget.html.twig' %}`

But when the page is rendered the widget is loaded again using an ajax call to this controller:
`Shopware\Storefront\Controller\CheckoutController::info()`

Which returns only the rendered widget, adressing the template name with exactly the same syntax:
`return $this->renderStorefront('@Storefront/storefront/layout/header/actions/cart-widget.html.twig', ['page' => $page]);`

This does not load my customized template but rather the original which comes with shopware in the vendor directory. I would expect it to load the same overriden one which is used when including it in another template.

I tried debugging this behaviour but without any success. Of course I deleted the cache and also updated shopware to the latest 6.1.1-dev

**Comment by mitelg** [comment]
seems to be a duplicate of https://github.com/shopware/platform/issues/491

**Comment by ssltg** [comment]
Hi @merlin-it ,
can you please send me the content of your /custom/plugins/MyPlugin/src/Resources/views/storefront/layout/header/actions/cart-widget.html.twig File for further checks?

Greets,
Stefan

**Comment by merlin-it** [comment]
Hi @ssltg 
thanks for your fast reply. My modified template is no big deal and for the moment just for testing.
It looks like this:

`{% sw_extends '@Storefront/storefront/layout/header/actions/cart-widget.html.twig' %}

{% block layout_header_actions_cart_widget %}
    included widget
    {{ parent() }}
{% endblock %}`

When I load the page the text "included widget" is shortly displayed in the header, but when the ajax call is made it gets replaced by the content of the original template and the text from my template disapears.

Greets, 
André

**Comment by ssltg** [comment]
Hi André,

i tried your setup and could not reproduce your issue. Could you please try to update to shopware 6.1.3 and check if the issue still apears?

Greets,
Stefan

**Comment by merlin-it** [comment]
Hi @ssltg 
in the meantime I had to take another approach also for other reasons, which worked as a workaround for this problem. I will try to reproduce it in a clean setup when I find a free moment :)

Cheers, André

**Comment by merlin-it** [comment]
As I said it works for me with the different approach. I did not have the time to try to reproduce it in a clean setup and nobody else confirmed the behaviour, so I will close the issue. 
Thanks anyway...
