### ISSUE TITLE
Shopware 6 product variant update issue

### ISSUE THREAD

**Issue by tekbird** [shopware/shopware#508]
I am testing the shopware 6 admin API using the latest version of Shopware (6.1.1) and found this strange behaviour. 

I am invoking the PATCH method of product API to update the variant option value. However, the option value gets added to the existing option instead of replacing it.

Can you suggest a way to replace an existing option value with a new one for a product?

Following is a Fiddler screenshot of the update call.
![2020-02-06_14h34_54](https://user-images.githubusercontent.com/678518/73941702-02866580-48ee-11ea-91cc-799acdd2749f.png)

Following is Postman response showing the option value added up:
![2020-02-06_14h37_07](https://user-images.githubusercontent.com/678518/73941820-36618b00-48ee-11ea-94b6-24b9936ead15.png)

**Comment by OliverSkroblin** [comment]
Hi @tekbird,

Patch requests against the API only add relations or update the entities behind them. Overwriting a relation is not possible this way.

To delete the existing linked options you have to send a DELETE request with the id's.

In your case this would be the following

```
DELETE /product_option {
    productId: ...
    optionId: ...
}
```

**Comment by tekbird** [comment]
Hi @OliverSkroblin, thanks for clarification. But the route you mentioned '/product_option' returns 404. can you please provide the correct one?

**Comment by tekbird** [comment]
I found that the route /product-option seems to exist. But it neither supports DELETE or when I do a GET, I get the following:

{
    "errors": [
        {
            "code": "0",
            "status": "500",
            "title": "Internal Server Error",
            "detail": "Argument 1 passed to Shopware\\Core\\Framework\\DataAbstractionLayer\\Cache\\EntityCacheKeyGenerator::getEntityContextCacheKey() must be of the type string, array given, called in C:\\Bitnami\\shopware-6.1.1-0\\apps\\shopware\\htdocs\\vendor\\shopware\\core\\Framework\\DataAbstractionLayer\\Cache\\CachedEntityReader.php on line 90"
        }
    ]
}

**Comment by r4dul** [comment]
Hi @tekbird ,
I'm in the same situation. Did you managed to solve this somehow?

**Comment by r4dul** [comment]
Ok,
Yea, it seems that first, the relations between product and options need to be deleted and then created again.
If anyone encounters this issue, here's is what I did to achieve the goal: 
To achieve that I used the Shopware's _action/sync endpoint as described here: https://shopware.stoplight.io/docs/admin-api/docs/guides/writing-entities/bulk-payloads.md and also disabled indexing-behavior header.
