### ISSUE TITLE
Questions regarding custom CMS element implementation

### ISSUE THREAD

**Issue by gruhn** [shopware/shopware#509]
I'm currently deep diving into custom CMS element development in Shopware 6. I went through the [dedicated HowTo](https://docs.shopware.com/en/shopware-platform-dev-en/how-to/custom-cms-element?category=shopware-platform-dev-en/how-to) and I'm now dissecting the implementation of the [built-in CMS elements](https://github.com/shopware/platform/tree/6.1/src/Administration/Resources/app/administration/src/module/sw-cms/elements).

My initial expectation was that for each CMS element I could write a single Vue component which would serve both as the "main component" and as the storefront implementation. This turned out to be not as easy as I thought. I guess it's not even intended to work that way. However, I don't understand the purpose of some design decisions which, I believe, get in the way here. Could you please elaborate on them.

Exemplary, consider the [product-box element](https://github.com/shopware/platform/tree/d1802e10d3ac87bafd6e1f2d230398ea9373b40b/src/Administration/Resources/app/administration/src/module/sw-cms/elements/product-box).

### Dependency Injection

What is the benefit of dependency injecting `this.repositoryFactory` here?

https://github.com/shopware/platform/blob/d1802e10d3ac87bafd6e1f2d230398ea9373b40b/src/Administration/Resources/app/administration/src/module/sw-cms/elements/product-box/config/index.js#L14

From what I have seen `repositoryFactory` is more or less just a wrapper for the REST API. 

Dependency injection here makes the component un-reusable anywhere where the dependency provider is not in the parent component chain. From the [Vue docs](https://vuejs.org/v2/guide/components-edge-cases.html#Dependency-Injection):

> [...] there are downsides to dependency injection. It couples components in your application to the way they’re currently organized [...]

Getting a reference to `repositoryFactory` like this instead:
```js
import { Service } from 'src/core/shopware'

const repositoryFactory = Service('repositoryFactory')
```
seems to work fine for me so far.

### Prop Mutation in Child Component

When a user changes a config field, the value is stored [by mutating the `element` prop](https://github.com/shopware/platform/blob/d1802e10d3ac87bafd6e1f2d230398ea9373b40b/src/Administration/Resources/app/administration/src/module/sw-cms/elements/product-box/config/index.js#L40-L42) (defined in [cms-element mixin](https://github.com/shopware/platform/blob/d1802e10d3ac87bafd6e1f2d230398ea9373b40b/src/Administration/Resources/app/administration/src/module/sw-cms/mixin/sw-cms-element.mixin.js#L14-L17)). This violates [Vue's one-way data flow principle](https://vuejs.org/v2/guide/components-props.html#One-Way-Data-Flow) and makes it hard to reason when and how state is shared between components. Couldn't this be solved idiomatically with [custom events](https://vuejs.org/v2/guide/components-custom-events.html)? 

### Why `initElementConfig`/`initElementData`?

Why do we have to call `initElementConfig`/`initElementData`? 

https://github.com/shopware/platform/blob/d1802e10d3ac87bafd6e1f2d230398ea9373b40b/src/Administration/Resources/app/administration/src/module/sw-cms/elements/product-box/component/index.js#L76-L84

At least `initElementConfig` is called in virtually every component and all it does is merging `this.element.config` with the defaults. Both are provided by the parent component so why is this not happening in the parent component? Also, this is happening multiple times. For example every time I close and reopen the config component popup.

Ideally (as I envision it), I would define my "main component" with one prop corresponding to each config option: 

```js
props: [ 
   'product', 
   'boxLayout', 
   'displayMode', 
   'verticalAlign'
]
```
It would be the parent components job to pass the correct values, initialized with defaults. It should also fetch the additional data that needs to come with `product`.

### Difference Between `config` and `data`

Somewhat related to the previous point, I don't really get the distinction between `this.element.config` und `this.element.data`. 

Of course `this.element.config.product` comes with pure configuration fields like `required` while `this.element.data.product` holds the data associated with the given product. However, `this.element.config.product` also has a `value` field which seems to me perfectly fine for holding the data. They are mostly updated together anyway:

https://github.com/shopware/platform/blob/d1802e10d3ac87bafd6e1f2d230398ea9373b40b/src/Administration/Resources/app/administration/src/module/sw-cms/elements/product-box/config/index.js#L40-L42

I realize that `this.element.data.product.value` stores a product ID here instead of full product record. I don't understand why though. The ID is included in the product record. I can imagine that this is due to the way configuration is stored in the database. It would be convenient if this ID <-> record translation would happen in the parent component as well.

**Comment by pantrtxp** [comment]
Hi @gruhn,

for discussions please head over to our [forum](https://forum.shopware.com/categories/shopware-6) 
If you want to suggest changes please create Tickets for your Ideas [here](issues.shopware.com). In our IssueTracker people will be able to vote for issues which makes identifying what the community wants easier.

Sunny Regards
Pantrtxp
