### ISSUE TITLE
document.taxOffice not editable

### ISSUE THREAD

**Issue by schaltwerkdesign** [shopware/shopware#511]
` {% block document_footer_tax_office %}<li>{{ 'document.taxOffice'|trans({'%taxOffice%': config.taxOffice})|sw_sanitize }}</li>{% endblock %}`

taxOffice is not editable in document settings in administration. block is defined in documents/base.html.twig

**Comment by ssltg** [comment]
Thank you for mention this. We fixed it and it will soon be merged for the next release.
