### ISSUE TITLE
Entity relation product-option does not support DELETE

### ISSUE THREAD

**Issue by tekbird** [shopware/shopware#518]
This is a re-post of the issue at https://issues.shopware.com/issues/NEXT-6948. I am re-posting this since we did not get response over that channel,

**Comment by keulinho** [comment]
Hey @tekbird,

as it is a relation endpoint you can reach this option through the main product endpoint.

It should be possible to delete this option via: `DELETE api/v1/product/{productId}/options/{optionId}`.

This is currently a limitations that the endpoints of mapping entities can not be accessed directly.

Kind regards
Jonas

**Comment by tekbird** [comment]
It works!
