### ISSUE TITLE
npm install is broken for administration and its dependencies

### ISSUE THREAD

**Issue by MDSLKTR** [shopware/shopware#519]
**Description**  
https://raw.githubusercontent.com/shopware/platform/6.1/src/Administration/Resources/app/administration/package.json

When running npm install in `Administration/Resources/app/administration` the installation will fail because the shopware depedencies are not available on the registry:

"@shopware/eslint-config-base": "1.0.0",
"@shopware/webpack-copy-after-build": "1.0.0",
"@shopware/webpack-kill-process-on-failed-build": "1.0.0",
"@shopware/webpack-plugin-injector": "1.0.0",

**Possible Solution**  
Use the now used company scope:
`@shopware-ag`

See:
https://registry.npmjs.org/@shopware/webpack-plugin-injector -> Broken
https://registry.npmjs.org/@shopware-ag/webpack-plugin-injector -> Works

**Comment by klarstil** [comment]
Hey @MDSLKTR 
thanks for opening this issue. A `npm install` isn't working cause we're using private packages which will be managed by [lerna](https://github.com/lerna/lerna).

We're in the middle of migrating from lerna to public packages, so we're able to use `npm install` normally again.

In the mean time you can install the dependencies using `npm run lerna -- bootstrap` in the `platform/src/Administration/Resources` folder.

Best regards
