### ISSUE TITLE
Administration Variants: onOptionEdit is not defined 

### ISSUE THREAD

**Issue by bilobait-lohrmann** [shopware/shopware#52]
If you have variants generated for a product and you want to edit a variant after that, following error is raised in the console:

> ReferenceError: onOptionEdit is not defined
>     at click (eval at nr (app.js?1558934040:21), <anonymous>:3:3303)
>     at He (app.js?1558934040:21)
>     at HTMLAnchorElement.n (app.js?1558934040:21)
>     at HTMLAnchorElement.o._wrapper (app.js?1558934040:21)
> Ze @ app.js?1558934040:21
> Ve @ app.js?1558934040:21
> Ue @ app.js?1558934040:21
> He @ app.js?1558934040:21
> n @ app.js?1558934040:21
> o._wrapper @ app.js?1558934040:21

**Comment by seggewiss** [comment]
Thank you for reporting that error.
We are implementing the variant edit feature right now. But we will implement a hint that this feature is in development as a quick fix.

**Comment by mitelg** [comment]
see this commit https://github.com/shopware/platform/commit/00b2799b9e6e5e835aa7f0eff7151bcd2f65e08a
