### ISSUE TITLE
No way to configure shipping taxes

### ISSUE THREAD

**Issue by Zyles** [shopware/shopware#521]
**Description**  

There is no way to set what tax a shipping method uses. I can't find anything in the docs either.

Either this is a very deeply hidden feature or it doesn't exist. Which it should since without it, we wouldn't be able to run a store.

**Comment by GerDner** [comment]
In Germany this is regulated by Law. You can't decide which Tax to use, the shipping tax is decided by the "mix" in your cart and depends on the articles in your cart.

**Comment by Zyles** [comment]
So this platform can not be used outside Germany.

Gotcha.

**Comment by elkmod** [comment]
@Zyles - thank your for raising the issue. If you allow me put this right - you CAN use it outside of Germany - in fact, the calculation mechanism referred to by @GerDner does apply to most of the tax systems. Designing the system with maximum flexibility in mind it would be a bummer to actually hard-set this to a fixed tax rate.

However, if this is a hard requirement for Shopware to work within a certain trade/tax system, we will look into that. Maybe you can give us a hint here @Zyles ?

**Comment by Zyles** [comment]
"can" sure if your tax system works like Germany.

But you also run into problems when you want to sell outside EU. For example Norway. Configuring 0% tax is not possible, because Shopware wants to tax the shipping anyway. And you can't display excl. tax prices on the website for customers outside EU either if the visitor selects Norway as destination.

A lot of EU countries have fixed tax rates depending on what service you are charging, including, but not limited to shipping costs, surcharges for things like invoice fees etc. I don't have a list of all these countries.

Germany has a lot of laws that are not applicable in other countries. I believe you also need to have the text "inc. tax" near all prices and stuff. Which is not required in other countries either.

But the inability to being able to set tax rates for additional fees such as shipping, or a payment surcharge is a huge fail if you want this platform to work in other countries than Germany or those that are the same as Germany.

Some countries also have different rules whether tax should be applied on the billing country or the destination country.

At the end of the day, if you want this platform to succeed outside Germany, you should have a more flexible tax system and probably have an option to use German tax rules and the system will follow that if required.

We will not be investing in this platform until there is proper support for this and I do not want to put devs on work to overhaul the entire core tax mechanic just to be able to launch the store.

**Comment by Zyles** [comment]
Also here is a fun article for you if you want to even consider the US market: https://www.bigcommerce.com/blog/shipping-sales-tax/

Which is state level taxation. Afaik when I checked the demos I could only setup country level.

**Comment by mnaczenski** [comment]
State-level taxes are already possible in the tax module.

Thank you for raising this issue, we are always open for recommendations on how to improve our software, especially when it comes to internationalization. We will have a look at the issue of missing tax rates for shipping costs in the future and will add it there. Something like a dropdown with available taxes and an auto mode (current calculation).

**Comment by lutek** [comment]
@mnaczenski I spent a few days analyzing your platform (v6). It looks great, unfortunately I stopped at the same as @Zyles, taxes for shipping. The invoice calculates wrong tax summary for products with different tax rates. 
Not complying with EU countries disqualifies it. 
Display (tax inc. etc) can be changed by "encoding in template" but this should be built in.

Currently my shop has been running for over 10 years on Prestashop, from which I want to escape (spaghetti code), more regression error than new development. 

The shop has grown and I am looking for a platform for a growing business. If you want to succeed outside Germany these changes should be a priority.

**Comment by mnaczenski** [comment]
@lutek It's already on our public roadmap and planned in the next months.

**Comment by lutek** [comment]
oh I'd like to hear next month, not months ;) I really like your platform.

**Comment by axzx** [comment]
I would like to ask if there is any progress on this issue?

**Comment by mnaczenski** [comment]
Yeah, when the roadmap is fixed, it will be also visible on the roadmap.
We started developing this week. @axzx

**Comment by shyim** [comment]
It is already released
