### ISSUE TITLE
 from where to  find event of checkout page in shopware 6?any one can give the  checkout page events.?

### ISSUE THREAD

**Issue by thsekeer** [shopware/shopware#524]
**Description**  

**Possible Solution**  

**Additional context**

**Comment by keulinho** [comment]
Hey @thsekeer,

as all storefront page events these events can be found under `platform/src/Storefront/Page`. For checkout specific pages check out  `platform/src/Storefront/Page/Checkout`.

For Problems like this the [gitter channel](https://gitter.im/shopware/platform?utm_source=share-link&utm_medium=link&utm_campaign=share-link) or the [Forum](https://forum.shopware.com/categories/shopware-6-en) are better place, as GitHub issues should be used report potential bugs.

Kind regards
Jonas
