### ISSUE TITLE
Unable to access thumbnail elements which arent at first or last place

### ISSUE THREAD

**Issue by Sheek44** [shopware/shopware#530]
**Description**  
"element.data.media.thumbnails" gives back an array which contains all rendered thumbnails for an image. How do i address elements in the middle of the array? Since "|sort" sorts the array in order of the thumbnails width, its only possible to address the first ("|first") or last ("|last") element, but none of the middle elements. "element.data.media.thumbnails[1]" e.g. returns "null"

**Comment by OliverSkroblin** [comment]
Hey @MortisReturns,
`element.data.media.thumbnails` is an EntityCollection where you can simply loop the items. 

If you need to access an exact index, you can simple call the next() function of the collection to get the next item.
