### ISSUE TITLE
TypeError: Cannot read property '_tc' of null

### ISSUE THREAD

**Issue by patchee500** [shopware/shopware#538]
I tried to reuse the [Media Media Item Component](https://component-library.shopware.com/components/sw-media-media-item) in the review detail view of the admin section. The items passed to this component were joined (`criteria.addAssociation`) to the repository criteria of the review entity.

I then found out that these items don't come with some legacy `delete` (`src/Administration/Resources/app/administration/src/core/data/EntityProxy::delete`) method which is being utilized by the [Media Modal Delete Component](https://component-library.shopware.com/components/sw-media-modal-delete).
This is the reason I then implemented and injected/added the delete method to the loaded items myself.
Deletion now works fine, but I still receive some "File could not be deleted" message in the admin section even though my own `delete` method is returning a resolved promise.
Some further investigation revealed the following error, which seems to hint at some translation problem:

```
TypeError: Cannot read property '_tc' of null
    at VueComponent.Vue.$tc (vue-i18n.esm.js?a925:185)
    at VueComponent.snippets (index.js?3af7:65)
    at Watcher.get (vue.esm.js?a026:4482)
    at Watcher.evaluate (vue.esm.js?a026:4587)
    at VueComponent.computedGetter [as snippets] (vue.esm.js?a026:4839)
    at VueComponent.updateSuccessNotification (index.js?3af7:172)
    at eval (index.js?3af7:125)
    at async Promise.all (:8080/index 0)
```
When investigating `src/Administration/Resources/app/administration/src/app/component/media/sw-media-modal-delete/index.js` I find code like this:

```
return {
    successOverall: 'global.sw-media-modal-delete.notification.successOverall.message.mediaAndFolder',
    errorOverall: this.$tc(
        'global.sw-media-modal-delete.notification.errorOverall.message.mediaAndFolder'
    ),
    modalTitle: this.$tc('global.sw-media-modal-delete.titleModal.mediaAndFolder'),
    deleteMessage: this.$tc(
        'global.sw-media-modal-delete.deleteMessage.mediaAndFolder',
        this.itemsToDelete.length,
        {
            mediaCount: this.mediaItems.length,
            folderCount: this.folders.length
        }
    )
};
```
and also

```
const notification = {
    title: this.$root.$tc('global.default.success'),
    message: this.$root.$tc(
        this.snippets.successOverall,
        successAmount,
        {
            count: successAmount,
            total: totalAmount
        }
    ),
    growl: successAmount + failureAmount === totalAmount
};
```
which raises some questions.  

1. Is there a reason some template strings (`successOverall`) are not wrapped in translation functions?
2. What is the difference between `this.$tc()` and `this.$root.$tc()`? `this.$tc()` seemed not to be accessible in my case and therefore the reason of the error. When changing the code to only use `this.$root.$tc()` it worked fine.

**Comment by jleifeld** [comment]
1: The `sucessOverall` get wrapped later in an translation function:
```
updateSuccessNotification(successAmount, failureAmount, totalAmount) {
            const notification = {
                title: this.$root.$tc('global.default.success'),
                message: this.$root.$tc( // here
                    this.snippets.successOverall,
                    successAmount,
                    {
                        count: successAmount,
                        total: totalAmount
                    }
                ),
                ...
        }
```

2. In regular components we dont need `this.$root.$tc()`. I don´t know the exact reason why it was used at this place. Normally `this.$tc` should work fine. That there is no access to `this.$tc` is strange because we added the i18n plugin directly to the vue instance. I think it will be a timing problem and `this.$root.$tc()` is an dirty fix for this.

**Comment by patchee500** [comment]
> The sucessOverall get wrapped later in an translation function:

:man_facepalming: Ah, that makes sense, thanks for pointing out.  

> In regular components we dont need this.$root.$tc(). I don´t know the exact reason why it was used at this place. Normally this.$tc should work fine.  

Thanks for the clarification. It helps to know using this.$tc should be sufficient. Maybe if I find the time, I'll investigate on this further.

**Comment by jleifeld** [comment]
I will close this issue then. When you have further problems you can reopen it.

Thanks for your contribution 👍
