### ISSUE TITLE
Import/export possibilities

### ISSUE THREAD

**Issue by djedrzejewski** [shopware/shopware#539]
**Description**  
For Shopware 5.x there was a import/export plugin available
https://store.shopware.com/en/swagef36a3f0ee25f/shopware-import/export.html
In it's description there's info, that this plugin would be built-in in the Shopware 6 version. It's also mentioned in Roadmap:
https://www.shopware.com/en/roadmap/
What's the progress there? It would be quite handy, because now there is no convenient way to share the work done in admin panel, such as creating the Shopping Experiences.

Or maybe there is a way, which could be used before import/export function release?

**Comment by pantrtxp** [comment]
Hi @djedrzejewski 

The Import/Export feature is planned for the 6.2 release, which will be released around the end of april.
RC will be available some time earlier

Sunny regards
Pantrtxp
