### ISSUE TITLE
Seeding migrations

### ISSUE THREAD

**Issue by JoshuaBehrens** [shopware/shopware#542]
**Description**  
The feature of having a DAL is super nice but it is ugly to seed data like custom field sets as you have to provide them on activation and update. A migration would suit the needs better in case of a changing structure. The migrations seem not to have access to the container to get a repository to work with data. That would be really helpful as migrations already keep track of being run once or not.

**Example**  
```
<?php declare(strict_types=1);

namespace FooBar\Migration;

use Doctrine\DBAL\Connection;
use Shopware\Core\Framework\Migration\DataMigrationStep;

class Migration1581949429 extends DataMigrationStep
{
    public function getCreationTimestamp(): int
    {
        return 1581949429;
    }

    public function updateData(Container $container): void
    {
    }

    public function updateDataDestructive(Container $container): void
    {
    }
}
```

**Comment by mitelg** [comment]
hey @JoshuaBehrens 
the migration system should be as independent as possible from all the other parts of the Shopware core. So it could be run without a running shopware (in theory).

**Comment by JoshuaBehrens** [comment]
That is... ok. It is understandable. So I just use inserts instead? I can't depend on meta-configuration this way. How do I ensure properly the existance or migration of custom field data? Do I really have to do that like in the 5-days by comparing the updating version and change the custom field sets?

**Comment by JoshuaBehrens** [comment]
The more annoying part is that these fields get translations in a manner that is unusual in the thoughts on this framework. They are not served as translatation but inside a json field. I know that admin translations are only served as registered key in the Locale object and by translated content. That custom fields are handled like content that is ok... somehow... when you compare them to shopware 5 attributes it was possible to translate them externally by adding some snippets. These custom fields are not because the custom field itself holds itself the translation. Why does it do that? Because this translation is part of the input field attributes that used to generate the editing field. That can be overriden but in `sw-form-field-renderer::bind` but that is such a hassle an huge overload. How can this be solved in an other way (Translate custom fields like classic attributes in 5)?

**Comment by pweyck** [comment]
I think a decent solution would be, if could provide a snippet in the config and use it as a default. The users could still overwrite it, but the snippet would be the default.

Example Config:
```
{
  "type": "text",
  "label": {
    "snippet": "myplugin.mycustomfield.label",
    "en-GB": "My label override"
  },
  "helpText": {
    "snippet": "myplugin.mycustomfield.helptext"
  },
  "placeholder": {
    "en-GB": "Code Placeholder"
  },
  "componentName": "sw-field",
  "customFieldType": "text",
  "customFieldPosition": 1
}
```
You would only need to insert this config once, and you could just update the snippet file. Would that solve your problem?

**Comment by JoshuaBehrens** [comment]
I solved it currently that way:

```
const { Component } = Shopware;

Component.override('sw-form-field-renderer', {
    computed: {
        bind() {
            const result = this.$super('bind'),
                config = this.config,
                translatableFields = this.translatedFields[this.componentName] || [];

            translatableFields.forEach(field => {
                if (config[field] && config[field].i18n && this.$te(config[field].i18n)) {
                    result[field] = this.$t(config[field].i18n);
                }
            });

            return result;
        }
    }
});
```

I provide snippets in addition to that change. And my migration to add this field looks like this
```
$connection->insert('custom_field_set', [
    'id' => Uuid::fromHexToBytes(self::SET_ID),
    'name' => 'custom_set_product',
    'config' => '{"label": {"en-GB": "Foobar", "de-DE": "Foobar", "nl-NL": "Foobar"}, "translated": true}',
    'active' => true,
    'created_at' => date_create('@' . $this->getCreationTimestamp()),
], [
    'created_at' => 'datetime',
]);
$connection->insert('custom_field_set_relation', [
    'id' => Uuid::fromHexToBytes(self::SET_RELATION_ID),
    'set_id' => Uuid::fromHexToBytes(self::SET_ID),
    'entity_name' => 'product',
    'created_at' => date_create('@' . $this->getCreationTimestamp()),
], [
    'created_at' => 'datetime',
]);
$connection->insert('custom_field', [
    'id' => Uuid::fromHexToBytes(self::CUSTOM_FIELD_ID),
    'set_id' => Uuid::fromHexToBytes(self::SET_ID),
    'name' => 'custom_set_product_baz',
    'active' => true,
    'config' => json_encode([
        'type' => 'switch',
        'label' => [
            'i18n' => 'foobar.customFields.baz',
        ],
        'validation' => 'required',
        'componentName' => 'sw-field',
        'customFieldType' => 'switch',
        'customFieldPosition' => $position,
    ]),
    'type' => CustomFieldTypes::BOOL,
    'created_at' => date_create('@' . $this->getCreationTimestamp()),
], [
    'created_at' => 'datetime',
]);
```
That is pretty similar to your suggestion. Pull request like this?

**Comment by JoshuaBehrens** [comment]
For shopware 6.2 I had to change my solution to this:
```
const { Component } = Shopware;

Component.override('sw-form-field-renderer', {
    computed: {
        bind() {
            const result = this.$super('bind'),
                config = this.config;

            ['label', 'placeholder', 'helpText'].forEach(field => {
                if (config[field] && config[field].i18n && this.$te(config[field].i18n)) {
                    result[field] = this.$t(config[field].i18n);
                }
            });

            return result;
        }
    }
});
```

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
