### ISSUE TITLE
Signup form email

### ISSUE THREAD

**Issue by TaiKamilla** [shopware/shopware#545]
Hi
Sign up form does weird stuff
If you make up a very fake email throws an error
Expected response code 354 but got code "554", with message "554 5.5.1 Error: no valid recipients
"
Test email used
(asdfasdfasdfkljkldsauhiuweqn@iasdfklnhjkaeiuqwoerqcwnqerw.com)
But if you fill the right email (a real existing domain), it works
Solution for this?

![image](https://user-images.githubusercontent.com/15035750/74735536-3304c280-5251-11ea-9994-04d8757a305d.png)

![image](https://user-images.githubusercontent.com/15035750/74735548-37c97680-5251-11ea-918e-946877774d53.png)

I did try in prod, and it gives an error too, but it does not show

To show the error I changed the `.env`  `APP_ENV=prod` -> `APP_ENV=dev`

![image](https://user-images.githubusercontent.com/15035750/74735573-444dcf00-5251-11ea-930a-4b75352e34c9.png)

**Comment by pantrtxp** [comment]
Hi @TaiKamilla 

Thank you for bringing this up
as you already created a ticket for this, all I can tell you is that we will fix this issue with the created ticket 
https://issues.shopware.com/issues/NEXT-7121 

Sunny regard 
Pantrtxp

**Comment by shyim** [comment]
This has been fixed meanwhile. The email works
