### ISSUE TITLE
Inherited properties does not show up in product association

### ISSUE THREAD

**Issue by zaifastafa** [shopware/shopware#559]
**Description**  
When fetching a variant product from the repository which does not have its own property assigned such as for e.g `unit`, then even if we add the `unit` in the criteria as an association, the unit shows up as `NULL` whereas it should show the inherited property in the resulting entity.

This makes it an additional overhead to check if the unit does not exist then we have to fetch the unit from the parent record.  

**Possible Solution**  
If the property is inherited, then the search result should still give correct inherited value instead of null. 

**Additional context**  
Found this error for the `unit` property but I am sure it should be applicable for other properties too which require an association in the criteria object.

**Comment by keulinho** [comment]
Hey @zaifastafa,

the repositories do not consider inherited fields by default. If you want to read the inherited values too you have to set the `considerInheritance` flag on the Context to true by `$context->setConsiderInheritance(true)`.

Kind regards
Jonas
