### ISSUE TITLE
Get rid of cacheHash

### ISSUE THREAD

**Issue by htuscher** [shopware/shopware#560]
**Description**  
Symfony usually uses the `APP_ENV` to construct the cache path like e.g. `var/cache/dev/`. Shopware added a cacheId, which results in paths like `var/cache/dev_h52f02c65f249e550e4ba5c77eb3625ab`. 
This path is unpredictable, because it's randomly generated.

For most users this may not be a problem, but you can't use e.g.  opcache preload (PHP 7.4) easily with this approach.
https://symfony.com/blog/new-in-symfony-4-4-preloading-symfony-applications-in-php-7-4

```
; php.ini
opcache.preload=/path/to/project/var/cache/prod/App_KernelProdContainer.preload.php
```

You can only specify the path to one file. Therefore the path must be predictable.

I'm not quite sure why this additional random cacheId was introduced, but it seems to be only changed during the HTTP-Cache warmup. Therefore I suggest, that separating the HTTP cache from the regular Symfony cache would solve this issue.

**Comment by mitelg** [comment]
hey @hhoechtl 
we are aware of that. There is also a ticket for that issue: https://issues.shopware.com/issues/NEXT-6104
The reason for the "random" string is that the DI container must be build new, once a plugin is activated/deactivated

**Comment by hlohaus** [comment]
In between you can override the getCacheHash method:
https://github.com/shopware/core/blob/master/Kernel.php#L274

**Comment by timrasche** [comment]
Still open? disappointing...

**Comment by shyim** [comment]
The preload file is now outside of the cache folder
