### ISSUE TITLE
Create an order via API : AsynchronousPaymentHandlerInterface::pay to allow JsonResponse or RedirectResponse.

### ISSUE THREAD

**Issue by vttn** [shopware/shopware#565]
**Description**  
We are creating a Shopware payment plugin. The current payment handler interfaces are a bit limited. You are forced to return a redirect response using AsynchronousPaymentHandlerInterface. This is not practical for a lot of payment methods.

**Example**  
1. Customer is at /checkout/confirm page with a number of line items
2. Customer selects Payment Method A. 
    * Payment Method A uses 3D secure via JavaScript (iframe).
    * On the /checkout/confirm customer gets a form (iframe) to enter their payment details.
    * * The customer enters payment details. Payment details are verified without charging the customer. Once payment details are verified we create the order in the shopware System.
3. Create order in Shopware. Return a JSON response verifying the order creation. Do some background work. I.e. Setup Shopware finished URL. etc.
4. Evaluate JSON response. Redirect the customer to an external gateway is everything is okay. Otherwise show errors.
4. From the external gateway the customer is redirected back to shopware with either a success or failure of the order transaction.

One way to implement this checkout flow is by using custom controllers, however we would like to benefit as much as possible from the Shopware platform.

**One quick fix would be to change the AsynchronousPaymentHandlerInterface::pay to allow JsonResponse or RedirectResponse.

**Comment by keulinho** [comment]
Hey @vttn,

from the gitter chat:
> The payment method on the /checkout/confirm page can do the redirects via JavaScript

coudn't that make problems with cross-origin resource sharing (CORS) if js redirects to a different resource?

**Comment by mitelg** [comment]
hey @vttn 
in our PayPal integration we do something like this: https://github.com/shopwareLabs/SwagPayPal/blob/master/src/Resources/app/storefront/src/plus/payment-wall.js#L257
which is indeed only a workaround. your suggestion sounds good at first glance.

**Comment by vttn** [comment]
@keulinho @mitelg

We are using the same checkout flow for Salesforce, Wordpress/WooCommerce and other integrations.

For example, if I create an order and get a JSON response. I could do something like this.

```
// bare in mind this is rough code that we use in every checkout process.
var settings = {
  "url": "http://shopware.local/checkout/order",
  "method": "POST",
  "timeout": 0,
  "headers": {
    "sw-access-key": "SWSCMEJYAFJ5UVFRDVPLRNNLTQ"
  },
};

$.ajax(settings).done(function (response) {
  if(response.orderId){
    if(response.redirectUrl){
         window.location.href = response.redirectUrl;
    }else{
          window.['customOject'].submit();  // this does the 3D redirect
   }
   }
});
```

The larger point is that we would like not to "hack" Shopware, if a simple solution is available.

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
