### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by WaqarAhmedBajwa** [shopware/shopware#58]
![Screenshot](https://user-images.githubusercontent.com/10218862/58479969-cdc4ea80-8172-11e9-9bd6-50a550d0c47f.png)

Argument 2 passed to Shopware\...\NavigationController::home() must be and instance of shopware\...\SalesChannelContext null given, called in .../symfony/http-kernel/HttpKernel.php
as shown in the image.

**Comment by mitelg** [comment]
Hello @WaqarAhmedBajwa 
this is a common problem currently. Could you please check if your host URL and the URL in `sales_channel_domain` DB table are the same?

**Comment by WaqarAhmedBajwa** [comment]
> Hello @WaqarAhmedBajwa
> this is a common problem currently. Could you please check if your host URL and the URL in `sales_channel_domain` DB table are the same?

Thank you @mitelg , URLs were different.
