### ISSUE TITLE
First plugin's active status is being changed on changing another's active status in the plugin list.

### ISSUE THREAD

**Issue by deepakk-webkul** [shopware/shopware#581]
Preconditions (*)
Shopware version 6.1.3 with demo data installed
PHP 7.2.22
Production Mode

In Plugin Page, If we try to click on the label (activated /deactivated) then another plugin's status has been changed automatically.

![Screenshot](https://user-images.githubusercontent.com/50043226/75223688-04e12e80-57cd-11ea-8393-506424f09be9.png)

[Screencast 2020-02-25 12:38:58.webm.zip](https://github.com/shopware/platform/files/4248591/Screencast.2020-02-25.12.38.58.webm.zip)

**Comment by GitEvil** [comment]
Hi, Deepak, I too have encountered this behaviour before. However I wasn't able to reproduce it reliably. Do you mind to elaborate on that a little further, if the problem persists? Does it happen only for the first time you click the switch or is this repeatable?

**Comment by deepakk-webkul** [comment]
Hi @GitEvil, I checked for the same, this happens always when I click on the `Active Label` not on the `Active Switch`, clicking on the switch is working fine. Please watch the video provided in the link - `Screencast 2020-02-25 12:38:58.webm.zip`, you will get it.

**Comment by GitEvil** [comment]
Thank you, I have created a ticket for the issue. 
https://issues.shopware.com/issues/NEXT-7278

**Comment by shyim** [comment]
Has been fixed a while ago. The checkbox name was the same
