### ISSUE TITLE
cache:clear not working for base.html.twig

### ISSUE THREAD

**Issue by TaiKamilla** [shopware/shopware#582]
Hi!

I created a new theme through the CLI

And I created "custom/plugins/MY_Theme/src/Resources/views/storefront/base.html.twig" to try to overwrite base.html.twig, and try to "bin/console theme:compile && bin/console cache:clear"

is not enough for some reason, but if you delete "var/cache" it works

Why is "cache:clear" not working?

**Comment by shyim** [comment]
This has been fixed from a while ago. The twig warump cache has been disabled
