### ISSUE TITLE
Fresh install gives you the option to select default language, but gives an error when not selecting English or German

### ISSUE THREAD

**Issue by MarcianoH** [shopware/shopware#592]
**Description**  
When doing a fresh install, you have the option to select the default language. When selecting for example "Dutch", you get an application error vendor/shopware/recovery/Install/src/Service/ShopService.php at line 161, because the only records in the table "language" are English and Deutsch

**Possible Solution**  
1. Show only languages available in the table "language"
2. Fill the table "language"

![Screenshot from 2020-02-28 01-00-41](https://user-images.githubusercontent.com/12809560/75497869-dbd7be00-59c5-11ea-8603-b22a5d5e76a0.png)

**Comment by mitelg** [comment]
seems to be the same problem as https://issues.shopware.com/issues/NEXT-6920

this ticket is already in progress, so it should be fixed soon

**Comment by Phil23** [comment]
Fixed with 6.2.0
