### ISSUE TITLE
Aggregate Category filters via the salesChannel API

### ISSUE THREAD

**Issue by MDSLKTR** [shopware/shopware#594]
**Description**
Since gitter has been no help and this problem a bit too extensive, i'll try to explain what my current problem with the salesChannel API regarding aggregations is. Currently entity aggregations work like this, for instance as in the docs for manufacturer:

```
{
    "limit": 1,
    "aggregations": [
        {
            "name": "manufacturers",
            "type": "entity",
            "definition": "product_manufacturer",
            "field": "manufacturerId"
        }
    ]
}
```
This returns the manufacturers for given product request properly.

The first question here would be how to i aggregate product properties into the same formatted array?
```
{
    "limit": 1,
    "aggregations": [
        {
            "name": "properties",
            "type": "entity",
            "definition": "product_property", // or product_properties
            "field": "propertyIds"
        }
    ]
}
```
wont work since there doesn't seem to be an existing definition.

The Storefront itself has the following widget request:
```
/cms/navigation/{NAV_ID}/filter
```

returning the result below filled with all the joy you need to build filters.
```
{
    "manufacturer": {
		"entities": [...]
	},
    "price": {...},
	"shipping-free": {...},
	"rating": {...},
	"properties: {
		"entities": [...]
	}
}
```

So the main question is: How to get the same aggregations as the storefront but only using the salesChannel API? If they exist, please add them to the docs.

**Additional context**  
Shopware Version 6.1.1
SalesChannel API Version 1

Thanks in Advances,
Simon

**Comment by GerDner** [comment]
I don't know if this is exactly what you are looking for but i'm aggregating the Filter Options for filter form elements in the storefront like so:

```php
     $filterDefinition = [
            [
                "name" => "properties.group",
                "type" => "terms",
                "definition" =>"property_group",
                "field" => "properties.group.name",
                "aggregation" => [
                  "name" => "subaggregation",
                  "type" => "terms",
                  "definition" =>"property_group_option",
                  "field" => "properties.name",
                ]
            ],
        ];

```
You should be able to directly aggregate property_name ans skip the group name if you don't need it.

**Comment by OliverSkroblin** [comment]
Hey @MDSLKTR,

try this aggregation:

```
{
    "limit": 1,
    "aggregations": [
        {
            "name": "properties",
            "type": "entity",
            "definition": "property_group_option",  // means: load this entity for the selected ids
            "field": "properties.id"   // means: use this field to fetch the ids 
        }
    ]
}

```

**Comment by MDSLKTR** [comment]
@GerDner Thanks for your reply, this works in terms of "terms" aggregations but what the above described endpoint does, is return nested entity aggregations.

@OliverSkroblin Thanks for your reply, This works directly for property_group_options, but. what it need is the options nested in aggregated property_groups.


So this is what i need basicly except that the `propertyGroups` aggregation does not work yet:

```
aggregations: [
                {
                    name: 'manufacturers',
                    type: 'entity',
                    definition: 'product_manufacturer',
                    field: 'manufacturerId',
                },
                {
                    name: 'priceRange',
                    type: 'stats',
                    field: 'price',
                },
                {
                    name: 'rating',
                    type: 'max',
                    field: 'ratingAverage',
                },
                {
                    name: 'shippingFree',
                    type: 'filter',
                    filter: [
                        {
                            type: 'equals',
                            field: 'shippingFree',
                            value: true,
                        },
                    ],
                    aggregation: {
                        name: 'shippingFree',
                        type: 'max',
                        field: 'shippingFree',
                    },
                },
                {
                    name: 'propertyGroupOptionsPlain',
                    type: 'entity',
                    definition: 'property_group_option',
                    field: 'properties.id', 
                },
                {
                    name: 'propertyGroups',
                    type: 'entity',
                    definition: 'property_group',
                    field: 'properties.group.id',
                    aggregation: {
                            name: 'propertiesGroupOptions',
                            type: 'entity',
                            definition: 'property_group_option',
                            field: 'properties.id', // or property_group_options.id or properties.group.options.id
                        },
                },
```

**Comment by MDSLKTR** [comment]
So "propertiesGroupOptions" or the subaggregation here doesn't do anything. How would i be able to include the options inside such an aggregation?

**Comment by MDSLKTR** [comment]
So this works too:

```
{
                    name: 'propertyGroups',
                    type: 'terms',
                    definition: 'property_group',
                    field: 'properties.group.name',
                    aggregation: {
                        name: 'propertiesGroupOptions',
                        type: 'entity',
                        definition: 'property_group_option',
                        field: 'properties.id',
                    },
                },
```

So terms with entity subaggregations are also ok, yet i would like an entity aggregation with entity option subaggregation.

**Comment by OliverSkroblin** [comment]
Hi @MDSLKTR,

this isn't possible. An Entity Aggregation is an metric aggregation and can not have additional buckets. 
I would suggest you just use the aggregation I sent you and then make a call to /property-group and load the appropriate groups and options. The storefront does this in the same way.

If you then load the groups you can also define a filter on the id in the `options` association.

**Comment by MDSLKTR** [comment]
@OliverSkroblin As long as the storefront does the same thing, this is fine :). Would it be possible to expand the docs a little with examples concerning this?
