### ISSUE TITLE
MailService Event or Interface missing

### ISSUE THREAD

**Issue by Gainto** [shopware/shopware#601]
**Description**  
The MailService actually fires an event after the mail has been sent.
The service should also fire an event, after all data has been gathered but before the mail has been sent.
That gives you the possibility to manipulate the data just before the mail has been sent.

If that's not possible, it would be nice if the MailService(s) would implement some kind of MailServiceInterface to make it at least decoratable.

**Example**  
I see no way to resolve my actual use case without touching every entity:
I extended the Mail-Template Section in the admin area with an "cc recipient" field.
Before an email has been sent, it should check if the referenced e-mail template has an cc recipient and add it, before sending the mail.

The extension would give developers the opportunity to change mail-related logic within a single place in the code. otherwise the only way around is to subscribe to every event which fires an email and add the additional data.

**Comment by hlohaus** [comment]
Heey. Please check the Master and my pull requests. :)
