### ISSUE TITLE
"Call to a member function set() on null"

### ISSUE THREAD

**Issue by WaqarAhmedBajwa** [shopware/shopware#61]
In case of **Register** a customer with **Post request** " in **sales-channel-api/v1/customer** throws an error "Call to a member function set() on null".

![Register](https://user-images.githubusercontent.com/10218862/58630418-c891a800-82f8-11e9-8870-d6706fc3d13a.png)

**Comment by keulinho** [comment]
The problem is that you don't provide the billingAddress as an JSON-Object.
Try following payload for the billing address:
```
"billingAddress": {
    "street": "address street",
    "zipcode": "123",
    "city": "XYZ",
    "countryId": "C84...."
}
```

**Comment by WaqarAhmedBajwa** [comment]
After updating with this JSON-Object, It leads to new error
detail:"The **salutation** entity with id \"E538CB23-F22E-4C04-BEDE-2D663C7B5AAC\" does not exists.".(Also changed salutationId)
 code: "VIOLATION::ENTITY_DOES_NOT_EXISTS".
