### ISSUE TITLE
Bugs, Bugs, Bugs

### ISSUE THREAD

**Issue by TormentedSoul666** [shopware/shopware#611]
Im Ernst Leute,
ich versuche mit 6.1 produktiv zu arbeiten und seit heute morgen gibt es nur Bugs bei Exceptions, Controller Routing, usw,

Wer pusht so was auf stable?!

**Comment by TormentedSoul666** [comment]
Post Deployment ist auch wegen falschen Dependencies im Eimer:

```
`PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Too few arguments to function Shopware\Core\Framework\DataAbstractionLayer\Dbal\EntityDefinitionQueryHelper::__construct(), 0 passed in /app/var/cache/dev_ha9093661bb6fedc2eba2c29cf47c95f9/ContainerCkrrGc1/CoreShopware_Core_KernelDevDebugContainer.php on line 13470 and exactly 1 expected in /app/platform/src/Core/Framework/DataAbstractionLayer/Dbal/EntityDefinitionQueryHelper.php:36
	Stack trace:
	#0 /app/var/cache/dev_ha9093661bb6fedc2eba2c29cf47c95f9/ContainerCkrrGc1/CoreShopware_Core_KernelDevDebugContainer.php(13470): Shopware\Core\Framework\DataAbstractionLayer\Dbal\EntityDefinitionQueryHelper->__construct()
	#1 /app/var/cache/dev_ha9093661bb6fedc2eba2c29cf47c95f9/ContainerCkrrGc1/CoreShopware_Core_KernelDevDebugContainer.php(10417): ContainerCkrrGc1\CoreShopware_Core_KernelDevDebugContainer->getEntityReaderProfilerService()
	#2 /app/var/cache/dev_ha9093661bb6fedc2eba2c29cf47c95f9/ContainerCkrrGc1/CoreShopware_Core_KernelDevDebugContainer.php(13 in /app/platform/src/Core/Framework/DataAbstractionLayer/Dbal/EntityDefinitionQueryHelper.php on line 36
	
Execution aborted, a subcommand failed!
`
```

**Comment by TormentedSoul666** [comment]
```
trace: {
    ./platform/src/Core/Framework/DataAbstractionLayer/Dbal/EntityDefinitionQueryHelper.php:36 {
      Shopware\Core\Framework\DataAbstractionLayer\Dbal\EntityDefinitionQueryHelper->__construct(AntiJoinBuilder $antiJoinBuilder)^
      › 
      › public function __construct(AntiJoinBuilder $antiJoinBuilder)
      › {
    }
    ./var/cache/dev_h2aa03e6828d6053cc571d2dae2561cbc/ContainerCMyYCtK/CoreShopware_Core_KernelDevDebugContainer.php:13467 { …}
    ./var/cache/dev_h2aa03e6828d6053cc571d2dae2561cbc/ContainerCMyYCtK/CoreShopware_Core_KernelDevDebugContainer.php:7247 { …}
    ./var/cache/dev_h2aa03e6828d6053cc571d2dae2561cbc/ContainerCMyYCtK/CoreShopware_Core_KernelDevDebugContainer.php:13266 { …}
    ./var/cache/dev_h2aa03e6828d6053cc571d2dae2561cbc/ContainerCMyYCtK/CoreShopware_Core_KernelDevDebugContainer.php:13019 { …}
    ./vendor/symfony/dependency-injection/Container.php:444 { …}
    ./vendor/symfony/dependency-injection/Argument/ServiceLocator.php:40 { …}
    ./vendor/symfony/console/CommandLoader/ContainerCommandLoader.php:45 { …}
    ./vendor/symfony/console/Application.php:542 { …}
    ./vendor/symfony/console/Application.php:743 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:143 { …}
    ./vendor/symfony/console/Descriptor/ApplicationDescription.php:91 { …}
    ./vendor/symfony/console/Descriptor/ApplicationDescription.php:68 { …}
    ./vendor/symfony/console/Descriptor/TextDescriptor.php:202 { …}
    ./vendor/symfony/console/Descriptor/Descriptor.php:55 { …}
    ./vendor/symfony/console/Helper/DescriptorHelper.php:67 { …}
    ./vendor/symfony/console/Command/ListCommand.php:75 { …}
    ./vendor/symfony/console/Command/Command.php:255 { …}
    ./vendor/symfony/console/Application.php:1029 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:100 { …}
    ./vendor/symfony/console/Application.php:272 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:83 { …}
    ./vendor/symfony/console/Application.php:148 { …}
    ./bin/console:43 { …}
  }
}

```
WTAF?

**Comment by keulinho** [comment]
Hey @TormentedSoul666,

a more detailed issue description would help us a lot in trying to reproduce/understand your issues. 

Regarding your specific problem with the dependencies:
It seems  like the cache is stale, a simple `./psh.phar cache` should solve that specific issue.

If you have any further issues, please provide some more context, like how you did the update and from what version you updated, etc.

Kind regards
Jonas

P.S. we try to communicate in english on github, i hope this is fine for you.

**Comment by TormentedSoul666** [comment]
Hey @keulinho, thank you for fast answering.
I'm working on a plugin with an own Controller and I'm using `Shopware\Core\Framework\DataAbstractionLayer\Dbal\EntityDefinitionQueryHelper` for some database stuff.

Anyways, I've cleared the Cache with .`/psh.par cache` a thousand times and also deleted the folders manually but surprise, they immediately show up again. bin/console immediately throws the Stack Trace Exceptions from my comments above and doesn't work at all.

My Storefront greetz me with 
`Too few arguments to function Shopware\Core\Framework\DataAbstractionLayer\Dbal\EntityDefinitionQueryHelper::__construct(), 0 passed in /app/var/cache/dev_h2aa03e6828d6053cc571d2dae2561cbc/ContainerCMyYCtK/CoreShopware_Core_KernelDevDebugContainer.php on line 13467 and exactly 1 expected`

IMHO it's fair to say that this issue has to do with latest commits about dependency management and especially the Twig Cache.

**Comment by keulinho** [comment]
Can you try to deactivate your plugin?
Does the error still persist?

Also did you run `./psh.phar init` or `./psh.phar update` after you updated platform via git?
(Note that `./psh.phar init` will reset your DB, if you don't want that use `./psh.phar update`)

**Comment by TormentedSoul666** [comment]
I can't run `init`, because the Docker Stack is deployed on a staging system with other people working on the content.
I pulled Development and Platform, did `composer update` and then tried `./psh.par update` with the following Exception:

```
Starting Execution of 'update' ('/app/dev-ops/common/actions/update.sh')

(1/6) Starting
> rm -rf var/cache
	
(2/6) Starting
> bin/console plugin:refresh
	PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Too few arguments to function Shopware\Core\Framework\DataAbstractionLayer\Dbal\EntityDefinitionQueryHelper::__construct(), 0 passed in /app/var/cache/dev_h2aa03e6828d6053cc571d2dae2561cbc/Container77CxMhj/CoreShopware_Core_KernelDevDebugContainer.php on line 13470 and exactly 1 expected in /app/platform/src/Core/Framework/DataAbstractionLayer/Dbal/EntityDefinitionQueryHelper.php:36
	Stack trace:
	#0 /app/var/cache/dev_h2aa03e6828d6053cc571d2dae2561cbc/Container77CxMhj/CoreShopware_Core_KernelDevDebugContainer.php(13470): Shopware\Core\Framework\DataAbstractionLayer\Dbal\EntityDefinitionQueryHelper->__construct()
	#1 /app/var/cache/dev_h2aa03e6828d6053cc571d2dae2561cbc/Container77CxMhj/CoreShopware_Core_KernelDevDebugContainer.php(10417): Container77CxMhj\CoreShopware_Core_KernelDevDebugContainer->getEntityReaderProfilerService()
	#2 /app/var/cache/dev_h2aa03e6828d6053cc571d2dae2561cbc/Container77CxMhj/CoreShopware_Core_KernelDevDebugContainer.php(13 in /app/platform/src/Core/Framework/DataAbstractionLayer/Dbal/EntityDefinitionQueryHelper.php on line 36
	
Execution aborted, a subcommand failed!
```

I can't deactivate my Plugins, because I can't neither run bin/console (it throws the same exception as the post deployment update) nor deactivate them through the Backend, since it throws the same Exception as the Frontend.

**Comment by TormentedSoul666** [comment]
I didn't check the commit in depth because of other stuff I have to do but I'm pretty sure that https://github.com/shopware/platform/commit/7768470fd3ee853f0f1459bcf72ec40512afa4aa is causing the issues.

**Comment by keulinho** [comment]
IMHO the commit looks unrelated and i'm not able to reprodruce the issue in a clean chackout on 6.1 branch.

Can you mark your plugin as deactivated ober the DB by setting the `active` flag to `0` in the `plugin` table and try to run the update command again?

Do you create a own instance of the `EntityDefinitionQueryHelper` in your plugin or do you use the service from the DI container?
How do you create/use the `EntityDefinitionQueryHelper`.

**Comment by TormentedSoul666** [comment]
Well, at least the undeletable Twig Cache has little to do with your approaches to solve the problem.
The idea with the database is good, I wasn't thinking about that, thanks.

I use Dependency Injection over the Container, making instances of all used classes would create quite a mess :) 

I instantiate it as an object and then use it mainly in method chains on several Field related stuff.

**Comment by TormentedSoul666** [comment]
@keulinho you were right, it was indeed the plugin, thanks.

Keep up the good work, Shopware 6 is an impressive product and the definitive E-Commerce future.

**Comment by mitelg** [comment]
nice to see, that you got your issue solved 👍 
I'm currently working on the stability of Shopware if erroneous plugins are installed or activated. so it would be nice, if you could tell me a way to reproduce this error. maybe there is a way to prevent Shopware doing nothing at all
