### ISSUE TITLE
Developer project is too slow

### ISSUE THREAD

**Issue by d3tr1tus** [shopware/shopware#616]
Hi i cloned and installed everything what is in readme written and it works. My problem is that admin and frontend is ultra slow. It seems that API working bad and every request wait to previous request. So i think i have not allowed sync. I have actual version of Docker and also NPM. Can someone help me please? Developing with this speed takes a lot of time and unfortunately i don't have it.

![Bildschirmfoto 2020-03-05 um 08 29 37](https://user-images.githubusercontent.com/37714206/75957986-8dda2300-5ebb-11ea-97c8-74dea97f85a4.png)

**Comment by shyim** [comment]
How does your setup look like?

**Comment by d3tr1tus** [comment]
@shyim 

```
npm - 6.14.2
Docker version 19.03.5, build 633a0ea
```

I made it with [this](https://github.com/shopware/platform#quickstart--installation) setup.

**Comment by shyim** [comment]
and OS?

**Comment by d3tr1tus** [comment]
@shyim 
![Bildschirmfoto 2020-03-09 um 11 33 22](https://user-images.githubusercontent.com/37714206/76205044-c9495a00-61f9-11ea-8132-f07644c86d82.png)

**Comment by keulinho** [comment]
hey @d3tr1tus,

the performance of docker on mac is a known issue, therefore we recommend using docker-sync for FS syncing.
Please follow [this guide](https://docs.shopware.com/en/shopware-platform-dev-en/getting-started/system-installation-guides/docker-sync), on how to enable docker-sync on mac.

**Comment by d3tr1tus** [comment]
Great!! Thank you @keulinho a lot! That's much better 🔝 😄
