### ISSUE TITLE
VIOLATION::ENTITY_DOES_NOT_EXISTS

### ISSUE THREAD

**Issue by WaqarAhmedBajwa** [shopware/shopware#62]
"title": "Constraint violation error",
"detail": "The \"**salutation**\" entity with id \"B3A89CA8-BBEF-4F49-AE07-2C6C993E1766\" does not exists." as  Image describing the error

![Register](https://user-images.githubusercontent.com/10218862/58688871-13fe9180-839f-11e9-8b0c-75aa76164878.png)

**Comment by jenskueper** [comment]
Hey there,

why are your UUIDs uppercase and have "-" in between? Since the "-" have no importance to an UUID, we leave them out. We should add an error during insert.

Best regards,
Jens Küper

**Comment by WaqarAhmedBajwa** [comment]
Made UUID string in **lowercased** and removing **"-"** in UUID string did not resolve this bug as shown in the image
![Register](https://user-images.githubusercontent.com/10218862/58699453-f50bf980-83b6-11e9-8ef0-b666a1bfa729.png)

**Comment by jenskueper** [comment]
Okay. Have you created a new salutation with the id fc13567... before? You must use a valid salutation id in order to create a new customer.

**Comment by WaqarAhmedBajwa** [comment]
I used different UUID in second attempt as above 2 attachments are showing different UUIDs. So that could be avoid from duplication. But error is same every time.

**Comment by keulinho** [comment]
The salutationId is a foreign key and therefore a salutation with the given ID must exist in the system.
Try to get all Salutations from the API with a GET request against `sales-channel-api/v1/salutation` and use an ID from the response.
You have to do the same for the `countryId`.

**Comment by WaqarAhmedBajwa** [comment]
Yes It worked. Thank you @keulinho and @jenskueper
