### ISSUE TITLE
ProductProperty search and create missing

### ISSUE THREAD

**Issue by tinect** [shopware/shopware#621]
**Description**  
I tried to use Repositories to create and search for propertyGroups and PropertyGroupOptions.
While using productProperty-Repo there is no possibility to add a propertyGroupOption with its existing to a product.
I am not entirely involved in this technology, but it looks like Collection and Entity is missing?

**Example**  
Example with search:

> $productPropertyCriteria = new Criteria();
> $productPropertyCriteria->addFilter(new EqualsFilter('optionId', $propertyId));
> $productPropertyCriteria->addFilter(new EqualsFilter('productId', $productId));
> $count = $this->productPropertyRepository->search($productPropertyCriteria, $context)->count(); //crash with status 500, Mapping definition neither have entities nor collection.

**Comment by OliverSkroblin** [comment]
Hi @tinect,

As the error indicates, the `product_property` entity is a mapping definition. This means that it is a definition for a Many To Many mapping table. Such definitions do not have their own repository. 

If you want to create and search property groups and options you can use `property_group.repository` and `property_group_option.repository`

If you would like to have all options of a product you can do the following:

```
$criteria = new Criteria();
$criteria->addFilter(new EqualsFilter('products.id', $productId);
$optionsOfProduct = $this->optionRepository->search($criteria, $context);
```

**Comment by tinect** [comment]
Thank you @OliverSkroblin

**Comment by tinect** [comment]
`optionRepository` is `property_group_option.repository`? Didn't get that running in any way :-(
