### ISSUE TITLE
Custom CMS Block repeater slot

### ISSUE THREAD

**Issue by d3tr1tus** [shopware/shopware#630]
Hi is possible add in custom CMS block repeater slot like for example [here](https://www.advancedcustomfields.com/resources/repeater/)  in ACF for Wordpress? 

I didn't find some solutions 🤔 

Thank you.

**Comment by moorl** [comment]
Would be enough to set multiple slots to a block. Actually the amount of the slots are strictly defined - so i need to set a 5-slots block to create a 5-slides slider.

**Comment by pantrtxp** [comment]
Hi @d3tr1tus 
this is not supported by shopware yet.
if you wish to make a feature request please consider doing this [here](https://issues.shopware.com)

Sunny regards
pantrtxp

**Comment by d3tr1tus** [comment]
@pantrtxp thank you for your response. I hope that in future will somethink like that possible 😊
