### ISSUE TITLE
Not compatible with composer 1.10:  package install and theme.json load not working

### ISSUE THREAD

**Issue by themazim** [shopware/shopware#641]
**Description**  
Requiring plugins/extension and loading themes via composer 1.10 misbehaves heavily.

Seems the theme.json is not correctly loaded and trying to install a custom plugin/theme via composer results in error

```
➜  shopware git:(dev) ✗ composer require mynameisunknown/main-theme:"@dev" --prefer-source

                                                                                       
  [RuntimeException]                                                                   
  The `url` supplied for the path (custom/static-plugins/*) repository does not exist  
```

**Possible Solution**  
I assume the internal logic for loading themes/theme.json in composer 1.10 is no longer compatible and needs to be adjusted.
Also removing repository with path `custom/static-plugins/*` from composer.json fixes the install problem.

As a workaround using composer 1.9 solves the issue.

**Comment by mitelg** [comment]
hey @themazim 
FYI composer has already fixed the repository issue https://github.com/composer/composer/issues/8679
we made a fix for the development template and also checked the production template. but I will re-check your issue tomorrow

**Comment by themazim** [comment]
seems this is not yet shipped with the latest brew (even though it should just download from the source).

However, themes are not loaded correctly. The theme.json is not interpreted as expected. 
Both times just installed with `composer install`

Here is a little example:
theme.json views part:
```
 "views": [
     "@Storefront",
     "@Plugins",
     "@MyTheme"
  ],
```

trying to extend `base.html.twig` like this:

```
{% sw_extends '@parent/storefront/base.html.twig' %}

{% block base_body %}
    this should be the one and only output.
{% endblock %}
```

with composer 1.9:
As expected, whole body is replaced with: `this should be the one and only output.`

with composer 1.10:
Normal Shopware storefront is shown.

**Comment by mitelg** [comment]
your plugin/theme is present in the `custom/static-plugins` directory?

**Comment by themazim** [comment]
no, since it is a normal package. it's present in vendor/distributor/theme-name

**Comment by mitelg** [comment]
composer released a bugfix version. does the problem still exist?

**Comment by themazim** [comment]
Seems this is no longer happening for me.
