### ISSUE TITLE
Multiple deliveries for one order Rest API

### ISSUE THREAD

**Issue by ghost** [shopware/shopware#642]
Hello,

We use the REST-api to process orders and send them to the customer. 
But we have a question about setting a delivery to the state shipped when we sent the order. 

I've made this work by using an internal request: ("/api/v{version}/_action/order_delivery/{orderDeliveryId}/state/{transition}", name="api.action.order.state_machine.order_delivery.transition_state", methods={"POST"})
Because I kept getting the message that an order-delivery stateMachine is write protected in the documented API. 
 
This sets the whole order-delivery to the status shipped. But I was wondering if it is possible that an order has more than one delivery. Because when we import an order, deliveries is an array. 

But from what I've seen until now an order only contains 1 or 0 deliveries. 
So is there an situation that an order has 2 separate deliveries or more?
And do they have separate state machines which can be set to shipped?

**Comment by pantrtxp** [comment]
Hi @rickvdb,

An order can have multiple shipments due to various reasons. 
E.g. when a shop has more than one warehouse.

Sunny regards
pantrtxp

**Comment by ghost** [comment]
Hi @pantrtxp,

If it is possible for an order to have multiple order deliveries handled from different locations and at different times, that raises a question with me: how can we (officially) update the state of an individual order delivery if we only handled one of multiple deliveries (i.e. a partial shipment)? As I said, I found the undocumented '_action/order_delivery/{orderDeliveryId}/state/{transition}' endpoint and that seems to work, but I'm not sure if this is actually supported functionality that's not prone to unannounced API changes.

Regards, 
rickvdb

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
