### ISSUE TITLE
database:create-migration -p Somename should not stopping with: More than one pluginname starting with "%s" was found: %s'

### ISSUE THREAD

**Issue by gotu** [shopware/shopware#644]
**Description**  
When having two plugins called: "Somename" and "SomenameTheme" then you can't generate migrations for the first of this plugins.

**Example**  
When having two plugins called: "Somename" and "SomenameTheme" then trying to:
```
bin/console database:create-migration --plugin=Somename
```
results in:
```
 More than one pluginname starting with "Somename" was found: SomenameTheme\SomenameTheme;Somename\Somename
```
Changing the comparision to strings to be equal instead of comparing the string "prefix" here:
[https://github.com/shopware/platform/blob/fb4bc791e185512bfde8cd0ea462b0cf527cf82f/src/Core/Framework/Migration/Command/CreateMigrationCommand.php#L78](https://github.com/shopware/platform/blob/fb4bc791e185512bfde8cd0ea462b0cf527cf82f/src/Core/Framework/Migration/Command/CreateMigrationCommand.php#L78)
would solve that.

**Comment by shyim** [comment]
Has been fixed with https://github.com/shopware/platform/commit/fcc1c92634282d737f38cb0bfcbd376e9678ff7c
