### ISSUE TITLE
Shopfront Guest Checkout broken

### ISSUE THREAD

**Issue by saschaarthur** [shopware/shopware#651]
Hello,

Currently shopfront has a bug preventing you to register, when you tick "dont create an account".

Heres a patch solving this issue.

Index: Controller/RegisterController.php

```
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- Controller/RegisterController.php	(revision efb43405897a0013c6d7e12c13e131b244acd094)
+++ Controller/RegisterController.php	(revision 2849f8e7b9e13b841ac9b778a76656a0d21e762a)
@@ -230,10 +230,12 @@
             ]));
         }
 
-        if ($this->systemConfigService->get('core.loginRegistration.requirePasswordConfirmation', $context->getSalesChannel()->getId())) {
-            $definition->add('passwordConfirmation', new NotBlank(), new EqualTo([
-                'value' => $data->get('password'),
-            ]));
+        if (!$data->has('guest')) {
+            if ($this->systemConfigService->get('core.loginRegistration.requirePasswordConfirmation', $context->getSalesChannel()->getId())) {
+                $definition->add('passwordConfirmation', new NotBlank(), new EqualTo([
+                    'value' => $data->get('password'),
+                ]));
+            }
         }
 
         return $definition;
```
Cant create a PR, because i dont have permission / its not wanted for this repo(?).

**Comment by mitelg** [comment]
creating a PR should be no problem 🤔 https://github.com/shopware/platform/pulls
never heard about a permission problem 🤔 
the fact that there are more than 50 open PRs should show, that we very well want PRs 😉✌️

**Comment by saschaarthur** [comment]
but the URL is https://github.com/shopware/storefront not this one here.
Edit: But i see also the see the source here, so why is it duplicated/where should the PR be against?
Thought here its a git submodule, but seems just a hard copy?

**Comment by mitelg** [comment]
platform is our mono repository, which contains the source of all modules of the Shopware e-commerce platform. this is split up into several many repositories, like the Storefront. so you have the possibility to only require the components you need. similar to the Symfony framework, which has the same structure.
so if you like to contribute, the platform repo is the right place 🙂👍

**Comment by saschaarthur** [comment]
Push failed: remote: Permission to shopware/platform.git denied to saschaarthur. unable to access 'https://github.com/shopware/platform.git/': The requested URL returned error: 403

I dont care, i close it, done have time for stuff like this.

![grafik](https://user-images.githubusercontent.com/4057921/76960172-34421180-691b-11ea-9dba-e1e589d8fde0.png)

**Comment by mitelg** [comment]
hey @saschaarthur 

of course you are not allowed to push directly to our repository :wink: this is because you are not part of our organisation. 
but that is no problem: all you need is a fork of the repository you want to contribute to. 
Please have a look [here for a detailed guide](https://docs.shopware.com/en/shopware-platform-dev-en/community/contributing-code) on how to contribute code.

we would be sorry to hear, if this prevented you from contributing.
