### ISSUE TITLE
Shopware 6 APP_DEBUG

### ISSUE THREAD

**Issue by saschaarthur** [shopware/shopware#652]
After installing shopware 6 i realized that APP_DEBUG is not set in the .env.

And it seems that in this case Symphony is showing bugs including stacktrace to the customer.
This is really bad and should be disabled on production environments.

I set it on my prod environment to 0, so theres at least nothing showing to the customer...

**Comment by shyim** [comment]
This is normally not needed when you set APP_ENV to prod.
