### ISSUE TITLE
Allow Order / Payment / Delivery State to be changed WITHOUT sending an email

### ISSUE THREAD

**Issue by AlexBachmann** [shopware/shopware#653]
**Description**  
The fact, that in Shopware 6 it's required for an order / delivery / payment state to be connected to an email template is quite annoying. Right now you cannot change the state of an order without sending an email. I can not imagine that this is the desired behaviour of all shop admins that use shopware. Please allow us to change a state without sending an email to the customer.

**Comment by AlexBachmann** [comment]
I'd like to add one more thing. The fact that each order state change triggers an email is highly confusing for the customer. Especially when an order / payment / delivery state is being reopened. 

Image, that the state of an order / payment/ delivery needs to be reopened. In many cases, this state is only an intermediate state, to be able to reach a new state, that was previously unreachable. 

It is absolutely not desirable that the customer get's two emails in this case.

**Comment by shyim** [comment]
Is possible since some minor updates :)
