### ISSUE TITLE
Profiling:Collector:db.html.twig not found

### ISSUE THREAD

**Issue by SC-cmarquardt** [shopware/shopware#66]
Hi,

I installed Shopware 6 locally on a Linux system.
The Symfony Toolbar raises a 500 network error, because the mentioned file Profiling:Collector:db.html.twig (referenced in https://github.com/shopware/platform/blob/master/src/Core/Profiling/DependencyInjection/services.xml#L42) is not found.

When changing the syntax to 
```
<service id="Shopware\Core\Profiling\Doctrine\ConnectionProfiler">
        <tag name="data_collector"
	    template="@Profiling/Collector/db.html.twig"
            id="app.connection_collector"
            priority="200"
        />
</service>
```

as described here https://symfony.com/doc/current/templating.html#referencing-templates-in-a-bundle everything works.

Bug or not? Feature? :-)
Please advise.

Kind regards,
Christopher

**Comment by keulinho** [comment]
That's a bug for sure. 
We have internally already created a PR for that, should be fixed on the master shortly

**Comment by keulinho** [comment]
We have fixed the problem in https://github.com/shopware/platform/commit/30a17009e2a9a233eda32f8c9ed267fe6f07a75b
