### ISSUE TITLE
EntityStore returns empty names for variant products

### ISSUE THREAD

**Issue by runelaenen** [shopware/shopware#660]
**Description**  
In the administration, when using the product-store, it will return empty names for variants that have a linked name. (a.k.a. not overridden by the variant, same name as the parent)

**Possible Solution**  
Add a explicit EntityRepository for product entities which loads the necessary data.

**Additional context**  
Empty option in rule-builder because product store returns emtpy names:
![Screenshot 2020-03-18 at 10 15 00](https://user-images.githubusercontent.com/3930922/76947127-71030e00-6905-11ea-9efa-a0ebed71885d.png)

**Comment by pantrtxp** [comment]
Hi @runelaenen,

This kind of behavior is known to us and will be fixed with the 6.2 release 
https://issues.shopware.com/issues/NEXT-7610 

Sunny regards
Pantrtxp

**Comment by runelaenen** [comment]
Okay thank you. I had looked through the issue tracker but couldn't find the issue yet. Thanks!
