### ISSUE TITLE
filename too long on Windows checkouts

### ISSUE THREAD

**Issue by tiggerduck** [shopware/shopware#665]
**Description**  
On Windows there is always a limitation on the length of the file name.
It would be nice if you could reduce the file names and paths here a little.
Otherwise, no developer is able to use your product under Windows.

`
Cloning into 'C:\workspace\shopware_platform_614'...
POST git-upload-pack (gzip 1025 to 583 bytes)
remote: Enumerating objects: 414, done.
remote: Counting objects: 100% (414/414), done.
remote: Compressing objects: 100% (283/283), done.
remote: Total 301042 (delta 189), reused 310 (delta 119), pack-reused 300628
Receiving objects: 100% (301042/301042), 120.50 MiB | 1.31 MiB/s, done.
Resolving deltas: 100% (218342/218342), done.
error: unable to create file src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-configurator/sw-product-variants-configurator-restrictions/sw-product-variants-configurator-restrictions.html.twig: Filename too long
error: unable to create file src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-configurator/sw-product-variants-configurator-restrictions/sw-product-variants-configurator-restrictions.scss: Filename too long
error: unable to create file src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-configurator/sw-product-variants-configurator-selection/sw-product-variants-configurator-selection.html.twig: Filename too long
Updating files: 100% (7924/7924), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
error: unable to create file src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-configurator/sw-product-variants-configurator-restrictions/sw-product-variants-configurator-restrictions.html.twig: Filename too long
error: unable to create file src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-configurator/sw-product-variants-configurator-restrictions/sw-product-variants-configurator-restrictions.scss: Filename too long
error: unable to create file src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-configurator/sw-product-variants-configurator-selection/sw-product-variants-configurator-selection.html.twig: Filename too long
Updating files: 100% (7924/7924), done.
`

**Possible Solution**  
Reduce filenames and paths

**Comment by tinect** [comment]
Hey @tiggerdruck.
Additionally, there isn't any part of support for windows, iirc :-)
Suggest using virtual machine with Linux which works great.

**Comment by tiggerduck** [comment]
Hi @tinect 
and you have your IDE (e.g. PHPStorm) inside the virtual machine?
At least I have the IDE under Windows and I can no longer work with the Shopware 6.1.4 sources. 

IST:
src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-configurator/sw-product-variants-configurator-selection/sw-product-variants-configurator-selection.html.twig

SOLL:
src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-configurator/selection/selection.html.twig

**Comment by tinect** [comment]
Yes, I'm working inside the vm.
Didn't try that, but maybe it works for you: https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/

**Comment by pantrtxp** [comment]
Hi @tiggerduck,

as @tinect already stated, we do not support windows at this moment.
I cant tell you if or when we will. We suggest using a virtual machine.
We have a Doc for this [here](https://docs.shopware.com/en/shopware-platform-dev-en/getting-started/system-installation-guides/vagrant)

Sunny regards
Pantrtxp

**Comment by tiggerduck** [comment]
The recommend solution is to sync my code inside the VM-Box as described in the documentaiton: https://docs.shopware.com/en/shopware-platform-dev-en/getting-started/system-installation-guides/vagrant?category=shopware-platform-dev-en/getting-started/system-installation-guides


> Because of technical reasons, the vagrant machine acts like a remote web server, so with this setup, you'll develop your code on your PC and then upload/synchronize it to the vagrant machine.


I follow these instructions to use version 6.1.0 in projects and with 6.1.4 that shouldn't work anymore, really?

**Comment by pantrtxp** [comment]
@tiggerduck can you tell me where it is stated, that it won't work with 6.1.4 anymore? 
I am not aware of this being done. Have you maybe configured something wrong? 

Sunny regards
Pantrtxp
