### ISSUE TITLE
Making new inputs to register form less pain

### ISSUE THREAD

**Issue by JoshuaBehrens** [shopware/shopware#666]
**Description**  
Client requests a certain field in the register form. Twiggedy twig 🍃 and its there. But how can one easily read and apply it server side? There is the AccountRegistrationService that has a method that has everything one need for it `register(DataBag $data, bool $isGuest, SalesChannelContext $context, ?DataValidationDefinition $additionalValidationDefinitions = null): string` but it is not part of an interface. Yikes, so it is hard to decorate it properly and make use of its return value and the newly added parameter in the databag. There is also the `CustomerRegisterEvent` that is triggered on registration or after a double-optin has been confirmed. Due to the double-optin delay there is no databag present in the event. And it is not always triggered immediately when the customer registers and it is a double-optin process.

How can I solve it more easily? Just add some interfaces and PR it? Store databag and put it to event later as well?

**Comment by JoshuaBehrens** [comment]
It gets even worse. I have an additional field for the addresses. It has to be validated in context of an other field. As in your validation builders don't have the context I can't put a constraint on a field and compare it against an other. So I have to put the constraint on the outer collection (the address). Now I have the whole data and can compare different fields but every violation I build for the address is forced to be at the specific address object by https://github.com/shopware/platform/blob/87fc9e8cf4cdab0650e0caaf9a8ba12bab2902c2/src/Core/Framework/Validation/DataValidator.php#L54-L65 to be on the address data although I choose a different path on violation building.

**Comment by JoshuaBehrens** [comment]
This customer validator is not working for saving address when a logged in customer changes their address as the customer is not validated. A bad workaround so far :/

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
