### ISSUE TITLE
Custom Admin page tutorial/documentation

### ISSUE THREAD

**Issue by vttn** [shopware/shopware#668]
**Description**  
We would like to port our shopware 5 app to shopware 6. The challenge we are facing is customizing the admin setting area for our plugins. We would like to register webhooks

**Example**  
A good example is the SwagPayPal bundle that has a custom admin settings page. Can we have a generic tutorial/documentation that explains what is going on?

**Comment by shyim** [comment]
We have a docs page about that https://developer.shopware.com/docs/guides/plugins/apps/administration/add-custom-modules
