### ISSUE TITLE
npm build: permission denied mkdir

### ISSUE THREAD

**Issue by ghost** [shopware/shopware#67]
I tried to install shopware6 in Docker. When running the install script (./psh.phar install) I always get an authorization error with npm install:

 Error: EACCES: permission denied, mkdir '/app/vendor/shopware/platform/src/Administration/Resources/administration/node_modules/node-sass/.node-gyp'

**Comment by somakolli** [comment]
I have the same error. How did you fix this?

Edit: I fixed it with `chown -R root:root platform`.
