### ISSUE TITLE
Allow us to login a specific CustomerEntity

### ISSUE THREAD

**Issue by AlexBachmann** [shopware/shopware#675]
**Description**  
Right now the Shopware\Core\Checkout\Customer\SalesChannel\AccountService gives us two options to login customers.

```php
public function login(string $email, SalesChannelContext $context, bool $includeGuest = false): string
```
and 
```php
public function loginWithPassword(DataBag $data, SalesChannelContext $context): string
```
It would be very beneficial to add a new, third option, that allows us, to login a specific CustomerEntity:
```php
public function loginCustomer(CustomerEntity $customer, SalesChannelContext $context): string
```
**Benefits**
There are two main reasons, that come to my mind:

1.  Remove code duplication. The first two options pretty much do the same. Retrieve a CustomerEntity and trigger the login process for this CustomerEntity. Extracting the second part into its own **public** method, could reduce code duplication, but also help us avoid missing logic in one of the two processes. See https://github.com/shopware/platform/issues/676
2. Furthermore, a developer might need to be able to login one specific customer, without knowing the password. Using the email address of the customer alone is not sufficient, since one user might have multiple customer accounts with the same email address (using guest accounts). One Use-Case for this scenario might be, that a plugin developer might want to login a customer of a specific order. It is essential that the correct customer entity is logged in, so the user can see the particular order in the order history of his account, once he has been logged in.

**Comment by shyim** [comment]
Resolved with https://github.com/shopware/platform/commit/4b5bf12f03c4165344356ca083e42913e8b22a2e
