### ISSUE TITLE
Resolve differences between login() and loginWithPassword() methods of AccountService

### ISSUE THREAD

**Issue by AlexBachmann** [shopware/shopware#676]
**Description**  
There are differences between the login() method and the loginWithPassword() method, that are either erroneous or at least not obviously explained.

For example, it's not obvious, why within the login() method, there is no check, whether the retrieved customer is active or not (actually whether or not to only include active customers should probably be a parameter). This actually probably constitutes a **security** problem, since using the login() method, the developer could unconsciously login deactivated customers, without even knowing it.

What's missing is a check, like we find it in the loginWithPassword() method:
```php
if (!$customer->getActive()) {
    throw new InactiveCustomerException($customer->getId());
}
```
Furthermore, there is no obvious reason, why the login() method does not update the last login date of the customer entity.
```php
$this->customerRepository->update([
            [
                'id' => $customer->getId(),
                'lastLogin' => new \DateTimeImmutable(),
            ],
], $context->getContext());
```

**Possible Solution**  
There are several ways to approach this problem:

1. Consider consolidating the login logic of a CustomerEntity to its own method (please make this method public) See: https://github.com/shopware/platform/issues/675
2. Consider only returning **active** customers by the getCustomerByEmail() method. Maybe make the method configurable via parameters.
3. If the differences between these methods are done so willingly, please make them more obvious for developers who use this API, by updating the docs.

**Comment by shyim** [comment]
The class contains now only a Code for programmatic login in a customer. The customer-relevant parts are moved into the store-api
