### ISSUE TITLE
missing QuantityFrom and QuantityTo in CalculatedPrice

### ISSUE THREAD

**Issue by tinect** [shopware/shopware#682]
**Description**  
We cannot see a logical behaviour in CalculatedPrice. There is just `quantity` which stays for QuantityFrom or QuantityTo. You only can know which one it is, if the last one in the list.

**Possible Solution**  
Add equivalent QuantityFrom AND QuantityTo to storefront.

**Additional context**  
So, everyone can change in storefront the `From, From, From, From, To` to something consistently, like `To, To, To, To, To`

**Comment by OliverSkroblin** [comment]
Hi @tinect,

a `CalculatedPrice` has nothing to do with the scaled prices of products. The `CalculatedPrice` has a quantity, i.e. it is a price that was calculated on the basis of a quantity.
