### ISSUE TITLE
Can't send example email in administration

### ISSUE THREAD

**Issue by JoshuaBehrens** [shopware/shopware#683]
**Description**  
I open up an email template to send an example email. On sending a message pops up that I have to select a sales channel. I do and retry. Still not working.

**Possible Solution**  
I think there is wrong parameter passed into the email sending method that should be the sales channel but it is not.

**Additional context**  
![cannot-send-demo-email](https://user-images.githubusercontent.com/1133593/77326026-73a49f80-6d19-11ea-9620-d0fc48805eab.gif)

**Comment by pantrtxp** [comment]
Hi @JoshuaBehrens 
This is a little confusing, but you have to hit "save" before you are able to test this. 
There is no live-saving in our modules. 
Select Sales Channel -> Click save -> send test mail -> works

**Comment by JoshuaBehrens** [comment]
Thanks for clearing up 👍 

Do I get it right, that there are no mails automatically added to a sales channel? I have to enable them for every sales channel first? But mails are working without assignment 💭

**Comment by shyim** [comment]
Solved already 
![image](https://user-images.githubusercontent.com/6224096/106258445-1e30fd00-621e-11eb-88c8-5c9a5b2692ed.png)

**Comment by JoshuaBehrens** [comment]
Woohoo
