### ISSUE TITLE
Elasticsearch deep paging

### ISSUE THREAD

**Issue by htuscher** [shopware/shopware#687]
**Description**  
When building remote system integrations, it's often necessary to compare the entire product data. What you do, you iterate over all articles of Shopware via API, compare them locally and then issue create/update/delete accordingly.
If you have many articles (> 10k), you're gonna run into an issue with elasticsearch. The default limit for the result window is 10000. It's not possible to use regular pagination deeper than that (for good reasons).

In elasticsearch there are 2 ways around this:
* Search After (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html#request-body-search-search-after)
* Scroll (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html#request-body-search-scroll)

It's really necessary that both of this features are implemented in the elasticsearch integration to have the possibility to build efficient integrations with a large number of products.

**Comment by htuscher** [comment]
https://issues.shopware.com/issues/NEXT-7819

**Comment by mitelg** [comment]
hey @hhoechtl 
thanks for raising this up. as you already opened a ticket on our issue tracker, I will close this here, to avoid duplication
