### ISSUE TITLE
Can't update to new version

### ISSUE THREAD

**Issue by d3tr1tus** [shopware/shopware#688]
Hi i want update my Shopware to 6.1.4 but all the time i get just this error 

![Bildschirmfoto 2020-03-24 um 14 03 15](https://user-images.githubusercontent.com/37714206/77429219-98f8e280-6dd9-11ea-9f6f-72bf68b8ba76.png)

and after that my whole site not working

![Bildschirmfoto 2020-03-24 um 14 08 07](https://user-images.githubusercontent.com/37714206/77429349-d2c9e900-6dd9-11ea-901b-ffc09292054b.png)

Do you have any solution for me please?

**Comment by pantrtxp** [comment]
Hi @d3tr1tus ,
Maybe you can get some help [here](https://docs.shopware.com/de/shopware-6-de/update-guides/shopware-aktualisieren-updaten).
If this does not help try to update manually.

Sunny regards
Pantrtxp

**Comment by d3tr1tus** [comment]
Hi @pantrtxp 
yes that was useful thank you! I am using .htaccess for rewrite `public` directory but in this situation i had to use complete path with public. 😊
