### ISSUE TITLE
Admin Backend: Storefront and Headless form breaks with specific input

### ISSUE THREAD

**Issue by masonen** [shopware/shopware#69]
Hi, 

I found a bug in Admin Backend where the form input for payment methods breaks after an specific input.

Steps to reproduce: 
* Open Storefront or Headless configuration
* Remove all payment methods from list
* Hit save button
* An Error message apears
* Add at least one Payment Method
* Hit save button

After Performing those steps you are not able to choose a standart payment method. Trying so results in an JS error 
[shopware.local-1559910171237.log](https://github.com/shopware/platform/files/3265835/shopware.local-1559910171237.log)

This also aplies to other form fields. (but not always?). I managed to break all fields right now. Some fields seemed not to be breakable at first, but broke after i broke the following fields.

**Comment by SebastianFranze** [comment]
Thanks for reporting this issue to us. It seems like this is an issue with updating the correct default values when changing the available ones (especially deleting the selected default). We already created an ticket for this an will keep you up to date with the process.

**Comment by SebastianFranze** [comment]
Sorry for the late answer. We did not forget your issue. You can track progress att

https://issues.shopware.com/issues/NEXT-3650
