### ISSUE TITLE
Theme.json asset property seems not work

### ISSUE THREAD

**Issue by JoshuaBehrens** [shopware/shopware#698]
**Description**  
I set the asset property in the theme.json to something else than public. Still only Resources/public is copied to public/bundles. Is this intended?

Code from https://github.com/shopware/platform/issues/357 suggests it would be working.

**Possible Solution**  
Do not depend on symfony assets, maybe? Not a good way but maybe a way

**Comment by shyim** [comment]
Is fixed with https://github.com/shopware/platform/commit/031b2650416a961f01533dfdb818b6bb5e97e6fd
