### ISSUE TITLE
Email templates default date format customization

### ISSUE THREAD

**Issue by bystro** [shopware/shopware#704]
**Description**  
As a StringTemplateRenderer creates a new private `Twig\Environment` default instance https://github.com/shopware/platform/blob/master/src/Core/Framework/Adapter/Twig/StringTemplateRenderer.php#L21 the CoreExtension configuration seems to be impossible.

So we can not set default date format in email templates so that we could for example send tags like {{ order.orderDateTime|date }} as 21. März 2020 instead of the default `F j, Y H:i`.

We can not use:
- framework config
- `$twig->getExtension(CoreExtension::class)>setDateFormat()`
- `StringTemplateRenderer` decoration due to condition https://github.com/shopware/platform/blob/master/src/Core/Framework/Adapter/Twig/StringTemplateRenderer.php#L26

**Comment by shyim** [comment]
It's currently in code-review internally and will be fixed soon https://issues.shopware.com/issues/NEXT-10126
