### ISSUE TITLE
Overwriting theme wierd behaviour 

### ISSUE THREAD

**Issue by TaiKamilla** [shopware/shopware#707]
There is some weird behavior when overwriting theme files...

Example:
`platform/src/Storefront/Resources/views/storefront/page/content/index.html.twig`
 by this one
`custom/plugins/MyTheme/src/Resources/views/storefront/page/content/index.html.twig`
The Symfony Profiler will return `@Storefront` first, instead of `@MyTheme`

![image](https://user-images.githubusercontent.com/15035750/77927891-09a37180-72a8-11ea-8216-e7bd7893dde0.png)

**Comment by OliverSkroblin** [comment]
Does inheritance work for you? So the changes in your index.html.twig are working?

If so, it might be because of our implementation of sw_extend and sw_include which the profiler can't handle.

**Comment by TaiKamilla** [comment]
No, inheritance does not work

I already guessed that was because of sw_extend and sw_include
On the meantime until this is solved (https://github.com/shopware/platform/issues/614 I open that issue)
I did modified `platform/src/Storefront/Resources/views/storefront/page/content/index.html.twig`
with `{% sw_extends '@MyTheme/storefront/page/content/index.html.twig' %}`
I know that is not the way to go but I needed to move forward

Why is this (https://issues.shopware.com/issues/NEXT-7517) mark as "Priority Minor"??

There is a lot of issues with this sw_extend and sw_include
50% of my includes does not work with sw_extend and sw_include, or have weird behavior (like cart multiplying products every time something is added to the cart)
I had to extend and overwrite functions in a few controllers (like NavigationController, CheckoutController, AuthController) to replace `@Storefront` with `@MyTheme` because it loads `@Storefront` instead `@MyTheme`
But it will crash if SW updates those

I hope that this (https://issues.shopware.com/issues/NEXT-7517) is fixed soon cos is not cool to leave hacks everywhere

**Comment by shyim** [comment]
We have fixed the inheritance of themes in 6.4. See also the linked issue.
