### ISSUE TITLE
Error on "Update profile information" through API

### ISSUE THREAD

**Issue by WaqarAhmedBajwa** [shopware/shopware#71]
I have same error **No route found for "PUT /sales-channel-api/v1/customer/profile"** on  **PUT** request to **update customer profile**
Error1:
![ProfileError](https://user-images.githubusercontent.com/10218862/59197896-e0e0ad00-8bab-11e9-8b7b-c48da8cbf7ff.png)

and **No route found for \"POST /sales-channel-api/v1/customer/default-billing-address/c0f27908d47843f09b4bb31ba2baf0cd** on **POST** request to set billing address as a default.
Error2:
![default-billing](https://user-images.githubusercontent.com/10218862/59197934-f655d700-8bab-11e9-9183-af7574ebcfcd.png)

**Comment by keulinho** [comment]
I guess you are referring to the api routes described in the [Docs](https://docs.shopware.com/en/shopware-platform-dev-en/api/sales-channel-customer-api?category=shopware-platform-dev-en/api).
Unfortunately the document is not up to date, as we have changed the routes, we will update the documentation shortly.
To update the customer profile you can simply do a `PATCH` request against `/sales-channel-api/v1/customer` with the same Payload as before.
To mark an adress as the default billing address do another `PATCH` against `/sales-channel-api/v1/customer/address/{id}/default-billing` with an empty body.
