### ISSUE TITLE
Translated category text is not saved

### ISSUE THREAD

**Issue by themazim** [shopware/shopware#710]
**Description**  
changing translated category text is not saved.

Unfortunately no error logs and no issues within request response.

**Possible Solution**  
might be a logic flaw, no idea unfortunately.

**Comment by pantrtxp** [comment]
Hi @themazim 

please update to the latest version since the error can not be reproduced here. 
We can not reproduce this issue in the 6.1.4 or the current master branch.

Sunny regards
Pantrtxp

**Comment by themazim** [comment]
Sorry, did not open the side menu, where it would have stated: 6.1.4

![image](https://user-images.githubusercontent.com/2002126/78116350-6f0c7500-7404-11ea-9e13-8a5c255287c5.png)

(desperately waiting for 6.1.5 though, since the constant logouts are really annoying.)

**Comment by shyim** [comment]
Can't reproduce it on master
