### ISSUE TITLE
STORAGE_DATE_TIME_FORMAT can not be used to parse a datetime in PHP 7.2

### ISSUE THREAD

**Issue by JoshuaBehrens** [shopware/shopware#715]
**Description**  
Every date that is stored in the database is formated using `Defaults::STORAGE_DATE_TIME_FORMAT`. This is super nice to have a constant for this. It is also cool to be able to parse dates from it. Unfortunately php 7.2 can't do that:

```
<?php

const FORMAT = 'Y-m-d H:i:s.v';

var_dump(
    date_create()->format(FORMAT)
);
var_dump(
    date_create_from_format(
        FORMAT,
        date_create()->format(FORMAT)
    )
);
```

Output on php 7.2:
```
string(23) "2020-04-01 11:22:57.717"
false
```

Output on php 7.3:
```
string(23) "2020-04-01 11:22:57.717"
object(DateTime)#1 (3) {
  ["date"]=>
  string(26) "2020-04-01 11:22:57.718000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(10) "US/Pacific"
}
```

But why is this not an exception yet? Because `Shopware\Core\Framework\DataAbstractionLayer\FieldSerializer::decode` doesn't use it to decode it. So there is a format that is used to format but not to parse? That is super weird, don't you think so?

**Possible Solutions**  
* Bump required php version to 7.3
* Use different format
* Ignore this issue (no BC compared to the others)

**Additional information**
Fun fact. When you replace `v` in the format with `u` php 7.2 can parse it.
You can try that out online at [sandbox.onlinephpfunctions.com](http://sandbox.onlinephpfunctions.com/code/144f5e1ea53b6fbe1eb1539fb5e69042198c6950)

**Comment by mitelg** [comment]
does this problem also occur if you are using the date object? recently we replaced all occurrences of the date functions in the migrations with date objects, because the functions do not use milliseconds. so my point is, if there is no problem with the date objects, we should encourage people to use them instead 🙂

**Comment by JoshuaBehrens** [comment]
Wait. You wan't to tell me the objects behave differently than the old school functions 😲 
I just tested with sandbox.onlinephpfunctions.com seems not to be the case 😕  (I just replaced `date_create` with `DateTime::__construct` and `date_create_from_format` with `DateTime::createFromFormat`)

**Comment by mitelg** [comment]
have a look here https://3v4l.org/406RR

note that the milliseconds for the functions are **_always_** `000`
this is not the case for the date objects :wink:

**Comment by JoshuaBehrens** [comment]
In your 3v4l you are comparing `date` against `DateTime::format`. I instead compare `date_create`/`DateTime::__construct` to `date_create_from_format`/`DateTime::createFromFormat`.

But your hint that `date` is behaving differently is quite a catch. I will take that down into my virtual notes.
![grafik](https://user-images.githubusercontent.com/1133593/78242254-f5e34f80-74e1-11ea-802f-f7b6cb9e331f.png)

**Comment by shyim** [comment]
Its not relevant anymore. We will bump up the min to 7.4

**Comment by JoshuaBehrens** [comment]
Bump up the jam, bump it up 🎵
