### ISSUE TITLE
Shipping & Payment method translation have no default in emails

### ISSUE THREAD

**Issue by runelaenen** [shopware/shopware#718]
**Description**  
When sending (for example) an order confirmation e-mail, the Shipping and Payment methods are not shown if they don't have language-specific translations.
For example, shipping method name:
Dutch (Default Language): Verzendmethode X
French (Second Language): Not filled in, thus fall back on Dutch

The French e-mail will actually show an empty string, instead of falling back to the Dutch default translation.
This happens with both shipping and payment methods.

**Possible Solution**  

**Additional context**  
Example where the French version has 1 item translated for it's own:
Dutch:
![Screenshot 2020-04-02 at 11 16 04](https://user-images.githubusercontent.com/3930922/78231695-7ea6bf00-74d3-11ea-994a-23e344f23b37.png)

French:
![Screenshot 2020-04-02 at 11 15 58](https://user-images.githubusercontent.com/3930922/78231691-7d759200-74d3-11ea-85d1-412c44745cbc.png)

**Comment by shyim** [comment]
This has been fixed in the meanwhile. When it still occurs at your installation, use the translated.name always instead of .name
