### ISSUE TITLE
order.transactions.first.paymentMethod is NULL in mail Enter payment state: Reminded

### ISSUE THREAD

**Issue by kurtwithslc** [shopware/shopware#723]
**Description**  
i like to use the actual payment Method in the reminder mail, but variable order.transactions.first.paymentMethod is NULL in this template

Error is like this: Impossible to access an attribute ("name") on a null variable in "735a738a0d0bd23c3f8477aae93e2129" at line 4

line4: {% if order.transactions.first.paymentMethod.name == "Vorauszahlung" %}

**Comment by shyim** [comment]
We changed a lot in the meanwhile. Please check again
