### ISSUE TITLE
When installing, "Critical environment variable DATABASE_URL missing" thrown

### ISSUE THREAD

**Issue by hucario** [shopware/shopware#724]
**Description**  

When freshly installing Shopware 6, during database import at step 154/436, it pops an error about a missing environment variable.
This is odd, as I've tried several solutions to this problem:
I went into vendor/shopware/core/Kernel.php and added both 
```php
$_ENV['DATABASE_URL'] = "root@localhost:3306" 
```
and
```php
putenv("DATABASE_URL='root@localhost:3306'");
```
, as well as changing 
```php
            $url = $_ENV['DATABASE_URL']
                ?? $_SERVER['DATABASE_URL']
                ?? getenv('DATABASE_URL');
```
to read 
```
            $url = "root@localhost:3306"
            	?? $_ENV['DATABASE_URL']
                ?? $_SERVER['DATABASE_URL']
                ?? getenv('DATABASE_URL');
```
.
In vendor/shopware/recovery/install/index.php I've also inserted on the second line 
```php
$_ENV['DATABASE_URL'] = "root@localhost:3306";
```

**Additional context**  
The error thrown:
"Critical environment variable 'DATABASE_URL' missing!\n"
This provides no stack trace, I'm sorry.

The options I've provided to the installer:
Server: localhost
User: root (this may be a security vulnerability, but this is a test shop that can't be accessed outside of localhost so I'm not too worried about it)
Database name: shopware6

Shopware6 database is freshly created; the mysql credentials work.

I'm very new to PHP and shopware in general, so I'm sorry if I'm wasting your time with stupid noobish mistakes - I've searched for solutions but can't find any.

**Comment by shyim** [comment]
This issue seems very old. Check your PHP session settings and try it with an newer release
