### ISSUE TITLE
Translation Api-Endpoints are broken

### ISSUE THREAD

**Issue by ascheider** [shopware/shopware#73]
Currently all translation endpoints are broken.
Example: http://192.168.33.10/api/v1/product/022ac8c837714abdb964dc629ce4f5f5/translations or http://192.168.33.10/api/v1/product-manufacturer/01f4b5bf9fef4561b8a9ce3906472136/translations
The error message is: Column not found: 1054 Unknown column 'product_manufacturer_translation.id' in 'field list'
![grafik](https://user-images.githubusercontent.com/6016485/59330397-a5e89180-8cf1-11e9-8912-a8c2510ef5bb.png)

Since translation tables don't need id column it is DAL issue.
See related pull request: https://github.com/shopware/platform/pull/72

**Comment by keulinho** [comment]
We will be looking into this issue.
You are right, this is an issue regarding the DAL.

**Comment by OliverSkroblin** [comment]
Hey @ascheider,
i created a ticket and I'll take a look.

**Comment by ascheider** [comment]
@OliverSkroblin Hey Oliver, any updates on this issue?

**Comment by mitelg** [comment]
@ascheider is this the same issue as here? https://issues.shopware.com/issues/NEXT-3822

**Comment by ascheider** [comment]
@mitelg yes. it seems, currently all translation endpoints are broken no matter which endpoints are used. All translation tables have no column id which is correct.
So i guess it is DAL issue. I guess if you can solve the bug for the single endpoint, it will works for all of them.

**Comment by mitelg** [comment]
ok, then I will close the issue here and you can give the existing ticket an upvote, ok?

**Comment by ascheider** [comment]
@mitelg okay. i will give upvote to the existing ticket. I hope it will be fixed soon...
