### ISSUE TITLE
Queue status in administration

### ISSUE THREAD

**Issue by htuscher** [shopware/shopware#736]
**Description**  
If you have a large shop running with a lot of modifications, it's possible that you may run into problems with workers.

This is a necessary information for the shop administrator and should be visible in the administration interface.

Professional setups might use Grafana, but some basic stuff in the administration would be great.

**Example**  

Something like the Ruby Sidekiq Dashboard would be great.

**Comment by shyim** [comment]
Since 6.2.0 you can see the indexing status in the administration notification.
