### ISSUE TITLE
Outdated files in shopware/core release packages - missing NEXT-5398 feature

### ISSUE THREAD

**Issue by patpilus** [shopware/shopware#738]
**Description**  

It seems that at least [NEXT-5398](https://issues.shopware.com/issues/NEXT-5398) feature was never released (neither in 6.1.1 as stated in https://www.shopware.com/en/changelog/ nor the newest 6.1.5).

For example, as you can see `MigrationCollectionLoader` was updated 5 months ago:
https://github.com/shopware/core/blame/master/Framework/Migration/MigrationCollectionLoader.php#L26. 

Unfortunately none of `shopware/core` [release packages](https://github.com/shopware/core/releases) from 6.1.1 to 6.1.5 contains updated code.

Lack of this feature prevents Shopware Storefront migrations from being executed with `bin/console database:migrate --all` command.

Please reflect NEXT-5398 in the newest release and verify whether all features from the changelog are indeed released.

**Comment by shyim** [comment]
Hey,
is this still valid?
