### ISSUE TITLE
Elasticsearch not able to find products by tags / description.

### ISSUE THREAD

**Issue by themazim** [shopware/shopware#740]
**Description**  
using elasticsearch as search engine with the provided elasticsearch package, customers are not able to find products by description nor tags. Seems only the meta description is used as searchable field.

**Possible Solution**  
add all product information to searchable field (fulltext?) or search through and add tag / description fields into ES.

**Comment by shyim** [comment]
Hey,

we have refactored Elasticsearch on Shopware 6.4. Can you check it there too?

**Comment by themazim** [comment]
@shyim Thanks for refactoring. I abandoned shopware a long time ago in favor of shopify due to the countless issues. so unfortunately I am not going to check this. sorry.
