### ISSUE TITLE
cache not fully cleared on bin/console cache:clear

### ISSUE THREAD

**Issue by themazim** [shopware/shopware#741]
**Description**  
Clearing the cache with `bin/console clear:cache` does not fully clear cache folder, instead artifacts are left behind and pile up.
Seems the folder is being written while executing the cache:clear, thus leading to an issue while deleting and stopping the delete process. 

**Possible Solution**  
instead of allowing writes in the currently used cache folder, disable the use of said folder, create a new cache folder and direct new writes into that folder and afterwards delete the old cache folder.

**Comment by shyim** [comment]
That's symfony default behavior. It clears by default only container cache and warmups caches. If you want to delete the object cache too just run

```
./bin/console cache:pool:clear cache.object
```

**Comment by themazim** [comment]
Thanks  for the answer ~2 years and 3 months later. Already moved on to shopify - shopware was just not longer bearable.
