### ISSUE TITLE
NavigationController Cache - add state: has-flash

### ISSUE THREAD

**Issue by moorl** [shopware/shopware#743]
https://github.com/shopware/platform/blob/d48df92eeecf7cef5ba48869a4bf01b7d03243b3/src/Storefront/Controller/NavigationController.php#L38

Use case:
I want to add a flash message and redirect to a specific CMS page.

```
$this->addFlash('error', 'Some error.');
return $this->redirectToRoute('frontend.navigation.page', ['navigationId'=>'b33a7224601b4bbe95f98a5fd19fe60a']);
```

Result:
My flash message is not shown - it is just shown later on a other page

**Comment by shyim** [comment]
Use ajax to show it, or redirect to another page to show it.
