### ISSUE TITLE
Edited orders are not saved.

### ISSUE THREAD

**Issue by themazim** [shopware/shopware#747]
**Description**  
Edited orders (added a product) are not stored. Orders still have the previous products, but not the newly added product. no error on store.

**Comment by SkaveRat** [comment]
I just has the same problem. The solution was: waiting. It took several seconds for the order detail page to refresh and display the added item.
The missing feedback is not really great, though

**Comment by themazim** [comment]
thanks for the info. I just tried this, unfortunately this did not fix the issue, even after waiting 10 minutes, still not stored.

**Comment by shyim** [comment]
We have fixed lot of issues in Admin Ordners meanwhile. Feel free to create a new issue if it still exists
