### ISSUE TITLE
Getting errors when using console in docker volume

### ISSUE THREAD

**Issue by kabengwa** [shopware/shopware#751]
**Description**  

I get an error about database connection when i run `php bin/console cache:clear` in the volume folder. I have setup a docker environment behind a reverse proxy and used webdevops/php-apache-dev:ubuntu-18.04 to create a container in which i downloaded shopware 6 and succesfully set up a shop. However when i try to clear cache by heading to the volume directory i setup and executing `php bin/console cache:clear` i get an error that i put below. What am i ding wrong and how can i solve it.

**Possible Solution**  

I think the system is failing to connect to the right mysql container when i access it through the console

**Additional context**  

This is the error i get
```
In AbstractMySQLDriver.php line 93:

  An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known


In PDOConnection.php line 31:

  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known


In PDOConnection.php line 27:

  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known


In PDOConnection.php line 27:

  PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known
```

The .env file mysql setup looks like this. where label_db_test is the mysql container name.

> DATABASE_URL=mysql://root:mypass@db_test:3306/label_db_test

Any help is welcome.

**Comment by shyim** [comment]
You need to be in docker container. Outside is the database not accessible
