### ISSUE TITLE
Enable Frontend Webpack to process vue files and components

### ISSUE THREAD

**Issue by oriske** [shopware/shopware#766]
**Description**  
As we aere intensivly using vue.js for building frontend themes and plugins it would be nice if the Shopware webpack for the frontend would compile also vue files and components.

Actually we have to do a weired hack and workaround to get this working by building our onw webpack with laravel plugin in every theme and plugin and include the resulting js files as additional files (not by main.js)

**Comment by shyim** [comment]
Storefront webpack and admin can be extended by extensions. We will only add the required loaders https://developer.shopware.com/docs/guides/plugins/plugins/administration/extending-webpack?q=webpack
