### ISSUE TITLE
Link fields in administration

### ISSUE THREAD

**Issue by htuscher** [shopware/shopware#767]
**Description**  
Currently it's only possible to have a full URL in the administration on CMS elements.
No matter if you choose the link-to property of an image or create an inline link in the content.

There should be a way to select a category as link destination so that SEO urls are used properly (in case somebody changes them).

**Example**  

![image](https://user-images.githubusercontent.com/5076356/79966913-67ce0980-848e-11ea-967c-20b7de481924.png)

![image](https://user-images.githubusercontent.com/5076356/79966926-6ef51780-848e-11ea-8ccd-92f29de1519a.png)

**Comment by bnussbau** [comment]
i don't get why this isn't getting more attention. See https://github.com/shopware/platform/issues/304#issuecomment-557523170 for a "developer"-friendly solution. But for content managers this is really a problem.

**Comment by AndreasA** [comment]
The same is an issue for products etc.

It would already help if one could do something like this:
- product://<id>
- etc.

Of course, even better would be to provide an option to link to records directly using the admin interface / search.

**Comment by AndreasA** [comment]
It should also be possible to link to symfony routes nicely. Doesn't need to be all but some like cart, login etc. would be great.

**Comment by AndreasA** [comment]
It would also be good to support this for other non RTE fields like e.g. the external URL field in the category admin as maybe I want to link directly to the user registration or a product from menu entries - especially as this might be usable in other custom entities or CMS blocks then.

**Comment by shyim** [comment]
Solved in newer versions
