### ISSUE TITLE
Missing Expose Headers (CORS)

### ISSUE THREAD

**Issue by juliankoehn** [shopware/shopware#771]
The Sales-Channel API is not exposing Headers
e.g.
`sales-channel-api/v1/customer/login` is allowing the following headers
```
Access-Control-Allow-Headers: Content-Type,Authorization,sw-context-token,sw-access-key,sw-language-id,sw-version-id
```

And sending:
```
sw-context-token: vj3kqfMOVVgfUzuj7QhAacYEtFUku0Ma
sw-language-id: 
sw-version-id: 
```

**Possible Solution** 

They have to be exposed see: 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers

**Comment by juliankoehn** [comment]
Looks like they could just be extended here:

https://github.com/shopware/platform/blob/master/src/Core/Framework/Api/EventListener/CorsListener.php

```php
$response = $event->getResponse();
        $response->headers->set('Access-Control-Allow-Origin', '*');
        $response->headers->set('Access-Control-Allow-Methods', 'GET,POST,PUT,PATCH,DELETE');
        $response->headers->set('Access-Control-Allow-Headers', implode(',', $corsHeaders));
```

**Comment by shyim** [comment]
Fixed with
https://github.com/shopware/platform/commit/dda51100399dff704021700b1ce039b029cab968 and
https://github.com/shopware/platform/commit/04c93396a1fc49716fe024f033fbe0ced2296a47
