### ISSUE TITLE
[BUG] Set called on FrozenParameterBag and other issues when calling CLI debug:config

### ISSUE THREAD

**Issue by AndreasA** [shopware/shopware#784]
If you set APP_DEBUG=0 (or environment to  `prod` and not set it at all).
And call e.g. 
`bin/console debug:config twig` it results in 

```
In FrozenParameterBag.php line 58:
                                                      
  Impossible to call set() on a frozen ParameterBag.                                                
```

The reason is that in the Framework Bundle PHP file you are doing way too much, e.g. setParameter for locale. However, even without this call it would still result in another error:
`Cannot load from an extension on a compiled container.`

**Possible Solution**  

- Usually in Symfony bundles the Bundle file itself is very slim, all `setParameter` or `load` calls are done in the `Extension` class or in a CompilerPass but never in the bundle definition class.

- `setParameter` with locale should not be done here, it should be done in a `config` file, e.g. the `services.yaml` under `/config` in the template or similar.

See also https://symfony.com/doc/4.4/bundles/extension.html
and also https://symfony.com/doc/4.4/bundles/configuration.html

**Comment by shyim** [comment]
Works on master. Update to the latest release :)

**Comment by AndreasA** [comment]
@shyim 
I am currently using 6.2.3 which is the latest official release and the issue still exists.

Try the following command:
`bin/console debug:config --env=prod --no-debug shopware`

**Comment by shyim** [comment]
Seems not to work on prod but this works
```
bin/console debug:config --env=dev shopware
```

**Comment by AndreasA** [comment]
To be more precise it is the `no-debug` that is the issue. With 
`APP_DEBUG=1 bin/console debug:config --env=prod shopware` 
the issue also does not occur. If I remember correctly dhere is no `--debug` equivalent to `--no-debug` but with APP_DEBUG=1 this can be overridden.

Not 100% sure if it is a bug here or in Symfony.
It is definitely related to how you set the parameter though (not in an extension).

**Comment by shyim** [comment]
Works now
