### ISSUE TITLE
Failing migration (Migration1585490020ActivateHoneypotCaptcha) without Storefront installed 

### ISSUE THREAD

**Issue by AndreasA** [shopware/shopware#789]
**Description**  
According to Video trainings I can use Shopware6 without storefront (e.g. I only need it headless). 

The specified above migration in `shopware/core` references a class in `shopware/storefront`. This means it will fail, if storefront is not installed (e.g. if shopware is only used headless).

**Possible Solution**  
- Move the migration to `shopware/storefront` as this seems to be only related to storefront anyway. However, for existing installations, the migration has to be kept but can e.g. be empty.
- Another solution would be to use the name directly and not referencing a class As we are talking about migrations (which means they should not be deleted or modified but another migration would be needed), it should result in a state used for that version, and that one should always be the original value anyway and not any changes the constant might receive. 
If it changes, another migration would be needed normally.

**Additional context**  
```
In Migration1585490020ActivateHoneypotCaptcha.php line 32:
                                                                                                     
  Attempted to load class "HoneypotCaptcha" from namespace "Shopware\Storefront\Framework\Captcha".  
  Did you forget a "use" statement for another namespace?                                           
```

**Comment by shyim** [comment]
We have already a meta ticket for that. https://issues.shopware.com/issues/NEXT-8572
I would close this then
