### ISSUE TITLE
"update line item quantity" is not yet implemented

### ISSUE THREAD

**Issue by cschwerdt** [shopware/shopware#79]
Hi,
the "update line item quantity" is not yet implemented but mentioned in the docs. Maybe the route is unnecessary anyway, because you can change the quantity by the update route?

https://github.com/shopware/platform/blob/master/src/Docs/Resources/current/3-api/100-sales-channel-cart-api.md#update-line-item-quantity

**Comment by mitelg** [comment]
Hi @cschwerdt 
this route does not exists and the functionality, as you already said, is ensured by the `PATCH /sales-channel-api/v{version}/checkout/cart/line-item/{id}` route.

we will update the docs accordingly. thanks for pointing this out! :+1: I will leave the issue open, until the docs are fixed :wink:

**Comment by mitelg** [comment]
hey @cschwerdt 
with the next deployment the docs should be updated. thanks again!
