### ISSUE TITLE
Kernel with HTTP Cache enabled fails without storefront installed and missing parameter

### ISSUE THREAD

**Issue by AndreasA** [shopware/shopware#791]
**Description**  
According to Video trainings I can use Shopware6 without storefront (e.g. I only need it headless). 

However, if I do so it fails as the parameter `shopware.http.cache.enabled` does not exist and if I set it manually and set it to `true` it will fail due to missing class.

Another solution would be to place an extended Kernel in `Storefront` which would make sense as it requires core and extends it. 

**Possible Solution**  
Check if parameter exists (`hasParameter`) and if it is `true` and HTTP Cache is available and only enabled it if set correspondingly.

**Comment by shyim** [comment]
We have already a meta ticket for that. https://issues.shopware.com/issues/NEXT-8572
I would close this then
