### ISSUE TITLE
APP_ENV=test - Some calls fail due to missing custom tables, so setting up the test environment is missing tables

### ISSUE THREAD

**Issue by AndreasA** [shopware/shopware#793]
**Description**  
For internal tests you added Custom entity definitions when using `APP_ENV=test` or `--env=test`. This results in the table for this custom entity to be missing, if setting up the environment for tests which results in e.g. `dal:refresh:index --env=test` or `system:install --env=test` to fail.

You should only load this service definition in your own internal test for these custom entities.

**Possible Solution**  
In `\Shopware\Core\Framework\Framework::build` you load a `services_test.xml` which might make sense. However, it should definitely not load the custom entity service defintion part. This should only be loaded in your custom tests, e.g. by extending the `Framework`, e.g. extend the original and only load the file there (or add a custom parameter to load these custom entity defintions)

**Additional context**  
```
In AbstractMySQLDriver.php line 42:
                                                                                                                      
  An exception occurred while executing 'SELECT COUNT(DISTINCT `attribute_test`.id) FROM `attribute_test` LIMIT 50':  
                                                                                                                      
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'attribute_test' doesn't exist       
                                                                                                                    
```

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
