### ISSUE TITLE
Documentation (User): group_concat_max_len still required?

### ISSUE THREAD

**Issue by AndreasA** [shopware/shopware#800]
**Description**  
Hi,

I am wondering if this setting is actually still required because you are setting it when initializing the database connection in the Kernel anyway? And I hope it isn't required because most servers will be setup with the default value which is `1024`.

EDIT:
In the developer docs this information has been removed but the user docs still mentions it.
https://docs.shopware.com/en/shopware-6-en/first-steps/system-requirements?category=shopware-6-en/getting-started

Apparently in the developer documentation this has already been adjusted:
https://docs.shopware.com/en/shopware-platform-dev-en/system-guide/system-requirements?category=shopware-platform-dev-en/system-guide

**Possible Solution**  
Remove it also from the user docs as it has been removed from the dev docs, see the following change:
https://github.com/shopware/platform/commit/423a6edf32372968df29351f4b653f6bde08b327

**Comment by shyim** [comment]
Its not required anymore. I have updated the docs. Should be live tomorrow :)
