### ISSUE TITLE
NEXT-8428 - Link to customer in order overview

### ISSUE THREAD

**Issue by Phil23** [shopware/shopware#802]
EN:
It would be helpful if I could open the customer right from the order. Currently I have to copy the name into the search and hope that there is only one unique hit.

DE:
Es wäre hilfreich, wenn ich aus der Bestellung heraus gleich den Kunden öffnen könnte. Aktuell muss ich den Namen in die Suche kopieren und hoffen, dass es nur einen eindeutigen Treffer gibt.

**Comment by pantrtxp** [comment]
@91175don

**Comment by 91175don** [comment]
test

**Comment by bpicho** [comment]
interested

**Comment by mmularski** [comment]
interested

**Comment by t2oh4e** [comment]
interested

**Comment by kavindu-dev** [comment]
interested
