### ISSUE TITLE
NEXT-8427 - EAN rename to GTIN

### ISSUE THREAD

**Issue by Phil23** [shopware/shopware#803]
EN:
For the EAN, the obsolete designation is used ("European Article Number") which has been replaced by GTIN ("Global Trade Item Number") since 2005. We should adapt this at least in the English language.

DE:
Für die EAN wird die veraltete Bezeichnung verwendet ("European Article Number") die seit 2005 durch GTIN ("Global Trade Item Number") abgelöst wurde. Dies sollten wir mindestens in der englischen Sprache anpassen.

**Comment by ngoedde** [comment]
Interested

**Comment by ngoedde** [comment]
@Phil23 In the same step I'd suggest to add a new label "GTIN" to the product detail page in the storefront. What do you think?
