### ISSUE TITLE
NEXT-4506 - Shopware 6 does not support JPG 2000

### ISSUE THREAD

**Issue by pantrtxp** [shopware/shopware#804]
EN: 
Shopware does not recognize the image format JPG 2000 and therefore does not display it. But JPG 2000 is very important, especially when it comes to performance.
JPG 2000 should be supported

DE:
Shopware erkennt das Bildformat JPG 2000 nicht und zeigt es somit nicht an. JPG 2000 ist aber gerade wenn es um Performance geht sehr wichtig.
JPG 2000 sollte unterstützt sein

**Comment by aragon999** [comment]
Interested

**Comment by shyim** [comment]
@pantrtxp This ticket is currently not possible to implement. PHP does not support this without additional extensions

**Comment by shyim** [comment]
Is not supported with PHP
