### ISSUE TITLE
NEXT-4560 - Buy buttons for expanded variant products are not displayed in the category listing

### ISSUE THREAD

**Issue by pantrtxp** [shopware/shopware#805]
EN:
Buy buttons for expanded variant products should be displayed in the storefront category listing instead of detail button.

DE:
Buy-Buttons für aufgefächerte Variantenprodukte sollten im Storefront Categorylisting angezeigt werden.

![image](https://user-images.githubusercontent.com/44392193/81270870-a4336500-904b-11ea-957d-df7bb3744876.png)

**Comment by aragon999** [comment]
Interested
