### ISSUE TITLE
NEXT-5263 - PDF Upload

### ISSUE THREAD

**Issue by pantrtxp** [shopware/shopware#806]
EN:
Currently it is not possible to select PDF files in the Upload. This is due to the inputs accept attribute. 
This should be modified, the default file type should not be images only

DE:
Derzeit ist es nicht möglich, PDF-Dateien im Upload auszuwählen. Dies ist auf das Attribut Eingaben akzeptieren zurückzuführen. 
Dies sollte geändert werden. die Standarddatentypen sollten nicht nur Bilder sein

**Comment by FalkoHilbert** [comment]
intrested

**Comment by sobyte** [comment]
interested

**Comment by jkrzefski** [comment]
interested

**Comment by FalkoHilbert** [comment]
in what context should PDF documents be allowed
