### ISSUE TITLE
NEXT-7312 - Show variants in Product overview / stock

### ISSUE THREAD

**Issue by pantrtxp** [shopware/shopware#808]
EN:

It would be really clever if you could show the variants of a product in the master / slave system in the product overview. Main product then to unfold and indented the variants. This would have the decisive advantage that you can also see the stock levels and do not have to click through to the point Generate variants in the main product. And searching is possible but not a solution.

DE:
Es wäre wirklich clever, wenn man die Varianten eines Artikels im Master / Slave System in der Artikelübersicht einblenden könnte. Hauptartikel dann zum Aufklappen und eingerückt die varianten. Das hätte den entschiedenen Vorteil, dass man auch die Lagerbestände sieht und sich dafür nicht extra bis zum Punkt Varianten generieren im Hauptartikel durchklicken muss. Und suchen geht zwar ist aber keine Lösung.

https://sbp-issuetracker-attachments.s3.eu-west-1.amazonaws.com/1572379930_5db89d1a5991d_1572379910_5db89d06b7ab3_Bildschirmfoto%202019-10-29%20um%2021.07.27.png

**Comment by OliverSkroblin** [comment]
Hey, 

if the main variants are collapsed, how do you want to do that with the pagination of the variants? There are systems that work with over 10000 variants.

**Comment by pantrtxp** [comment]
That is why the "Design" label is set. Here are still some things to be discussed with our design. 
Maybe the Design department even decides that this issue can not be implemented today

**Comment by kmendzie** [comment]
interested

**Comment by FiveDigital** [comment]
Maybe it's not a good idea to have a collapse/expand mechanism but it might be possible to have an icon at the articles with variants that links to a product list specific for the article. In the list you see only the variants of that article with an own pagination. So it's more like a filter for a parent ID.

**Comment by Weltraumakustik** [comment]
Quick update: We've looked into this idea and decided on this draft: https://share.goabstract.com/71b9510b-5e50-4370-acea-43e4b76f2f34
