### ISSUE TITLE
NEXT-5469 Pagination of properties in SW6 admin is missing

### ISSUE THREAD

**Issue by pantrtxp** [shopware/shopware#809]
EN:
At the moment its not possible to list more than 25 properties in the SW6 Admin (Catalogues -> Properties) because the pagination of the properties is missing.

DE:
Aktuell ist es nicht möglich mehr als 25 Eigenschaften im SW6 Admin (Katalog -> Eigenschaften) zu listen, da die Paginierung der Eigenschaften hier fehlt.

**Comment by tbkruse** [comment]
interested

-- Edit --
@pantrtxp I just checked this behavior in a freshly set up shopware 6.2 Boost Day system and the pagination is working fine. Is this behavior restricted to a specific browser?
https://send.firefox.com/download/349c9abd9e682c53/#0cP9KNYToAvlRJVYKUtUOw

**Comment by pantrtxp** [comment]
@tbkruse it seems like this was implemented by one of our developers. Maybe this ticket is da duplicate. 
I'll close it then :)

**Comment by Braintelligence** [comment]
Was this issue related to this one? https://github.com/shopware/platform/issues/971

It's on different parts of the UI but maybe the same mistake was made for the pagination?
