### ISSUE TITLE
NEXT-8340 - Filename and extension are swapped when uploading media

### ISSUE THREAD

**Issue by Phil23** [shopware/shopware#810]
EN:
If files are uploaded whose file name consists only of numbers, the hyphen and/or the underscore, the file name and extension are swapped.

Steps to reproduction: 
Upload file 99999-00.jpg, name after upload: jpg.99999-00
Upload file 99999_00.jpg, name after upload: jpg.00_99999
Upload file 9999900.jpg, name after upload: jpg.9999900
Upload File A99999-00.jpg, name after upload: correct
Upload File 9ABC9999-00.jpg, name after upload: correct

[sw-bug-filename.jpg](https://sbp-issuetracker-attachments.s3.eu-west-1.amazonaws.com/1588233865_5eaa8689b348a_1588233863_5eaa86874f7e2_sw-bug-filenamen.jpg)

DE:
Werden Dateien hochgeladen, deren Dateiname nur aus Zahlen, dem Bindestrich und oder dem Unterstrich bestehen, werden Filename und Erweiterung vertauscht.

Schritte zur Reproduktion: 
Upload File 99999-00.jpg, Name nach Upload: jpg.99999-00
Upload File 99999_00.jpg, Name nach Upload: jpg.00_99999
Upload File 9999900.jpg, Name nach Upload: jpg.9999900
Upload File A99999-00.jpg, Name nach Upload: korrekt
Upload File 9ABC9999-00.jpg, Name nach Upload: korrekt

[sw-bug-filenamen.jpg](https://sbp-issuetracker-attachments.s3.eu-west-1.amazonaws.com/1588233865_5eaa8689b348a_1588233863_5eaa86874f7e2_sw-bug-filenamen.jpg)

**Comment by wexotht** [comment]
Interested

**Comment by lx-wnk** [comment]
Interested

**Comment by alexbaat** [comment]
interested

**Comment by alexbaat** [comment]
@jinnoflife @wexotht Do you want to work on this together?

**Comment by wexotht** [comment]
@alexbaat I'm currently working on this, so you guys go ahead :) 
https://github.com/shopware/platform/issues/860
