### ISSUE TITLE
NEXT-5582 Order confirmation to shop owner

### ISSUE THREAD

**Issue by pantrtxp** [shopware/shopware#811]
EN:
Hello,
as far as I could see there is no way to send the order confirmation email to the shop owner.
A switch in the settings like in Shopware 5 would be nice.

DE:
Hallo,
Soweit ich sehen konnte, gibt es keine Möglichkeit, die Auftragsbestätigungs-E-Mail an den Ladenbesitzer zu senden.
Ein Schalter in den Einstellungen wie in Shopware 5 wäre schön.

**Comment by kiplingi** [comment]
Interested

**Comment by JonasResch99** [comment]
interested

**Comment by SRaromicon** [comment]
Interested
