### ISSUE TITLE
NEXT-6109 - Migration of the "supportText" attribute for configuration items from the "Theme.php" in the "Theme.json" not possible

### ISSUE THREAD

**Issue by pantrtxp** [shopware/shopware#812]
EN:
Due to the change from Shopware 5 "Theme.php" to Shopware 6 "Theme.json", the "supportText" attribute for configuration elements is no longer supported in Shopware 6 "Theme.json".
In Shopware 5, the "supportText" attribute can be used to display an additional and directly visible note about a configuration element in the theme manager. This attribute cannot be used under Shopware 6.

However, the display of information for configuration elements is essential for migrating Shopware 5 "Theme.php" to Shopware 6 "Theme.json" and has considerably improved usability when configuring the theme.

DE:
Durch den Wechsel der Shopware 5 "Theme.php" zur Shopware 6 "Theme.json" wird das Attribute "supportText" für Konfigurationselemente in der Shopware 6 "Theme.json" nicht mehr unterstützt.
Unter Shopware 5 kann mit dem Attribute "supportText" ein zusätzlicher und direkt sichtbarer Hinweis eines Konfigurationselements im Theme-Manager dargestellt werden. Dieses Attribute kann unter Shopware 6 nicht verwendet werden.

Das Anzeigen von Informationen für Konfigurationselemente ist jedoch essentiell für eine Migration der Shopware 5 "Theme.php" zur Shopware 6 "Theme.json" und verbesserte die Usability bei der Konfiguration des Themes erheblich.

https://sbp-issuetracker-attachments.s3.eu-west-1.amazonaws.com/1576753058_5dfb57a2dd622_1576753053_5dfb579d64ecb_a5dec70a-7f9b-4336-811b-cc7c391e430d.png

**Comment by lx-wnk** [comment]
Interested
