### ISSUE TITLE
NEXT-8313 - Clear Cache Shortcut on Mac incorrectly displayed

### ISSUE THREAD

**Issue by Phil23** [shopware/shopware#813]
EN:
The shortcut to clear the cache should be on Mac control+S, but this shortcut is already assigned elsewhere, the actual shortcut is control+C, this would have to be changed on the shortcut overview.

DE:
Das Shortcut zum Cache löschen soll auf Mac control+S sein, dieses Shortcut ist aber schon anderweitig vergeben, das Tatsächliche Shortcut ist control+C, das müsste auf der Übersicht der Tastenkürzel eben geändert werden.

**Comment by sobyte** [comment]
@Phil23 That's the current state in `6.2-BoostDay` branch
<img width="242" alt="Bildschirmfoto 2020-05-14 um 14 45 57" src="https://user-images.githubusercontent.com/1705079/81935925-aa988280-95f1-11ea-9d1a-6743ed37768f.png">
Isn't this already correct?
