### ISSUE TITLE
NEXT-6407 No "Upload media" button on the manufacturer details page

### ISSUE THREAD

**Issue by pantrtxp** [shopware/shopware#815]
EN:
The logo field in the manufacturer detail has only one button for uploading media files. Everywhere else there is also a second button to insert media files that are already in the media collection of the shop.

For the sake of uniformity, insert the second button like this 
![image](https://user-images.githubusercontent.com/44392193/81271540-8a465200-904c-11ea-9627-2bfe522e471e.png)

DE:
Das Logo-Feld im Hersteller-Detail hat nur einen Button zum Hochladen von Mediendateien. Überall sonst gibt es hier auch noch einen zweiten Button zum Einfügen von Mediendateien, die schon in der Mediensammlung des Shops vorhanden sind.

Im Sinne der Einheitlichkeit den zweiten Button einfügen, etwa so

**Comment by wexollm** [comment]
interested

**Comment by FalkoHilbert** [comment]
interested

**Comment by wexollm** [comment]
@pantrtxp Should you be able to upload more than one media image, if no. Then we just need to add the open media button that opens the sidebar with media ?

**Comment by pantrtxp** [comment]
Just one will suffice :) 
Exactly. this is what is missing :+1:

**Comment by wexollm** [comment]
@pantrtxp nice, then I just need to commit :)
