### ISSUE TITLE
NEXT-8305 - Products should only be assignable to categories of type "category"

### ISSUE THREAD

**Issue by Phil23** [shopware/shopware#816]
EN:
It should neither be possible to assign products to categories which are structuring elements or to assign this category to products in the product page.

The card in which products can be assigned to categories should only be displayed if the category is of the type "category"

To prevent assignments of wrong categories in the Product page we should only display categories which are of the type "category".

DE:
Es sollte weder möglich sein, Produkte Kategorien zuzuordnen, die strukturierende Elemente sind, noch sollte es möglich sein, diese Kategorie Produkten auf der Produktseite zuzuordnen.

Die Karte, in der Produkte Kategorien zugeordnet werden können, sollte nur angezeigt werden, wenn die Kategorie vom Typ "Kategorie" ist.

Um Zuordnungen von falschen Kategorien auf der Produktseite zu verhindern, sollten wir nur Kategorien anzeigen, die vom Typ "Kategorie" sind.

**Comment by pantrtxp** [comment]
EN:
Please implement this validation only on the admin site. If a project wants another behavior, it would be difficult to disable the PHP validation for this

DE:
Bitte die Validierung nur auf Admin Seite implementieren. Wenn ein Projekt ein anderes Verhalten möchte ist es schwer die PHP Validierung zu deaktivieren

**Comment by wexomep** [comment]
Interested

**Comment by wexomartin** [comment]
> To prevent assignments of wrong categories in the Product page we should only display categories which are of the type "category".

Instead of removing them on the admin productpage, could we grey them out instead? We could end up loosing the hierarchy if hiding some categories completely.

**Comment by mitelg** [comment]
@wexomartin sounds like a question for the design channel :wink:
