### ISSUE TITLE
NEXT-7087 CmsSectionEntity instead of CmsBlockEntity when sorting sections in SalesChannelCmsPageRepository

### ISSUE THREAD

**Issue by pantrtxp** [shopware/shopware#817]
shopware/platform/src/Core/Content/Cms/SalesChannel/SalesChannelCmsPageRepository.php:37

is:
$page->getSections()->sort(function (CmsBlockEntity $a, CmsBlockEntity $b) {

should be:
$page->getSections()->sort(function (CmsSectionEntity $a, CmsSectionEntity $b) {

**Comment by BrentRobert** [comment]
interested
