### ISSUE TITLE
NEXT-7286 Media upload: Query whether file should be replaced or renamed always applies to all files

### ISSUE THREAD

**Issue by pantrtxp** [shopware/shopware#818]
EN:
If you're loading several pictures into the Media Manager via the Upload File button, which are already there, a modal appears that asks if the file should be replaced, renamed or skipped. 

If there are several files for which this query should be made, there is a checkbox in the modal at the left of the buttons for cancel and continue that the decision made should be applied to all elements. 
This checkbox has no real effect. If the checkbox is removed, the decision is applied to all files anyway. A new modal should open instead.

 

DE:
Lädt man über die Upload File Schaltfläche mehrere Bilder in den Media Manager, die es bereits dort gibt, erscheint ein Modal, welches fragt, ob die Datei ersetzt, umbenannt oder übersprungen werden soll. 

Gibt es mehrere Dateien, bei denen diese Abfrage erfolgen müsste, gibt es in dem Modal links neben den Schaltflächen für Abbruch und Fortsetzen noch die Checkbox, dass die getroffene Entscheidung auf alle Elemente übernommen werden soll. 
Diese Checkbox hat keine wirklich Auswirkung. Entfernt man die Checkbox wird die Entscheidung hier trotzdem für alle Files übernommen. Stattdessen sollte sich ein neues Modal öffnen.

**Comment by lx-wnk** [comment]
Interested
