### ISSUE TITLE
NEXT-8288 - Required fields on newsletter registration

### ISSUE THREAD

**Issue by Phil23** [shopware/shopware#819]
EN:
The fields like salutation and name need to be optional, since the GDPR ("DSGVO") says you only should collect data you need.

DE:
Die Felder wie Anrede und Name müssen optional sein, da das GDPR ("DSGVO") besagt, dass Sie nur die Daten erheben sollen, die Sie benötigen.

**Comment by kiplingi** [comment]
Interested

**Comment by RicoMahr** [comment]
Interested

**Comment by shyim** [comment]
This limitation should be only on Template. From PHP Side is only the email address required
