### ISSUE TITLE
NEXT-8285 - JS Error in Admin Area Users & Rights (New User)

### ISSUE THREAD

**Issue by Phil23** [shopware/shopware#820]
EN:
Description: When I create a new user in the User & Rights section and then change the password directly, the browser does not react anymore and I get a JS error message. When I refresh the browser, the entered password is accepted/changed.

Environment: Staging (freshly set up)

Steps to reproduction: 
1. login admin area
2. navigation to the user & rights area
3. create a new user 
4. fill in mandatory fields
5. click save
6. click change password
7. enter password

Expected result: Confirmation that the password has been changed.

Actual result: Crash of the Admin.

 

DE:
Beschreibung: Wenn ich einen neuen Nutzer im Bereich Benutzer & Rechte anlege und im Anschluss das Passwort direkt ändere, reagiert der Browser nicht mehr und ich erhalte eine JS Fehlermeldung. Wenn ich den Browser refreshe, dann ist das eingegebene Passwort angenommen/geändert.

Umgebung: Staging (frisch aufgesetzt)

Schritte zur Reproduktion: 
1. Login Admin Bereich
2. Navigation zum Bentuzer & Rechte Bereich
3. Neuen Benutzer anlegen 
4. Pflichtfelder ausfüllen
5. Speichern klicken
6. Passwört ändern klicken
7. Passwort eingeben

Erwartetes Ergebnis: Bestätigung das das Passwort geändert wurde.

Tatsächliches Ergebnis: Absturz des Admins.

[image%20%289%29.png](https://sbp-issuetracker-attachments.s3.eu-west-1.amazonaws.com/1587998215_5ea6ee07824a6_1587997853_5ea6ec9d1635a_image%20%289%29.png)

**Comment by runelaenen** [comment]
interested
