### ISSUE TITLE
NEXT-7312 - Variant groups are not sorted in the storefront

### ISSUE THREAD

**Issue by pantrtxp** [shopware/shopware#821]
Currently when I change the order of variant groups in the storefront visibility it is not affecting the storefront at all.
Only changes in the order of the variant options are visible in the storefront.

Wenn ich derzeit die Reihenfolge der Variantengruppen in der Storefront Sichtbarkeit ändere, hat das keinerlei Auswirkungen auf die Storefront.
Nur Änderungen in der Reihenfolge der Variantenoptionen sind in der Storefront sichtbar.

**Comment by alexbaat** [comment]
interested

**Comment by lx-wnk** [comment]
Interested

**Comment by alexbaat** [comment]
@jinnoflife Do you want to work on this together?

**Comment by lx-wnk** [comment]
@pantrtxp Either I misunderstand the error or the problem no longer exists.

If I understand everything correctly, is the target of the topic to order that options?
![image](https://user-images.githubusercontent.com/20777072/82188715-9523a100-98ee-11ea-804f-1b6697ca827a.png)

**Comment by pantrtxp** [comment]
Hi @jinnoflife
It seems like this issue is already fixed. Sorry for your time. 
We could not reproduce it either.

Sunny Regards
Pantrtxp

**Comment by lx-wnk** [comment]
No problem :)
Thanks for the response!
