### ISSUE TITLE
NEXT-7416 - Double click on "Send order" leads to an error page

### ISSUE THREAD

**Issue by pantrtxp** [shopware/shopware#822]
EN:

If you want to buy an item in the Storefront and double click on "Send order" in the order process, you will be redirected to an error page. This is because the request is sent twice.

DE:

Wenn man in der Storefront einen Artikel kaufen möchte und im Bestellprozess auf "Send order" doppelt klickt, wird man zu einer Fehlerseite weitergeleitet. Das liegt daran, dass der Request doppelt abgeschickt wird.

**Comment by lx-wnk** [comment]
Interested

**Comment by kiplingi** [comment]
Interested
