### ISSUE TITLE
NEXT-7417 - Replace comma automatically by dot - Price fields

### ISSUE THREAD

**Issue by pantrtxp** [shopware/shopware#823]
EN:

In the price fields of the articles it would make sense to replace commas directly with points when entering them. In this way, prices could also be entered using the numeric keypad.

Currently the price input only works with points.

DE:

In den Preisfeldern der Artikel würde es Sinn ergeben, Kommata bei Eingabe direkt durch Punkte zu ersetzen. So könnten Preise auch umgänglich mit dem Numblock eingegeben werden.

Aktuell funktioniert die Preiseingabe nur mit Punkten.

**Comment by wexomep** [comment]
Interested
