### ISSUE TITLE
NEXT-8260 - Sorting the properties in the filter has wrong order

### ISSUE THREAD

**Issue by Phil23** [shopware/shopware#827]
EN:
When using properties that are either numeric or individually increasing in value. For example, diameters 10, 20, 30 ..., are displayed correctly in the back end and also on the detail page in the front end. In the filter in the frontend on the category page, this is listed without any sorting, which is extremely annoying if e.g. 15 diameters are stored there for selection and these are completely unsorted.

Environment: Shopware 6.1.5

Steps for reproduction: Create properties in the backend in the desired order.

Expected result: Same order of the variants in the filter on the shop page.

Actual result: Unsorted values in the filter on the shop page.

 

DE:
Bei der Nutzung von Eigenschaften, welche entweder numerisch oder individuell im Wert steigend angelegt sind. Bspw. Durchmesser 10, 20, 30 ..., werden im Backend und auch auf der Detailseite im Frontend richtig dargestellt. Im Filter im Frontend auf der Kategorieseite wird dies jedoch ohne jegliche Sortierung aufgelistet, was extrem störend ist wenn dort bspw. 15 Durchmessser zur Auswahl hinterlegt sind und diese völlig unsortiert sind.

Umgebung: Shopware 6.1.5

Schritte zur Reproduktion: Anlegen von Eigenschaften im Backend in gewünschter Reihenfolge.

Erwartetes Ergebnis: Gleiche Reihenfolge der Varianten im Filter auf der Shopseite.

Tatsächliches Ergebnis: Unsortierte Werte im Filter auf der Shopseite.

[Backend.jpg](https://sbp-issuetracker-attachments.s3.eu-west-1.amazonaws.com/1587824614_5ea447e682c9d_1587824595_5ea447d35b547_Backend.jpg) [Frontend.jpg](https://sbp-issuetracker-attachments.s3.eu-west-1.amazonaws.com/1587824614_5ea447e6cd53d_1587824595_5ea447d3904da_Frontend.jpg)

**Comment by tbkruse** [comment]
interested

**Comment by Sune-dev** [comment]
interested
