### ISSUE TITLE
NEXT-7534 - Files with capitalized file extension can not be uploaded

### ISSUE THREAD

**Issue by pantrtxp** [shopware/shopware#828]
EN:

Files that have a capitalized file extension (such as ".JPG" or ".PNG") cannot be uploaded to media management. It should be a small improvement. Tested in Shopware v6.1.3 Stable Version.

DE:

Dateien mit einer großgeschriebenen Dateierweiterung (wie z.B. ".JPG" oder ".PNG") können nicht in die Medienverwaltung hochgeladen werden. Dies sollte eine kleine Verbesserung sein. Getestet in Shopware v6.1.3 Stabile Version.

https://sbp-issuetracker-attachments.s3.eu-west-1.amazonaws.com/1583509562_5e62703ac96ee_1583509532_5e62701c17a55_Bildschirmfoto%202020-03-06%20um%2016.43.44.png)

https://sbp-issuetracker-attachments.s3.eu-west-1.amazonaws.com/1583509563_5e62703b2b257_1583509532_5e62701c542e4_Bildschirmfoto%202020-03-06%20um%2016.42.32.PNG

**Comment by mitelg** [comment]
should be already fixed with https://github.com/shopware/platform/commit/d4967da816994b04918ba524cdd33330f1f428b1
