### ISSUE TITLE
NEXT-7553 - Contact form in Modalbox: Link to the data protection regulations does not work.

### ISSUE THREAD

**Issue by pantrtxp** [shopware/shopware#829]
EN:

The link to the privacy policy in the contact form is not available. Tested with the current Chrome. See screenshot in the attachment.

DE:

Der Link zu den Datenschutzbestimmungen in dem Kontaktformular ist nicht aufrufbar. Getestet mit dem aktuellen Chrome. Siehe Screenshot im Anhang.

https://sbp-issuetracker-attachments.s3.eu-west-1.amazonaws.com/1583777181_5e66859d00916_1583777178_5e66859ac05d4_Download.png

**Comment by Devcommerce** [comment]
Interested
