### ISSUE TITLE
NEXT-8195 - Order time is displayed incorrectly

### ISSUE THREAD

**Issue by Phil23** [shopware/shopware#830]
EN:
Admin, the order time is displayed incorrectly in the listing.

https://github.com/shopware/platform/blob/master/src/Administration/Resources/app/administration/src/module/sw-order/page/sw-order-list/sw-order-list.html.twig#L119

orderDate -> orderDateTime.

In the order confirmation mail the time zone is also wrong. Probably the current timezone is not passed to twig. Can you handle: {{{ order.orderDateTime|date("m/d/Y H:i", "Europe/Paris") }} - So give the timezone.

 
DE:
Admin wird die Bestellzeit im Listing falsch ausgegeben.

https://github.com/shopware/platform/blob/master/src/Administration/Resources/app/administration/src/module/sw-order/page/sw-order-list/sw-order-list.html.twig#L119

orderDate -> orderDateTime.

Bei der order confirmation mail ist die zeitzone ebenfalls falsch. Vermutlich wird die aktuelle Zeitzone nicht an twig gereicht. Kann man umgehen mit: {{ order.orderDateTime|date("m/d/Y H:i", "Europe/Paris") }}  - Also mitgeben der Zeitzone.

**Comment by wannevancamp** [comment]
interested

**Comment by BrentRobert** [comment]
interested
