### ISSUE TITLE
NEXT-7687 - Invoice number cannot be selected when creating a credit memo document

### ISSUE THREAD

**Issue by pantrtxp** [shopware/shopware#832]
EN:

When creating a credit document on the order details page, it is impossible to select an invoice. The loading circle does not disappear and no selection is offered.

In the browser console (under Chrome 80.0.3987.132 and Firefox 74.0) the error "TypeError: this.order.getAssociation is not a function" appears. The corresponding code is in this file
```
application/vendor/shopware/platform/src/administration/resources/app/administration/src/module/sw-order/component/sw-order-document-settings-credit-note-modal/index.js:48
```

The error occurs on a fresh installation of shopware.

DE:

Beim Erstellen eines Gutschriftdokuments auf der Bestellungs-Detailseite ist es unmöglich eine Rechnung auszuwählen. Der Ladekreis verschwindet nicht und es wird keine Auswahl angeboten.

In der Browserkonsole (unter Chrome 80.0.3987.132 und Firefox 74.0) erscheint dabei der Fehler "TypeError: this.order.getAssociation is not a function". Der entsprechende Code ist in der Datei
```
application/vendor/shopware/platform/src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-document-settings-credit-note-modal/index.js:48
```
zu finden.

Der Fehler tritt auf einer frischen Installation von Shopware auf.

**Comment by runelaenen** [comment]
interested
