### ISSUE TITLE
NEXT-8184 - Change stocks in product overview

### ISSUE THREAD

**Issue by Phil23** [shopware/shopware#833]
EN:
It would be convenient if you could change the stock levels of items in the product overview without having to open the product. 
If you compare the external stock list with the stock in the shop and find a difference it is quite complicated to change the stock (open item, scroll down, enter new quantity, save). If you could just click on the box in the overview and change the quantity there, it would increase the comfort enormously.

DE:
Es wäre praktisch, wenn man die Bestände von Artikeln in der Produktübersicht ändern könnte, ohne dafür das Produkt öffnen zu müssen. 
Gleicht man die externe Bestandsliste mit den Beständen im Shop ab und stellt hierbei eine Differenz fest ist es relativ kompliziert (Artikel öffnen, runter scrollen, neue Artikelmenge eintragen, Speichern) diese zu ändern. Könnte man einfach in der Übersicht in das Kästchen klicken und dort die Anzahl ändern würde das den Komfort enorm erhöhen.

**Comment by niclashc** [comment]
Interested

**Comment by niclashc** [comment]
@Phil23 @pantrtxp

If I understand correctly this is already a feature?
![image](https://user-images.githubusercontent.com/65213674/81903353-f5020b00-95c1-11ea-9928-410500650612.png)

**Comment by mitelg** [comment]
yes your are right @niclashc :+1:
