### ISSUE TITLE
NEXT-8183 - HTML description of the Sections in the Theme Manager (Theme.json)

### ISSUE THREAD

**Issue by Phil23** [shopware/shopware#834]
EN:
You can use the configuration property "sections => label" to display a heading in the Theme Manager (Theme.json). However, some configuration sections require so much explanation that a heading is no longer sufficient.

The user interface should then be improved with an additional HTML description of the "section". In Shopware 5 this could be realized with "attributes => html" in the theme.php For Shopware 6 there is unfortunately no function to display HTML descriptions in the theme manager.

This function is essential for a migration from Shopware 5 to Shopware 6

 

DE:
Mithilfe der Konfigurationseigenschaft "sections => label" kann im Theme-Manager (Theme.json) eine Überschrift angezeigt werden. Einige Konfigurationsbereiche sind jedoch so erklärungsbedürftig, dass eine Überschrift nicht mehr ausreicht.

Die Nutzerführung sollte dann mit einer zusätzlichen HTML-Beschreibung der "Section" verbessert werden. In Shopware 5 konnte das mit "attributes => html" in der theme.php realisiert werden. Für Shopware 6 gibt es leider keine Funktion, um HTML-Beschreibungen im Theme-Manager anzuzeigen.

Diese Funktion ist jedoch essentiell für eine Migration von Shopware 5 auf Shopware 6. [sw5-1.JPG](https://sbp-issuetracker-attachments.s3.eu-west-1.amazonaws.com/1587537905_5e9fe7f1822dc_1587537548_5e9fe68cb2d25_sw5-1.JPG) [sw6-1.JPG](https://sbp-issuetracker-attachments.s3.eu-west-1.amazonaws.com/1587537905_5e9fe7f1c369e_1587537549_5e9fe68d01f3b_sw6-1.JPG)

**Comment by lx-wnk** [comment]
Interested
