### ISSUE TITLE
NEXT-8145 - CSS gets unminified by Autoprefixer

### ISSUE THREAD

**Issue by Phil23** [shopware/shopware#836]
EN:
When you run theme:compile command in prod environment the css needs to be minified. 
Within Storefront/Theme/ThemeCompiler.php the following line returns a minified css output

```
$cssOutput = $this->scssCompiler->compile($variables . $concatenatedStyles);
```

After that it puts the output into the Autoprefixer

```
$autoPreFixer = new Autoprefixer($cssOutput);
return $autoPreFixer->compile();
```

The Autoprefixer returns the css again however now with new lines included, so it isn't minified anymore.
This is because of the used OutputFormat

```
return $css_document->render(\Sabberworm\CSS\OutputFormat::createPretty());
```

With the OutputFormat to createCompact it would return the minfied version.

Steps to reproduce: 
Run theme:compile and open the all.css of the theme.

Expected result: 
A minified css.

Actual result: 
A non-minified css 

DE:
Wenn Sie den Befehl theme:compile in der Umgebung prod ausführen, muss das css minimiert werden. 
In Storefront/Theme/ThemeCompiler.php gibt die folgende Zeile eine verkleinerte css-Ausgabe zurück

```
$cssOutput = $this->scssCompiler->compile($variables . $concatenatedStyles);

```

Danach legt es die Ausgabe in den Autoprefixer

```
$autoPreFixer = new Autoprefixer($cssOutput);
return $autoPreFixer->compile();
```

Der Autoprefixer gibt das css wieder zurück, allerdings jetzt mit neuen Zeilen, so dass es nicht mehr verkleinert wird.
Dies liegt an dem verwendeten OutputFormat

```
return $css_document->render(\Sabberwurm-\CSS\OutputFormat::createPretty());
```

Mit dem OutputFormat zu createCompact würde es die verkleinerte Version zurückgeben.

Schritte zur Reproduktion: 
theme:compile ausführen und die all.css des Themes öffnen.

Erwartetes Ergebnis: 
Eine verkleinerte css.

Tatsächliches Ergebnis: 
Ein nicht-minifiziertes css

**Comment by wexotht** [comment]
Interested

**Comment by alexbaat** [comment]
Interested

**Comment by shyim** [comment]
This is fixed with this commit. But the commit is not released from the package
https://github.com/padaliyajay/php-autoprefixer/commit/475d41b7ee4213de6ce869fb8b58f384ebdd3186

**Comment by tobiasberge** [comment]
I could help with this one if you want. You can ping me in slack
