### ISSUE TITLE
NEXT-8142 - Thumbnails of variants use full image size

### ISSUE THREAD

**Issue by Phil23** [shopware/shopware#837]
EN:
Variants have the same photos as the products themselves assigned (2048px).

The thumbnails of the variants use these large images for display and scale the whole thing using HTML instead of responsive picture elements.

This means that a lot of unnecessary data has to be loaded. In our case an article with 24 variants which makes up a few MB in the end.

DE:
Varianten haben die gleichen Fotos wie die Produkte selbst zugewiesen (2048px).

Die Thumbnails der Varianten verwenden diese großen Bilder für die Darstellung und skalieren das ganze per HTML statt mit responsive Picture Elementen.

Dadurch müssen extrem viel unnötige Daten geladen werden. In unserem Fall ein Artikel mit 24 Varianten was dann unterm Strich gleich ein paar MB ausmacht.

https://sbp-issuetracker-attachments.s3.eu-west-1.amazonaws.com/1587120319_5e9988bf58c94_1587120317_5e9988bd22b7b_Bildschirmfoto%202020-04-17%20um%2012.45.02.png

**Comment by tbkruse** [comment]
interested
