### ISSUE TITLE
NEXT-7703 - "Accept All" for the Cookie Manager

### ISSUE THREAD

**Issue by pantrtxp** [shopware/shopware#838]
EN:

Currently it is not possible to accept all cookies. There should be a setting to accept all cookies (could be activated per setting)

DE:

Derzeit ist es nicht möglich, alle Cookies zu akzeptieren. Es sollte eine Einstellung geben, alle Cookies zu akzeptieren (könnte per Einstellung aktiviert werden)

**Comment by JonasResch99** [comment]
interested

**Comment by wexollm** [comment]
interested
