### ISSUE TITLE
Delivery note data is overwritten

### ISSUE THREAD

**Issue by pantrtxp** [shopware/shopware#839]
EN:
In the case of a delivery note that was created individually and assigned to a second sales channel, the data is overwritten with that of the main delivery note when the document is created for a purchase order, although the individual delivery note is created for a purchase order from the second sales channel.

—
DE:
Bei einem Lieferschein, der individuell angelegt und einem zweiten Verkaufskanal zugewiesen wurde, werden bei der Belegerstellung für eine Bestellung die Daten mit denen des Hauptlieferscheins überschrieben, obwohl der individuelle Lieferschein für eine Bestellung aus dem zweiten Verkaufskanal erstellt wird.

**Comment by alexbaat** [comment]
interested
