### ISSUE TITLE
Introduce Phive

### ISSUE THREAD

**Issue by szepeviktor** [shopware/shopware#84]
You could remove tools from the repository if you use Phive.
See https://github.com/phar-io/phive
Very easy to configure!

**Comment by szepeviktor** [comment]
After that you may consider reducing the repo size by removing those tools https://help.github.com/en/articles/removing-sensitive-data-from-a-repository

**Comment by mitelg** [comment]
hey @szepeviktor 
I'm currently working on moving our CI tooling from platform to the development template. so the main repo size will be decreased. I will take your issue and your PR into account :+1: 
thanks for your contribution

**Comment by szepeviktor** [comment]
All right.

**Comment by szepeviktor** [comment]
> moving our CI tooling from platform to the development template

@mitelg Does it mean that platform contribution (PR-s) won't be checked?

**Comment by mitelg** [comment]
just a little hint :blush: as we are shortly before our first release, it will may take some time, as I don't want to struggle up our CI pipeline before the release :wink:

**Comment by mitelg** [comment]
> @mitelg Does it mean that platform contribution (PR-s) won't be checked?

Currently there are no checks here on github anyway :grin: all checks are done internally on bitbucket and bamboo.
I will take that to my task :wink:

**Comment by szepeviktor** [comment]
What a shame! You develop modern code and use Atlassian products? No words can describe their quality.

**Comment by szepeviktor** [comment]
> I don't want to struggle up our CI pipeline before the release 😉

My _base package_ for developer teams includes [these 3 zero-coverage tests](https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/Continuous-integration-Continuous-delivery.md#coding-style--coding-standard):

1. parallel syntax check
1. coding standards check (this check can do much more than its name suggests, e.g. find var_dump-s or detect dead code)
1. static analysis

It costs nearly nothing to introduce them, and keeps your code quality very high even if you don't have time to write unit/functional tests.

**Comment by mitelg** [comment]
Don't get me wrong here, we already use these tools :blush: 
but if I now move phar files from here to there, or introduce phive, I have to adjust our CI. and this is mostly not done in five minutes :wink:

**Comment by janbuecker** [comment]
> What a shame! You develop modern code and use Atlassian products? No words can describe their quality.

We have plans to migrate to an internal GitLab instance and we may can use parts of it's CI configuration for travis ci like we are doing with Shopware 5.

**Comment by janbuecker** [comment]
Some weeks ago, we've evaluated phive as replacement for the phar files. At the end of the day, the key servers are really unreliable and not all tools are available with a signature, which does not make much sense right now. We'll keep an eye on phive and once it's more mature, we'll evaluate it again.
