### ISSUE TITLE
NEXT-7952 - Search endpoint ignores parameters "limit"

### ISSUE THREAD

**Issue by pantrtxp** [shopware/shopware#841]
EN:

When calling the search endpoint and passing the parameter "limit" it is ignored and limit=10 is assumed

DE:

Beim Aufrufen des Search-Endpunktes und übergeben des Parameters "limit" wird dieser Ignoriert und limit=10 angenommen

Schritte zur Reproduktion:

url: ... "api/v1/search/product?limit=1"
requestbody =
{
"filter" : [

{ "type" : "equals", "field" : "coverId", "value" : null }
]
}

Erwartetes Ergebnis:

Rückgabe von einem Produkt.
"links" :

{ "first" : "http://www.ldbs-shop.de.cloud8-vm556.de-nserver.de/api/v1/search/product?limit=1&page=1", "last" : "http://www.ldbs-shop.de.cloud8-vm556.de-nserver.de/api/v1/search/product?limit=1&page=701", "next" : "http://www.ldbs-shop.de.cloud8-vm556.de-nserver.de/api/v1/search/product?limit=1&page=2", "self" : "http://www.ldbs-shop.de.cloud8-vm556.de-nserver.de/api/v1/search/product?limit=1" }
,
"meta" :

{ "totalCountMode" : 1, "total" : 701 }
,

Tatsächliches Ergebnis:

Rückgabe von 10 Produkten.
"links" :

{ "first" : "http://www.ldbs-shop.de.cloud8-vm556.de-nserver.de/api/v1/search/product?limit=10&page=1", "last" : "http://www.ldbs-shop.de.cloud8-vm556.de-nserver.de/api/v1/search/product?limit=10&page=71", "next" : "http://www.ldbs-shop.de.cloud8-vm556.de-nserver.de/api/v1/search/product?limit=10&page=2", "self" : "http://www.ldbs-shop.de.cloud8-vm556.de-nserver.de/api/v1/search/product?limit=1" }
,
"meta" :

{ "totalCountMode" : 1, "total" : 701 }

**Comment by wexotht** [comment]
Interested

**Comment by vanWittlaer** [comment]
interested

**Comment by shyim** [comment]
Hint: Should be in the RequestCriteriaBuilder
