### ISSUE TITLE
NEXT-8102 - Some text elements in Admin are displayed in English, although German is available and set (and vice versa)

### ISSUE THREAD

**Issue by Phil23** [shopware/shopware#842]
DE:
Ändert man die User Interface Language im Admin (zB von urpsrünglich Deutsch auf Englisch), werden die Feldbeschriftungen 
im Theme-Modul und in der Länder-Karte im Steuermodul nicht korrekt mitgeändert.
Die Buttons haben dann korrekterweise eine Englische Beschriftung, die Felder und Kartentitel etc. werden aber noch auf Deutsch angezeigt, und umgekehrt. Vergleiche Screenshots unten.

EN:
Changing the user interface language in the administration fails to change field and card titles in themes and the tax module. Buttons are labelled in English, while fields are labelled in German. And vice versa.

![image](https://user-images.githubusercontent.com/2599065/81273419-207b7780-904f-11ea-8621-e707381aae72.png)
![image](https://user-images.githubusercontent.com/2599065/81273428-25d8c200-904f-11ea-979e-e15d0666f0ab.png)
![image](https://user-images.githubusercontent.com/2599065/81273442-2b360c80-904f-11ea-9c9e-d5811b154250.png)
![image](https://user-images.githubusercontent.com/2599065/81273458-30935700-904f-11ea-9d9b-72863bc9f78c.png)

**Comment by moritzreichelt** [comment]
interested
