### ISSUE TITLE
NEXT-7962 - Create new shipping method not possible

### ISSUE THREAD

**Issue by pantrtxp** [shopware/shopware#843]
**EN**:

Description: When I try to create a new shipping method in a standard installation, I get the error "An error occurred while saving the entity "test".

Error message in the developer console
> {"errors":[{"code": "c1051bb4-d103-4f74-8988-acbcafc7fdc3", "status": "400", "detail": "This value should not be blank.", "template": "This value should not be blank. ", "meta":{"parameters":{"{ value }}": "zero"}}, "source":{"pointer":"\/0\/prices\/0\/price"}},{"code": "c1051bb4-d103-4f74-8988-acbcafc7fdc3", "status": "400", "detail": "This value should not be blank. ", "template": "This value should not be blank.", "meta":

{"parameters":}

[\{value }}"null"}}, "source":\{"pointer":"\/0\/prices\/1\/price"}]

It does not matter if I fill out only the mandatory fields or all fields. It simply does not work.

Existing shipping methods can be edited.

**DE**:

Beschreibung: Wenn ich in einer Standardinstallation versuche eine neue Versandart anzulegen kommt der Fehler "Beim Speichern der Entität "test" ist ein Fehler aufgetreten."

Fehlermeldung in der Entwicklerkonsole
> {"errors":[\{"code":"c1051bb4-d103-4f74-8988-acbcafc7fdc3","status":"400","detail":"Dieser Wert sollte nicht leer sein.","template":"This value should not be blank.","meta":{"parameters":{"{{ value }}":"null"}},"source":\{"pointer":"\/0\/prices\/0\/price"}},\{"code":"c1051bb4-d103-4f74-8988-acbcafc7fdc3","status":"400","detail":"Dieser Wert sollte nicht leer sein.","template":"This value should not be blank.","meta":{"parameters":{"{{ value }}":"null"}},"source":\{"pointer":"\/0\/prices\/1\/price"}}]}

Es ist egal ob ich nur die Pflichtfelder oder alle Felder ausfülle. Es geht einfach nicht.

Bestehende Versandarten kann man bearbeiten.

**Comment by SeboBlock** [comment]
interested

**Comment by MDSLKTR** [comment]
interested

**Comment by alexbaat** [comment]
interested

**Comment by kavindu-dev** [comment]
interested
