### ISSUE TITLE
NEXT-7967 - Shopping Experiences: text editing in Edge not possible

### ISSUE THREAD

**Issue by pantrtxp** [shopware/shopware#844]
EN:
In *Content > Shopping Experiences*, while editing a page:

If you select text to edit it via the appearing bar (e.g. color), the selection of the text disappears when you click on a option. This means that the text will not be edited.

DE:
In *Inhalte > Erlebniswelten*, bei der Bearbeitung einer Seite:

Wenn man Text markiert, um ihn über die dann erscheinende Leiste zu bearbeiten (z.B. Farbe), verschwindet bei klicken auf die Änderungen die Markierung des Textes. Das führt dazu, dass keine Bearbeitung erfolgt.

**Comment by runelaenen** [comment]
@pantrtxp In which version of Edge did this happen? The old version, or the new chromium-based version?

**Comment by pantrtxp** [comment]
@runelaenen 
Sadly I can not tell you this. This is all the information we got.
This ticket was created over issues.shopware.com 

Maybe you could try both?

**Comment by runelaenen** [comment]
I'm on Mac so can only try the newest version. It doesn't seem to be happening on here.
