### ISSUE TITLE
NEXT-8064 - [Feature] - System info in the Admin

### ISSUE THREAD

**Issue by Phil23** [shopware/shopware#845]
EN:
To make the support of SW6 a bit easier, a module for viewing the system info would be useful. This module should show whether the system requirements are really fulfilled, whether the directory structure is correct or the required rights are set, whether the files exist or have been modified - thus comparable with the system info as we already know it from SW5.

DE:
Um den Support von SW6 etwas einfacher gestalten zu können, wäre ein Modul zur Einsicht der Systeminfo sinnvoll. Hierbei sollte einsehbar sein, ob die Systemanforderungen auch wirklich erfüllt sind, ob die Verzeichnisstruktur korrekt ist bzw. die benötigten Rechte darauf gesetzt sind, die Dateien vorhanden bzw. angepasst worden sind - also vergleichbar mit der Systeminfo, wie man sie bereits aus SW5 kennt.

**Comment by akluth** [comment]
Interested.

**Comment by lx-wnk** [comment]
Interested

**Comment by px-flo** [comment]
interested

**Comment by MDSLKTR** [comment]
interested

**Comment by TjadeHoff** [comment]
interested

**Comment by JensBrunken** [comment]
Interested
