### ISSUE TITLE
NEXT-7986 - Shopping Experiences: "Hero image" element doesn't display thumbnails but the original image

### ISSUE THREAD

**Issue by pantrtxp** [shopware/shopware#846]
EN:

Shopping Experiences:
When choosing a "Hero image" element in a layout, the different generated thumbnail sizes aren't being used, but the original image in its original size. This means that the image is not adjusted, for example in mobile views.

DE:

Erlebniswelten:
Beim verwenden eines "Banner"-Elements (Bild mit Text) in einem Layout, werden bei dem hinterlegten Bild nicht die verschiedenen generierten Thumbnailgrößen verwendet, sondern das Originalbild in der ursprünglichen Größe. Dadurch wird das Bild, beispielsweise bei Mobile-Ansichten nicht angepasst.

**Comment by ca-tb** [comment]
interested

**Comment by ca-tb** [comment]
The description of this issue is incorrect, or at least i dont understand, because the image from this block is used as a background image, also, it loads obviously only one image...
