### ISSUE TITLE
NEXT-8010 - Product detail page images are downloaded anew each time the magnifying glass function is used

### ISSUE THREAD

**Issue by pantrtxp** [shopware/shopware#847]
EN:

Description:
On the PDP (product detail page) the product images are downloaded by the Javascript every time the customer moves the mouse over them.

environment:
Local, live and demo shop tested

Steps to reproduction:
Go to product detail page
Open the developer console and display and empty the network tab
Move the product image with the mouse
In the developer console, the image is requested again from all.js each time

Expected result:
A product image once loaded should be used from the browser cache.

Actual result:
Image is reloaded again and again.

DE:

Beschreibung:
Auf der PDP (Produktdetailseite) werden die Produktbilder jedesmal neu vom Javascript heruntergeladen, wenn der Kunde mit der Maus darüber fährt.

Umgebung:
Lokal, live und Demoshop getestet

Schritte zur Reproduktion:
Auf Produktdetailseite gehen
Entwicklerconsole öffnen und den Netzwerk-Tab anzeigen und leeren
Mit der Maus mehr das Produktbild fahren
In der Entwicklerkonsole wird jedes mal das Bild erneut von all.js angefordert

Erwartetes Ergebnis:
Ein einmal geladenes Produktbild sollte aus dem Browsercache verwendet werden.

Tatsächliches Ergebnis:
Bild wird immer wieder neu geladen.

**Comment by tbkruse** [comment]
interested
