### ISSUE TITLE
NEXT-8012 - Visualization of variants with stock 0 and sales does not work properly

### ISSUE THREAD

**Issue by Phil23** [shopware/shopware#848]
EN:
If some variant articles are partially in stock 0 (and have been marked as sales), then the shopping cart button is correctly hidden.

Unfortunately, as a user (shop customer) you cannot see in the storefront UI which variants are not available (in my example red - M and white - M/XL - see variantenbestand.png) and you have to click through (see variantenauswahl.png).

In css there might already be the border 1px dashed for this. But it obviously does not work or not always.

environment:

Steps to reproduction: 
For the variant article from the demo data, set some to stock 0 and sales.

Expected result: 
Mark the variant boxes with a dotted frame.

Actual result: 
Continuous frame - no withdrawal of variants with stock.

DE:
Wenn Variantenartikel teilweise Bestand 0 haben (und als Abverkauf markiert wurden), dann wird richtigerweise der Warenkorb Button ausgeblendet.

Leider sieht man in der Storefront UI als User (Shop-Kunde) nicht, welche Varianten nicht verfügbar sind (in meinem Beispiel Rot - M und Weiß - M/XL - siehe variantenbestand.png) und muss sich durchklicken (siehe variantenauswahl.png).

Im Css dürfte es dafür bereits bereits den border 1px dashed geben. Der greift aber offenbar nicht bzw. nicht immer.

Umgebung:

Schritte zur Reproduktion: 
Beim Variantenartikel aus den Demodaten manche auf Bestand 0 und Abverkauf setzen.

Erwartetes Ergebnis: 
Kennzeichnung der Variantenboxen mit gestricheltem Rahmen.

Tatsächliches Ergebnis: 
Durchgehender Rahmen - keine Abhebung von Varianten mit Bestand.

https://sbp-issuetracker-attachments.s3.eu-west-1.amazonaws.com/1586159963_5e8ae15bddbaa_1586159565_5e8adfcdb544e_variantenauswahl.png

**Comment by wexollm** [comment]
interested
