### ISSUE TITLE
NEXT-7442 - Display of accountless customers in the Admin

### ISSUE THREAD

**Issue by pantrtxp** [shopware/shopware#851]
EN:

It would make sense if accountless customers were also marked as such. Currently the only marking is "no login yet" at "last login".

DE:

Es würde Sinn ergeben, wenn Schnellbesteller auch als solche gekennzeichnet werden. Aktuell ist die einzige Kennzeichnung "noch kein Login" bei "Letzter Login".

**Comment by MDSLKTR** [comment]
interested

**Comment by sobyte** [comment]
interested

**Comment by SeboBlock** [comment]
interested
