### ISSUE TITLE
NEXT-7788 - Disable ratings

### ISSUE THREAD

**Issue by pantrtxp** [shopware/shopware#852]
EN:

It would be nice if you could disable the ratings completely.

DE:

Es wäre schön wenn man die Bewertungen komplett deaktivieren könnte.

**Comment by sebi007** [comment]
Interested

**Comment by wexollm** [comment]
interested

**Comment by stephan4p** [comment]
interested

**Comment by akm-manjurul-alam** [comment]
interested
