### ISSUE TITLE
NEXT-7072 - Search in mail templates without function

### ISSUE THREAD

**Issue by pantrtxp** [shopware/shopware#854]
EN: 

The search field in the mail template listing is without function. The listing will be reloaded. But it is not filtered by the search term.

DE:

Das Suchfeld im Listing der Mailtemplates ist ohne Funktion. Zwar wird das Listing neu geladen. Es wird aber nicht nach dem Suchbegriff gefiltert.

**Comment by vanWittlaer** [comment]
interested
