### ISSUE TITLE
NEXT-8493 - Missing blocks and JS plugins on account order edit page

### ISSUE THREAD

**Issue by pantrtxp** [shopware/shopware#855]
EN:
src/Storefront/Resources/views/storefront/page/account/order/index.html.twig misses some blocks for extensions
Additionally the JS plugins on the form are missing. they should be the same as the confirm page form

DE:
in src/Storefront/Resources/views/storefront/page/account/order/index.html.twig fehlen Blöcke für Erweiterungen
Zusätzlich fehlen die JS plugins auf dem Form element. Es sollte dieselben haben wie die Form auf der Confirm Page

**Comment by BrentRobert** [comment]
interested

**Comment by leichteckig** [comment]
QA approved :heavy_check_mark:
