### ISSUE TITLE
[BoostDay] Make Salutations optional

### ISSUE THREAD

**Issue by wexomartin** [shopware/shopware#873]
In many countries salutations are not used at all, so it should be optional if this is present in frontend.

Currently in 6.2 we have the following values as standard:
- mr
- mrs
- not_specified 

An idea could be that if Mr and Mrs gets deleted so only not_specified is left, it will hide all fields in frontend regarding salutation. As soon as more than 1 salutation is created the option to choose in frontend will be present again.

**Comment by pantrtxp** [comment]
Hello @wexomartin, 
this issue is currently being worked on for the next patch :) 
You can track the state [here](https://issues.shopware.com/issues/NEXT-7739)
Sunny regards 
Pantrtxp
