### ISSUE TITLE
guest order`s currencyId is not match with context`s currencyId

### ISSUE THREAD

**Issue by SangyoonKim-iotrust** [shopware/shopware#874]
**Description**  
I`m now using shopware 6.1.5 as backend api

for guest pay test, I changed api context with /sales-channel-api/v1/context with this payload
![image](https://user-images.githubusercontent.com/53167182/81664916-fb399f80-947a-11ea-97f2-c792086daf5f.png)

and this is final cart price
![image](https://user-images.githubusercontent.com/53167182/81665171-5bc8dc80-947b-11ea-9928-573a59392769.png)

but after create guest order, it shows different currency is used.
![image](https://user-images.githubusercontent.com/53167182/81665036-291ee400-947b-11ea-89bf-bbefbe670c29.png)

it seems guest order only using sales channel`s default currency.

**Comment by shyim** [comment]
This should be already fixed with the new cart restore epic. Feel free to write if its still not working
