### ISSUE TITLE
[BoostDay] Notepad

### ISSUE THREAD

**Issue by jkrzefski** [shopware/shopware#883]
**Description**  
There should be a notepad for customers to save their favorite products to, so they have easy access to them and can quickly buy these products over and over again. The feature already existed in Shopware 5 and is really a basic in ecommerce that should be available in Shopware 6 as well. While we're at it, I propose we make the notepad actually good and not only *existing*.

* A notepad should be available for everyone, not just logged in customers. So we need the possibility to link a notepad to a session or to a customer.
* A user should be able to have multiple notepads, name them and move products between them.
* Users should be able to make their notepad public or leave them private (default). Public notepads should be accessible with a link.
* The price of a product should be saved for every entry on every notepad for that point in time. The idea is to be able to calculate price changes since the product was added to the notepad and display them to the user. ("Product is 10 % cheaper than it was when it was added to the list.")
* A cronjob should send mails for discounted products on notepads. When a product's price is temporarily discounted, all users with this product in one of their notepads should receive a notification mail.

![414mjn](https://user-images.githubusercontent.com/11394739/81702738-f6b9ba80-946b-11ea-984e-ee0ff0465a4d.jpg)

**Example**  
Let's say a customer would like to save some products he really likes into a list of his favorites. Now let's say, this were to happen in a Shopware 6 shop. See the problem?

**Comment by mitelg** [comment]
related existing ticket https://issues.shopware.com/issues/NEXT-4900

**Comment by pantrtxp** [comment]
Hi @jkrzefski 
please do not forget, that the boostday is one-day only. Tasks should be somewhat completable within the 8 hours of this day. 
The mentioned issue is a little more complex and should be developed by our core developers.

Anyway as @mitelg mentioned there is already an existing ticket. If this ticket gets enough votes we'll consider implementing this functionality. 
If you'd like to I would add your ideas to the ticket. This way people would get a little more details. What do you think? 

Sunny Regards
Pantrtxp

**Comment by JoshuaBehrens** [comment]
Hey @pantrtxp you underestimate what @jkrzefski is able to do within 8 hours 😬  For real this is a bigger task, yes. And maybe just the first more common parts from shopware 5 are a more realistic approach but 8 hours is just one worker. Just increase the amount of workers and you can make 8 hours to 80 hours 😉  That is how business administration works, doesn't it?

**Comment by jkrzefski** [comment]
@JoshuaBehrens Just how nine women can deliver a baby in one month, right?

**Comment by jkrzefski** [comment]
I believe, this is a feature request that can fairly easily be split into multiple parts. If we split the requirements into the basics and some advanced features, we would implement as much of it as we can in the given timespan and have the rest of it still open for future pull requests.

@pantrtxp But I can also understand, that you would rather have your core developers on this and have the feature thoroughly tested before releasing it. And for that, I would like it very much, if you add my suggestions to the existing ticket.

**Comment by mitelg** [comment]
my suggestion is to implement the whole thing at once and do not implement the first parts or something like that.

> While we're at it, I propose we make the notepad actually good and not only existing.

you said it by yourself :wink:

**Comment by pantrtxp** [comment]
I have added your Ideas as a comment :) 
If we implement this feature may be some of your wishes will remain open for another BoostDay.

If you are fine with my comment I'd like this issue to be closed since it is a duplicate

Sunny regards 
Pantrtxp

**Comment by jkrzefski** [comment]
@pantrtxp Looks good to me. Just one question: Is there a reason for the changes from `notepad` to `wishlist` in the feature list? Is there a difference between the two that I missed?

**Comment by mitelg** [comment]
naming things... we are good at that :smile:

**Comment by pantrtxp** [comment]
No, there is not, but since the ticket is called "Wishlist functionality missing" I thought I was keeping it consistent

**Comment by jkrzefski** [comment]
Alright, I can live with that.
