### ISSUE TITLE
Miss 'description' section in 'extra' section (composer.json) 

### ISSUE THREAD

**Issue by brtsos** [shopware/shopware#933]
**Description**  
Miss 'description' section in 'extra' section (composer.json) 
https://docs.shopware.com/en/shopware-platform-dev-en/how-to/indepth-guide-bundle/setup

**Possible Solution**  
Add in example composer.json:
`
"extra": {
        "shopware-plugin-class": "Swag\\BundleExample\\BundleExample",
        "copyright": "(c) by shopware AG",
        "description": {
            "de-DE": "Beispiel für Shopware",
            "en-GB": "Example description for Shopware"
        }
        "label": {
            "de-DE": "Beispiel für Shopware",
            "en-GB": "Example for Shopware"
        }
    }
`

**Additional context**

**Comment by mitelg** [comment]
sounds like a good issue for a PR to the docs :blush:

**Comment by shyim** [comment]
I have created a PR for the new docs
