### ISSUE TITLE
NEXT-6803 - Error in calculation of the price matrix by property weight

### ISSUE THREAD

**Issue by alexbaat** [shopware/shopware#945]
**Description**  
In case shippingcosts are calculated based on weight, it should take into account the quantity of the lineitem. So in case the weight of 1 item of a product is 2Kg and the quantity of the orderline is 3, it should calculate shippingcosts with 2 * 3 = 6Kg. Currently it uses 2Kg. 

**Possible Solution**  
Multiply the weight of the product with the quantity in the lineitem.

**Comment by mitelg** [comment]
hey @alexbaat 
thanks for the issue :blush: :+1: I will close this here, as you already created a PR for that :+1: 
we will handle the issue there :wink: 

https://github.com/shopware/platform/pull/946
https://issues.shopware.com/issues/NEXT-6803
