### ISSUE TITLE
Broken URLs after manual installation

### ISSUE THREAD

**Issue by akerbel** [shopware/shopware#95]
Hi.

I have installed developer version without docker. During installation I have entered application URL as "http://shopware.loc", how it was offered by installation helper. 
And now I got all urls as "http://shopware.loc/http://shopware.loc/index.php/navigation/...". 

I have tryed to edit or delete "APP_URL" parameter in .env and .env.dist, but it had no effect. Dropping cache in symfony console also didn't help.

What I did wrong? I can't get even into the admin panel.

**Comment by jenskueper** [comment]
Hello!

Can you post the content auf your .env file in root dir of the shopware installation (you might want to exclude the line with the database credentials)?

**Comment by akerbel** [comment]
Of course

```
APP_ENV=dev
APP_URL=http://shopware.loc

MAILER_URL=smtp://mailhog:1025

INSTANCE_ID=

COMPOSER_HOME=/Users/anton.kerbel/.composer

SHOPWARE_SES_HOSTS=elasticsearch:9200
SHOPWARE_SES_ENABLED=0
SHOPWARE_SES_INDEXING_ENABLED=0
SHOPWARE_SES_INDEX_PREFIX=sw

FEATURE_NEXT_516=1
```

**Comment by jenskueper** [comment]
This looks fine. Have you created a vhost for shopware.loc in your apache/nginx configuration? If thats the case, please ensure that it maps to the **public** directory of your shopware installation.

**Comment by akerbel** [comment]
Thanks for help. I am closing the issue because "shopware" is not needed anymore. Next time I will try better with docker installation.
