### ISSUE TITLE
error handling within the administration custom entities 

### ISSUE THREAD

**Issue by ChristopherDosin** [shopware/shopware#950]
If you have a custom entity extension with a required flag for a field and a custom input with a required field for example, the error handling within the administration does not work properly.

You're getting only the notification `An error occurred while saving the entity ..`.

But you don't get the specific error which should be something like `Input field bar is required`. In the end the user does not know why his entry can't be saved. 

Also there is no UI that determines the error e.g a red border for the required input which fails and also maybe scroll to the error. Otherwise the error would not be visible within the viewport.

However within the Network tab you're getting at least an almost correct error.

<img width="1411" alt="Bildschirmfoto 2020-05-19 um 12 40 38" src="https://user-images.githubusercontent.com/8193345/82312466-c2944b80-99cf-11ea-8b58-be4836b3e59c.png">

**component js**
```
const { mapApiErrors } = Shopware.Component.getComponentHelper();

Shopware.Component.override('sw-category-detail-base', {
    .....
    computed: {
        mapApiErrors('category', ['bar'])
    }
....
```
**twig file**
```
<sw-text-field 
     required 
     :error="categoryBarError"  
     v-model="category.extensions.foo.bar"
     ....
```
**EntityDefinition**
```
....
    public function defineFields(): FieldCollection
    {
        (new StringField('bar', 'bar'))->setFlags(new Required()),
```

**Comment by ChristopherDosin** [comment]
Another example:
You have a `VARCHAR(255)` field within your table.
Within the administration you have a `<sw-textarea-field type="textarea" ...`.

Now if you type in more than 255 characters you only get an error message "Could not be saved`. Only within the network tab you'll the exact error message e.g `This value is too long. It should have 255 characters or less.`.

<img width="1437" alt="Bildschirmfoto 2020-05-25 um 21 08 39" src="https://user-images.githubusercontent.com/8193345/82835387-8def2b00-9ecc-11ea-9b8b-d7664807c9c2.png">

**Comment by ChristopherDosin** [comment]
And another error handling related issue: If you upload a file that is too big because of the server settings restrictions there should be also a feedback for the user e.g error message based on the 413 response.

Otherwise the user would never know why the picture isn't uploaded. Currently nothing happens. No feedback, nothing. You only see the issue within the network tab.

<img width="1072" alt="Bildschirmfoto 2020-05-25 um 21 28 30" src="https://user-images.githubusercontent.com/8193345/82836368-0ce56300-9ecf-11ea-8d3e-97b80dd1247b.png">

**Comment by s-andy** [comment]
Hi. I faced a similar issue.
This should be:
```
const { mapPropertyErrors } = Shopware.Component.getComponentHelper();

Shopware.Component.override('sw-category-detail-base', {
    .....
    computed: {
        mapPropertyErrors('category', ['foo.bar'])
    }
....
```

**Comment by MarcelSchmaeing** [comment]
Hello,

Within our company roadmap and work capacity, we try to address each bug or improvement request but admit that not each one will be resolved. To continue our culture of honesty and openness, we are closing this issue to focus on our roadmap on behalf of all Shopware users.

If you feel like this issue is still impacting you, please create a new issue and let us know.
Thank you again for your valuable feedback.
