### ISSUE TITLE
GET /store-api/v1/context Route not working with empty request body in 6.2

### ISSUE THREAD

**Issue by MDSLKTR** [shopware/shopware#953]
**Description**  
The Route GET /store-api/v1/context described here: https://docs.shopware.com/en/shopware-platform-dev-en/store-api-guide/sales-channel?category=shopware-platform-dev-en/store-api-guide is throwing an internal server error when using with with a 6.2 demostore not supplying any payload. It should handle this error service a bad request or use any sensible default in my opinion.

**Additional context**  
You can see the error and the request (https://wwweewew.shopwaredemo.store/store-api/v1/context) here:

<img width="1456" alt="Bildschirmfoto 2020-05-19 um 14 42 23" src="https://user-images.githubusercontent.com/9129687/82328382-173fc280-99e0-11ea-90da-213fabc9eeee.png">

Default Saleschannel Storefront and Headless were tested.

**Comment by MDSLKTR** [comment]
Note that the request body is empty, so with
```
{
    "includes": {
        "sales_channel_context": ["currentCustomerGroup"]
    }
}
```
it works, but the case should be handled when **no payload is given**.

**Comment by shyim** [comment]
I cannot reproduce that.
![image](https://user-images.githubusercontent.com/6224096/82826381-4efdad00-9ead-11ea-9418-c890ef514953.png)

Can you give a curl example?

**Comment by MDSLKTR** [comment]
Hey @shyim this should do it: `curl -i -H "sw-access-key: SWSCBHFSNTVMAWNZDNFKSHLAYW" https://wwweewew.shopwaredemo.store/store-api/v1/context`

resulting in:

```
HTTP/2 500
date: Tue, 26 May 2020 10:25:17 GMT
content-type: application/json
server: nginx
x-powered-by: PHP/7.3.11
cache-control: no-cache, private
access-control-allow-origin: *
access-control-allow-methods: GET,POST,PUT,PATCH,DELETE
access-control-allow-headers: Content-Type,Authorization,sw-context-token,sw-access-key,sw-language-id,sw-version-id
sw-version-id:
sw-language-id:
sw-context-token: T7mVQxnqukdK62siiucAu7sERiMCnLPf
x-frame-options: deny
set-cookie: sw-states=deleted; expires=Mon, 27-May-2019 10:25:16 GMT; Max-Age=0; path=/; httponly
set-cookie: sw-cache-hash=deleted; expires=Mon, 27-May-2019 10:25:16 GMT; Max-Age=0; path=/; httponly

{"errors":[{"code":"0","status":"500","title":"Internal Server Error","detail":"Argument 1 passed to Shopware\\Core\\System\\SalesChannel\\Api\\StructEncoder::encode() must be an instance of Shopware\\Core\\Framework\\Struct\\Struct, null given, called in \/var\/www\/html\/vendor\/shopware\/platform\/src\/Core\/System\/SalesChannel\/Api\/StructEncoder.php on line 203"}]}%
```

This demo instance is running 6.2.0

**Comment by craftzingdev** [comment]
Experiencing the same error? Any solutions?

**Comment by abvdveen** [comment]
Same here, using Shopware 6.3.2.1 and shopware-pwa canary.

**Comment by MDSLKTR** [comment]
This is not really a problem if you use the request body as described in the docs

**Comment by abvdveen** [comment]
Well, something seems broken, as I haven't modified anything on a standard shopware-pwa instance and get this error in the console when loading a random page. Shouldn't something that's broken be fixed? :)

**Comment by shyim** [comment]
GET should deliver the current sales channel context as json encoded. I guess some plugin is breaking the encoder. Maybe list your plugins here.

Cloud to fail too
```
curl -H "sw-access-key: SWSCBHFSNTVMAWNZDNFKSHLAYW" https://www.shopwaredemo.store/store-api/v3/context
```

**Comment by shyim** [comment]
Has been fixed in meanwhile
