### ISSUE TITLE
Migration1584953715UpdateMailTemplatesAfterOrderLink.php fails when no German language

### ISSUE THREAD

**Issue by KobusPost** [shopware/shopware#961]
**Description**  
Migration1584953715UpdateMailTemplatesAfterOrderLink.php fails when there is no german language configured. The german languageid is an expected argument in the migration. If fails because a string is expected and null is given

**Possible Solution**  
Add german language in admin interface and execute migration.

**Comment by shyim** [comment]
Is already fixed
