### ISSUE TITLE
[SEARCH PERFORMANCE] Only Store UNIQUE keywords in product_keyword_dictionary

### ISSUE THREAD

**Issue by AlexBachmann** [shopware/shopware#964]
**Description**  
I encountered this problem in Shopware 6.1.5 in the **Shopware\Core\Content\Product\SearchKeyword\ProductSearchKeywordIndexer** but I just took a quick look at the **Shopware\Core\Content\Product\DataAbstractionLayer\SearchKeywordUpdater** and the problem seems to be exactly the same.

You are storing the same keyword into this table over and over again, without checking if it's already there.

```php
private function insertDictionary(array $dictionary): void
    {
        $queue = new MultiInsertQueryQueue($this->connection, 50, false, true);
        foreach ($dictionary as $insert) {
            $queue->addInsert(ProductKeywordDictionaryDefinition::ENTITY_NAME, $insert);
        }

        // try batch insert
        try {
            $queue->execute();
        } catch (\Exception $e) {
            // catch deadlock exception and retry with single insert
            $query = new RetryableQuery(
                $this->connection->prepare('INSERT IGNORE INTO `product_keyword_dictionary` (`id`, `language_id`, `keyword`) VALUES (:id, :language_id, :keyword)')
            );

            foreach ($dictionary as $insert) {
                $query->execute($insert);
            }
        }
    }
```
This is a BIG problem. The same keyword (a brand name) for example can come up in every product, so a **single** run of the indexer can insert the same keyword hundreds of times to the dictionary. 

Why is this bad? Let's consider a normal search by the user. In the Shopware\Core\Content\Product\SearchKeyword\ProductSearchTermInterpreter the following happens:

1. It transforms the search term into slops, to find similar sounding keywords from the dictionary
2. **Now the slops are un against the dictionary. If the user's search term is similar enough, our keywords (that have been entered hundreds of times) come back.** 
3. Now the search term is split into its words and the put together in all possible orders of these words (no problem here)
4. Now the matches are scored. And here, we really get a problem. We calculate the levenstein distance of ALL our matches (step 2) against ALL of our combined search tokens (step 3). This algorithm is O(m*n). And it calculates the distance for EVERY match, even if these matches contain the exact same keyword.

 To illustrate this problem a little bit more: For one of our customers, a product search (the product name was entered) resulted in 27.000 calculations of the levenstein distance. After we made sure, that only unique keywords (`$matches = array_unique($matches)`) are being calculated against the tokens, these calculations dropped to 44!

Of course simply running array_unique against the matches before scoring the matches is not the proper way of fixing the issue. It would be match smarter to make sure, that each keyword is only stored ONCE for every language in the product_keyword_dictionary table.

**Comment by shyim** [comment]
This should be fixed in 6.2.0. Can you test it there again?
