### ISSUE TITLE
Payment finalize-transaction inaccessible in headless environment

### ISSUE THREAD

**Issue by elkmod** [shopware/shopware#965]
**Description**  
The [PaymentTransactionChainProcessor](https://github.com/shopware/platform/blob/6.2/src/Core/Checkout/Payment/Cart/PaymentTransactionChainProcessor.php#L156) hard-codes the return URL to `payment.finalize.transaction` ([PaymentController](https://github.com/shopware/platform/blob/6.2/src/Core/Checkout/Payment/Controller/PaymentController.php#L33)), which is `storefront`-scoped.

In a headless scenario we can not require a storefront sales channel to be present, so that route might be inaccessible.

**Possible Solution**  

Change the `payment.finalize.transaction` route to `store-api` (scope and path). I don't see a problem with keeping the redirect functionality.

**Comment by mitelg** [comment]
is it possible to call a store-api route without any authentication? I think that was the reason, why we used the storefront route, (before we had the store API) because the Saleschannel API was not callable without access key.

**Comment by elkmod** [comment]
Well in that case, we have to put the access key or another identification into the token in order to be able to map the correct sales channel. The current implementation is conceptually flawed 😞

**Comment by mitelg** [comment]
there is a ticket for that https://issues.shopware.com/issues/NEXT-6356 please upvote :blush:
