### ISSUE TITLE
SQL_CALC_FOUND_ROWS is deprecated since MySQL 8.0.17

### ISSUE THREAD

**Issue by AndreasA** [shopware/shopware#966]
**Description**  
SQL_CALC_FOUND_ROWS and FOUND_ROWS has been deprecated since 8.0.17
Please check 

See MySQL documentation: https://dev.mysql.com/doc/refman/8.0/en/information-functions.html#function_found-rows

**Possible Solution**  
As described use two queries. One with limit and one without limit that just does a count.
It is also supposed to be faster as `count(*)` is using optimizations, whereas SQL_CALC_FOUND_ROWS disables those.
You actually already need to execute SELECTs already anyway as the FOUND_ROWS is a second query. So this change should really be easy to do.

**Additional context**  
https://dev.mysql.com/doc/refman/8.0/en/information-functions.html#function_found-rows

Current code line:
https://github.com/shopware/platform/blob/6.2/src/Core/Framework/DataAbstractionLayer/Dbal/EntitySearcher.php#L183

**Comment by OliverSkroblin** [comment]
Hi @AndreasA ,
Thanks for the info. We are already working on a solution here. Unfortunately it is not as easy as you think. For example, SELECT COUNT(*) does not work if it is a query with GROUP BY. There are other Edge Cases where a simple exchange is not possible

But we will provide a solution here soon.

**Comment by AndreasA** [comment]
True but it should still be possible.
However, if you are already working on it, it is fine.

**Comment by shyim** [comment]
Is fixed in trunk

**Comment by JoshuaBehrens** [comment]
@shyim can you provide the commit hash? :)

**Comment by shyim** [comment]
https://github.com/shopware/platform/commit/fcd225b528018cd63605fce23cdf268100a02633#diff-190e02b450bcbfc256eaa1f1d13d6d7835e027ec261f188d1d5fbcfdc44eb1f5
