### ISSUE TITLE
Article Property search pagination broken

### ISSUE THREAD

**Issue by PhenomEY** [shopware/shopware#971]
The pagination for the article properties doesnt work. it only shows 1 page even if there is more. 
So you cant choose your properties if you have too many because you can only see the first page.

**Comment by Braintelligence** [comment]
I also have this issue which is a huge problem.

**Comment by pantrtxp** [comment]
We are currently fixing this for the 6.2.1. This should be fixed in the next couple of days.
https://issues.shopware.com/issues/NEXT-8764 here is the ticket for this (only german though) 

We have experienced this behavior in some modules and will try to fix it globally. 

Sunny regards
Pantrtxp

**Comment by Braintelligence** [comment]
Awesome, thank you @pantrtxp 👍
