### ISSUE TITLE
window.apiAccessUrl = "{{ url('frontend.api-access') }}"; missing in base.html.twig

### ISSUE THREAD

**Issue by oriske** [shopware/shopware#974]
Please add

window.apiAccessUrl = "{{ url('frontend.api-access') }}";

to base.html.twig

to the block

  {% block base_script_token %}

as in the production template

**Comment by mitelg** [comment]
hey @oriske 
it is in the code? https://github.com/shopware/platform/blob/6.2/src/Storefront/Resources/views/storefront/base.html.twig#L116 and also in the Storefront many repo: https://github.com/shopware/storefront/blob/v6.2.0/Resources/views/storefront/base.html.twig#L116
are you on the right platform branch?

**Comment by oriske** [comment]
OK it is in there now.
Maybe my mistake but i have been on "shopware/platform": "6.2.x@dev"

Herzliche Grüsse 

Oliver Riske
