### ISSUE TITLE
Symfony Mailer instead of Swiftmailer

### ISSUE THREAD

**Issue by AndreasA** [shopware/shopware#976]
**Description**  
Symfony has its own mailer bundle now which would be nice if it were used by default.

It is also going to replace swiftmailer in the long term, so it would be nice if Shopware were to use it too.

It also has some nice options to test mail sending.

**Comment by shyim** [comment]
Is In Review already and will be in 6.4.0.0
https://issues.shopware.com/issues/NEXT-12246
