### ISSUE TITLE
German Shortcut for Clear Cache wrong

### ISSUE THREAD

**Issue by aagd** [shopware/shopware#987]
**Description**  

In `platform/src/Administration/Resources/app/administration/src/app/snippet/de-DE.json` line 882 reads:   
`    "keyboardShortcutSpecialShortcutClearCacheMac": "control s",`

**Possible Solution**  
Line 882 should read:  
`    "keyboardShortcutSpecialShortcutClearCacheMac": "control c",`

**Additional context**  
English version is OK

**Comment by mitelg** [comment]
hey @aagd 
thanks for the hint.
sounds like an easy pick for a PR 😉

**Comment by ThomasChr** [comment]
Yes, that was an easy one :-)
Thanks @aagd !
Hope you didn't want to make the PR yourself!

**Comment by aagd** [comment]
@ThomasChr  No, thank you for helping out. Would have taken me too long. Next time, I'll try it myself.
