### ISSUE TITLE
[PHPStorm] Can't connect to database

### ISSUE THREAD

**Issue by MajorKuprich** [shopware/shopware#988]
**Description**  
I try to configure database connection in PHPStorm.
From adminer I can connect to db.
Credentials are the same like in adminer.
But it still throws exception:
`[08001] Could not create connection to database server. Attempted reconnect 3 times. Giving up.
java.net.ConnectException: (Connection refused).`
The problem is only with this project.

**Possible Solution**  
I think the issue is with hostname.
I also try localhost, app_mysql, mysql (with root user) - no result.

**Additional context**  
![db connection](https://i.imgur.com/GkFZu2c.png)

**Comment by ireznik** [comment]
Do you use docker as development environment? If so, check the port of the database if it is exposed to access from outside of the docker network. Docker does not expose all services as default.

**Comment by MajorKuprich** [comment]
Thank You,
I checked the db container port and it shows different than default: 4406. :)
It works now.
