### ISSUE TITLE
store-api/v1/customer wrong method

### ISSUE THREAD

**Issue by juliankoehn** [shopware/shopware#994]
**Description**  
According to the [docs](https://docs.shopware.com/en/shopware-platform-dev-en/store-api-guide/account?category=shopware-platform-dev-en/store-api-guide) the endpoint has a POST method:
```json
POST /store-api/v1/account/customer

{
    "includes": {
        "customer": [
            "firstName",
            "lastName",
            "active"
        ]
    }
}
```

API Response:

```
{
    "errors": [
        {
            "code": "0",
            "status": "405",
            "title": "Method Not Allowed",
            "detail": "No route found for \"POST /store-api/v1/account/customer\": Method Not Allowed (Allow: GET)"
        }
    ]
}
```

**Additional context** 
Shopware Version: 6.2.0 Stable

**Comment by mitelg** [comment]
hey @juliankoehn 
this is probably a copy paste error in the docs :see_no_evil: :wink: 

looking at the source https://github.com/shopware/platform/blob/6.2/src/Core/Checkout/Customer/SalesChannel/CustomerRoute.php#L65
it must be `GET`

would be an easy pick for an PR to fix the docs accordingly :blush:

**Comment by juliankoehn** [comment]
This would mean we should use the "Sales-channel-api" endpoint [here](https://docs.shopware.com/en/shopware-platform-dev-en/sales-channel-api/sales-channel-customer-api?category=shopware-platform-dev-en/sales-channel-api#get-detailed-customer-information)

I would rather guess, that it should be Post, so we can use "includes" on the new store-api endpoint. Would at least make sense in point of "consistency" on the api endpoints. 

The Endpoint within the source takes the [Criteria params](https://docs.shopware.com/en/shopware-platform-dev-en/admin-api-guide/reading-entities):
```php
$criteria = $this->requestCriteriaBuilder->handleRequest(
            $request,
            $criteria,
            $this->customerDefinition,
            $context->getContext()
        );
```

**Comment by juliankoehn** [comment]
As reference the Product API endpoint [ProductListingRoute.php](https://github.com/shopware/platform/blob/6.2/src/Core/Content/Product/SalesChannel/Listing/ProductListingRoute.php#L75) accepts POST with Criteria

**Comment by mitelg** [comment]
ok, that would also makes sense :blush: 
I was not involved in the development of the store-api, so that was a quick guess of mine. My colleagues (@shyim ) may say more about that issue

**Comment by shyim** [comment]
Feel free to make an PR to allow also POST :)
You can also send that parameter using GET Parameter, it looks ugly, but should work :) 
Btw you can also look into https://api-doc.friendsofshopware.com/?urls.primaryName=Store%20API%20(6.2.0)#/
It should be more compatible

**Comment by juliankoehn** [comment]
@shyim sadly, i have no php dev environment, swapped years ago to golang. I ported a lot of the shopware api to an golang-sdk. Anyway thanks for sharing your swagger! :-)

**Comment by shyim** [comment]
Its fixed in meanwhile
